M7R0
I-user_numeric%&falseG6",
I/user_precision"")F$,
I0user_precision0""!F$,
I(epsilon$"""!"#F$,
I)test_sepF(F$,
I-taylor_level"#5F$,
I.numeric_levelF/F$,
I*max_levelF/F$,
I/weakness_level""&F$,
I#x0F(F$,
I#y0F(F$,
I&x_min!""F$,
I&y_minF7F$,
I&x_maxF+F$,
I&y_maxF+F$,
I'user_pF+F$,
I'user_qF+F$,
I'user_f7$F(F(F$,
I)user_gcfF(F$,
I0all_crit_pointsF(F$,
I)save_allF#F$,
I*vec_tableQ-TEST_VEC.TABF$F$,
I-finite_tableQ-TEST_FIN.TABF$F$,
I+finite_resQ-TEST_FIN.RESF$F$,
I/infinite_tableQ-TEST_INF.TABF$F$,
I-infinite_resQ-TEST_INF.RESF$F$,
I,hamiltonianF#F$,
I.ishamiltonianf*6#%#vfG6#%%exprGF$F$C$>8$-%)norpoly2G6%,&-%%diffG6$&9$6#F+%"xG
F+-Fen6$&Fhn6#""#%"yGF+FjnF`o@%%(roundedG@%/-%&evalfG6#FU$F(F(%%trueGF#@%/FUF(F
ioF#F$F$F$F$,
I'p4mainf*F$6*%#gcG%$gcfG%*gcdresultG%'orig_fG%"gG%#geG%#gnG%"jGF$F$C=>%+normal
exitGF(>FboF"@%0F'F(>%'DigitsGF'>F^q-%&floorG6#-%'evalhfG6#F^q@$1F^qF%C$-%'writ
efG6%Q^pPlease~increase~precision~or~decrease~accurracy.~Precision~=~%d~<=~Accu
rracy~=~%d.|+F$F^qF%-%%quitGFin@$55/-%6CheckIfGoodPolynomialG6#&F=FinF#/-Fdr6#&
F=F^oF#/-Fdr6#F?F#C$-Fjq6#QipThe~system~is~not~well-defined~(not~polynomial,~or
~coefficients~do~not~evaluate~numerically.)|+F$F]r-Fjq6#QGLET~US~STUDY~THE~DIFF
ERENTIAL~SYSTEM:|+F$-Fjq6%Q:~~~~x'~=~%a|+~~~~y'~=~%a|+|+F$FfrFjr-%)openfileG6#F
B-Fjq6&Q*%d|+%d|+%d|+F$F@F;F<@$/F@""$-Fjq6'Q1~~~~%g~%g~%g~%g|+F$F6F9F8F:-Fis6#%
)terminalG@%/F?F(C'>8'F=>8&-%'my_gcdG6$FfrFjr>FU&F]uF^o>F?&F]u6#F`t>F=-%)simpli
fyG6#&F]uFinC&>FUF_o>F[uF=>F=7$-Fhu6#*&&F[uFinF+F?F7-Fhu6#*&&F[uF^oF+F?F7@$FarC
$-Fjq6#QNError:~The~given~gcf~is~not~a~common~factor.|+F$F]r-%*write_gcfGF]sFhs
-%0write_vec_fieldG6#F=Fdt@%-FMFawC$-Fjq6#Q<The~system~is~Hamiltonian.|+F$>FLFi
o>FLF#@$4-%'memberG6$F@<$F_oF`tC.>%)log_fileGFD>%,result_fileGFF-Fjq6#QOLET~US~
STUDY~THE~SYSTEM~AT~THE~FINITE~REGION|+|+F$-Fis6#FdxFbs-Fjq6%Q9~~~~x'~=~%a|+~~~
~y'~=~%a|+F$FcvFgv-Fjq6#Q6AT~THE~FINITE~REGION|+F$@$5/FUF+3/FUF_o0F?F+C%-Fjq6$Q
DThe~system~has~a~common~factor:~%a|+F$F?-Fjq6$QJHence~we~shall~study~the~reduc
ed~system:|+F$F?-Fjq6%F\yFfrFjrFdt@%4F"C->8(-%0find_real_rootsG6%F=FjnF`o>8)&Fc
zFin>8*&FczF^o-Fis6#Fbx-Fjq6$Q$%d|+F$,&-%%nopsG6#FhzF+-Fd[l6#F[[lF+Fdt-Fjq6#QZ-
-------------------------------------------------------|+F$?(8+F+F+Fc[lFio-%*si
ng_typeG6&F=-%#opG6$F+&Fhz6#F\\l-Fa\l6$F_oFc\lF(>FboFio?(F\\lF+F+Ff[lFio-F^\l6&
F=-Fa\l6$F+&F[[lFd\l-Fa\l6$F_oF]]lF(>FboF"C(>F[[l-%8find_real_roots_numericGFfz
F][l-Fjq6$Fa[lFf[lFdtFh[l?(F\\lF+F+Ff[lFioFi\l-%*closefileGF^[l-Fi]lFix@$4-F]x6
$F@<$F+F`tC*>FbxFH>FdxFJ-Fjq6#QFLET~US~STUDY~THE~SYSTEM~AT~INFINITY|+|+F$Fbs@%F
dy-Fjq6%F\y*&F?F+FfrF+*&F?F+FjrF+Fjx-Fjq6#Q-AT~INFINITY|+F$@$FayC%FgyFjyF]zFdt@
%3/F;F+/F<F+-%5vec_field_diff_chartGFfz-%)pl_chartGFaw@$F\^lC$Fh]lFj]l-Fi]lFjs@
$F_tC/>FbxFD>FdxFFF][l-Fjq6$Fa[lF+Fdt-Fjq6#QIWe~shall~study~the~differential~sy
stem:|+F$@%FdyFg^lFjx-Fjq6%Q7in~the~point~(%a,%a).|+F$F4F5@$FayC%FgyFjyF]zFdt-F
^\l6&F=F4F5F(Fh]lFj]lFdt-Fjq6#QR|+We~have~finished~the~study~of~the~vector~fiel
d.|+F$-%.closeallfilesGF$>FipF+F$6+FboF=F?F;F<FLFbxFdxFipF$F$,
I6CheckIfGoodPolynomialf*6#%"fGF$F$F$O-%%typeG6$-Ffo6#Fhn-%(polynomG6$%(numeric
G7$FjnF`oF$F$F$F$,
I+normalexitF(F$,
I/user_exeprefixQ(cmd~/c~F$F$
