M7R0
I+weak_focusf*6&%"fG%#x0G%#y0G%&chartG6,%&stypeG%#ffG%%aa10G%%aa01G%%bb10G%"sG%
"gG%#_xG%#ggG%$lypG6"F4C,-%'writefG6%Q:(%a,%a)~is~a~weak~focus.|+F49%9&-%)openf
ileG6#%,result_fileGF6-F=6#%)terminalG@%%,hamiltonianGC'-F76#QTSince~the~system
~is~hamiltonian,~we~have~a~center.|+F4F<FFF@>8$""%C.>8%-%,translationG6'9$%"xG%
"yGF:F;>8&-%&coeffG6%-FX6%&FN6#"""FSFhnFT""!>8'-FX6%-FX6%FfnFSFinFTFhn>8(-FX6%-
FX6%&FN6#""#FSFhnFTFin>8)-%%sqrtG6#,&*&F[oFhnFaoFhn!""*$FVFhoF`p>8*7$,&*(FaoFhn
-%%subsG6$<#/FS,&*(FjoFhn8+FhnFaoF`pF`p*(FVFhnFTFhnFaoF`pFhnFfnFhnFjo!"#Fhn*(FV
Fhn-Fhp6$FjpFfoFhnFjoF`qF`p,$*&-Fhp6$<#/FS,&*(FjoFhnFSFhnFaoF`pF`pF_qFhnFfoFhnF
joF`pF`p>Fcp-%&evalfG6#-Fhp6$/F^qFSFcp-F76$Q6The~local~system:~%a|+F4Fcp>8,,&-F
hp6$<$/FS,&%"zG#FhnFho%"wGF_s/FT*&^##F`pFhoFhn,&F^sFhnF`sF`pFhn&FcpFgnFhn*&^#Fh
nFhn-Fhp6$F[s&FcpFgoFhnFhn>Fgr-%'expandG6#Fgr@$%)save_allGC%F<-F76$Q)z'~=~%a|+F
4FgrF@@%/%/weakness_levelGFinC%-F=6$F?FB-F76#QenLyapunov~constants~are~not~calc
ulated.~(weakness~level=0)|+F4>FJFinC%@%%-user_numericG>8--%)lyapunovG6%,&FgrFh
n*&^#F`pFhnF^sFhnFhnF^sF`s>Fdu-%,lyapunovsymGFgu-F76$Q:Lyapunov~information:~%a
|+F4Fdu@%0&FduFgnFinC'Fjt-F76$Q=The~order~of~weakness~is~%d|+F4&FduFgo-F76$Q9Ly
apunov~constant~is~%g|+F4,$FcvF`pF@@%2FcvFinC'-F76#QBWe~have~an~unstable~singul
arity.|+F4F<F`wF@>FJFhnC'-F76#Q?We~have~a~stable~singularity.|+F4F<FewF@>FJF`p@
%/&Fdu6#""$FhoC'-F76#QMWe~have~a~center~(the~system~is~quadratic).|+F4F<F_xF@>F
JFK@%&Fdu6#FKC'-F76#QPWe~have~a~center~(the~system~is~linear+cubic).|+F4F<FgxF@
>FJFKC'-F76$QGThe~order~of~weakness~is~at~least~%d.|+F4,&FhtFhnFhnFhnF<F\yF@>FJ
FinF<-F76#QZ########################################################|+F4F@Fay-%
1write_weak_focusG6&F:F;9'FJF46#FDF4F4,
I)lyapunovf*6%F%F^sF`s6,%"aG%'bindirG%'infileG%(outfileG%(exefileG%'resultG%'rn
dnumG%#wlG%&linfoG%$auxGF4F4C,>Fcp-%%iremG6$-%%randGF4"%+5>FV-%$catG6&%,user_tm
pdirGQ'P4LYP_F4FcpQ%.INPF4>F[o-Fa[l6&Fc[lFd[lFcpQ%.OUTF4@%/%0user_precision0GFi
n>Fao-Fa[l6$%,user_bindirG%,user_lypexeG>Fao-Fa[l6$F`\l%0user_lypexe_mpfG>Fgr-%
4preparelyapunovfileG6&FVFRF:F;>F^q&FgrFgn-F76#QDDetermining~lyapunov~constants
~...|+F4>Fdu-%(ssystemG6#-Fa[l6.%/user_exeprefixGQ!F4FaoQ#~"F4FVQ$"~"F4F[oQ)"~M
APLE~F4%.user_platformGFg]l%2user_sumtablepathGQ""F4>Fjo-%3readlyapunovresultG6
$F[oF^q7%-%#opG6#Fjo&FgrFgo&FgrF\xF46)Fe]lFc[lFa\lFe\lF\\lF`\l%/user_removecmdG
F4F4,
I3readlyapunovresultf*6$%)filenameG%*weaklevelG6)%(lypdataG%&VdataG%"jG%"nG%%wv
alG%'lypvalG%&okvalGF4F4C.>FJ-%)readdataG6$FRFhn-F76$Q4lyapunov~data~=~%a|+F4FJ
>FN7">F[oFhn-F=6$FBF??(FVFhnFhnF:%%trueGC&@$0&FJ6#F[oF`p-F76%Q*V(%d)=%g|+F4-%&r
oundG6#Fh`l&FJ6#,&F[oFhnFhnFhn>FN7$-Fc^l6#FN7$F]alF`al@$/F]alF`pC$>F[oFbal[>F[o
,&F[oFhnFhoFhn@$Fial>F[oFbal>FcpF]al>Fao-F^al6#F`al>Fjo&FJ6#F^blF@7$FjoFaoF4F4F
4F4,
I4preparelyapunovfilef*6&F\_l%#_fGF^sF`s6)F%%&cubicG%"LG%"dGF]zFa_lFdzF4F4C.>FJ
-%4optimizepolynomial2G6%F:F;Fgy>FN%&falseG-F=6#FR-F76$Q$%d|+F4,&F\\lFhoFhoFhn>
F[o-%%ddegG6%FJF;Fgy@%/F[oFhoC$>FcpF]x-F76#Q#3|+F4@%/F[oF]xC$>Fcp""&@%33/-FX6%-
FX6%FJF;FhoFgyFinFin/-FX6%-FX6%FJF;FinFgyFhoFin/-FX6%-FX6%FJF;FhnFgyFhnFinC$-F7
6#Q#5|+F4>FNFd`lC$>FcpFht-F76$F\dlFhtC$>FcpFhtFgfl-F76$Q$%g|+F4)"#5,$%/user_pre
cisionGF`p>FV-%.coeff_degree2GFadl-F76$F\dl-%%nopsG6#FV?(FjoFhnFhnFgglFd`lC$>Fa
o&FVFd^l-F76'Q/~~%d~%d~%g~%g|+F4&FaoFgn&FaoFgo-F^r6#-%#ReG6#&FaoF\x-F^r6#-%#ImG
Fghl-%*closefileGFicl7%FcpF[oFNF4F4F4F4,
I,lyapunovsymf*6%F\clF^sF`s6+F%FezFdz%"kG%"TG%"VGFbz%#okGFa_lF4F4C,>FJ-Fdcl6%FR
F:F;>FN-%3preparelyapunovsymG6%FJF:F;>FVFfn>FcpF_`l>F^qFgclFa`l?(F[oFhnFhnFVFd`
lC(>Fao-%)sumtableG6#,$F[oFho>FjoFin?(FgrFhnFhn-Fhgl6#FaoFd`l>Fjo,&FjoFhn-%4par
t_lyapunov_coeffG6'FJF:F;&FaoF_t,&F[oFhoFhnFhnF`p>Fcp7$-Fc^l6#Fcp7$FjoF[o-F76&Q
2k=%d~V~=~%a~=~%f|+F4F[oFjo-F^rFd^l@$-%,reduce_nneqG6$FjoFinC$>F^qFd`lF\blF@@%F
^q>Fcp&Fcp6#F`p>Fcp7$FinFin7%Fg[mFfo&FNF\xF4F4F4F4,
I3preparelyapunovsymf*F[z6(F^clF_clF`clF]zFa_lFdzF4F4C'>FJFgcl>FV-F`dlF[jl@%/FV
Fho>FjoF]x@%/FVF]xC$>FjoF]el@%33/-FX6%-FX6%FRF:FhoF;FinFin/-FX6%-FX6%FRF:FinF;F
hoFin/-FX6%-FX6%FRF:FhnF;FhnFin>FJFd`l>FjoFht>FjoFht>FN-FdglF[jl7%FjoFVFJF4F4F4
F4,
I)sumtablef*6#Fb_l6&F_cl%"rGF/%+st_compareGF4F4C&>FJ-%*piecewiseG6%/FRFin7#7#Fh
n-%$mapG6$Fc^l-Fa`m6$&%)combinatG6#%(permuteG-&Ff`m6#%*partitionG6$FRFR>F[of*6$
Ff_mF/F46$%)operatorG%&arrowGF4@%2&FRFgn&F:FgnFd`l@%/FfamFgam-T#6$&FR6#;FhoF`p&
F:F^bmFgclF4F46$Fg_mF[o>FJ-%%sortG6$FJF[oOFJF4F4F4F4,
I4part_lyapunov_coefff*6'%)vecfieldGF^sF`sF_clFdil6(%"RG%%exprGF%%"vG%#wwG%"iGF
4F4C%>FJ-Fa`m6$f*6#F]cmF4FaamF4-%-lyp_findpolyG6&T$T&T(,&FRFhnFhnFhnF4F46(FjbmF
RF^sF:F`sF;Fgy@%4-%'memberG6$FinFJC&>FVF`p?(FjoFhnFhn,&-Fhgl6#FJFhnF`pFhnFd`l@%
-%%typeG6$,&FjoFhnF`pFhn%$oddG>FV-%)lyp_RegzG6&FV&FJFd^lF:F;>FV-%)lyp_ImgzGFcem
>FjoFhdm@%F[emC%>FV-%/lyp_multc_polyG6'FVFinF`pF:F;>6$FVF[o-Fc^l6#-%'lyp_LLG6'F
VFdemF:F;,&9(F_sFdsFhn>Fao-%)simplifyG6#-F\ilFi`lC$>F`fmFafm>Fao-Fjfm6#-FfhlFi`
l>FaoFinOFaoF4F4F4F4,
I/lyp_multc_polyf*6'F%F]z%"bGF^sF`sF4F4F4O-F^t6#*&,&F:Fhn*&FhsFhnF;FhnFhnFhnFRF
hnF4F4F4F4,
I-lyp_findpolyf*6&%#vfGF^sF`sFb_l6$Ff_mFdilF4F4C%>FJFin?(FNFinFhnFgyFd`l>FJ,&FJ
Fhn*(-FX6%-FX6%FRF:FNF;,&FgyFhnFNF`pFhn)F:FNFhn)F;F^imFhnFhnFJF4F4F4F4,
I)lyp_Regzf*6&F%F0F^sF`s6#Ff_mF4F4C(>FJ-F^t6#*&FRFhnF:Fhn>FJ-F]fm6'FJFinF`pF;Fg
y>FJ-%%diffG6$FJF;>FJ-%&lyp_GGFadl>FJ,&FJFhn-%.lyp_conj_polyGFadlFhnO-F]fm6%FJF
_sFinF4F4F4F4,
I)lyp_Imgzf*FcimFdimF4F4C'>FJFgim>FJF^jm>FJFbjm>FJ,&FJFhnFfjmF`pO-F]fm6%FJFinFd
sF4F4F4F4,
I'lyp_LLf*6'F%F0F^sF`sFb_lFdimF4F4C$>FJ-F_jm6$FgimF;7$FJ-FX6%-FX6%FJF;FgfmFgyFg
fmF4F4F4F4,
I&lyp_Gf*F[z6&Fdil%#fkGFf_m%"lGF4F4C%>FVFin@$1Fin-%'degreeG6$FRF:?(FJFinFhnF[]n
Fd`lC$>FN-FX6%FRF:FJ@$1Fin-F\]n6$FNF;?(F[oFinFhnFe]nFd`l@%0FJF[o>FV,&FVFhn**-FX
6%FNF;F[oFhn,&FJFhnF[oF`pF`p)F:FJFhn)F;F[oFhnFho>FV,&FVFhn*(F]^nFhnF`^nFhnFa^nF
hnFhn-F^tFiglF4F4F4F4,
I.lyp_conj_polyf*F[z6#%#zbGF4F4C$-%)assumingG6$7#-F^t6#-%*conjugateGFicl7$'F:%%
realG'F;Fe_n-%%evalG6$-Fh_n6$-Fh_n6$%"%G<#/F:FJ/F;F:/FJF;F4F4F4F4
