M7R0
I-assoc_pointsf*6#%#vfG6&%#LfG%#LgG%%exprG%"wG6"F+C'>8$-%.coeff_degree2G6%-%&ev
alfG6#&9$6#"""%"xG%"yG>F.-%$mapG6$f*6#F)F+6$%)operatorG%&arrowGF+7$,&F5F8!""F8&
F66#""#F+F+F+F.>8%-F06%-F36#FGF9F:>FK-F=6$f*F@F+FAF+7$F5,&FGF8FFF8F+F+F+FK-%(co
nvertG6$<$-%#opG6#F.-Fen6#FK%%listGF+F+F+F+,
I/newton_diagramf*F$6-%'pointsG%#pkG%#pjG%#pLG%"kG%"jG%"LG%%hsetG%"NGF*%"pGF+F+
C'>8+-F"6#F6>F.Fio>8,-%%nopsGFfn?(8(F8F8,&F^pF8FFF8%%trueGC$>FK&F.6#Fbp@$-%'mem
berG6$FKFio?(8),&FbpF8F8F8F8F^pFdpC$>8&&F.6#F^q@$-F[q6$FbqFio@%31&FKF7&FbqF71&F
KFH&FbqFH>Fio-%'removeG6$f*6#FfoF+FAF+/F6T#F+F+6$F_oFbqFio?(8*F8F8F^pFdpC$>8'&F
.6#Fjr@$33-F[q6$F]sFio0FjrFbp0FjrF^q@%531F[r&F]sF71F^r&F]sFH31F\rF[t1F_rF]t>Fio
-Fbr6$f*FerF+FAF+FfrF+F+6$F`oF]sFio@$532F[rF[t2F[tF\r32F\rF[t2F[tF[rC$>8-*&,&F_
rF8F^rFFF8,&F\rF8F[rFFFF@$1,&*&F`uF8,&F[tF8F\rFFF8F8F_rF8F]t>Fio-Fbr6$f*FerF+FA
F+FfrF+F+FetFioFioF+F+F+F+,
I(GAMMA_1f*6#%"sG6)FcoFfo%"qG%"rGFao%#skG%"GGF+F+C(>F.-F`pF[p>FKF5>FbqFG@$1F\rF
[rC$>FKFG>FbqF5@%/F.FI>Fjr7$FKFbqC&>F]s&F66#""$@%F]uC%>F]sFbq>FbqFK>FKFfw@$FjtC
$>F]sFbq>FbqFfw?(Fbp""%F8F.FdpC$>F^q&F6Fhp@%2&F^qF7F[rC%>F]sFbq>FbqFK>FKF^q@%2F
ixF\rC$>F]sFbq>FbqF^q@$2FixF[t>F]sF^q@%2""!F\r>FjrFcw>Fjr7$FbqF]sFjrF+F+F+F+,
I-quasi_degreef*F_v6&%"hG%&alphaG%%betaG%"dGF+F+C'>F.,$*&,&-Fen6$FIFGF8-Fen6$FI
F5FFF8,&-Fen6$F8FGF8-Fen6$F8F5FFFFFF>FK-%&numerGFfn>Fbq-%&denomGFfn>F]s,&*&FKF8
F_[lF8F8*&FbqF8FjzF8F87%FKFbqF]sF+F+F+F+,
I-center_type1f*6&%"fGF9Fco%$dirG6&F`v%"gG%"mG%"bGF+F+C'>FK-%+first_termG6$F69%
>Fbq-%$maxG6$Fhy-%'degreeG6$FKFj\l>F]s-%%signG6#-F36#-%%subsG6$/Fj\lF8FK@%-%%ty
peG6$Fbq%%evenG>F.7%F]sF8-Fd]l6#-F36#9&>F.7%F]sFFFc^l@%/9'F8C*@$/F.7%FFF8F8O"#5
@$/F.7%F8F8F8O""*@$/F.7%F8FFF8OFhw@$/F.7%FFFFF8OF8@$/F.7%FFF8FFO"#7@$/F.7%F8F8F
FO"#6@$/F.7%F8FFFFOFIOFcxC*@$F__lOFg_l@$Fd_lOFb_l@$Fi_lOFhw@$F]`lOF8@$Fa`lOFi`l
@$Ff`lOFd`l@$F[alOFIOFcxF+F+F+F+,
I-center_type2f*F^\lFa\lF+F+C'>FKFg\l>FbqF\]l>F]sFc]l@%F]^l>F.Fb^l>F.Fi^l@%F[_l
C*@$F__lOFg_l@$Fd_lOFb_l@$Fi_lOFhw@$F]`lOF8@$Fa`lOFi`l@$Ff`lOFd`l@$F[alOFIOFcxC
*@$F__lOFb_l@$Fd_lOFg_l@$Fi_lOFhw@$F]`lOF8@$Fa`lOFd`l@$Ff`lOFi`l@$F[alOFIOFcxF+
F+F+F+,
I&powerf*6$%"aGFd\lF+F+F+@%/Fj\lFhyF8)F6Fj\lF+F+F+F+,
I-sort_set_posf*6%F`v%#y0GFcv6%F\elFaoFcoF+F+C'>F.7#-%"$G6#;F8,&FhvF8F8F8>FKF8?
(FbqF8F8FhvFdpC%@$3-%+reduce_lltG6$Fj\l-Fen6$F8&F66#Fbq/FKFbqC$>&F.Fhn7$Fj\lFg^
l>FK,&FKF8F8F8>F\glFgfl>FKF_gl@$Fifl>F\glF]glF.F+F+F+F+,
I-sort_set_negf*FbelFdelF+F+C'>F.Fgel>FKF8?(FbqF8F8FhvFdpC%@$3-%*reduce_gtGFdfl
FiflC$>F\glF]gl>FKF_gl>F\glFgfl>FKF_gl@$Fifl>F\glF]glF.F+F+F+F+,
I0put_separatricef*6)%%xposG%&stypeG%0transformationsG%#ptG%&transG%*vec_fieldG
%$sepG6#%)newentryGF+F+C$>F.7)Fg^lF\_l9(9)9*Fj\l%(roundedG@%/F6F8C$>%(NumXPosG,
&F]jlF8F8F8>%(ManXPosG7$-Fen6#F`jlF.C$>%(NumXNegG,&FfjlF8F8F8>%(ManXNegG7$-Fen6
#FijlF.F+6&F]jlFfjlF`jlFijlF+F+,
I2append_trajectorsf*F+6%%%man1G%%man2GFboF+F+C,-%&printG6$Q+ManYNeg~=~F+%(ManY
NegG-Fe[m6$Q+ManYPos~=~F+%(ManYPosG-Fe[m6$Q+ManXNeg~=~F+Fijl-Fe[m6$Q+ManXPos~=~
F+F`jl>F.7"@$0%(NumberYGFhyC$>FK-%4make_transformationG6#Fh[m>F.7$FZ7$-FenF\]mF
K?(FbqF8F8F]jlFdpC$>FK-F[]m6#&F`jlFhfl>F.7$FZ7$-FenFe]mFK@$Ff\mC$>FK-F[]m6#F\\m
>F.7$FZ7$-FenF_^mFK?(FbqF8F8FfjlFdpC$>FK-F[]m6#&FijlFhfl>F.7$FZ7$-FenFh^mFKF.F+
F+F+F+,
I1split_trajectorsf*6#F_il6'%(sep_posG%(sep_negGFboF`vFb\lF+F+C&>F.Fd\m>FKFd\m?
(FbqF8F8FhvFdpC$>F]s-Fen6$"")Fgfl@$0F]tFhyC$>Fbp-Fd]l6#-F36#-Fi]l6$/%"tGF8-Fh\l
6$-%%diffG6$F]tFh`mFh`m@%2FhyFbp>F.7$FZFgfl>FK7$FgnFgfl7$F.FKF+F+F+F+,
I4make_transformationf*F`_m6,Fco%%histGF\ilF]ilF`v%#x0GFcel%#x1G%#y1GF\elF+F+C+
>FKF5>FbqFG>F]sFfw>Fbp&F66#""&>F^q,(F\rF8*&F[tF8Fh`mF8F8*&F]tF8FbpF8F8>Fjr,(F_r
F8*&&F]sFgwF8Fh`mF8F8*&&F]s6#FcxF8FbpF8F8>F.-F`pFhn?(F+F8F8F+2FhyF.C(>F`u&FKFfn
>Fio,&&F`uF7F8*(&F`uFgwF8-Fidl6$F^q&F`uFbbmF8-Fidl6$Fjr&F`u6#""'F8F8>F^p,&&F`uF
HF8*(&F`uF^cmF8-Fidl6$F^q&F`u6#""(F8-Fidl6$Fjr&F`u6#F\`mF8F8>F^q-%4optimizepoly
nomial1G6$FioFh`m>Fjr-Fcem6$F^pFh`m@%3/F^qFhy/FjrFhy>F.Fhy>F.,&F.F8FFF87$F^qFjr
F+F+F+F+,
I1write_trajectorsf*6%F_ilFiamFcel6/Fco%#w1G%#s1G%#s2GFbo%#elG%$hypG%#w2G%$dl1G
%$dl2G%$dl3G%$dl4G%$dl5GF+F+C9>F.Fhv>F^qFhy>FjrFhy>F^pQ!F+>F`uQ"~F+>8.Fdgm>8/Fd
gm>80Fdgm@$0F.FhyC1-%)openfileG6$%,result_fileG%)terminalG-%'writefG6#QI|+|+The
~invariant~separatrices~are:~(t>0)|+F+-Fahm6#Fdhm>FK<*F8FhwFcbmF\emFg_lFb_l"#8"
#9>Fio<*FIFcxFbdmF\`mFi`lFd`l"#:"#;>Fbq-Fen6$FbdmF5-Ffhm6#-%(sprintfG6$Q&~[%d]F
+Fbq@%-F[q6$FbqFKC(F`hm-Ffhm6$Q5[01]:~%a~:~unstable|+F+-Fen6$F\`mF5Fihm>F^p-%$c
atG6$F^pQ)~~~|gr~~~~F+>F`u-Fgjm6$F`uQ&~~^~~F+>Fhgm-Fgjm6$FhgmFijmC(F`hm-Ffhm6$Q
3[01]:~%a~:~stable|+F+FcjmFihm>F^pFfjm>F`u-Fgjm6$F`uQ&~~v~~F+>FhgmF_[n@%-F[q6$F
bq<)FIFhwFcbmFbdmFb_lFd`lF]im>Fjgm-Fgjm6$FjgmQ%-<-*F+@%-F[q6$Fbq<)F8FcxF\emF\`m
Fg_lFi`lFaim>Fjgm-Fgjm6$FjgmQ%->-*F+>Fjgm-Fgjm6$FjgmQ%****F+@%-F[q6$Fbq<)F8FcxF
\emF\`mFb_lFd`lFbim>Fjgm-Fgjm6$FjgmQ%-<-~F+@%-F[q6$Fbq<)FIFhwFcbmFbdmFg_lFi`lF^
im>Fjgm-Fgjm6$FjgmQ%->-~F+>Fjgm-Fgjm6$FjgmQ%***~F+>F\hm-Fgjm6$F\hm-Fiim6$Q+~~%0
2d~~~~F+F8?(FbpFIF8F.FdpC*>F]s-Fen6$FbdmFfx@%53-F[q6$Fbq<%F8F\emFb_l-F[q6$F]s<%
FIFbdmFd`l3-F[q6$Fbq<%FIFbdmFi`l-F[q6$F]s<%F8F\emFg_lC'F`hm-Ffhm6#Q3hyperbolic~
sector|+F+Fihm>Fjr,&FjrF8F8F8>F`u-Fgjm6$F`uQ$HYPF+@%53-F[q6$Fbq<&FhwFcbmFg_lF^i
m-F[q6$F]s<&FcxF\`mFi`lFaim3-F[q6$Fbq<&FcxF\`mFd`lFbim-F[q6$F]s<&FhwFcbmFb_lF]i
mC'F`hm-Ffhm6#Q1elliptic~sector|+F+Fihm>F^q,&F^qF8F8F8>F`u-Fgjm6$F`uQ$ELLF+C&F`
hm-Ffhm6#Q2parabolic~sector|+F+Fihm>F`u-Fgjm6$F`uQ$PARF+>FbqF]sFfim@%F]jmC(F`hm
-Ffhm6%Q7[%02d]:~%a~:~unstable|+F+Fbp-Fen6$F\`mFfxFihm>F^pFfjm>F`uF[[n>FhgmF_[n
C(F`hm-Ffhm6%Q5[%02d]:~%a~:~stable|+F+FbpF`cnFihm>F^pFfjm>F`uFg[n>FhgmF_[n@%F\\
n>FjgmF`\n@%Fd\n>FjgmFh\n>FjgmF\]n@%F`]n>FjgmFd]n@%Fh]n>FjgmF\^n>FjgmF`^n>F\hm-
Fgjm6$F\hm-Fiim6$Fh^nFbp>Fbq-Fen6$Fbdm&F6Ffn>F]sFdim@%F__nC'F`hmF_`nFihm>FjrFc`
n>F`uFe`n@%53-F[q6$Fbq<%FhwFcbmFg_l-F[q6$F]s<%FcxF\`mFi`l3-F[q6$Fbq<%FcxF\`mFd`
l-F[q6$F]s<%FhwFcbmFb_lC'F`hmFianFihm>F^qF]bn>F`uF_bnC&F`hmFcbnFihm>F`uFgbnF`hm
-Ffhm6&QFThe~singularity~(%a,%a)~has~index~%a|+F+Fj\lFg^l,(F8F8F^q#F8FIFjr#FFFI
-Ffhm6#QKSector~representation~(counterclockwise):|+F+-Ffhm6#F^p-Ffhm6#Q"|+F+-F
fhm6#F`uFdgn-Ffhm6#FhgmFdgn-Ffhm6#FjgmFdgn-Ffhm6#F\hm-Ffhm6#Q#|+|+F+FihmF+F+F+F
+,
I1manifold_blow_upf*6$%#_gG%"nG6*%(lambda1G%(lambda2GFb\lF_\lF\el%$dfxGFaoF_zF+
F+C*>Fbq-%+optimizevfG6%F6F9F:>F.-%&coeffG6%-Fbin6%F\rF9F8F:Fhy>FK-Fbin6%-Fbin6
%F_rF:F8F9Fhy>F]s-%$addG6$*&&FbpF_sF8)F9FjrF8/Fjr;FIFj\l>F^q-F]jn6$*(FjrF8F`jnF
8)F9,&FjrF8FFF8F8Fbjn>Fio-%'expandG6#,&-Fi]l6$/F:F]s,&F_rF8*&FKF8F:F8FFF8*&F^qF
8-Fi]l6$Fa[o,&F\rF8*&F.F8F9F8FFF8FF?(FjrFIF8Fj\lFdpC$>Fio-%%evalG6$Fio/F`jn*&-F
bin6%FioF9FjrF8,&*&F.F8FjrF8F8FKFFFF>F]s-F]\o6$F]sF_\oO-Fi]l6$/F9Fh`mF]sF+F+F+F
+,
I2manifold2_blow_upf*6$Fb\lFfhn6+%#L1G%#L2GF_\lFjhnFao%"iGF_zF\el%#n1GF+F+C+>F.
-Fbin6%-Fbin6%F5F9F8F:Fhy>FK-Fbin6%-Fbin6%FGF:F8F9Fhy>Fbq-F]jn6$*&&FioFhpF8)F9F
bpF8/FbpFcjn>F]s-F]jn6$*(FbpF8Fc^oF8)F9,&FbpF8FFF8F8Fe^o>Fjr,&-Fi]l6$/F:Fbq,&FG
F8Fc[oFFF8*&F]sF8-Fi]l6$F`_o,&F5F8Fh[oFFF8FF>FbpFI>F^pFj\l?(F+F8F8F+2Fbp,&Fj\lF
8F8F8@%-%,reduce_nneqG6$,&*&FbpF8F.F8F8FKFFFhyC%>Fjr-F]\o6$Fjr/Fc^o*&-Fbin6%Fjr
F9FbpF8F_`oFF>Fbq-F]\o6$FbqFe`o>FbpF_qC$>F^pF[_o>FbpFj_o-F]jn6$*&-Fbin6%FbqF9F^
qF8)Fh`mF^qF8/F^q;FIF^pF+F+F+F+,
I8center_manifold_blow_upf*F^]o61%$vf1G%$vf2G%#h1G%#h2GFaoFa]oF_il%#_yG%'lambda
G%#okGFc]o%#dxGFd\lFc\l%#amGF+F+C)@%FhilC$>F.F2>FKFNC$>F.F5>FKFG>F^q-Fbin6%-%(c
ollectG6$-Fi]l6$/F9FhyFGF:F:F8>FjrFhy>FhgmFj\l?(FbpFIF8FhgmFdpC+>F^p,$*&-Fbin6%
-F`co6$-Fi]l6$/F:FhyFKF9F9FbpF8F^qFFFF@$34Fhil%.user_simplifyG>F^p-%1user_simpl
ifycmdGFcgn>Fbq-F\[o6#-Fi]l6$/F:,&FioF8*&F^pF8Fd^oF8F8F.>F]s-F\[o6#,&-Fi]l6$F_e
oFKF8**F^pF8FbpF8Fj^oF8FbqF8FF>F.-Fi]l6$/FioF:Fbq>FK-Fi]l6$F\foF]s>Fjr,&FjrF8Fa
eoF8>Fjgm-Fcem6$-Fi]l6$FbdoF.F9@$/FjgmFhy>Fhgm,&FhgmF8F8F8>FjgmFcfo7%FjrFjgm-Fh
\l6$FjgmF9F+F+F+F+,
I+blowing_upf*6&F%FiamFcel%-finite_pointG6)FcvF\bo%$n_dG%#g1G%)q_degreeG%"zG%+t
rajectorsGF+F+CV@$%)save_allGF`hm-Ffhm6&QAblowing~up~%a~in~point~(%a,%a).|+F+F6
Fj\lFg^lFihm@%50Fj\lFhy0Fg^lFhyC'>FK-F^in6%-%,translationG6'F6F9F:Fj\lFg^lF9F:@
$F[hoF`hm-Ffhm6%Q?moving~(%a,%a)~to~the~origin.|+F+Fj\lFg^l-Ffhm6$Q6new~vector~
field:~%a|+F+FKFihm>FKF]in>Fbq-FjnFhn>F]s-F]vFhfl>Fbp-F\z6#F]s@$F[hoF`hm-Ffhm6$
Q4Newton~diagram:~%a|+F+Fbq-Ffhm6$Q)g1~=~%a|+F+F]s-Ffhm6$Q:[alpha,beta,degree]~
=~%a|+F+FbpFdgn-Ffhm6#QK1.~Blowing~up~in~the~positive~x-direction|+F+-Ffhm6#QK-
----------------------------------------|+F+Fdgn-Ffhm6#Q4blowing~up~level~1|+F+
-Ffhm6#Q4------------------|+F+-Ffhm6$Q>blowing~up~%a~in~point~(0,0)|+F+FKFihm>
F^q-%)blow_upxG6'FKFbpF8F9F:@$F[hoF`hm-Ffhm6$Q;blowing~up~vectorfield~%a|+F+Fix
Fihm-%,sing_eigenvG6'F^qF8F87#7+Fj\lFg^lF8F8&FbpF7Fhy&FbpFHF8&FbpFgwF8@$F[hoF`h
m-Ffhm6#Qen---------------------------------------------------------|+F+Fdgn-Ff
hm6#QK2.~Blowing~up~in~the~negative~x-direction|+F+FfjoFdgnFdgnFijoF\[pF_[pFihm
>F^q-Fd[p6'FKFbpFFF9F:@$F[hoF`hmFg[pFihm-F[\p6'F^qFFF87#7+Fj\lFg^lFFF8F_\pFhyF`
\pF8Fa\pFF@$32FF-Fen6$F8F[t0&F^qFgwFhyC.@$F[hoF`hm-Ffhm6#QK3.~Blowing~up~in~the
~positive~y-direction|+F+FfjoFihm>F\\m-%)blow_upyG6&FKFbpF87#7+Fj\lFg^lF8F8F8F_
\pFhyF`\pFa\p>Fg\mF8@$F[hoF`hmFdgn-Ffhm6#QK4.~Blowing~up~in~the~negative~y-dire
ction|+F+FfjoFihm>Fh[m-F_^p6&FKFbpFF7#7+Fj\lFg^lF8FFF8F_\pFhyF`\pFa\p>Fjr-F^[mF
+-F`fm6%FjrFj\lFg^l@$4F\_l>Fjr-F^_mF_s>F]jlFhy>FfjlFhy>Fg\mFhy>F`jlFd\m>FijlFd
\m>F\\mFd\m>Fh[mFd\mFjrF+6)F`jlFijlF\\mFh[mF]jlFfjlFg\mF+F+,
I)blow_upxf*6'F%FbvF`\lF9F:6/F`zFazFbz%#vxG%#vyG%#pgG%#qgG%#tgGF_\lFb\lFcvF`v%&
deltaGF+F+C/>F.&Fj\lF7>FK&Fj\lFH>Fbq&Fj\lFgw>F]sFhy>FbpFhy>F^qFhy>FjrFhy>FioFhy
>F^p-%4optimizepolynomial2G6%F5F\_lFeil?(F+F8F8F+0F^pFhyC*>F`u-%'nltermG6%F^pF
\_lFeil>Fhgm,&-F]]l6$Fhy-F`]l6$F`uF\_lF8FFF8>Fjgm-F]]l6$Fhy-F`]l6$F`uFeil>F\hm,
&*&F.F8FhgmF8F8*&FKF8FjgmF8F8>F]s,&F]sF8*(Fg^lF8-Fi]l6$/F\_lFg^lF`uF8)F\_l,(F\h
mF8F8F8FbqFFF8F8>Fbp,&FbpF8*,Fg^lF8)F\_l,&F\hmF8FbqFFF8FKF8FeilF8F`cpF8FF@$/F\h
mFbqC$>F^q,&F^qF8*&Fg^lF8F`cpF8F8>Fio,&FioF8**Fg^lF8FKF8FeilF8F`cpF8FF>F^p-Feap
6%,&F^pF8F`uFFF\_lFeil>F^p-Feap6%FGF\_lFeil?(F+F8F8F+FhapC)>F`uF[bp>FhgmF`bp>Fj
gm,&FebpF8FFF8>F\hmFjbp>Fbp,&FbpF8*(F.F8FhcpF8F`cpF8F8@$F[dpC$>Fjr,&FjrF8F`cpF8
>Fio,&FioF8*&F.F8F`cpF8F8>F^pFddp7%7$F]sFbpF_fmFioF+F+F+F+,
I)blow_upyf*6&F^ilFfgo%*directionGF[il6*FggoF\boFhhnFihn%$vecGFb\l%$manGF_ilF+F
+C->FK-%/transformationG6'F6FhyF8F8Fhy>F.-Fd[p6'FK7%F[apFi`pF]apFg^lF9F:>FK-Fhf
p6'&F.F7FhyF8F8Fhy@$F[hoF`hm-Ffhm6$Q<blowing~up~vector~field~%a|+F+FK>Fbq-Fi]l6
$Fbdo-Fen6$F8&F.FH>F]s-Fi]l6$Fbdo-F\am6$&F.FgwF:-Ffhm6%QT(0,0)~is~a~singular~po
int~with~eigenvalues~%a,~%a.|+F+F]sFbqFihm@%55-%+reduce_eeqG6$FbqFhy-Fihp6$F]sF
hy-%,reduce_gteqG6$Fhy*&FbqF8F]sF8C)>Fbp*&-Fi]l6%FdcoFbdo-F\am6$-Fen6$FIFagpF9F
8,&FbqF8F]sFFFF>F^q-Fhfp6'FagpF8FhyFbpF8@$F[hoF`hm-Ffhm6#Q[oTransform~this~vect
or~field~so~that~the~linear~part~is~diagonal|+F+-Ffhm6$Q=The~new~vector~field~i
s~%a.|+F+-Fhfp6'F^qFhyF8F8FhyFihm@%-F^hlFjhpC'>Fio-Fbhn6$F^q%-taylor_levelG@$F[
hoF`hm-Ffhm6$Q:unstable~separatrice~x=%aF+-Fi]l6$/Fh`mF:FioFihm@%-F]`oF\ip>Fjr7
)F\_l7$FhyFhy7&FbpF8F8FhyF^qFioF8Fhil>Fjr7)F\_lFi[qFj[qF^qFio-F_bl6&-Fi]l6$Fbdo
F[rF9FbqFg^lFhil@%-F^hl6$FhyFbqC'>FioF[[q@$F[hoF`hm-Ffhm6$Q9stable~separatrice~
x=%a|+F+Fb[qFihm@%Ff[q>Fjr7)F\_lFi[qFj[qF^qFioFIFhil>FjrF\\qC(>Fio-FhaoF\[q@$F[
hoF`hm-Ffhm6$Q6center~manifold~x=%a|+F+-Fi]l6$/F9F:&FioF7-Ffhm6$Q:on~center~man
ifold~y'=%a|+F+-Fi]l6$Fg]q&FioFHFihm@%-F^hlF\ip@%2Fhy-Fi]l6$/F9F8&Fio6#FF>Fjr7)
F\_lFi[qFj[qF^q-Fi]l6$F[]oFh]qFcbmFhil>Fjr7)F\_lFi[qFj[qF^qFj^qFbdmFhil@%Fb^q>F
jr7)F\_lFi[qFj[qF^qFj^qF\emFhil>Fjr7)F\_lFi[qFj[qF^qFj^qF\`mFhil@%Fhjp@%-F]`o6$
FbqF]sC&>FbpFcip>F^qF\jp>Fio-F\]oF\[q>Fjr7)F\_lFi[qFj[qF^qFioFhwFhil>Fjr7)F\_lF
i[q7&FhyF8F8FhyFagpFhyFhwFhil@%Fe_qC&>FbpFcip>F^qF\jp>FioF[`q>Fjr7)F\_lFi[qFj[q
F^qFioFcxFhil>Fjr7)F\_lFi[qF``qFagpFhyFcxFhilOFjrF+F+F+F+,
I,sing_eigenvf*6'FggoF`\l%$lvlGF[ilFihl6.FcvF`vFcoF`]oFa]oF_zF\ilFcfp%#ffGF]ilF
b\lF_ilF+F+C$@%0FfwFhyC'>F^q-%1find_real_roots1G6$FfwF:>FKFd\m?(FbqF8F8-F`p6#Fi
xFdp@%/FeilF8>FK-F`el6%FK-Fen6$FbqFix%&falseG>FK-FdglFabq?(FbqF8F8-F`p6#&F^qFHF
dp@%F^bq>FK-F`el6%FK-Fen6$FbqFjbqFdp>FK-FdglF^cq?(FbqF8F8F`cmFdpC(>Fjr-Fen6$F8&
FKFhfl>F]s-F]\o6$F][l/F:Fjr>Fbp-F]\o6$-F\amFhaqF\dq@$-Fen6$FIFhcqC$>F]s-F3Fhio>
Fbp-F3Fhp@$F[hoF`hm@%3F[ip-Fihp6$FbpFhyC%-Ffhm6$QB(0,%a)~is~a~non-elementary~po
int|+F+FjrFihm-%,blowing_up2G6(F5Fjr,&Fg^lF8F8F8F\_lFeilFdbq@%55F[ipF\eq-F^ip6$
Fhy*&F]sF8FbpF8C0>Fio-F\am6$FjzF9>Fio-Fi]l6%FdcoF\dq*&FioF8,&F]sF8FbpFFFF@$Fbdq
>Fio-F36#Fio>F^p-Fhho6'F5F9F:FhyFjr@$Fbdq>F^p-F3Fcgn>F`u7&F8FhyFioF8>Fhgm-Fhfp6
'F^pF8FhyFioF8@$Fbdq>Fhgm-F3Fjgn-Ffhm6&QS(0,%a)~is~a~singular~point~with~eigenv
alues~%a,%a|+F+FjrF]sFbp-Ffhm6#QAmoving~this~point~to~the~origin|+F+-Ffhm6$Q<th
e~new~vector~field~is~%a|+F+F^p-Ffhm6#Q[otransform~this~vector~field~so~that~th
e~linear~part~is~diagonal|+F+-Ffhm6$F_hqFhgm@%F`^qC%>Fjgm-Fbhn6$FhgmF][q-Ffhm6$
Q;unstable~separatrice~y=%a|+F+-Fi]l6$/Fh`mF9Fjgm@%-F]`oF]eq-Ffhl6)FeilF8F\_l7$
FhyFjrF`uFhgmFjgm-Ffhl6)Feil-F\\l6&-Fi]l6$Fdco&FhgmFHF:F]sFj\lF\_lFdiqF`uFhgmFj
gm@%-F^hl6$FhyF]sC%>FjgmFhhq-Ffhm6$Q9stable~separatrice~y=%a|+F+F]iq@%Faiq-Ffhl
6)FeilFIF\_lFdiqF`uFhgmFjgmFeiqC&>Fjgm-FhaoFihq-Ffhm6$Q6center~manifold~y=%a|+F
+&FjgmF7-Ffhm6$Q=on~center~manifold~is~x'=%a|+F+&FjgmFH@%-F^hlF]eq@%2Fhy-Fd]l6#
-F36#-Fi]l6$Fe^q&FjgmFgw-Ffhl6)FeilFcbmF\_lFdiqF`uFhgm-Fi]l6$F[]oF][r-Ffhl6)Fei
lFbdmF\_lFdiqF`uFhgmF_\r@%Fe[r-Ffhl6)FeilF\emF\_lFdiqF`uFhgmF_\r-Ffhl6)FeilF\`m
F\_lFdiqF`uFhgmF_\r@%F`^qC$-Ffhm6&QS(0,%a)~is~an~unstable~node~with~eigenvalues
~%a,%a|+F+FjrF]sFbp@%-F]`o6$F]sFbpC+>Fio*&F^fqF8FdfqFF>Fio-Fi]l6%FdcoF\dqFio@$F
bdq>FioFgfq>F^pFjfq@$Fbdq>F^pF^gq>F`uF`gq>FhgmFbgq>Fjgm-F\]oFihq-Ffhl6)FeilFhwF
\_lFdiqF`uFhgmFjgm-Ffhl6)FeilFhwF\_lFdiq7&F8FhyFhyF8FjfqFhyC$-Ffhm6&QP(0,%a)~is
~a~stable~node~with~eigenvalues~%a,%a|+F+FjrF]sFbp@%F^]rC+>FioFb]r>FioFd]r@$Fbd
q>FioFgfq>F^pFjfq@$Fbdq>F^pF^gq>F`uF`gq>FhgmFbgq>FjgmF^^r-Ffhl6)FeilFcxF\_lFdiq
F`uFhgmFjgm-Ffhl6)FeilFcxF\_lFdiqFc^rFjfqFhyC-@$F[hoF`hm-Ffhm6#QUx=0~is~a~line~
of~singularities~-~point~is~star-like|+F+>F^q-Fgaq6$F][lF:>FKFd\m?(FbqF8F8F[bqF
dp@%F^bq>FKF`bq>FKFfbq?(FbqF8F8FhbqFdp@%F^bq>FKF]cq>FKFbcq-Ffhm6#QZthe~non-elem
entary~singular~points~(contact~points)~are:|+F+?(FbqF8F8F[bqFdp-Ffhm6$Q((0,%a)
|+F+Fbbq?(FbqF8F8FhbqFdp-Ffhm6$F_arF_cqFihm?(FbqF8F8F`cmFdp-Fceq6(F5FfcqFeeqF\_
lFeilFdpFihmF+F+F+F+,
I-blowing_upy2f*6(F%FfgoF`\lF[ilFihl%%singG6&F\boFggo%#sxG%#syGF+F+C*>F.Fgfp>FK
-Fd[p6'F.F]gpFg^lF9F:>F.-Fhfp6'F[rFhyF8F8Fhy@$F[hoF`hm@%/Fg^lF8-Ffhm6#QHblowing
~up~in~the~positive~y-direction|+F+-Ffhm6#QHblowing~up~in~the~negative~y-direct
ion|+F+-Ffhm6$QAblowing~up~the~vector~field~%a.|+F+F.Fihm@%/FfilFdbqC%>Fbq-Fd]l
6#-F36#-Fi]l6$Fe^q-Fh\l6$-Fi]l6$FbdoFagpF9>F]s-Fd]l6#-F36#-Fi]l6$/F:F8-Fh\l6$-F
i]l6$FdcoF[hpF:@$/FbqF]s@%2FhyFbq-Ffhl6)FeilFhwF\_lFi[qFc^rF.Fh`m-Ffhl6)FeilFcx
F\_lFi[qFc^rF.Fh`mC%@$/F[drFhyYQ^pcase~not~treated:~star-like~points~should~bec
ome~non~star-like~after~second~blowup.F+>FbqFecr@%2Fhy*&Fg^lF8FeilF8-Ffhl6)Feil
,&F^imF8FbqFFF\_lFi[qFc^rF.Fh`m-Ffhl6)Feil,&FaimF8FbqFFF\_lFi[qFc^rF.Fh`mF+F+F+
F+,
I,blowing_up2f*6(F%F\ilF^aqF[ilFihlFiar6(F\boFdgoFegoFfgo%$trfGFggoF+F+C:@$F[ho
-Fahm6$FdhmFchm-Ffhm6$Q5Blowing~up~level~%d|+F+Fg^lF\[p-Ffhm6%Q?blowing~up~%a~i
n~point~(0,%a)|+F+F6Fj\l@%-F]`o6$Fj\lFhyC%>F.-Fhho6'F6F9F:FhyFj\l-Ffhm6$Q=movin
g~(0,%a)~to~the~origin|+F+Fj\l-Ffhm6$Q5new~vector~field~%a|+F+F.>F.F6>FK-FjnFfn
>Fbq-F]vFhn>F]s-F\zFhfl-Ffhm6$Q3Newton~diagram~%a|+F+FK-Ffhm6$Q8[alpha,beta,deg
ree]=%a|+F+F]sFihm@%Fbcr@%F^bqC$>Fbp7+FhyFj\lF8FFF8F[tFhyF]tF[cm-Ffar6(F.F]sFF7
$-Fen6#F\_lFbpFeilFdbqC$>Fbp7+FhyFj\lF8F8F8F[tFhyF]tF[cm-Ffar6(F.F]sF8FbirFeilF
dbq@%F^bqC$>FbpF_ir-Ffar6(F.F]sFFFbirFeilFdpC$>FbpFgir-Ffar6(F.F]sF8FbirFeilFdp
@$F[hoFifr-Ffhm6#QHblowing~up~in~the~positive~x~direction|+F+>F^q-Fd[p6'F.F]sF8
F9F:-Ffhm6$FegpFixFihm>Fbp7+FhyFj\lF8F8F[tFhyF]tF8F[cm-F[\p6'F^qF8Fg^lFbirFeil@
%Fbcr@%F^bqC$>FbpFgirFhirC$F_irF`ir@%F^bqC$>FbpFgirFajrC$F_irF]jr@$F[hoFifr-Ffh
m6#QI---------------------------------------|+F+-Ffhm6$Q2Back~to~level~%d|+F+,&
Fg^lF8FFF8FihmF+F+F+F+,
I(ManXPosFd\mF+,
I(ManXNegFd\mF+,
I(NumXPosFhyF+,
I(NumXNegFhyF+,
I(NumberYFhyF+,
I(ManYPosFd\mF+,
I(ManYNegFd\mF+
