M7R0
I5vec_field_diff_chartf*6%%"fG%"xG%"yG6*%"dG%%f_U1G%%f_V1G%%f_U2G%%f_V2G%$linG%
%singG%(sdegreeG6"F1C4>8$-%$maxG6$-%%ddegG6%&9$6#"""9%9&-F96%&F<6#""#F?F@>8%-%+
optimizevfG6%7$*&)%#z2GF4F>,&*&%#z1GF>-%%subsG6$<$/F?*$FN!""/F@*&FQF>FNFXF;F>FX
-FS6$FUFCF>F>,$*&)FN,&F4F>F>F>F>FRF>FXFQFN>8&-FI6%7$*&FMF>,&*&FQF>-FS6$<$/F?,$F
WFXFYF;F>F>-FS6$FeoFCF>F>*&FinF>FcoF>FQFN>8'-FI6%7$*&FMF>,&-FS6$<$/F?FZ/F@FWF;F
>*&FQF>-FS6$FdpFCF>FXF>,$*&FinF>FhpF>FXFQFN>8(-FI6%7$*&FMF>,&-FS6$<$Fep/F@FgoF;
F>*&FQF>-FS6$FeqFCF>F>F>*&FinF>FhqF>FQFN@$4-%'memberG6$%0all_crit_pointsG<$F>""
$C&-%'writefG6#QCWe~make~use~of~the~Poincare~disc.|+F1-%)openfileG6#%,result_fi
leG-Fer6#QHWe~make~a~study~on~the~Poincare~disc.|+|+F1-Fir6#%)terminalG>8)7$-%4
optimizepolynomial1G6$-FS6$/FN""!&FGF=FQ-Ffs6$-FS6$Fjs&FGFDFQ@%3/&FcsF=F[t/&Fcs
FDF[tC(@$F\rC&-Fer6#QFInfinity~is~a~line~of~singularities.|+F1FhrF[uF_s>FG-FI6%
7$*&F\tF>FNFX*&FatF>FNFXFQFN>F\p-FI6%7$*&&F\pF=F>FNFX*&&F\pFDF>FNFXFQFN>F\o-FI6
%7$*&&F\oF=F>FNFX*&&F\oFDF>FNFXFQFN>F]q-FI6%7$*&&F]qF=F>FNFX*&&F]qFDF>FNFXFQFN>
8*F>>F]wF[t-%,show_chartsG6$7&FGF\oF\pF]q7&Q#U1F1Q#V1F1Q#U2F1Q#V2F1-Fir6#%*vec_
tableG-%0write_vec_fieldG6#-FS6%/FQF?/FNF@FG-F\x6#-FS6%F`xFaxF\o-F\x6#-FS6%F`xF
axF\p-F\x6#-FS6%F`xFaxF]q-Fer6$Q$%d|+F1F]w@%-%%typeG6$,&F4F>FXF>%%evenGC$>8+F[t
-Fer6#Q#1|+F1C$>FiyF>-Fer6#Q$-1|+F1F_s@%F\r@%/F]wF[t-%/find_inf_rootsG6)F4F<FGF
\pF?F@Fiy-%4find_inf_roots_singG6$FGF\p-Fer6#QOSingularities~at~infinity~are~no
t~determined.|+F1F1F1F1F1,
I,show_chartsf*6$%%flstG%(namelstG6$F%%"kGF1F1?(FGF>F>-%%nopsG6#F<%%trueGC%-Fer
6$QJThe~differential~system~on~the~%s~chart:|+F1&F?6#FG>F4-%%evalG6#&F<F_\l-Fer
6%Q<~~~~z1'~=~%a|+~~~~z2'~=~%a|+|+F1&F4F=&F4FDF1F1F1F1,
I.behaviour_inff*6$F%F)64%#p1G%#q1G%#_xG%#_yG%"gG%$jacG%&deltaG%$rhoG%&sigmaG%%
aa10G%%aa01G%%bb10G%"sG%#zzG%$zzbG%#L1G%#L2G%$lypGF1F1C,>F4-FS6$<$/F&*&F\oF>,&*
$F\oFEF>*$F\pFEF>FX/F'*&F\pF>Fg^lFXF;>FG-FS6$Fd^lFC>F]q7$*&)Fg^lF?F>,&*&Fg^lF>F
4F>F>*&F\oF>,&*&F\oF>F4F>F>*&F\pF>FGF>F>F>!"#F>*&Fb_lF>,&*&Fg^lF>FGF>F>*&F\pF>F
f_lF>Fi_lF>>F]q-%)norpoly2G6%F]qF\oF\p>F]q-FI6%-FS6$<$/F\oF&/F\pF'F]qF&F'>Fcs-%
)jacobianG6%F]q/F&F[t/F'F[t>F]wz'6&FetFgt&Fcs6#Fbr&Fcs6#""%\[[[[[[[[\[[mF>[[[\[
[\[[[[[mFX>Fiy,&FetF>FealF>>8,,&*$FiyFEF>F]w!"%@$-%+reduce_lltG6$F[blF[t@%-%+re
duce_eeqG6$FiyF[tC1>8--%&evalfG6#-%&coeffG6%-F^cl6%FivF'F[tF&F>>8.-F[cl6#-F^cl6
%-F^cl6%FivF&F[tF'F>>8/-F[cl6#-F^cl6%-F^cl6%F[wF'F[tF&F>>80-F[cl6#-%%sqrtG6#,&*
&FcclF>F[dlF>FX*$FiblFEFX>F]q7$,&*(F[dlF>-FS6$<#/F&,&*(FcdlF>F\oF>F[dlFXFX*(Fib
lF>F\pF>F[dlFXF>FivF>FcdlFi_lF>*(FiblF>-FS6$FbelF[wF>FcdlFi_lFX*&-FS6$<#/F&,&Fe
elFX*(FiblF>F'F>F[dlFXF>F[wF>FcdlFX>F]q-F[cl6#Fe`l>F]q,&-FS6$<$/F&,&81#F>FE82F
\gl/F'*&^##FXFEF>,&F[glF>F]glFXF>FivF>*&^#F>F>-FS6$FhflF[wF>F>>F]q-F[cl6#-%'exp
andG6#F]q>F]q*&F]qF>-F[cl6#-F^cl6%-F^cl6%-F^cl6%F]qF]glF[tF[glF>FdglF>FX>85-%)l
yapunovG6%,&%#ggGF>*&^#FXF>F[glF>F>F[glF]gl@%0&FhhlF=F[tC)-Fer6$Q>The~order~of~
weakness~is~%d.|+F1&FhhlFD-Fer6$Q>The~lyapunov~constant~is~%g.|+F1,$FbilFXFhrFd
ilFhilF_s@%2FbilF[tC&-Fer6#QBThe~equator~is~weakly~repelling.|+F1FhrF_jlF_sC&-F
er6#QCThe~equator~is~weakly~attracting.|+F1FhrFcjlF_s@%5/&FhhlFdalFE/&FhhlFfalF
>C&-Fer6#QIWe~have~a~center~behaviour~at~infinity.|+F1FhrF][mF_sC&-Fer6$QSThe~o
rder~of~weakness~at~infinity~is~at~least~%d.|+F1,&%/weakness_levelGF>F>F>FhrFa[
mF_sFhr-Fer6#QL##########################################|+F1F_sFf[mC%>83-F[cl6
#,&FiyF\gl-Fgdl6#F[blFagl>84-F[cl6#,&FiyF\glF_\mF\gl@%-%*reduce_gtGFfblC&-Fer6#
Q;The~equator~is~repelling.|+F1FhrFj\mF_sC&-Fer6#Q<The~equator~is~attracting.|+
F1FhrF^]mF_sF1F1F1F1,
I)pl_chartf*6#F%63%"jG%"cGF)%"pG%"qGFb]l%"hGF*F+F,F-%$f_CG%#geG%#gnG%#t1G%#t2G%
#t3GF1F1C9>F\p%'user_pG>F]q%'user_qG@$30F`rF>0F`rFbrC%-Fir6$F[sFas-Fer6%Q^oWe~m
ake~the~study~on~the~Poincare-Lyapunov~disc~of~degree~(%d,%d).|+F1F\pF]qF_s>FG-
%0quasihom_degreeG6'F<F&F'F\pF]q>Fcs,&*&)FNF]qF>-FS6$<$/F&*&F\oF>)FNF\pFX/F'*&F
QF>Ff_mFXFCF>F>*.F\oF>F]qF>F\pFXF\`mF>FQF>-FS6$Fi_mF;F>FX>F]w,$**F\oF>F\pFX)FN,
&F\pF>F>F>F>F``mF>FX>Fiy-FI6%-FS6$/F\oF>7$*&FcsF>)FNFGF>*&F]wF>F_amF>FQFN>F[bl-
FI6%-FS6$/F\oFXF]amFQFN>Fcs,&*&F\`mF>-FS6$<$/F&*&FQF>F\`mFX/F'*&F\oF>Ff_mFXF;F>
F>*.F\oF>F\pF>F]qFXFf_mF>FQF>-FS6$F\bmFCF>FX>F]w,$**F\oF>F]qFX)FN,&F]qF>F>F>F>F
bbmF>FX>FiblFh`m>FcclFbam>Fcs,&*()%"rGFf`mF>%$_coGF>-FS6$<$/F&*&F`cmF>)F_cmF\pF
X/F'*&%$_siGF>)F_cmF]qFXF;F>FX*()F_cmFhbmF>FicmF>-FS6$FccmFCF>FX>F]w,&**F]qF>Ff
cmF>FicmF>FacmF>FX**F\pF>FjcmF>F`cmF>F]dmF>F>>F[dl7$-%)norpoly3G6&*&FcsF>)F_cmF
GF>F_cmF`cmFicm-Ffdm6&*&F]wF>FidmF>F_cmF`cmFicmFhw-F\x6#-FS6$<$/FQF&/FNF'Fiy-F
\x6#-FS6$FaemF[bl-F\x6#-FS6$FaemFibl-F\x6#-FS6$FaemFccl-%9write_vec_field_cylin
derG6#F[dlF_s@$Ff^mCD>Fcs-%1find_real_roots1G6$-FS6$Fjs&FiyF=FQ>FcdlFet>F[glFgt
-Fir6#%)log_fileG-Fer6$F`y,&-Fg[l6#FcdlF>-Fg[l6#F[glF>F_s-Fer6#QJThe~differenti
al~system~on~the~U1~chart:|+F1Fhr-Fer6%Q]oFirst~we~study~the~system~on~the~U1~c
hart~(x=1/z2^%d,y=z1/z2^%d).|+F1F\pF]qFj^m-Fer6%Q;~~~~z1'~=~%a|+~~~~z2'~=~%a|+F
1F[gm&FiyFDF_s?(F4F>F>FdgmFi[lC&>F]gl-Fb\l6$-%%diffG6$F[gmFQ<$/FQ&Fcdl6#F4Fjs>F
[\m-Fb\l6$-Fhhm6$F[gmFNFjhm>Fb\m-Fb\l6$-Fhhm6$FahmFNFjhm-%)type_infG6)FiyF>F\im
F]glF[\mFb\mF[t>%(roundedGFi[l?(F4F>F>FfgmFi[lC&>F]gl-F[cl6#-Fb\l6$Fghm<$/FQ&F[
glF]imFjs>F[\m-F[cl6#-Fb\l6$FaimFdjm>Fb\m-F[cl6#-Fb\l6$FfimFdjm-Fiim6)FiyF>Ffjm
F]glF[\mFb\mF[t>F\jm%-user_numericG>Fcs-Fgfm6$-FS6$Fjs&F[blF=FQ>FcdlFet>F[glFgt
F^gmFagmF_s-Fer6#QJThe~differential~system~on~the~V1~chart:|+F1Fhr-Fer6%Q\oNow~
we~study~the~system~on~the~V1~chart~(x=-1/z2^%d,y=z1/z2^%d).|+F1F\pF]qFj^m-Fer6
%F`hmFj[n&F[blFDF_s?(F4F>F>FdgmFi[lC&>F]gl-Fb\l6$-Fhhm6$Fj[nFQFjhm>F[\m-Fb\l6$-
Fhhm6$Fj[nFNFjhm>Fb\m-Fb\l6$-Fhhm6$Fe\nFNFjhm-Fiim6)F[blFbrF\imF]glF[\mFb\mF[t>
F\jmFi[l?(F4F>F>FfgmFi[lC&>F]gl-Fb\l6$F[]nFdjm>F[\m-Fb\l6$F`]nFdjm>Fb\m-Fb\l6$F
e]nFdjm-Fiim6)F[blFbrFfjmF]glF[\mFb\mF[t>F\jmFd[n@%3-Febl6$-FS6$<$/FQF[tFjs&Fib
lF=F[t-Febl6$-FS6$F^_n&FiblFDF[tC/F^gmFjyF_s-Fer6#QJThe~differential~system~on~
the~U2~chart:|+F1Fhr-Fer6%Q[oNow~we~study~the~system~on~the~U2~chart~(x=z1/z2^%
d,y=1/z2^%d).|+F1F\pF]qFj^m-Fer6%F`hmF`_nFe_nF_s>F]gl-Fb\l6$-Fhhm6$F`_nFQF^_n>F
[\m-Fb\l6$-Fhhm6$F`_nFNF^_n>Fb\m-Fb\l6$-Fhhm6$Fe_nFNF^_n-Fiim6)FiblFEF[tF]glF[
\mFb\mF[tC&F^gm-Fer6#Q#0|+F1F_s-Fer6#QQIn~the~U2~chart,~no~extra~singularity~is
~found.|+F1@%3-Febl6$-FS6$F^_n&FcclF=F[t-Febl6$-FS6$F^_n&FcclFDF[tC/F^gmFjyF_s-
Fer6#QJThe~differential~system~on~the~V2~chart:|+F1Fhr-Fer6%Q\oNow~we~study~the
~system~on~the~V2~chart~(x=z1/z2^%d,y=-1/z2^%d).|+F1F\pF]qFj^m-Fer6%F`hmF]bnFbb
nF_s>F]gl-Fb\l6$-Fhhm6$F]bnFQF^_n>F[\m-Fb\l6$-Fhhm6$F]bnFNF^_n>Fb\m-Fb\l6$-Fhhm
6$FbbnFNF^_n-Fiim6)FcclFgalF[tF]glF[\mFb\mF[tC&F^gmFaanF_s-Fer6#QQIn~the~V2~cha
rt,~no~extra~singularity~is~found.|+F1F16%Fb^mFd^mF\jmF1F1,
I/find_inf_rootsf*6)F)F%F*F,F&F'F06/%$p_dG%$q_dGFg]mFh]mFb]lF[^mF\^m%$totGFe]mF
]^mF^^mF_^mFi]mF1F1CH>F4-%&ntermG6&&F?F=9(9)F<>FG-F\en6&&F?FDF_enF`enF<>F\o-F\e
n6&F^enF_enF`en,&F<F>FXF>>F\p-F\en6&FdenF_enF`enFhen>Fcdl,&-FS6$/F_enF>FGF>*&F`
enF>-FS6$F`fnF4F>FX>F]q-Fgfm6$FcdlF`en>FcsFiv>F]wF[wF^gm-Fer6$F`y,&-Fg[l6#FcsFE
-Fg[l6#F]wFEF_s>Fiy,&F\gnF>F^gnF>FhgmFhr-Fer6#QgnFirst~we~study~the~system~on~t
he~U1~chart~(x=1/z2,y=z1/z2):|+F1Fj^m-Fer6%F`hm&F@F=&F@FDF_s@$%)save_allGC%Fhr-
Fer6#Q9We~change~z1->x,~z2->y.|+F1F_s?(F[blF>F>F\gnFi[lC&>Fibl-Fb\l6$-FhhmFffn/
F`en&FcsF`\m>Fccl-Fb\l6$,&F\pF>*&F`enF>F\oF>FX<$F`fnFehn>F[dl,$-Fb\l6$F4F\inFX-
Fiim6)F@F>FfhnFiblFcclF[dl9*>F\jmFi[l?(F[blF>F>F^gnFi[lC&>Fibl-F[cl6#-Fb\l6$Fdh
n/F`en&F]wF`\m>Fccl-F[cl6#-Fb\l6$Fjhn<$F`fnF\jn>F[dl-F[cl6#,$-Fb\l6$F4FcjnFX-Fi
im6)F@F>F]jnFiblFcclF[dlFcin>F\jmFd[n>Fcdl,&-FS6$/F`enF>F4F>*&F_enF>-FS6$Fa[oFG
F>FX@%-Febl6$-FS6$/F_enF[tFcdlF[t>F]q<#F[t>F]q<"F^gm-Fer6$F`y,$-Fg[lF\hlFEF_s>F
iy,&FiyF>Fb\oF>Fg_nFhr-Fer6#QgnFirst~we~study~the~system~on~the~U2~chart~(x=z1/
z2,y=1/z2):|+F1Fj^m-Fer6%F`hm&9'F=&F[]oFDF_s@$FjgnC%FhrF\hnF_s?(F[blF>F>Fb\oFi[
lC&>Fibl-Fb\l6$-Fhhm6$FcdlF_en/F_en&F]qF`\m>Fccl-Fb\l6$,&F\oF>*&F_enF>F\pF>FX<$
Ff]oFa[o>F[dl,$-Fb\l6$FGF]^oFX-Fiim6)F[]oFEFg]oFiblFcclF[dlFcin@$/FiyF[t-Fer6#Q
KNo~singular~points~at~infinity~are~found.|+F1F16#F\jmF1F1,
I4find_inf_roots_singf*6$F*F,6&Fb]lF[^mF\^mFe]mF1F1C?>F4-%2find_real_roots11G6$
7$-FS6$FjsF;-FS6$FjsFCFQF^gm-Fer6$F`y,&-Fg[l6#Fh\lF>-Fg[l6#Fi\lF>F_s-Fer6%Q^oTh
e~differential~system~on~the~U1~chart:|+~~~~z1'~=~%a|+~~~~z2'~=~%a|+F1F;FCFhr-F
er6#Q^oFirst~we~shall~study~the~system~on~the~U1~chart~(x=1/z2,~y=z1/z2):|+F1-F
er6%F`hmF;FC@$Fjgn-Fer6#Q9~we~change~z1->x,~z2->y|+F1F_s>FGFh\l>F\oFi\l?(F\pF>F
>-Fg[lF_\lFi[l-%*sing_typeG6&-FS6%FbemFcemF<&FG6#F\pF[tF>>F\jmFi[l?(F\pF>F>-Fg[
l6#F\oFi[l-F`ao6&Fbao&F\oFeaoF[tF>>F\jmFd[n@$/,&F^aoF>FhaoF>F[tC%Fj^m-Fer6#QKNo
~singular~points~found~in~the~U1~chart.|+F1F_s@%3-Febl6$-FS6%F__nFjsF^enF[t-Feb
l6$-FS6%F__nFjsFdenF[t>F47#F[t>F47"F^gm-Fer6$F`y-Fg[lF]imF_s-Fer6%Q^oThe~differ
ential~system~on~the~U2~chart:|+~~~~z1'~=~%a|+~~~~z2'~=~%a|+F1F^enFdenFhr-Fer6#
QfnNow~we~study~the~system~on~the~U2~chart~(x=z1/z2,~y=1/z2):|+F1-Fer6%F`hmF^en
Fden@$FjgnFh`oF_s?(F\pF>F>FecoFi[l-F`ao6&-FS6%FbemFcemF?&F4FeaoF[tFE@$/FecoF[tC
%Fj^m-Fer6#QKNo~singular~points~found~in~the~U2~chart.|+F1F_sF1Fi^oF1F1,
I+saddle_inff*6)F%%&chartG%#x0GF]^l%"bGF^^lF06)Ff]m%#ffGFb]lFi]m%'stableG%$sepG
%&stypeGF1F1C4>F4*&F_enF>,&F`enF>F[]oFXFX>FG-%,translationG6'-FS6$FaemF<F&F'F@F
[t>F\o-%/transformationG6'FGF4F>F>F[t>F\p-%.normalizationGFiao>F\p-FI6%F\pF&F'@
%FjgnFj^mF_s-Fer6#QIMoving~this~saddle~point~to~the~origin.|+F1-Fer6$Q=The~new~
vector~field~is~%a.|+F1FG-Fer6#Q\oTransform~this~vector~field~so~that~the~linea
r~part~is~diagonal.|+F1-Fer6$F`goF\o-Fer6$QenMake~a~1000~normalization.|+So~the
~new~vector~field~is~%a.|+F1F\pF_s-Fer6#QJWe~calculate~the~invariant~separatric
es.|+F1@%-Fabl6$F`enF[tC$>F]qF>>F]wFXC$>F]qF[t>F]wF>>Fcs-%)manifoldG6%F\p%-tayl
or_levelGF]q@%/F]qF>C&@$FjgnFj^m-Fer6$Q?The~stable~separatrice~is~%a.|+F17$%"tG
Fcs-Fer6$QAThe~unstable~separatrice~is~%a.|+F17$F[tFbioF_sC&@$FjgnFj^m-Fer6$Fei
oFaio-Fer6$F`ioFfioF_s-%-write_saddleG6,F@F[tF4F>F>F[tF\p7#Fcs7#F]wF?@$3/Fb^mF>
/Fd^mF>C$@%F[io@$0FcinF[t>F]wF>@$Fijo>F]wFX@%/F?F>-F^jo6,F@F[t,$F4FXF>FXF[tF\p7
#-FS6$/Fbio,$FbioFXFcsFajoFbr-F^jo6,F@F[tFa[pF>FXF[tF\pFb[pFajoFgalF1F1F1F1,
I'se_inff*F]eo6.Fi]mFf]mFbeoFb]l%#s1G%"mG%#amGFeeo%+center_sepGFdeo%#hhGFceoF1F
1C:>FGFheo>F\oF[fo>F\p-Fbfo6'F\oFGF>F>F[t>F4-FffoFeao>F4-FI6%F4F&F'Fj^m-Fer6%QO
The~point~(%a,%a)~is~a~semi~hyperbolic~point.|+F1F@F[t@%FjgnFj^mF_s-Fer6#QBMovi
ng~this~point~to~the~origin.|+F1FdgoFago-Fer6$F`goF\p-Fer6$FhgoF4F_sFigo@%-Febl
6$F[]oF[tC*@%F]ho>F[dlF>>F[dlF[t>Fibl-Fgho6%F4FihoF[dl>F]q-FS6$<$/FQ,&F&F>F>F>F
jsF;>F]q-Ffs6$F]qF&>F]q-%+first_termGFi^p>Fcs-%'degreeGFi^p>F]w-%%signG6#-F[cl6
#-FS6$/F&F>F]q@%-Fcy6$FcsFfy@%2F[tF]w@%/F[dlF[t>Fiy7$F>F[t>Fiy7$FEF[t@%F_`p>Fiy
7$FbrF[t>Fiy7$FgalF[t@%F]`p@%F_`p>Fiy7$""&F[t>Fiy7$""'F[t@%F_`p>Fiy7$""(F[t>Fiy
7$"")F[tC&@%-FablFi]p>F[dlF>>F[dlF[t>F[bl-%0center_manifoldGF`^p>Fibl-FS6$/F&Fb
ioFj[n>Fiy7$&F[blFdalF>Fj^m@$-F^r6$F[gm<&F>FEFbrFgal-Fer6#Q=The~point~is~a~sadd
le-node.|+F1@$/F[gmF]ap-Fer6#Q@The~point~is~an~unstable~node.|+F1@$/F[gmFgap-Fe
r6#Q>The~point~is~a~~stable~node.|+F1@$-F^r6$F[gm<$F`apFdap-Fer6#Q8The~point~is
~a~saddle.|+F1F_s-%6write_semi_elementaryG6,F@F[tFGF>F>F[tF4Fiy7#FiblF?@$FcjoC%
@%/FcinF[t>Fiy7$-%#opG6$F[gm7*FbrFgalF>FEF]apF`apFdapFgapFahm>Fiy7$-Fjdp6$F[gm7
*FEF>FgalFbrFgapFdapF`apF]apFahm>Fccl7$-Fb\l6#*&)FXFcinF>Fh\lF>-Fb\l6#*&FgepF>F
i\lF>@%F^[p-F`dp6,F@F[tFGF>F>F[tFcclFiyFbdpFbr-F`dp6,F@F[tFGF>F>F[tFcclFiyFbdpF
galF1F1F1F1,
I)type_inff*F]eo6&%"LG%-lambda_ratioG%1lambda_ratio_numG%1lambda_ratio_denGF1F1
@%3Fh]p-FeblF^hoC&Fj^m-Fer6%Q;(%a,%a)~is~nonelementary.|+F1F@F[tF_s-%'de_infG6&
F<F?F@Fcin@%5Fh]pFifp-Fi[p6)F<F?F@F[]oF_enF`enFcin@%-Fabl6$*&F[]oF>F`enF>F[tC(F
j^m-Fer6%Q6(%a,%a)~is~a~saddle.|+F1F@F[t@%2-%$absG6#-F[cl6#F`en-F`hp6#-F[cl6#F[
]o>FG*&F[]oF>F`enFX>FG*&F`enF>F[]oFX@%334F\jm-Fcy6$F[]o%(integerG-Fcy6$F`enFbip
C)>F\o-%&numerGF_\l>F\p-%&denomGF_\lF_s-Fer6%QHThe~ratio~between~eigenvalues~is
~%a:%a|+F1F\pF\oFhrF\jpF_sC*>FG-%(convertG6$-F[clF_\l%)rationalG>F\oFgip>F\pFji
pF_s-Fer6%QXThe~ratio~between~eigenvalues~is~%a:%a~(approximation)|+F1F\pF\oFhr
FhjpF_sF_s-F[eoFdgpC(>F4-Fb_pFahp@%2F[tF4C%Fj^m-Fer6%Q>(%a,%a)~is~an~unstable~n
ode.|+F1F@F[tF_sC%Fj^m-Fer6%Q;(%a,%a)~is~a~stable~node.|+F1F@F[tF_s@%F^hp>FGFih
p>FGF[ip@%F]ipC)>F\oFgip>F\pFjipF_sF\jpFhrF\jpF_sC*>FGFajp>F\oFgip>F\pFjipF_sFh
jpFhrFhjpF_s-%+write_nodeG6&F@F[tF4F?@$FcjoC$@$Fijo>F4Fa[p@%F^[p-Fe\q6&F@F[tF4F
br-Fe\q6&F@F[tF4FgalF1F1F1F1,
I'de_inff*6&F%F^eoF_eoF06#%+trajectorsGF1F1C'-Fer6%QMThe~point~(%a,%a)~is~a~non
elementary~point.|+F1F@F[t-Fer6#Q>Blowing~up~the~vector~field.|+F1>F4-%+blowing
_upG6&F^foF@F[t%&falseG-%1write_degenerateG6&F@F[tFh\lF?@$FcjoC%-Fer6$Q,Degree=
%d.|+F1F[]o@%/F[]oF[t>F4Fi\l>F4-%,change_stabGF^`o@%F^[p-Fb^qF]]q-Fb^qF_]qF1F1F
1F1,
I,change_stabf*6#Fdeo6(Fe]mFd]qFd[l%"aGF`eoFf]mF1F1C%>FGFbco?(F4F>F>Ff[lFi[lC&>
F\pFbco>F]q&F<F]im?(F\oF>F>Fb\oFi[l@%0F\oF`ap>F\p7$-FjdpFeao-Fjdp6$F\oF]qC%>Fcs
Fd`q@%-F^r6$Fcs<&F>Fbr""*"#5>FcsFE@%-F^r6$Fcs<&FEFgal"#6"#7>FcsF>@%-F^r6$Fcs<$F
]apFdap>FcsF`ap>FcsF]ap>F\p7$Fc`qFcs>FG7$-FjdpF_\lF\pFGF1F1F1F1
