M7R0
I-user_numeric%&falseG6",
I/user_precision"")F$,
I0user_precision0""!F$,
I(epsilon$"""!"#F$,
I)test_sepF(F$,
I-taylor_level"#5F$,
I.numeric_levelF/F$,
I*max_levelF/F$,
I/weakness_level""&F$,
I#x0F(F$,
I#y0F(F$,
I&x_min!""F$,
I&y_minF7F$,
I&x_maxF+F$,
I&y_maxF+F$,
I'user_pF+F$,
I'user_qF+F$,
I'user_f7$F(F(F$,
I)user_gcfF(F$,
I+user_curveGF$,
I0all_crit_pointsF(F$,
I)save_allF#F$,
I*vec_tableQ-TEST_VEC.TABF$F$,
I-finite_tableQ-TEST_FIN.TABF$F$,
I+finite_resQ-TEST_FIN.RESF$F$,
I/infinite_tableQ-TEST_INF.TABF$F$,
I-infinite_resQ-TEST_INF.RESF$F$,
I,hamiltonianF#F$,
I.ishamiltonianf*6#%#vfG6#%%exprGF$F$C$>8$-%)norpoly2G6%,&-%%diffG6$&9$6#F+%"xG
F+-Ffn6$&Fin6#""#%"yGF+F[oFao@%%(roundedG@%/-%&evalfG6#FV$F(F(%%trueGF#@%/FVF(F
joF#F$F$F$F$,
I'p4mainf*F$6*%#gcG%$gcfG%*gcdresultG%'orig_fG%"gG%#geG%#gnG%"jGF$F$C=>%+normal
exitGF(>FcoF"@%0F'F(>%'DigitsGF'>F_q-%&floorG6#-%'evalhfG6#F_q@$1F_qF%C$-%'writ
efG6%Q\pPlease~increase~precision~or~decrease~accuracy.~Precision~=~%d~<=~Accur
acy~=~%d.|+F$F_qF%-%%quitGFjn@$55/-%6CheckIfGoodPolynomialG6#&F=FjnF#/-Fer6#&F=
F_oF#/-Fer6#F?F#C$-F[r6#QipThe~system~is~not~well-defined~(not~polynomial,~or~c
oefficients~do~not~evaluate~numerically.)|+F$F^r-F[r6#QGLET~US~STUDY~THE~DIFFER
ENTIAL~SYSTEM:|+F$-F[r6%Q:~~~~x'~=~%a|+~~~~y'~=~%a|+|+F$FgrF[s-%)openfileG6#FC-
F[r6&Q*%d|+%d|+%d|+F$FAF;F<@$/FA""$-F[r6'Q1~~~~%g~%g~%g~%g|+F$F6F9F8F:-Fjs6#%)t
erminalG@%/F?F(C'>8'F=>8&-%'my_gcdG6$FgrF[s>FV&F^uF_o>F?&F^u6#Fat>F=-%)simplify
G6#&F^uFjnC&>FVF`o>F\uF=>F=7$-Fiu6#*&&F\uFjnF+F?F7-Fiu6#*&&F\uF_oF+F?F7@$FbrC$-
F[r6#QNError:~The~given~gcf~is~not~a~common~factor.|+F$F^r-%*write_gcfGF^sFis-%
0write_vec_fieldG6#F=Fet@%-FNFbwC$-F[r6#Q<The~system~is~Hamiltonian.|+F$>FMFjo>
FMF#@$4-%'memberG6$FA<$F`oFatC.>%)log_fileGFE>%,result_fileGFG-F[r6#QOLET~US~ST
UDY~THE~SYSTEM~AT~THE~FINITE~REGION|+|+F$-Fjs6#FexFcs-F[r6%Q9~~~~x'~=~%a|+~~~~y
'~=~%a|+F$FdvFhv-F[r6#Q6AT~THE~FINITE~REGION|+F$@$5/FVF+3/FVF`o0F?F+C%-F[r6$QDT
he~system~has~a~common~factor:~%a|+F$F?-F[r6$QJHence~we~shall~study~the~reduced
~system:|+F$F?-F[r6%F]yFgrF[sFet@%4F"C->8(-%0find_real_rootsG6%F=F[oFao>8)&FdzF
jn>8*&FdzF_o-Fjs6#Fcx-F[r6$Q$%d|+F$,&-%%nopsG6#FizF+-Fe[l6#F\[lF+Fet-F[r6#QZ---
-----------------------------------------------------|+F$?(8+F+F+Fd[lFjo-%*sing
_typeG6&F=-%#opG6$F+&Fiz6#F]\l-Fb\l6$F`oFd\lF(>FcoFjo?(F]\lF+F+Fg[lFjo-F_\l6&F=
-Fb\l6$F+&F\[lFe\l-Fb\l6$F`oF^]lF(>FcoF"C(>F\[l-%8find_real_roots_numericGFgzF^
[l-F[r6$Fb[lFg[lFetFi[l?(F]\lF+F+Fg[lFjoFj\l-%*closefileGF_[l-Fj]lFjx@$4-F^x6$F
A<$F+FatC*>FcxFI>FexFK-F[r6#QFLET~US~STUDY~THE~SYSTEM~AT~INFINITY|+|+F$Fcs@%Fey
-F[r6%F]y*&F?F+FgrF+*&F?F+F[sF+F[y-F[r6#Q-AT~INFINITY|+F$@$FbyC%FhyF[zF^zFet@%3
/F;F+/F<F+-%5vec_field_diff_chartGFgz-%)pl_chartGFbw@$F]^lC$Fi]lF[^l-Fj]lF[t@$F
`tC/>FcxFE>FexFGF^[l-F[r6$Fb[lF+Fet-F[r6#QIWe~shall~study~the~differential~syst
em:|+F$@%FeyFh^lF[y-F[r6%Q7in~the~point~(%a,%a).|+F$F4F5@$FbyC%FhyF[zF^zFet-F_
\l6&F=F4F5F(Fi]lF[^lFet-F[r6#QR|+We~have~finished~the~study~of~the~vector~field
.|+F$-%.closeallfilesGF$>FjpF+F$6+FcoF=F?F;F<FMFcxFexFjpF$F$,
I-prepareCurvef*F$F$F$F$C&-Fjs6#%,curve_tableG-%,write_curveG6#F@-F[r6#Qgn|+We~
have~finished~writing~the~curve~as~a~C++~readable~list.|+F$>FjpF+F$6$F@FjpF$F$,
I1prepareIsoclinesf*F$F$F$F$C&-Fjs6#%0isoclines_tableG-%0write_isoclinesG6#%/us
er_isoclinesG-F[r6#Qjn|+We~have~finished~writing~the~isoclines~as~C++~readable~
lists.|+F$>FjpF+F$6$F[clFjpF$F$,
I6CheckIfGoodPolynomialf*6#%"fGF$F$F$O-%%typeG6$-Fgo6#Fin-%(polynomG6$%(numeric
G7$F[oFaoF$F$F$F$,
I+normalexitF(F$,
I/user_exeprefixQ(cmd~/c~F$F$
