M7R0
I3chooseParameterSetf*6#%"rG6#%"kG6"F(C$?(8$"""F,-%%nopsG6#%0user_parametersG%%
trueG-%)unassignG6#-%(convertG6$&F06#F+%%nameG?(F+F,F,F-F1-%'assignG6$F5&-F66$-
%$catG6$F8Q'piecesF(F:6#9$F(F(F(F(,
I.ishamiltonianf*6#%#vfG6#%%exprGF(F(C$>F+-%)norpoly2G6%,&-%%diffG6$&FG6#F,%"xG
F,-FU6$&FG6#""#%"yGF,FYFin@%%(roundedG@%/-%&evalfGF9$""!FaoF1%&falseG@%/F+FaoF1
FboF(F(F(F(,
I'p4mainf*F(6,%#gcG%$gcfG%*gcdresultG%'orig_fG%"gG%#geG%#gnG%"jG%"iGF%F(F(C5>%*
numpiecesG-F.6#%.user_f_piecesG>%*numcurvesG-F.6#%,user_curvesG@$5/FcpFao4-%%ty
peG6$Ffp%%listGC$>Ffp7#%'user_fG>FcpF,>%+normalexitGFao@%0%0user_precision0GFao
>%'DigitsGF]r>F_r-%&floorG6#-%'evalhfG6#F_r@$1F_r%/user_precisionGC$-%'writefG6
%Q\pPlease~increase~precision~or~decrease~accuracy.~Precision~=~%d~<=~Accuracy~
=~%d.|+F(F_rFir-%%quitGFX-%)openfileG6#%*vec_tableG-F\s6#Q$P5|+F(-F\s6%Q'%d~%d|
+F(FcpFhp-F\s6&Q*%d|+%d|+%d|+F(%0all_crit_pointsG%'user_pG%'user_qG@$/F^t""$-F
\s6'Q1~~~~%g~%g~%g~%g|+F(%&x_minG%&x_maxG%&y_minG%&y_maxG-Fbs6#%)terminalG?(8-F
,F,FhpF1C$@$5-Faq6$&F[q6#F_u%)equationG-Faq6$Feu%#<=G>Feu,&-%$lhsG6#FeuF,-%$rhs
GF_v!""@$/-%6CheckIfGoodPolynomialGF_vFboC$-F\s6%Q[rThe~separating~curve~#%d:~%
a~is~not~well-defined~(not~polynomial,~or~coefficients~do~not~evaluate~numerica
lly.)|+F(F_uFeuF_s@$2FaoFhp?(F_uF,F,FhpF1C&>F[oF1>Fir"")Fas-%*write_gcfGF_v@$F
\wC(Fas-F\s6$Q$%d|+F(-F.6#%*vfregionsG@$2FaoFiw?(8+F,F,FiwF1C$-F\s6$Q#%dF(&&F[x
6#F_xFX?(F_uF,F,FhpF1C$-F\s6$Q$~%dF(&&FexFgnFfu@$/F_uFhp-F\s6#Q"|+F(Fas-F\s6$Fh
w-F.6#%-curveregionsG@$2FaoFey?(F_xF,F,FeyF1C$-F\s6$Fcx&&FgyFfxFX?(F_uF,F,FhpF1
C$-F\s6$F[y&&F_zFgnFfu@$F_yF`yF[u?(8,F,F,FcpF1CE-%3ChooseParameterSetG6#Fhz@$-F
aq6$%4user_numeric_piecesGFcq>%-user_numericG&F`[lF\[l@$-Faq6$%6user_precision_
piecesGFcq>Fir&Fg[lF\[l@$-Faq6$%/epsilon_piecesGFcq>%(epsilonG&F]\lF\[l@$-Faq6$
%0test_sep_piecesGFcq>%)test_sepG&Fd\lF\[l@$-Faq6$%4taylor_level_piecesGFcq>%-t
aylor_levelG&F[]lF\[l@$-Faq6$%5numeric_level_piecesGFcq>%.numeric_levelG&Fb]lF
\[l@$-Faq6$%1max_level_piecesGFcq>%*max_levelG&Fi]lF\[l@$-Faq6$%6weakness_level
_piecesGFcq>%/weakness_levelG&F`^lF\[l@$-Faq6$%*x0_piecesGFcq>%#x0G&Fg^lF\[l@$-
Faq6$%*y0_piecesGFcq>%#y0G&F^_lF\[l@$F`q>Fgq&FfpF\[l@$-Faq6$%0user_gcf_piecesGF
cq>%)user_gcfG&Fh_lF\[l>F[oFb[l@$55/-Ffv6#&FgqFXFbo/-Ffv6#&FgqFgnFbo/-Ffv6#Fj_l
FboC$-F\s6$Q]qThe~system~#%d~is~not~well-defined~(not~polynomial,~or~coefficien
ts~do~not~evaluate~numerically.)|+F(FhzF_s-F\s6#QGLET~US~STUDY~THE~DIFFERENTIAL
~SYSTEM:|+F(-F\s6%Q:~~~~x'~=~%a|+~~~~y'~=~%a|+|+F(Fc`lFg`lFasF[t@$FbtFdtF[u@%/F
j_lFaoC'>8'Fgq>8&-%'my_gcdG6$Fc`lFg`l>F+&F\blFgn>Fj_l&F\bl6#Fct>Fgq-%)simplifyG
6#&F\blFXC&>F+Fhn>FjalFgq>Fgq7$-Fgbl6#*&&FjalFXF,Fj_lFbv-Fgbl6#*&&FjalFgnF,Fj_l
Fbv@$F_`lC$-F\s6#QNError:~The~given~gcf~is~not~a~common~factor.|+F(F_s-FcwFj`lF
as-%0write_vec_fieldG6#FgqF[u@%-FHF_dlC$-F\s6#Q<The~system~is~Hamiltonian.|+F(>
%,hamiltonianGF1>FgdlFbo@$4-%'memberG6$F^t<$FhnFctC0>%)log_fileG%-finite_tableG
>%,result_fileG%+finite_resG@$2F,FcpC'-Fbs6#Fdel-F\s6#Q^p|+|+\/\/\/\/\/\/\/\/\/
\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/|+F(-F\s6$QE~~~~~
~~~~~~~~~~~~~~~~~~~~~PIECE~#%d|+F(Fhz-F\s6#Q]p\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/|+|+F(F[u-F\s6#QOLET~US~STUDY~T
HE~SYSTEM~AT~THE~FINITE~REGION|+|+F(FielF_al-F\s6%Q9~~~~x'~=~%a|+~~~~y'~=~%a|+F
(FbclFfcl-F\s6#Q6AT~THE~FINITE~REGION|+F(@$/-%0quasihom_degreeG6'FgqFYFinF_tF`t
,$%)infinityGFbvC%-Fbs6$FdelF]u-F\s6#QEError:~The~given~vector~field~is~0!|+F(F
_s@$5/F+F,3/F+Fhn0Fj_lF,C%-F\s6$QDThe~system~has~a~common~factor:~%a|+F(Fj_l-F
\s6$QJHence~we~shall~study~the~reduced~system:|+F(Fj_l-F\s6%FiflFc`lFg`lF[u@%4F
b[lC->8(-%0find_real_rootsG6%FgqFYFin>8)&F]ilFX>8*&F]ilFgn-Fbs6#Fael-F\s6$Fhw,&
-F.6#FbilF,-F.6#FeilF,F[u-F\s6#QZ----------------------------------------------
----------|+F(?(F_xF,F,F\jlF1-%*sing_typeG6&Fgq-%#opG6$F,&FbilFfx-Fhjl6$FhnFjjl
Fao>F[oF1?(F_xF,F,F^jlF1-Fejl6&Fgq-Fhjl6$F,&FeilFfx-Fhjl6$FhnFc[mFao>F[oFb[lC(>
Feil-%8find_real_roots_numericGF`ilFgil-F\s6$FhwF^jlF[uF`jl?(F_xF,F,F^jlF1F_[m-
%*closefileGFhil-F_\mFjel@$4-F\el6$F^t<$F,FctC,>Fael%/infinite_tableG>Fdel%-inf
inite_resG@$FgelC&FielF[flF^flFaflFegl-F\s6#QFLET~US~STUDY~THE~SYSTEM~AT~INFINI
TY|+|+F(F_al@%F^hl-F\s6%Fifl*&Fj_lF,Fc`lF,*&Fj_lF,Fg`lF,Fgfl-F\s6#Q-AT~INFINITY
|+F(@$F[hlC%FahlFdhlFghlF[u@%3/F_tF,/F`tF,-%5vec_field_diff_chartGF`il-%)pl_cha
rtGF_dl@$Fb\mC$F^\mF`\m-F_\mFcs@$FbtC/>FaelFbel>FdelFeelFgil-F\s6$FhwF,F[u-F\s6
#QIWe~shall~study~the~differential~system:|+F(@%F^hlFa]mFgfl-F\s6%Q7in~the~poin
t~(%a,%a).|+F(Fi^lF`_l@$F[hlC%FahlFdhlFghlF[u-Fejl6&FgqFi^lF`_lFaoF^\mF`\mF[u-F
\s6#QR|+We~have~finished~the~study~of~the~vector~field.|+F(-%.closeallfilesGF(>
FjqF,F(69F[oFgqFj_lF_tF`tFcpFhpFgdlFaelFdelFjqFb[lFirF_\lFf\lF]]lFd]lF[^lFb^lFi
^lF`_lFfpF[qF(F(,
I6CheckIfGoodPolynomialf*6#%"fGF(F(F(O-Faq6$-F_oFF-%(polynomG6$%(numericG7$FYFi
nF(F(F(F(,
I+normalexitFaoF(,
I-prepareCurvef*F(F(F(F(C&-Fbs6#%,curve_tableG-%,write_curveG6#%+user_curveG-F
\s6#Qgn|+We~have~finished~writing~the~curve~as~a~C++~readable~list.|+F(>FjqF,F(
6$FdamFjqF(F(,
I1prepareIsoclinesf*F(F(F(F(C&-Fbs6#%0isoclines_tableG-%0write_isoclinesG6#%/us
er_isoclinesG-F\s6#Qjn|+We~have~finished~writing~the~isoclines~as~C++~readable~
lists.|+F(>FjqF,F(6$FcbmFjqF(F(
