M7R0
I3chooseParameterSetf*6#%"rG6#%"kG6"F(C$?(8$"""F,-%%nopsG6#%0user_parametersG%%
trueG-%)unassignG6#-%(convertG6$&F06#F+%%nameG?(F+F,F,F-F1-%'assignG6$F5&-F66$-
%$catG6$F8Q(_piecesF(F:6#9$F(F(F(F(,
I.ishamiltonianf*6#%#vfG6#%%exprGF(F(C$>F+-%)norpoly2G6%,&-%%diffG6$&FG6#F,%"xG
F,-FU6$&FG6#""#%"yGF,FYFin@%%(roundedG@%/-%&evalfGF9$""!FaoF1%&falseG@%/F+FaoF1
FboF(F(F(F(,
I'p4mainf*F(6,%#gcG%$gcfG%*gcdresultG%'orig_fG%"gG%#geG%#gnG%"jG%"iGF%F(F(C7>%*
numpiecesG-F.6#%.user_f_piecesG>%*numcurvesG-F.6#%,user_curvesG@$5/FcpFao4-%%ty
peG6$Ffp%%listGC$>Ffp7#%'user_fG>FcpF,>%+normalexitGFao-%)openfileG6#%)terminal
G-%'writefG6$Q4user_precision0=%a|+F(%0user_precision0G-%*closefileGF]r@%0FcrFa
o>%'DigitsGFcr>Fir-%&floorG6#-%'evalhfG6#Fir-F\r6#%*vec_tableG-F`r6#Q$P5|+F(-F`
r6%Q'%d~%d|+F(FcpFhp-F`r6&Q*%d|+%d|+%d|+F(%0all_crit_pointsG%'user_pG%'user_qG@
$/F]t""$-F`r6'Q1~~~~%g~%g~%g~%g|+F(%&x_minG%&x_maxG%&y_minG%&y_maxGF[r?(8-F,F,F
hpF1C$@$5-Faq6$&F[q6#F[u%)equationG-Faq6$Fau%#<=G>Fau,&-%$lhsG6#FauF,-%$rhsGF[v
!""@$/-%6CheckIfGoodPolynomialGF[vFboC$-F`r6%Q[rThe~separating~curve~#%d:~%a~is
~not~well-defined~(not~polynomial,~or~coefficients~do~not~evaluate~numerically.
)|+F(F[uFau-%%quitGFX@$2FaoFhp?(F[uF,F,FhpF1C&>F[oF1>%/user_precisionG"")Fas-%*
write_gcfGF[v@$FjvC(Fas-F`r6$Q$%d|+F(-F.6#%*vfregionsG@$2FaoFhw?(8+F,F,FhwF1C$-
F`r6$Q#%dF(&&Fjw6#F^xFX?(F[uF,F,FhpF1C$-F`r6$Q$~%dF(&&FdxFgnFbu@$/F[uFhp-F`r6#Q
"|+F(Fas-F`r6$Fgw-F.6#%-curveregionsG@$2FaoFdy?(F^xF,F,FdyF1C$-F`r6$Fbx&&FfyFex
FX?(F[uF,F,FhpF1C$-F`r6$Fjx&&F^zFgnFbu@$F^yF_yF[r?(8,F,F,FcpF1CB-F"6#Fgz@$-Faq6
$%4user_numeric_piecesGFcq>%-user_numericG&F^[lFjz@$-Faq6$%6user_precision_piec
esGFcq>F_w&Fe[lFjz@$1FirF_wC$-F`r6&Q[qPlease~increase~precision~or~decrease~acc
uracy~for~region~#%d.~Precision~=~%d~<=~Accuracy~=~%d.|+F(FgzFirF_wFgv@$-Faq6$%
/epsilon_piecesGFcq>%(epsilonG&Fa\lFjz@$-Faq6$%0test_sep_piecesGFcq>%)test_sepG
&Fh\lFjz@$-Faq6$%4taylor_level_piecesGFcq>%-taylor_levelG&F_]lFjz@$-Faq6$%5nume
ric_level_piecesGFcq>%.numeric_levelG&Ff]lFjz@$-Faq6$%1max_level_piecesGFcq>%*m
ax_levelG&F]^lFjz@$-Faq6$%6weakness_level_piecesGFcq>%/weakness_levelG&Fd^lFjz@
$-Faq6$%*x0_piecesGFcq>%#x0G&F[_lFjz@$-Faq6$%*y0_piecesGFcq>%#y0G&Fb_lFjz@$F`q>
Fgq&FfpFjz@$-Faq6$%0user_gcf_piecesGFcq>%)user_gcfG&F\`lFjz>F[oF`[l@$55/-Fbv6#&
FgqFXFbo/-Fbv6#&FgqFgnFbo/-Fbv6#F^`lFboC$-F`r6$Q]qThe~system~#%d~is~not~well-de
fined~(not~polynomial,~or~coefficients~do~not~evaluate~numerically.)|+F(FgzFgv-
F`r6#QGLET~US~STUDY~THE~DIFFERENTIAL~SYSTEM:|+F(-F`r6%Q:~~~~x'~=~%a|+~~~~y'~=~%
a|+|+F(Fg`lF[al@%/F^`lFaoC'>8'Fgq>8&-%'my_gcdG6$Fg`lF[al>F+&F_blFgn>F^`l&F_bl6#
Fbt>Fgq-%)simplifyG6#&F_blFXC&>F+Fhn>F]blFgq>Fgq7$-Fjbl6#*&&F]blFXF,F^`lF^v-Fjb
l6#*&&F]blFgnF,F^`lF^v@$Fc`lC$-F`r6#QNError:~The~given~gcf~is~not~a~common~fact
or.|+F(Fgv-FbwF^alFas-%0write_vec_fieldG6#FgqF[r@%-FHFbdlC$-F`r6#Q<The~system~i
s~Hamiltonian.|+F(>%,hamiltonianGF1>FjdlFbo@$4-%'memberG6$F]t<$FhnFbtC0>%)log_f
ileG%-finite_tableG>%,result_fileG%+finite_resG@$2F,FcpC'-F\r6#Fgel-F`r6#Q^p|+|
+\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
\/|+F(-F`r6$QE~~~~~~~~~~~~~~~~~~~~~~~~~~PIECE~#%d|+F(Fgz-F`r6#Q]p\/\/\/\/\/\/\/
\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/|+|+F(F[r-F`r
6#QOLET~US~STUDY~THE~SYSTEM~AT~THE~FINITE~REGION|+|+F(F\flFcal-F`r6%Q9~~~~x'~=~
%a|+~~~~y'~=~%a|+F(FeclFicl-F`r6#Q6AT~THE~FINITE~REGION|+F(@$/-%0quasihom_degre
eG6'FgqFYFinF^tF_t,$%)infinityGF^vC%-F\r6$FgelF^r-F`r6#QEError:~The~given~vecto
r~field~is~0!|+F(Fgv@$5/F+F,3/F+Fhn0F^`lF,C%-F`r6$QDThe~system~has~a~common~fac
tor:~%a|+F(F^`l-F`r6$QJHence~we~shall~study~the~reduced~system:|+F(F^`l-F`r6%F
\glFg`lF[alF[r@%4F`[lC->8(-%0find_real_rootsG6%FgqFYFin>8)&F`ilFX>8*&F`ilFgn-F
\r6#Fdel-F`r6$Fgw,&-F.6#FeilF,-F.6#FhilF,F[r-F`r6#QZ---------------------------
-----------------------------|+F(?(F^xF,F,F_jlF1-%*sing_typeG6&Fgq-%#opG6$F,&Fe
ilFex-F[[m6$FhnF][mFao>F[oF1?(F^xF,F,FajlF1-Fhjl6&Fgq-F[[m6$F,&FhilFex-F[[m6$Fh
nFf[mFao>F[oF`[lC(>Fhil-%8find_real_roots_numericGFcilFjil-F`r6$FgwFajlF[rFcjl?
(F^xF,F,FajlF1Fb[m-FerF[jl-FerF]fl@$4-F_el6$F]t<$F,FbtC,>Fdel%/infinite_tableG>
Fgel%-infinite_resG@$FjelC&F\flF^flFaflFdflFhgl-F`r6#QFLET~US~STUDY~THE~SYSTEM~
AT~INFINITY|+|+F(Fcal@%Fahl-F`r6%F\gl*&F^`lF,Fg`lF,*&F^`lF,F[alF,Fjfl-F`r6#Q-AT
~INFINITY|+F(@$F^hlC%FdhlFghlFjhlF[r@%3/F^tF,/F_tF,-%5vec_field_diff_chartGFcil
-%)pl_chartGFbdl@$Fd\mC$Fa\mFb\m-FerFbs@$FatC/>FdelFeel>FgelFhelFjil-F`r6$FgwF,
F[r-F`r6#QIWe~shall~study~the~differential~system:|+F(@%FahlFc]mFjfl-F`r6%Q7in~
the~point~(%a,%a).|+F(F]_lFd_l@$F^hlC%FdhlFghlFjhlF[r-Fhjl6&FgqF]_lFd_lFaoFa\mF
b\mF[r-F`r6#QR|+We~have~finished~the~study~of~the~vector~field.|+F(-%.closeallf
ilesGF(>FjqF,F(6:F[oFgqF^`lF^tF_tFcpFhpFjdlFdelFgelFjqF`[lF_wFcrFc\lFj\lFa]lFh]
lF_^lFf^lF]_lFd_lFfpF[qF(F(,
I6CheckIfGoodPolynomialf*6#%"fGF(F(F(O-Faq6$-F_oFF-%(polynomG6$%(numericG7$FYFi
nF(F(F(F(,
I+normalexitFaoF(,
I6prepareArbitraryCurvef*F(F(F(F(C)>F[oF`[l-F\r6#%,curve_tableG-%,write_curveG6
#%+user_curveG-FerFbamF[r-F`r6#Qgn|+We~have~finished~writing~the~curve~as~a~C++
~readable~list.|+F(>FjqF,F(6%FgamFjqF[oF(F(,
I1prepareIsoclinesf*F(F(F(F(C&-F\r6#%0isoclines_tableG-%0write_isoclinesG6#%/us
er_isoclinesG-F`r6#Qjn|+We~have~finished~writing~the~isoclines~as~C++~readable~
lists.|+F(>FjqF,F(6$FgbmFjqF(F(
