M7R0
I3chooseParameterSetf*6#%"rG6#%"kG6"F(C$?(8$"""F,-%%nopsG6#%0user_parametersG%%
trueG-%)unassignG6#-%(convertG6$&F06#F+%%nameG?(F+F,F,F-F1-%'assignG6$F5&-F66$-
%$catG6$F8Q(_piecesF(F:6#9$F(F(F(F(,
I.ishamiltonianf*6#%#vfG6#%%exprGF(F(C$>F+-%)norpoly2G6%,&-%%diffG6$&FG6#F,%"xG
F,-FU6$&FG6#""#%"yGF,FYFin@%%(roundedG@%/-%&evalfGF9$""!FaoF1%&falseG@%/F+FaoF1
FboF(F(F(F(,
I'p4mainf*F(6,%#gcG%$gcfG%*gcdresultG%'orig_fG%"gG%#geG%#gnG%"jG%"iGF%F(F(C6>%*
numpiecesG-F.6#%.user_f_piecesG>%*numcurvesG-F.6#%,user_curvesG@$5/FcpFao4-%%ty
peG6$Ffp%%listGC$>Ffp7#%'user_fG>FcpF,>%+normalexitGFao-%)openfileG6#%)terminal
G-%*closefileGF]r@%0%0user_precision0GFao>%'DigitsGFcr>Fer-%&floorG6#-%'evalhfG
6#Fer-F\r6#%*vec_tableG-%'writefG6#Q$P5|+F(-Fas6%Q'%d~%d|+F(FcpFhp-Fas6&Q*%d|+%
d|+%d|+F(%0all_crit_pointsG%'user_pG%'user_qG@$/Fjs""$-Fas6'Q1~~~~%g~%g~%g~%g|+
F(%&x_minG%&x_maxG%&y_minG%&y_maxGF[r?(8-F,F,FhpF1C$@$5-Faq6$&F[q6#Fht%)equatio
nG-Faq6$F^u%#<=G>F^u,&-%$lhsG6#F^uF,-%$rhsGFhu!""@$/-%6CheckIfGoodPolynomialGFh
uFboC$-Fas6%Q[rThe~separating~curve~#%d:~%a~is~not~well-defined~(not~polynomial
,~or~coefficients~do~not~evaluate~numerically.)|+F(FhtF^u-%%quitGFX@$2FaoFhp?(F
htF,F,FhpF1C&>F[oF1>%/user_precisionG"")F]s-%*write_gcfGFhu@$FgvC(F]s-Fas6$Q$%d
|+F(-F.6#%*vfregionsG@$2FaoFew?(8+F,F,FewF1C$-Fas6$Q#%dF(&&Fgw6#F[xFX?(FhtF,F,F
hpF1C$-Fas6$Q$~%dF(&&FaxFgnF_u@$/FhtFhp-Fas6#Q"|+F(F]s-Fas6$Fdw-F.6#%-curveregi
onsG@$2FaoFay?(F[xF,F,FayF1C$-Fas6$F_x&&FcyFbxFX?(FhtF,F,FhpF1C$-Fas6$Fgx&&F[zF
gnF_u@$F[yF\yF[r?(8,F,F,FcpF1CA-F"6#Fdz@$-Faq6$%4user_numeric_piecesGFcq>%-user
_numericG&F[[lFgz@$-Faq6$%6user_precision_piecesGFcq>F\w&Fb[lFgz@$1FerF\wC$-Fas
6&Q[qPlease~increase~precision~or~decrease~accuracy~for~region~#%d.~Precision~=
~%d~<=~Accuracy~=~%d.|+F(FdzFerF\wFdv@$-Faq6$%/epsilon_piecesGFcq>%(epsilonG&F^
\lFgz@$-Faq6$%0test_sep_piecesGFcq>%)test_sepG&Fe\lFgz@$-Faq6$%4taylor_level_pi
ecesGFcq>%-taylor_levelG&F\]lFgz@$-Faq6$%5numeric_level_piecesGFcq>%.numeric_le
velG&Fc]lFgz@$-Faq6$%1max_level_piecesGFcq>%*max_levelG&Fj]lFgz@$-Faq6$%6weakne
ss_level_piecesGFcq>%/weakness_levelG&Fa^lFgz@$-Faq6$%*x0_piecesGFcq>%#x0G&Fh^l
Fgz@$-Faq6$%*y0_piecesGFcq>%#y0G&F__lFgz@$F`q>Fgq&FfpFgz@$-Faq6$%0user_gcf_piec
esGFcq>%)user_gcfG&Fi_lFgz>F[oF][l@$55/-F_v6#&FgqFXFbo/-F_v6#&FgqFgnFbo/-F_v6#F
[`lFboC$-Fas6$Q]qThe~system~#%d~is~not~well-defined~(not~polynomial,~or~coeffic
ients~do~not~evaluate~numerically.)|+F(FdzFdv-Fas6#QGLET~US~STUDY~THE~DIFFERENT
IAL~SYSTEM:|+F(-Fas6%Q:~~~~x'~=~%a|+~~~~y'~=~%a|+|+F(Fd`lFh`l@%/F[`lFaoC'>8'Fgq
>8&-%'my_gcdG6$Fd`lFh`l>F+&F\blFgn>F[`l&F\bl6#F_t>Fgq-%)simplifyG6#&F\blFXC&>F+
Fhn>FjalFgq>Fgq7$-Fgbl6#*&&FjalFXF,F[`lF[v-Fgbl6#*&&FjalFgnF,F[`lF[v@$F``lC$-Fa
s6#QNError:~The~given~gcf~is~not~a~common~factor.|+F(Fdv-F_wF[alF]s-%0write_vec
_fieldG6#FgqF[r@%-FHF_dlC$-Fas6#Q<The~system~is~Hamiltonian.|+F(>%,hamiltonianG
F1>FgdlFbo@$4-%'memberG6$Fjs<$FhnF_tC.>%)log_fileG%-finite_tableG>%,result_file
G%+finite_resG@$2F,FcpC'-F\r6#Fdel-Fas6#Q^p|+|+\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/|+F(-Fas6$QE~~~~~~~~~~~~~~~~~~~
~~~~~~~PIECE~#%d|+F(Fdz-Fas6#Q]p\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/|+|+F(F[r-Fas6#QOLET~US~STUDY~THE~SYSTEM~AT~T
HE~FINITE~REGION|+|+F(FielF`al-Fas6%Q9~~~~x'~=~%a|+~~~~y'~=~%a|+F(FbclFfcl-Fas6
#Q6AT~THE~FINITE~REGION|+F(@$/-%0quasihom_degreeG6'FgqFYFinF[tF\t,$%)infinityGF
[vC%-F\r6$FdelF^r-Fas6#QEError:~The~given~vector~field~is~0!|+F(Fdv@$5/F+F,3/F+
Fhn0F[`lF,C%-Fas6$QDThe~system~has~a~common~factor:~%a|+F(F[`l-Fas6$QJHence~we~
shall~study~the~reduced~system:|+F(F[`l-Fas6%FiflFd`lFh`lF[r@%4F][lC->8(-%0find
_real_rootsG6%FgqFYFin>8)&F]ilFX>8*&F]ilFgn-F\r6#Fael-Fas6$Fdw,&-F.6#FbilF,-F.6
#FeilF,F[r-Fas6#QZ--------------------------------------------------------|+F(?
(F[xF,F,F\jlF1-%*sing_typeG6&Fgq-%#opG6$F,&FbilFbx-Fhjl6$FhnFjjlFao>F[oF1?(F[xF
,F,F^jlF1-Fejl6&Fgq-Fhjl6$F,&FeilFbx-Fhjl6$FhnFc[mFao>F[oF][lC(>Feil-%8find_rea
l_roots_numericGF`ilFgil-Fas6$FdwF^jlF[rF`jl?(F[xF,F,F^jlF1F_[m@$4-F\el6$Fjs<$F
,F_tC,>Fael%/infinite_tableG>Fdel%-infinite_resG@$FgelC&FielF[flF^flFaflFegl-Fa
s6#QFLET~US~STUDY~THE~SYSTEM~AT~INFINITY|+|+F(F`al@%F^hl-Fas6%Fifl*&F[`lF,Fd`lF
,*&F[`lF,Fh`lF,Fgfl-Fas6#Q-AT~INFINITY|+F(@$F[hlC%FahlFdhlFghlF[r@%3/F[tF,/F\tF
,-%5vec_field_diff_chartGF`il-%)pl_chartGF_dl@$F_\mF(@$F^tC->FaelFbel>FdelFeelF
gil-Fas6$FdwF,F[r-Fas6#QIWe~shall~study~the~differential~system:|+F(@%F^hlF^]mF
gfl-Fas6%Q7in~the~point~(%a,%a).|+F(Fj^lFa_l@$F[hlC%FahlFdhlFghlF[r-Fejl6&FgqFj
^lFa_lFaoF[r-Fas6#QR|+We~have~finished~the~study~of~the~vector~field.|+F(-%.clo
seallfilesGF(>FjqF,F(6:F[oFgqF[`lF[tF\tFcpFhpFgdlFaelFdelFjqF][lF\wFcrF`\lFg\lF
^]lFe]lF\^lFc^lFj^lFa_lFfpF[qF(F(,
I6CheckIfGoodPolynomialf*6#%"fGF(F(F(O-Faq6$-F_oFF-%(polynomG6$%(numericG7$FYFi
nF(F(F(F(,
I6prepareArbitraryCurvef*F(F(F(F(C)>F[oF][l-F\r6#%,curve_tableG-%,write_curveG6
#%+user_curveG-F`rFj`mF[r-Fas6#Qgn|+We~have~finished~writing~the~curve~as~a~C++
~readable~list.|+F(>FjqF,F(6%F_amFjqF[oF(F(,
I1prepareIsoclinesf*F(F(F(F(C)>F[oF][l-F\r6#%0isoclines_tableG-%0write_isocline
sG6#%/user_isoclinesG-F`rF[bmF[r-Fas6#Qjn|+We~have~finished~writing~the~isoclin
es~as~C++~readable~lists.|+F(>FjqF,F(6%F`bmFjqF[oF(F(,
I3Hardware_precision"#:F(,
I-reduce_coefff*6$F[`mFY6&F\p%#g1G%#g2GF_p6"F_cmC&>8$-%(norpolyG6$9$9%>8%-%&num
erG6#Fbcm>8&-%&denomGF\dm@%/FicmFao7#Fao7#-%"$G6$*&-%&coeffG6%FicmFgcm8'F,F^dmF
[v/F\em;Fao-%'degreeG6$FicmFgcmF_cmF_cmF_cmF(,
I-write_numberf*6#%"nGF_cmF_cmF_cm@%F[o-Fas6$Q$%g|+6"-F_o6#Ffcm-Fas6$Q$%a|+F_cm
FfcmF_cmF_cmF_cmF(,
I+reduce_lltf*6$%"aG%"bGF_cm6$%)operatorG%&arrowGF_cm-%&evalbG6#1-F_o6#,&FfcmF,
FgcmF[v,$)"#5,$F\wF[vF[vF_cmF_cmF_cmF(,
I-reduce_evalfF_oF(,
I*reduce_gtf*FbfmF_cmFefmF_cm-Fifm6#1F`gmF\gmF_cmF_cmF_cmF(,
I,reduce_gteqf*FbfmF_cmFefmF_cm-Fifm6#1F_gmF\gmF_cmF_cmF_cmF(,
I+reduce_eeqf*FbfmF_cmFefmF_cm-Fifm6#2-F_o6#-%$absGF]gmF`gmF_cmF_cmF_cmF(,
I,reduce_nneqf*FbfmF_cmFefmF_cm-Fifm6#1F`gmFchmF_cmF_cmF_cmF(,
I4optimizepolynomial1f*F[cm6'F\p%"LGF_pF'%"zGF_cmF_cmC(>FbcmFccm@%4F[o>Fbcm-F66
$Fbcm%)rationalG>Fbcm-F_oF\dm>Ficm-%%evalG6#7#-Ffdm6$.-Fjdm6%FbcmFgcmF^dm/F^dm;
Fao-%$maxG6$Fao-F`em6$FbcmFgcm@$3Fdim%.user_simplifyG>Ficm-%$mapG6$%1user_simpl
ifycmdGFicm>Ficm-Fa[n6$f*6#F`imF_cmFefmF_cm@%-Faq6$F[fmFc`m@%1-Ffhm6#F[fmF`gmFa
oFfcmFfcmF_cmF_cmF_cmFicm-F]jm6#-%$addG6$*&&Ficm6#F\emF,)Fgcm,&F\emF,F[vF,F,/F
\em;F,-F.6#FicmF_cm6$F\wF[oF_cmF(,
I4optimizepolynomial2f*6%F[`mFYFin6&F\pF_pF_imF`imF_cmF_cmC'>Fbcm-FQ6%FfcmFgcm9
&@%Fdim>FbcmFfim>FbcmFjim>F^dm-F]jm6#7#-Ffdm6$.-Fjdm6%FbcmFgcmFicm/FicmFfjm>F^d
m-Fa[n6$f*Fh[nF_cmFefmF_cm-F\im6$FfcmT$F_cmF_cm6$FinFg]nF^dm-Fdcm6$-F]jm6#-Fc\n
6$*&&F^dm6#F'F,)Fgcm,&F'F,F[vF,F,/F';F,-F.6#F^dmFgcmF_cm6#F[oF_cmF(,
I+first_termf*6$%#_fGFY6#F[`mF_cmF_cmC$>Fbcm-F\imFecm@%/FbcmFaoFao*&-Fjdm6%Fbcm
Fgcm-%(ldegreeGF[[nF,)FgcmFj`nF,F_cmF_cmF_cmF(,
I*lleadtermf*F_`nFa`nF_cmF_cmC$>FbcmFd`n@%Ff`nFao*&-Fjdm6%FbcmFgcmFjjmF,)FgcmFj
jmF,F_cmF_cmF_cmF(,
I'nltermf*Fa]n6$F\p%"hGF_cmF_cmC$>Fbcm-Fdcm6$-F]anFecmFg]n@%0FbcmFaoC$>Ficm-F]a
n6$FbcmFg]n@%0FicmFaoFicmFbcmC$>Fbcm-Fdcm6$-F]an6$FfcmFg]nFgcm@%F`bnFbcmFfcmF_c
mF_cmF_cmF(,
I%ddegf*6%F``nFYFinFa`nF_cmF_cmC$>Fbcm-F_]nFf]n@%Ff`nFao-F`em6$Fbcm<$FgcmFg]nF_
cmF\`nF_cmF(,
I)low_ddegf*F`cnFa`nF_cmF_cmC$>FbcmFccn@%Ff`nFao-F[anFfcnF_cmF_cmF_cmF(,
I&ntermf*6&F``nFYFin%"dG6%F[`mF_pF\pF_cmF_cmC&>FbcmFccn>F^dmFao?(FicmFaoF,9'F1>
F^dm,&F^dmF,*(-Fjdm6%Fb^nFg]n,&FgdnF,FicmF[vF,)FgcmFicmF,)Fg]nF]enF,F,F^dmF_cmF
_cmF_cmF(,
I)low_deg1f*F_`nFa`nF_cmF_cmC$>Fbcm-F_o6$-FdcmF\fmFgcm@%/FbcmF`oFaoFj`nF_cmF_cm
F_cmF(,
I+optimizevff*Fa]nF_cmFefmF_cm7$-F_]n6%&Ffcm6#F,FgcmFg]n-F_]n6%&Ffcm6#FhnFgcmFg
]nF_cmF_cmF_cmF(,
I1quasihom_degree1f*6'F``nFYFin%"pG%"qG6%%#_xG%#_yGF[`mF_cmF_cmC%>F^dmFccn>F^dm
-%%subsG6%/Fgcm)FbcmFgdn/Fg]n)Ficm9(F^dm-F`em6$F^dm<$FbcmFicmF_cmF_cmF_cmF(,
I0quasihom_degreef*6'FKFYFinFgfnFhfnF_cmFefmF_cm-Fhjm6$,&-Fdfn6'F^fnFgcmFg]nFgd
nFfgnF,FgdnF[v,&-Fdfn6'FbfnFgcmFg]nFgdnFfgnF,FfgnF[vF_cmF_cmF_cmF(,
I,change_polyf*Fa]n6&F\pFianF'FcfmF_cmF_cmC&>FbcmFe]n>FicmFao?(F_cmF,F,F_cmF`bn
C&>F^dm-Ffan6%FbcmFgcmFg]n>Fbcm,&FbcmF,F^dmF[v>F\em-F]jm6$-F]jm6$F^dm/FgcmF,/Fg
]nF,@$2F`gm-Ffhm6#-F_oFg\n>Ficm,&FicmF,F^dmF,FicmF_cmF_cmF_cmF(,
I*sort_listf*6#%"sGF_cmFefmF_cm-%%sortG6$Ffcmf*6$%&sle_aG%&sle_bGF_cmFefmF_cm-F
ifm6#52F^fn&FgcmF_fn3/F^fnF_[o2Fbfn&FgcmFcfnF_cmF_cmF_cmF_cmF_cmF_cmF(,
I+reduce_impf*Fh[nF_cmFefmF_cm-F_o6#-%*reduce_imGF\fmF_cmF_cmF_cmF(,
I,reduce_conj%*conjugateGF(,
I*reduce_ref*Fh[nF_cmFefmF_cm,&Ffcm#F,Fhn-Fj[oF\fmF_\oF_cmF_cmF_cmF(,
I*reduce_imf*Fh[nF_cmFefmF_cm*&^##F[vFhnF,,&FfcmF,F`\oF[vF,F_cmF_cmF_cmF(,
I)openfilef*F_cm6&%#kkGF'%#fhG%&fnameGF_cmF_cmC%>%0currentopenfileG<"?(FbcmF,F,
9#F1C$>F\em-F]jm6#&9"F\dm@%/F\emF^r>F_]o-%&unionG6$F_]o<#,$FcglF[vC$?(FicmF,F,-
F.6#%-openfilelistGF1@$/-Fhjl6$F,&Fe^oF]]nF\em[@%1FicmFc^o>F_]o-F]^o6$F_]o<#-Fh
jl6$FhnFj^oC%>F^dm-%&fopenG6%F\em%&WRITEG%%TEXTG>F_]o-F]^o6$F_]o<#F^dm>Fe^o-F]^
o6$Fe^o<#7$F\emF^dm@$/-F.6#F_]oFao>F_]oF_^oF_cm6$F_]oFe^oF_cmF(,
I*closefilef*6#%)filenameGFe_nF_cmF_cm@%0FfcmF^rC$?(FbcmF,F,Fc^oF1@$/-Fhjl6$F,&
Fe^oF\dmFfcmF[_o@$1FbcmFc^oC%-%'fcloseG6#-Fhjl6$FhnFfao@$-F\el6$F]boF_]oC$>F_]o
-%&minusG6$F_]o<#F]bo@$Fe`o>F_]oF_^o>Fe^o-Febo6$Fe^o<#Ffao@$3-F\el6$F`^oF_]o2F,
Ff`o>F_]o-FeboF^^oF_cmFi`oF_cmF(,
I'writeff*6#%-formatstringG6#F_pF_cmF_cm?(FbcmF,F,Ff`oF1@%/&F_]oF\dmF`^o-%'prin
tfG6$Ffcm&Fh]o6#;FhnFb]o-%(fprintfG6%F]doFfcmFadoF_cmF_cmF_cmF(,
I0currentopenfileF_^oF(,
I-openfilelistF`]oF(,
I.closeallfilesf*F\aoF_cmF_cmF_cm?(F_cmF,F,F_cm0Fc^oFao-F`r6#-Fhjl6$F,&Fe^oF_fn
F_cmF_cmF_cmF(,
I(norpolyf*6$%"PGFYF_cmFefmF_cm@%F^[n-%'expandG6#-Fc[n6#-%'normalGF\fm-FheoF[fo
F_cmF_cmF_cmF(,
I)norpoly2f*6%FeeoFYFinF_cmFefmF_cm@%F^[nFgeoF^foF_cmF_cmF_cmF(,
I)norpoly3f*6&FeeoFYFinF`imF_cmFefmF_cm@%F^[nFgeoF^foF_cmF_cmF_cmF(,
I'my_gcdf*6$F``n%#_gG6+F[`mF\p%#f2GF^cm%#ffG%"cGFho%"lGF%6"F`goC'>8$-FQ6%9$FYFi
n>8%-FQ6%9%FYFin@$4F[oC$>Fcgo-F66$FcgoFhim>Fhgo-F66$FhgoFhim@%3/FcgoFao0-F^cn6%
FhgoFYFinFaoC%>8(7$FaoF,>8)F,>8*Fhgo@%3/FhgoFao0-F^cn6%FcgoFYFinFaoC%>F]io7$F,F
ao>F`ioF,>FbioFcgo@%33F]ho-%*num_coeffGFhio-FbjoFjhoC'>8+-%$lcmG6$-F`dm6#Fcgo-F
`dm6#Fhgo>8&*&FcgoF,FfjoF,>8'*&FhgoF,FfjoF,>Fbio-FQ6%*&-%$gcdG6$F_[pFb[pF,FfjoF
[vFYFin@%0-F^cn6%FbioFYFinFaoC(-Fas6$FchlFbio>F`ioF,>F]io7$-FQ6%*&FcgoF,FbioF[v
FYFin-FQ6%*&FhgoF,FbioF[vFYFin-Fas6#Fh^m-Fas6$Q+~~~~x'=%a|+F`go&F]io6#F,-Fas6$Q
+~~~~y'=%a|+F`go&F]io6#FhnC%-Fas6#QCThe~system~has~no~common~factors.|+F`go>F]i
o7$FcgoFhgo>F`ioFaoC'>8,F[o>F[oF1>Fbio-Fi[p6$FcgoFhgo@%F\\pC(-Fas6$QDThe~system
~has~a~comman~factor:~%a|+F`goFbio>F]io7$Fg\pFj\p>F`ioF,F[]pF]]pFb]pC%Fh]p>F]io
F\^p>F`ioFao>F[oF`^p7%F]ioF`ioFbioF`go6#F[oF`goF(,
I*num_coefff*6%F``nFYFin6*F[`mF_pF'%#l1G%#l2G%#s1G%#s2G%#okG6"F\`pC(@%4F[o>8$-F
66$-FQ6%9$9%9&Fhim>Fa`pFd`p>8+F1>8'-Fibm6$Fa`pFg`p>8%Fao?(F\`pF,F,F\`p3F[ap2Faa
p-F.6#F]apC'>Faap,&FaapF,F,F,>8)&F]ap6#Faap>8(-Fibm6$F[bpFh`p>8&Fao?(F\`pF,F,F
\`p3F[ap2Fcbp-F.6#F_bpC%>Fcbp,&FcbpF,F,F,>8*&F_bp6#Fcbp@$4-Faq6$F]cpFhim>F[apFb
oF[apF\`pF\`pF\`pF(,
I8findAllSeparatingCurvesf*6"6'%#fpGF'F%Fhp%0numcurveregionsGFgcpFgcpC->F][lF1>
F[oF1>8'-F.6#F[q>8(-F.6#Fcy>8$-Fg_o6%%0user_curvesfileGFi_oFj_o?(8&F,F,F_dpF1C$
@$5-Faq6$&F[q6#F\epF`u-Faq6$FbepFcu>Fbep,&-Fgu6#FbepF,-FjuFiepF[v@$/-F_vFiepFbo
C'-F_do6%FcvF\epFbep-F[bo6#Fgdp>%,returnvalueGFao%%NULLGOFgcp-Fedo6(FgdpQ0p5|+%
d~%d~%d~%d|+FgcpF[tF\tF\wF_dp?(F\epF,F,F_dpF1C%>%/user_numpointsG&%5user_numpoi
ntscurvesGFcep>FgqFbep@$4-%4findSeparatingCurveGFbfpC'Fafp-F[bo6#-Fg_o6%%*user_
fileGFi_oFj_o>FdfpFaoFefpOFgcpFafp>FdfpF,FefpFgcp6(FgqF]gpF[qF[oF][lFdfpFgcpF(,
I4findSeparatingCurvef*6#Ficp6.F[`m%$fU1G%$fV1G%$fU2G%$fV2G%#fCG%#z1G%#z2GFcjnF
_imF_pFadnFgcpFgcpCG>FgdpFgq>8/-F^cn6%FgdpFYFin@%/F]ipFao-Fedo6%9$FdwFaoC$>8--%
.coeff_degree2G6%%%gcffGFYFin-Fedo6%FdipFdwF]ip>Fgip-FiipF_ip-Fedo6%FdipF_x-F.6
#Fgip?(8.F,F,FbjpF1-Fedo6'FdipQ*~%d~%d~%gFgcp-Fhjl6$F,&Fgip6#Fejp-Fhjl6$FhnF[[q
-F_o6#-Fhjl6$F_tF[[q-Fedo6$FdipF^y>8%-F`gn6%/FY*$)8+F[tF[v/Fin*&8*F,)F\\qF\tF[v
Fgdp>Ff[q-FQ6%Ff[qF_\qF\\q>Ff[q-F`gn6%/F_\qFY/F\\qFin-F[dm6#Ff[q>Fgip-Fiip6%Ff[
qFYFinF`jp?(FejpF,F,FbjpF1FfjpFc[q>F_dp-F`gn6%/FY*&F_\qF,F[\qF[v/Fin*$F`\qF[vFg
dp>F_dp-FQ6%F_dpF_\qF\\q>F_dp-F`gn6%Fg\qFh\q-F[dm6#F_dp>Fgip-Fiip6%F_dpFYFinF`j
p?(FejpF,F,FbjpF1FfjpFc[q>F\ep-F`gn6%/FY,$Fj[qF[vF]\qFgdp>F\ep-FQ6%F\epF_\qF\\q
>F\ep-F`gn6%Fg\qFh\q-F[dmFcep>Fgip-Fiip6%F\epFYFinF`jp?(FejpF,F,FbjpF1FfjpFc[q>
Fcdp-F`gn6%Fb]q/Fin,$Fe]qF[vFgdp>Fcdp-FQ6%FcdpF_\qF\\q>Fcdp-F`gn6%Fg\qFh\q-F[dm
6#Fcdp>Fgip-Fiip6%FcdpFYFinF`jp?(FejpF,F,FbjpF1FfjpFc[q@%3/F[tF,/F\tF,CO>FgqFgd
p>%(user_x1G,$$FagmF[vF[v>%(user_x2GF\aq>%(user_y1G,$F\aqF[v>%(user_y2GF\aq>%"u
GFY>%"vGFin-F_do6#Q+Chart~R2:~Fgcp@$4-%;findSeparatingCurveInChartG6#FdipOFbo>F
gqFf[q>Fj`q,$F\aqF[v>F^aqF\aq>F`aqF`o>FcaqF\aq>FeaqFY>FgaqFin-F_do6#Q+Chart~U1:
~Fgcp@$F\bqOFbo>FgqF_dp>Fj`q,$F\aqF[v>F^aqF\aq>F`aqF`o>FcaqF\aq>FeaqFY>FgaqFin-
F_do6#Q+Chart~U2:~Fgcp@$F\bqOFbo>FgqFf[q>Fj`q,$F\aqF[v>F^aqF\aq>F`aq,$F\aqF[v>F
caqF`o>FeaqFY>FgaqFin-F_do6#Q,Chart~V1':~Fgcp@$F\bqOFbo>FgqF_dp>Fj`q,$F\aqF[v>F
^aqF\aq>F`aq,$F\aqF[v>FcaqF`o>FeaqFY>FgaqFin-F_do6#Q,Chart~V2':~Fgcp@$F\bqOFboC
V>8)-F`gn6%/FY*&%"UGF,)8,F[tF[v/Fin*&%"VGF,)F`fqF\tF[vFgdp>Fieq-Fcfo6&FieqF`fqF
^fqFcfq>Fieq-F`gn6$/F`fqFY-F[dm6#Fieq>Fgip-%.coeff_degree3G6&FieqFYF^fqFcfqF`jp
?(FejpF,F,FbjpF1-Fedo6(FdipQ-~%d~%d~%d~%gFgcpFijpF][qFa[q-F_o6#-Fhjl6$""%F[[qFc
[q>Fgq-F]jm6$Fgdp<$/FYF^fq/FinFcfq>Fj`qF`o>F^aqF\aq>F`aqF`o>Fcaq-F_o6#,$%#PiGFh
n>Feaq*&FYF,-%$cosG6#FinF,>Fgaq*&FYF,-%$sinGF]iqF,-F_do6#Q>Chart~R2~(Lyapunov-w
eights):~Fgcp@$F\bqOFbo>Fj`qF`o>F^aqF\aq>F`aq-F_o6#,$Fhhq#F[vFjgq>Fcaq-F_o6#,$F
hhq#F,Fjgq>FgqFieq>FeaqF[iq>FgaqF`iq-F_do6#Q>Chart~U1~(Lyapunov-weights):~Fgcp@
$F\bqOFbo>Fj`qF`o>F^aqF\aq>F`aqF_jq>Fcaq-F_o6#,$Fhhq#F_tFjgq>FgqFieq>FeaqF[iq>F
gaqF`iq-F_do6#Q>Chart~U2~(Lyapunov-weights):~Fgcp@$F\bqOFbo>Fj`qF`o>F^aqF\aq>F`
aqF_[r>Fcaq-F_o6#,$Fhhq#""&Fjgq>FgqFieq>FeaqF[iq>FgaqF`iq-F_do6#Q>Chart~V1~(Lya
punov-weights):~Fgcp@$F\bqOFbo>Fj`qF`o>F^aqF\aq>F`aq-F_o6#,$Fhhq#!"$Fjgq>FcaqFj
iq>FgqFieq>FeaqF[iq>FgaqF`iq-F_do6#Q>Chart~V2~(Lyapunov-weights):~Fgcp@$F\bqOFb
oOF1Fgcp6)Fj`qF^aqF`aqFcaqFeaqFgaqFgqFgcpF(,
I;findSeparatingCurveInChartf*Fahp6,%"mGFeemFeeoF'F`pF_pFcjnF[`m%9CURVES_ARRAY_
TO_LISTLISTG%-SimplifyPlotGFgcpFgcpC(>F`fqf*Fgcp6$%#ssGF'FgcpFgcpC%>Fgdp7#-Ffdm
6#;F,9#?(Ff[qF,F,F`_rF1C$>&FgdpFj\q&9"Fj\q@$-Faq6$Fd_r%&ArrayG@&/-%-ArrayNumDim
sG6#Fd_rFhn>Fd_r-F66$Fd_r%)listlistG/F]`rF,>Fd_r-F66$Fd_rFcq-%'CURVESG6#-FhjlFb
fpFgcpFgcpFgcp>Fgipf*6#FeeoFgcp6$FffmFgfmFgcp-F]jm6$Fdip/Fi`rT#FgcpFgcp6$Fc^rF`
fq>FdfpF,@%1-F`em6$Fgq7&FYFinF^fqFcfqFaoC%-F_do6$Q@%a:~Level~curve~is~a~constan
t.|+FgcpFgqFbipOF1C.>Fgdp,&-%&roundG6#-%%sqrtG6#F]gpF,F,F,>Ff[qFgdp>%%facsG&-%(
factorsG6#-F`gn6$<$/F^fqFeaq/FcfqFgaqFgq6#Fhn>F\ep-Fa[n6$f*6#%$facGFgcpF_arFgcp
-&%&plotsG6#%-implicitplotG6)Fdip/FY;Fj`qF^aq/Fin;F`aqFcaq/%%axesG%%noneG/%%vie
wG7$FcdrFedr/%%gridG7$FcarT%/%&colorG%&blackGFgcpFgcp6&Fb^rFgdpFeemFf[qF[cr>F\e
p-Fa[n6$FgipF\ep>F\ep-Fa[n6$f*FjcrFgcpF_arFgcp-Fhjl6#-%'selectG6$f*6#%#ptGFgcpF
_arFgcp-Faq6$FdipFcqFgcpFgcpFgcp7#-Fhjl6#-Fhjl6$F,FdipFgcpFgcpFgcpF\ep>F_dpFao?
(FcdpF,F,-F.FcepF1>F_dp,&F_dpF,-F.6#&F\epF^`qF,-Fedo6%FdipFdwF_dp>F_dpFao?(Fcdp
F,F,F\grF1C$?(FieqF,F,F_grF1C%>F_\q-%(sprintfG6%Q'%g~%g~Fgcp&F\ep6%FcdpFieqF,&F
\ep6%FcdpFieqFhn-Fedo6%FdipQ#%sFgcpF_\q>F_dp,&F_dpF,F,F,@%0FcdpF\gr-Fedo6$FdipQ
#,|+FgcpFc[q-F_do6%Q9%a:~%d~points~returned.|+FgcpFgqF_dp>FdfpFaoOF1Fgcp6)FeaqF
gaqFdfpF[crF[drFgqF]gpFgcpF(,
I)save_allFboF(,
I3real_roots_numericf*6$F[`mFY6&%%cplxGF_pF'F\p6"FhirC'>8$7#-%'fsolveG6&9$9%%(c
omplexG%+fulldigitsG@$/F[jr7#/FajrFajr>F[jr7">8'Fijr?(8%F,F,-F.6#F[jrF1@$1-Ffhm
6#-%#ImG6#&F[jr6#F][s)Fagm,$F\wF[vC%>Fg[s-%#ReGFf[s?(8&F,F,-F.6#F[[sF1@$-F^hm6$
Fg[s&F[[s6#F`\s[@$2Fa\sF`\s>F[[s7$-FhjlFb\sFg[s-FejnFb\sFhirFhirFhirF(,
I1find_real_roots1f*Feir6'FianF]pF^pF'FdfmFhirFhirC$@%F[oC$>F][sFijr>F`\s-Fcir6
$F`jrFajrC*>%-_EnvExplicitGF1>%1_EnvAllSolutionsGF1>%,_EnvTryHardGF1>F[jr7#-%&s
olveGFh]s@$/F[jr7#Fajr>F[jrFijr>F][sFijr>F`\sFijr?(F[[sF,F,F^[sF1C$>8(&F[jrFb\s
@%-%$hasG6$F]_s%'RootOfGC$>F]_s-F_o6#F]_s@$1-Ffhm6#-Fe[sFg_sFi[sC$>F]_s-F^\sFg_
s>F`\s7$-FhjlFg\sF]_s@$1-Ffhm6#-F_oF[`sFi[sC$>F]_sF_`s>F][s7$-FhjlFh[sF]_s7$-F6
6$-F66$F][s%$setGFcq-F66$-F66$F`\sFbasFcqFhirFhirFhirF(,
I8find_real_roots_numericf*6%F[`mFYFin6'F\pFianF_pF'FcfmFhirFhirC*>F[^sF1>F]^sF
1>F_^sF1>F][s-F_o6#-Fa[n6$%*allvaluesG7#-Fc^s6$-F66$F`jrFbas<$Fajr9&>F[jrFijr?(
F`\sF,F,-F.Fh[sF1C$>F]_s-F`gn6$&F][sFg\s7$FajrF[cs@$32-Ffhm6#-Fe[s6#&F]_s6#F,Fi
[s2-Ffhm6#-Fe[s6#&F]_s6#FhnFi[sC%>F]_s-Fa[n6$F^\sF]_s?(F[[sF,F,F^[sF1@$32-Ffhm6
#,&-Fhjl6$F,F^_sF,F\dsF[vFi[s2-Ffhm6#,&-Fhjl6$FhnF^_sF,FcdsF[vFi[sFh\s@$2F^[sF[
[sC%>F[jr7$-FhjlF_[sF]_s@$/F^[sF,-Fas6#Q=Numeric~real~singularities:|+Fhir-Fas6
'QC~~(%g,%g)~->~|fr~x'~=~%g,~y'~=~%g~|hr|+FhirF\dsFcds-F_o6#-F`gn6$<$/FajrF\ds/
F[csFcds&F`jrF]ds-F_o6#-F`gn6$Fjfs&F`jrFdds@$/F^[sFao-Fas6#QENo~numeric~singula
rities~are~found.|+FhirF[jrFhirFhirFhirF(,
I0find_real_rootsf*Fias6,F\pFianF_pF'Fcfm%#anGF^pFcjn%#snG%#bnGFhirFhirC2>F[^sF
1>F]^sF1>F_^sF1>F][sFbbs>F[jrFijr>8*Fijr?(F`\sF,F,F^csF1C&>F]_sFacs>8)-Fa[n6$F^
\sFf_s>8--Fa[n6$Fe[sFf_s@$32-Ffhm6#&F^isF]dsFi[s2-Ffhm6#&F^isFddsFi[sC$?(F[[sF,
F,-F.6#FehsF1@$32-Ffhm6#,&-Fhjl6$F,&FehsFb\sF,&FjhsF]dsF[vFi[s2-Ffhm6#,&-Fhjl6$
FhnFgjsF,&FjhsFddsF[vFi[sFh\s@$2F]jsF[[sC$>F[jrF\fs>Fehs7$-FhjlF^jsFjhs>8+Fijr>
8,Fijr?(F[[sF,F,F]jsF1@%5-Fa_s6$F`esFc_s-Fa_s6$FfesFc_s>Fj[t7$-Fhjl6#Fj[tFgjs>F
h[t7$-Fhjl6#Fh[tF^_s?(F`\sF,F,-F.Fi\tF1C$>&&Fh[tFg\sF]ds-F^\s6#F^]t>&F_]tFdds-F
^\s6#Fc]t@%/F[]tFao-Fas6#QKNo~symbolic~real~singularities~are~found.|+Fhir-Fas6
#Q>Symbolic~real~singularities:|+Fhir?(F[[sF,F,F[]tF1-Fas6'Fefs-Fhjl6$F,&Fh[tFb
\s-Fhjl6$FhnFc^t-F_o6#-F`gn6$<$/FajrFa^t/F[csFd^tF]gsFf^t@%/-F.Fe\tFao@%Fg]t-Fa
s6#QJNo~numeric~real~singularities~are~found.|+Fhir-Fas6#QPNo~other~numeric~rea
l~singularities~are~found.|+FhirF`fs?(F[[sF,F,F__tF1-Fas6'Fefs-Fhjl6$F,&Fj[tFb
\s-Fhjl6$FhnF\`t-F_o6#-F`gn6$<$/FajrFj_t/F[csF]`tF]gsF_`t7$Fh[tFj[tFhirFhirFhir
F(,
I2find_real_roots11f*6$F_imFY6+%#f1GF\goF[`mF\pF]pF^p%$ge2G%$gn2GF_pFhirFhirC,>
F[jr-F\im6$F]gsFajr>F][s-F\im6$FbgsFajr@%0-Fhjm6$-F`em6$F[jrFajrFaoFaoC$>F[[s-F
_]sFjat>F`\sF][s@%0-Fhjm6$-F`em6$F][sFajrFaoFaoC$>F[[s-F_]sFdbt>F`\sF[jrC$>F[[s
7$FijrFijr>F`\sFao>F]_s&F[[sF]ds>Fjhs&F[[sFdds>FehsFijr>Fh[tFijr?(Fj[tF,F,-F.Fg
_sF1@$2-Ffhm6#-F_o6#-F`gn6$/Fajr&F]_sFe\tF`\sFi[s>Fehs7$Ff[tF^dt?(Fj[tF,F,-F.6#
FjhsF1@$2-Ffhm6#-F_o6#-F`gn6$/Fajr&FjhsFe\tF`\sFi[s>Fh[t7$Fh\tF]et7$FehsFh[tFhi
rFhirFhirF(,
I.coeff_degree1f*6$F[`mFY6&F\pFadnF_pF_im6"FeetC(>8$-F\im6$9$9%>8%-Fhjm6$Fao-F`
em6$FhetF\ft>8'7"?(8&FaoF,F^ftF1@$0-Fjdm6%FhetF\ftFgftFao>Fdft7$-Fhjl6#Fdft7$Fg
ftFjft@$/-F.F_gtFao>Fdft7#7$FaoFaoFdftFeetFeetFeetF(,
I.coeff_degree2f*6%F[`mFYFin6)F\pFadnF_pF_im%#dxGFianF'FeetFeetC(>Fhet-F_]n6%F[
ftF\ft9&>8(F_ft>FdftFeft?(FgftFaoF,FbhtF1C%>8)Fjft>F^ft-Fhjm6$Fao-F`em6$FhetF`h
t?(8*FaoF,F^ftF1@$0-Fjdm6%FghtF`htF^itFao>Fdft7$F^gt7%FgftF^itFait@$Fbgt>Fdft7#
7%FaoFaoFaoFdftFeet6#F[oFeetF(,
I.coeff_degree3f*6&F[`mFYFinF`im6,F\p%#d1G%#d2G%#d3G%#j1GF]cmF^cm%#j2G%#j3GF_im
FeetFeetC(>Fhet-Fcfo6&F[ftF\ftF`ht9'>F^ftF_ft>8-Feft?(FbhtFaoF,F^ftF1C%>Fght-F_
]n6%-Fjdm6%FhetF\ftFbhtF`htFijt>Fgft-Fhjm6$Fao-F`em6$FghtF`ht?(8+FaoF,FgftF1C%>
F^it-Fjdm6%FghtF`htFj[u>Fdft-Fhjm6$Fao-F`em6$F^itFijt?(8,FaoF,FdftF1@$0-Fjdm6%F
^itFijtFe\uFao>F\[u7$-Fhjl6#F\[u7&FbhtFj[uFe\uFh\u@$/-F.F]]uFao>F\[u7#7&FaoFaoF
aoFaoF\[uFeetFjitFeetF(,
I0write_vec_fieldf*6#FK6$F_imF_pFeetFeetC(>Fhet-Fiip6%&F[ft6#F,FYFin-Fas6$Fdw-F
.6#Fhet?(F^ftF,F,Fa^uF1-Fas6&Q*%d~%d~%g|+Feet-Fhjl6$F,&Fhet6#F^ft-Fhjl6$FhnFi^u
-F_o6#-Fhjl6$F_tFi^u>Fhet-Fiip6%&F[ft6#FhnFYFinF_^u?(F^ftF,F,Fa^uF1Fd^uFeetFeet
FeetF(,
I9write_vec_field_cylinderf*Fg]uFh]uFeetFeetC(>Fhet-F`gq6&F]^uF%%$_coG%$_siGF_^
u?(F^ftF,F,Fa^uF1-Fas6'Q-%d~%d~%d~%g|+FeetFg^uF[_uF__u-F_o6#-Fhjl6$FjgqFi^u>Fhe
t-F`gq6&Fd_uF%F]`uF^`uF_^u?(F^ftF,F,Fa^uF1F``uFeetFeetFeetF(,
I-write_saddlef*6,Fj^lFa_lFcfmFdfmF^goFadnFK%$sepG%&stypeG%&chartG6%F_imF_pF'Fe
etFeetC*-F\r6#Fael-Fas6&Q*%d~%g~%g|+FeetF,-F_o6#F[ft-F_o6#F\ft-Fas6'Q/~~%g~%g~%
g~%g|+Feet-F_o6#F`ht-F_o6#Fijt-F_o6#9(-F_o6#9)-F^dl6#9*-Fas6$Q&~~%d|+Feet9-?(F^
ftF,F,-F.6#9+F1C'-Fas6$Q&~~%d~Feet&9,Fj^u>Fhet-Faet6$&FccuFj^u%"tG-Fas6$F_xFa^u
?(FgftF,F,Fa^uF1-Fas6%Q'~%d~%gFeet-Fhjl6$F,&Fhet6#Fgft-Fhjl6$FhnFgdu-Fas6#F^y-F
as6$Q&~~%g|+FeetF`\l-F\r6#F^rFeetFeetFeetF(,
I+write_nodef*6&Fj^lFa_l%%stabGF`auFeetFeetFeetC&Fcau-Fas6&FgauFhnFhauFjau-Fas6
%Q)~~%d~%d|+FeetF`htFijtF`euFeetFeetFeetF(,
I1write_weak_focusf*6&Fj^lFa_lF`auF_auFeetFeetFeetC&Fcau-Fas6&FgauF_tFhauFjau-F
as6%F[fuFijtF`htF`euFeetFeetFeetF(,
I3write_strong_focusf*FdeuFeetFeetFeetC&Fcau-Fas6'Q-%d~%d~%g~%g|+FeetFjgqF`htFh
auFjau-Fas6$F^cuFijtF`euFeetFeetFeetF(,
I6write_semi_elementaryf*6,Fj^lFa_lFcfmFdfmF^goFadnFKF_auF^auF`auFaauFeetFeetC*
Fcau-Fas6&FgauFc\rFhauFjauF\buFibu-Fas6&Q,~~%d~%d~%d|+Feet&FccuF^^u&FccuFe_uF_c
u@$553/F_cuFao-F\el6$Fegu<(F,FhnF_tFjgq""'""(330F_cuFao/FfguFaoF\hu33Fchu/FfguF
,-F\el6$Fegu<&FhnF_tF_huF`hu?(F^ftF,F,-F.6#FicuF1C&>Fhet-Faet6$FhcuF^du-Fas6$Q%
~~%dFeetFa^u?(FgftF,F,Fa^uF1FbduF[euF]euF`euFeetFeetFeetF(,
I2write_separatricef*6#F^au6(%&transGF_pF'%#p2GF_imFcfmFeetFeetC/>FhetF]^uF_du?
(F^ftFa^uF[vF,F1C&>FghtFi^u?(FgftF,F,FhnF1-Fas6$Q$~%gFeet-F_o6#&FghtFhdu?(FgftF
_tF,""*F1-Fas6$FgxFgjuF[eu>FdftFd_u-Fas6%Q'%g~%g|+Feet-F_o6#&FdftF^^u-F_o6#&Fdf
tFe_u>Fhet&F[ft6#F_t-Fas6'Q-%g~%g~%g~%g|+Feet-F_o6#&FhetF^^u-F_o6#&FhetFe_u-F_o
6#&FhetFh[v-F_o6#&Fhet6#Fjgq-F^dl6#&F[ftFh\v>Fbht-Faet6$&F[ft6#Fc\rF^du-Fas6$F_
x-F.6#Fbht?(FgftF,F,Fc]vF1-Fas6%Fddu-Fhjl6$F,&FbhtFhdu-Fhjl6$FhnFj]vF[eu-Fas6$F
dw&F[ft6#F_huFeetFeetFeetF(,
I1write_degeneratef*6&Fj^lFa_l%+trajectorsGF`au6#F_pFeetFeetC)Fcau-Fas6&FgauF_h
uFhauFjau-Fas6$FiemF`\l-Fas6$Fdw-F.F`bu?(FhetF,F,F]_vF1-Ffiu6#&F`htFb^u-Fas6$Fd
wFijtF`euFeetFeetFeetF(,
I*write_gcff*6#F[jp6-F_pFgfnFhfnFhhpFihpFcjnF]`uF^`uFadnF_imF\pFeetFeetC&-F\r6#
F_s>Fe\u-F^cn6%F[ftFYFin@%/Fe\uFao-Fas6$FdwFaoCE>F\[u-FiipF]`v-Fas6%Q&%d~%dFeet
Fe\uFa]u?(FhetF,F,Fa]uF1-Fas6&Fhjp-Fhjl6$F,&F\[uFb^u-Fhjl6$FhnF]av-F_o6#-Fhjl6$
F_tF]avF[eu>F^ftF[t>FgftF\t>8.-F`gn6%/FY*$)FbhtF^ftF[v/Fin*&FdftF,)FbhtFgftF[vF
[ft>Fgav-FQ6%FgavFdftFbht>Fgav-F[dm6#Fgav>F\[u-FiipFbbv-Fas6$F_xFa]u?(FhetF,F,F
a]uF1Fi`vF[eu>Fgav-F`gn6%/FY*&FdftF,F\bvF[v/Fin*$F_bvF[vF[ft>FgavFabv>FgavFdbv>
F\[uFgbvFhbv?(FhetF,F,Fa]uF1Fi`vF[eu>Fgav-F`gn6%/FY,$F[bvF[vF]bvF[ft>FgavFabv>F
gavFdbv>F\[uFgbvFhbv?(FhetF,F,Fa]uF1Fi`vF[eu>Fgav-F`gn6%F^cv/Fin,$FacvF[vF[ft>F
gavFabv>FgavFdbv>F\[uFgbvFhbv?(FhetF,F,Fa]uF1Fi`vF[eu@$50F^ftF,0FgftF,C)>Fgav-F
`gn6%/FY*&F^itF,)FghtF^ftF[v/Fin*&Fj[uF,)FghtFgftF[vF[ft>Fgav-Fcfo6&FgavFghtF^i
tFj[u>FgavFdbv>F\[u-F`gqFhevFhbv?(FhetF,F,Fa]uF1-Fas6'FegqF[avF^avFbav-F_o6#-Fh
jl6$FjgqF]avF[euF`euFeet6$F[tF\tFeetF(,
I,write_curvef*6#%'curvefGFg_vFeetFeetC$>Fe\uF\`v@%F_`v-Fas6#Q#0|+6"CE>F\[uFd`v
Fe`v?(FhetF,F,Fa]uF1Fi`vF[eu>F^ftF[t>FgftF\t>FgavFhav>FgavFabv>FgavFdbv>F\[uFgb
vFhbv?(FhetF,F,Fa]uF1Fi`vF[eu>FgavF\cv>FgavFabv>FgavFdbv>F\[uFgbvFhbv?(FhetF,F,
Fa]uF1Fi`vF[eu>FgavFgcv>FgavFabv>FgavFdbv>F\[uFgbvFhbv?(FhetF,F,Fa]uF1Fi`vF[eu>
FgavF`dv>FgavFabv>FgavFdbv>F\[uFgbvFhbv?(FhetF,F,Fa]uF1Fi`vF[eu@$FidvC)>FgavF^e
v>FgavFgev>FgavFdbv>F\[uF[fvFhbv?(FhetF,F,Fa]uF1F]fvF[euFeet6%F[tF\tF[oFeetF(,
I0write_isoclinesf*6#%+isoclinesfGFg_vFeetFeetC$>Fe\uF\`v@%F_`vF[gvCE>F\[uFd`vF
e`v?(FhetF,F,Fa]uF1Fi`vF[eu>F^ftF[t>FgftF\t>FgavFhav>FgavFabv>FgavFdbv>F\[uFgbv
Fhbv?(FhetF,F,Fa]uF1Fi`vF[eu>FgavF\cv>FgavFabv>FgavFdbv>F\[uFgbvFhbv?(FhetF,F,F
a]uF1Fi`vF[eu>FgavFgcv>FgavFabv>FgavFdbv>F\[uFgbvFhbv?(FhetF,F,Fa]uF1Fi`vF[eu>F
gavF`dv>FgavFabv>FgavFdbv>F\[uFgbvFhbv?(FhetF,F,Fa]uF1Fi`vF[eu@$FidvC)>FgavF^ev
>FgavFgev>FgavFdbv>F\[uF[fvFhbv?(FhetF,F,Fa]uF1F]fvF[euFeetF_ivFeetF(,
I)jacobianf*6%F[`m%$xeqG%$yeqG6#FM6"F]\w-F]jm6#-Fa[n6$f*F\\wF]\w6$FffmFgfmF]\w-
F`gn6$<$T&T$9$F]\wF]\w6&Fj[w9%F[\w9&7&-FU6$&Fi\w6#F,-Fgu6#F[]w-FU6$F`]w-Fgu6#F
\]w-FU6$&Fi\w6#FhnFb]w-FU6$Fj]wFf]wF]\wF]\wF]\wF(,
I,eigenvectorf*6&FcfmFdfmF^goFadn6$%#_cGFeemF]\wF]\wC%@%-Fghm6$F[]wFao>8$7$F,,$
*&Fi\wF,F[]wF[vF[v@%-Fghm6$Fi\wFao>Fh^w7$FaoF,@%-Fghm6$9'Fao>Fh^w7$F,,$*&F\]wF,
Fd_wF[vF[v>Fh^wF`_w@$F[oC$>8%-Fgbr6#z'6$&Fh^wFa]w&Fh^wF[^w[[[[[_[[[[sF,][[[[[[[
[[sF,>Fh^w-F_o6#7$*&Fb`wF,F]`wF[v*&Fc`wF,F]`wF[vFh^wF]\wF]\wF]\wF(,
I,translationf*6'FgaqFYFinFj^lFa_l6$F[atF\goF]\wF]\wC&>Fh^w-F`gn6$<$/F[]w,&F[]w
F,Fd_wF,/F\]w,&F\]wF,9(F,F`]w>F]`w-F`gn6$FbawFj]w@$F[oC$>Fh^w-Fehn6%Fh^wF[]wF\]
w>F]`w-Fehn6%F]`wF[]wF\]w7$Fh^wF]`wF]\wF]\wF]\wF(,
I/transformationf*6'FgaqFcfmFdfmF^goFadn6-F[atF\goFjfnF[gn%#_aG%#_bGFb^w%#_dG%"
MGF]cmF^cmF]\wF]\wC,>Fh^w-F`gn6$<$/FY,&*&F[]wF,8&F,F,*&F\]wF,8'F,F,/Fin,&*&Fd_w
F,FdcwF,F,*&FgawF,FfcwF,F,F`]w>F]`w-F`gn6$F`cwFj]w>8,,&*&F[]wF,FgawF,F,*&F\]wF,
Fd_wF,F[v>8(*&FgawF,F_dwF[v>8),$*&F\]wF,F_dwF[vF[v>8*,$*&Fd_wF,F_dwF[vF[v>8+*&F
[]wF,F_dwF[v>8--F`gn6%/FdcwFY/FfcwFin,&*&FddwF,Fh^wF,F,*&FgdwF,F]`wF,F,>8.-F`gn
6%FeewFfew,&*&F[ewF,Fh^wF,F,*&F_ewF,F]`wF,F,-Fien6%7$FbewF[fwFYFinF]\wF]\wF]\wF
(,
I.normalizationf*6#Fgaq6%%#L1G%#L2GFb^rF]\wF]\wC)>Fh^w-Fiip6%-F_]n6%F`]wFYFinFY
Fin>F]`w-Fiip6%-F_]n6%Fj]wFYFinFYFin>Fh^w-Fa[n6$f*F\\wF]\wFc\wF]\w-F_o6#-Ffhm6#
&Fi\w6#F_tF]\wF]\wF]\wFh^w>F]`w-Fa[n6$f*F\\wF]\wFc\wF]\wFigwF]\wF]\wF]\wF]`w>Fd
cw-Fhjm6$-Fhjl6#Fh^w-Fhjl6#F]`w@$4F[o>Fdcw-F66$FdcwFhim-Fien6%7$,$*&F`]wF,FdcwF
[v"%+5,$*&Fj]wF,FdcwF[vFdiwFYFinF]\wF]\wF]\wF(,
I)manifoldf*6%F\pFeem%'stableG6.%$vf1G%$vf2G%#h1G%#h2GF'FhfwFifwF^auF[gn%'lambd
aGF[`p%#n1GF]\wF]\wC*@%F[oC$>Fh^w-F_o6#F`]w>F]`w-F_o6#Fj]wC$>Fh^wF`]w>F]`wFj]w>
Fgdw-Fjdm6%-%(collectG6$-F`gn6$/FinFaoF`]wFYFYF,>F[ew-Fjdm6%-Fb[x6$-F`gn6$/FYFa
oFj]wFinFinF,>F_ewFao?(FddwFhnF,F[]wF1C)>Fbew*&-Fjdm6%-Fb[x6$-F`gn6$Ff[xF]`wFYF
YFddwF,,&*&FgdwF,FddwF,F,F[ewF[vF[v@$3F[iwF^[n>Fbew-Fc[n6#Fbew>Fdcw-Fheo6#-F`gn
6$/Fin,&F_dwF,*&FbewF,)FYFddwF,F,Fh^w>Ffcw-Fheo6#,&-F`gn6$Ff]xF]`wF,**FbewF,Fdd
wF,)FY,&FddwF,F[vF,F,FdcwF,F[v>Fh^w-F`gn6$/F_dwFinFdcw>F]`w-F`gn6$Ff^xFfcw>F_ew
,&F_ewF,Fh]xF,@$Fg\lC&-Fas6#Q>Testing~separatrix~for~x~>~0|+F]\w>F[fw-%1separat
rice_testG6'F_ewFi\wF[]wF\]wF,>8/F[]w?(F]\wF,F,F]\w34F[fw2Ff_xF\^lC%>Ff_x,&Ff_x
F,F,F,@%1Fe]lFf_xC)@$/Ff_xFe]lC$>Fh^w-F_oFghw>F]`w-F_oFihw>Fbew-F_o6#*&-Fjdm6%F
f\xFYFf_xF,,&*&FgdwF,Ff_xF,F,F[ewF[vF[v>Fdcw-Fheo6#-F`gn6$/Fin,&F_dwF,*&FbewF,)
FYFf_xF,F,Fh^w>Ffcw-Fheo6#,&-F`gn6$FeaxF]`wF,**FbewF,Ff_xF,)FY,&Ff_xF,F[vF,F,Fd
cwF,F[v>Fh^wFd^x>F]`wFh^x>F_ew,&F_ewF,FgaxF,C)>FbewF[ax@$F]]x>FbewF_]x>FdcwFaax
>FfcwFjax>Fh^wFd^x>F]`wFh^x>F_ewFebx>F[fw-Fc_x6'F_ewFi\wFf_xF\]wF,@$Fg\lC%-Fas6
#Q>Testing~separatrix~for~x~<~0|+F]\w>F[fw-Fc_x6'F_ewFi\wFf_xF\]wF[v?(F]\wF,F,F
]\wFh_xC%>Ff_xF]`x@%F_`xC)@$Fb`xC$>Fh^wFe`x>F]`wFg`x>FbewFi`x>FdcwFaax>FfcwFjax
>Fh^wFd^x>F]`wFh^x>F_ewFebxC)>FbewF[ax@$F]]x>FbewF_]x>FdcwFaax>FfcwFjax>Fh^wFd^
x>F]`wFh^x>F_ewFebx>F[fwF`cx-F`gn6$/FYF^duF_ewF]\w6#Fg\lF]\wF(,
I0center_manifoldf*Fiiw63F\jwF]jwF^jwF_jwF'FifwF^auF[gnF`jwF[`pFajwF[htFdfmFb^r
%#amGF_au%(stable2GF]\wF]\wC/@%F[oC$>Fh^wFfjw>F]`wFijwC$>Fh^wF`]w>F]`wFj]w>Fgdw
Fh[x>F[ewFao>F[fwF[]w?(FddwFhnF,F[fwF1C+>F_dw,$*&Fd\xF,FgdwF[vF[v@$F]]x>F_dw-Fc
[n6#F_dw>Fdcw-Fheo6#-F`gn6$/Fin,&F_ewF,*&F_dwF,Fi]xF,F,Fh^w>Ffcw-Fheo6#,&-F`gn6
$FegxF]`wF,**F_dwF,FddwF,Fa^xF,FdcwF,F[v>Fh^w-F`gn6$/F_ewFinFdcw>F]`w-F`gn6$Fbh
xFfcw>F[ew,&F[ewF,FggxF,>Ff_x-F\im6$-F`gn6$Ff[xFh^wFY@$/Ff_xFao>F[fw,&F[fwF,F,F
,>80-F]`n6$Ff_xFY>81-F`em6$FbixFY>82-F_o6#-F`gn6$/FYF,Fbix@%-Faq6$Ffix%%evenG@%
1FaoFjix@%/F\]wFao>83F,>FijxFhn@%Fgjx>FijxF_t>FijxFjgq@%Fejx@%Fgjx>FijxFc\r>Fij
xF_hu@%Fgjx>FijxF`hu>FijxF]w@$Fg\lC$@%-F\el6$Fijx<$FhnF_hu>84Fao>F\\yF,@$-F\el6
$Fijx<&FhnF_tF_huF`huC%-Fas6#QETesting~center~separatrix~for~x~>~0|+F]\w>Fbew-F
c_x6'F[ewFi\wF[fwF\\yF,?(F]\wF,F,F]\w34Fbew2F[fwF\^lC%>F[fwF`ix@%1Fe]lF[fwC)@$/
F[fwFe]lC$>Fh^wFe`x>F]`wFg`x>F_dw-F_o6#,$*&-Fjdm6%-Fb[x6$-F`gn6$/FinF[ewF]`wFYF
YF[fwF,FgdwF[vF[v>Fdcw-Fheo6#-F`gn6$/Fin,&F_ewF,*&F_dwF,)FYF[fwF,F,Fh^w>Ffcw-Fh
eo6#,&-F`gn6$Fh^yF]`wF,**F_dwF,F[fwF,)FY,&F[fwF,F[vF,F,FdcwF,F[v>Fh^wF`hx>F]`wF
dhx>F[ew,&F[ewF,Fj^yF,C)>F_dwFj]y@$F]]x>F_dwF^gx>FdcwFd^y>FfcwF]_y>Fh^wF`hx>F]`
wFdhx>F[ewFh_y>FbewFg\y@$Fg\lC$@%-F\el6$Fijx<$FjgqF_hu>F\\yFao>F\\yF,@$-F\el6$F
ijx<&F,FjgqF_huF`huC%-Fas6#QETesting~center~separatrix~for~x~<~0|+F]\w>Fbew-Fc_
x6'F[ewFi\wF[fwF\\yF[v?(F]\wF,F,F]\wFj\yC%>F[fwF`ix@%F`]yC)@$Fc]yC$>Fh^wFe`x>F]
`wFg`x>F_dwFh]y>FdcwFd^y>FfcwF]_y>Fh^wF`hx>F]`wFdhx>F[ewFh_yC)>F_dwFj]y@$F]]x>F
_dwF^gx>FdcwFd^y>FfcwF]_y>Fh^wF`hx>F]`wFdhx>F[ewFh_y>FbewFg\y>Ff_x-F\im6$-F`gn6
$Fb^yFh^wFY7%-F`gn6$FeexF[ewFf_xFijxF]\wFfexF]\wF(,
I'saddlef*6,F[`mFj^lFa_lFcfmFdfmF^goFadn%$rhoG%&sigmaGF`au6/%(lambda1G%(lambda2
G%-lambda_ratioG%1lambda_ratio_numG%1lambda_ratio_denGF]goF\pF]cm%#v1G%#v2GFjiw
%%sep1G%%sep2GF]\wF]\wCA-Fas6%Q<(%a,%a)~is~a~saddle~point.|+F]\w-F_oFc]w-F_oFg]
w-F\r6#FdelFgdy-F\r6#F^r>Fh^w,&9+#F,Fhn-Fgbr6#9,#F[vFhn>F]`w,&FbeyFceyFdeyFcey@
%2-Ffhm6#Fg`x-Ffhm6#Fe`x>Fdcw*&Fh^wF,F]`wF[v>Fdcw*&F]`wF,Fh^wF[v@%33F[iw-Faq6$F
h^w%(integerG-Faq6$F]`wFifyC(>Ffcw-F[dm6#Fdcw>Fddw-F`dmF_gy-Fas6%QHThe~ratio~be
tween~eigenvalues~is~%a:%a|+F^gvFddwFfcwF\eyFbgyF^eyC*>Fdcw-F66$-F_oF_gyFhim>Fd
cwFggy>FfcwF^gy>FddwFagy-Fas6%QXThe~ratio~between~eigenvalues~is~%a:%a~(approxi
mation)|+F^gvFddwFfcwF\eyF]hyF^ey>F_dw-F^^w6&,&Fd_wF,Fh^wF[vFgaw9),&9*F,Fh^wF[v
>Fbew-F^^w6&,&Fd_wF,F]`wF[vFgawFdhy,&FfhyF,F]`wF[v@$FbirC&F\ey-Fas6%QB~The~eige
nvalues~are:~|fr~%a,~%a~|hr|+F]\wFh^wF]`w-Fas6%QC~The~eigenvectors~are:~|fr~%a,
~%a~|hr|+F]\wF_dwFbewF^ey@$Fbir-F\r6$F^rFdel@%50F[]wFao0F\]wFaoC%>Fgdw-Fj`w6'Fi
\wFYFinF[]wF\]w-Fas6#QIMoving~this~saddle~point~to~the~origin.|+F^gv-Fas6$Q<The
~new~vector~field~is~%a|+F]\wFgdw>FgdwFi\w>F_ew-Fdbw6'Fgdw&F_dwFa]w&FbewFa]w&F_
dwF[^w&FbewF[^w-Fas6#Q\oTransform~this~vector~field~so~that~the~linear~part~is~
diagonal.|+F^gv-Fas6$FdjyF_ew>F[ew-Fdfw6#F_ew-Fas6#Q;Make~a~1000-normalization|
+F]\w-Fas6$QDso~that~the~new~vector~field~is~%a|+F]\wF[ew-Fas6#QIWe~calculate~t
he~invariant~separatrices|+F]\wF^ey@%2Fe`xFao>F[fwF,>F[fwFao>Ff_x-Fgiw6%F[ewF^]
lF[fw@%2Fg`xFao>F[fwF,>F[fwFao>Fbix-Fgiw6%-Fdbw6'F[ewFaoF,F,FaoF^]lF[fw@%-Fdgm6
$Fh^wFaoC%-Fas6$Q?The~stable~separatrice~is~%a.|+F^gv7$FbixF^du-Fas6$QAThe~unst
able~separatrice~is~%a.|+F^gv7$F^duFf_x@$FbirC&F\eyFb]zFf]zF^eyC%-Fas6$Fd]zFi]z
-Fas6$Fh]zFe]z@$FbirC&F\eyF]^zF_^zF^ey-Fas6#QZ#################################
#######################|+FjemF\eyFc^zF^ey-F[au6,F[]wF\]wFijyFjjyF[[zF\[zF[ew7$F
f_xFbix7$-%%signGF_fy-F[_zF]fy9-F]\wF]\wF]\wF(,
I-strong_focusf*6'F[dyFjcyFj^lFa_lF`au6%F]dyF^dyF_imF]\wF]\wC*>Fh^w,&F[]wFcey-F
gbr6#Fi\wFgey>F]`w,&F[]wFceyFe_zFcey@%-FdgmFf^wC'-Fas6%QE(%a,%a)~is~a~strong~un
stable~focus.|+F]\wF[ey-F_o6#Fd_wF\eyF\`zF^ey>FdcwF,C'-Fas6%QC(%a,%a)~is~a~stro
ng~stable~focus.|+F]\wF[eyF_`zF\eyFc`zF^ey>FdcwF[vFc^zF\eyFc^zF^ey-Fdfu6&F\]wFd
_wFdcwFgawF]\wF]\wF]\wF(,
I%nodef*6(F[`mF[dyFjcyFj^lFa_lF`au6(F_imF]dyF^dyF_dyF`dyFadyF]\wF]\wC,@%-F`fm6$
F\]wFaoC'-Fas6%Q;(%a,%a)~is~a~stable~node.|+F^gvF_`z-F_o6#FgawF\eyFbazF^ey>Fh^w
F[vC'-Fas6%Q>(%a,%a)~is~an~unstable~node.|+F^gvF_`zFeazF\eyFiazF^ey>Fh^wF,>F]`w
,&F\]wFcey-FgbrFc]wFgey>Fdcw,&F\]wFceyF_bzFcey@%2-Ffhm6#FigyF\fy>Ffcw*&F]`wF,Fd
cwF[v>Ffcw*&FdcwF,F]`wF[v@%33F[iwFjfy-Faq6$FdcwFifyC(>Fddw-F[dm6#Ffcw>Fgdw-F`dm
Fbcz-Fas6%FdgyFgdwFddwF\eyFeczF^eyC*>Ffcw-F66$-F_oFbczFhim>FfcwFicz>FddwFacz>Fg
dwFdcz-Fas6%F_hyFgdwFddwF\eyF_dzF^eyFc^zF\eyFc^zF^ey-Fbeu6&Fd_wFgawFh^wFdhyF]\w
F]\wF]\wF(,
I+degeneratef*6&F[`mFj^lFa_lF`au6#Fd^vF]\wF]\wC--Fas6%QD(%a,%a)~is~a~non-elemen
tary~point.|+F]\wFjdyF[ey-Fas6#Q@Blowing~up~the~vector~field...|+F]\wF\eyFhdzF^
ey>Fh^w-%+blowing_upG6&Fi\wF[]wF\]wF1Fc^zF\eyFc^zF^ey-Fa^v6&F[]wF\]wFh^wFd_wF]
\wF]\wF]\wF(,
I0semi_elementaryf*6+F[`mFj^lFa_lFcfmFdfmF^goFadnF^dyF`au6,FbdyFcdyF]goF\pF]cm%
+center_sepGFddyFedyF_auFjiwF]\wF]\wC=>Fh^w-F^^w6&Fd_wFgawFdhyFfhy>F]`w-F^^w6&,
&Fd_wF,FbeyF[vFgawFdhy,&FfhyF,FbeyF[v>FdcwF]jy>Fddw-Fdbw6'FdcwFb`w&F]`wFa]wFc`w
&F]`wF[^w>Ffcw-Fdfw6#Fddw-Fas6%Qhn(%a,%a)~is~semi-hyperbolic.|+Moving~this~poin
t~to~the~origin.|+F]\wFjdyF[ey-Fas6$FdjyFdcwF][z-Fas6$FdjyFddwFe[z-Fas6$Fj[zFfc
wF[\zF\ey-Fas6%Q=(%a,%a)~is~semi-hyperbolic.|+F]\wFjdyF[ey@$FbirC)-Fas6#QBMovin
g~this~point~to~the~origin.|+F^gvF^gzF][zF`gzFe[zFbgzF[\zF^ey@%-F`fm6$FbeyFao>F
bewF,>FbewFao>Fgdw-Fgex6%FfcwF^]lFbew>F[ew-F`gn6$Feex&FgdwFa]w>F_ew-F`gn6$Feex-
Fgiw6%-Fdbw6'FfcwFaoF,F,FaoF^]lFbew>F_dw&FgdwF^hw@%-F\el6$F_dw<$F,F_tC)-Fas6#Q8
We~have~a~saddle-node.|+F]\w-Fas6$Q7center~separatrice~%a|+F]\w7$F^duF[ew-Fas6$
Q9unstable~separatrice~%a|+F]\w7$F_ewF^duF\eyFfiz@$FbirC$FiizF]jzF^ey@%-F\el6$F
_dw<$FhnFjgqC)FfizFiiz-Fas6$Q7stable~separatrice~%a|+F]\wF`jzF\eyFfiz@$FbirC$Fi
izFhjzF^ey@%/F_dwF_huC)-Fas6#Q3We~have~a~saddle.|+F]\w-Fas6$Q@unstable~center~s
eparatrice~%a|+F]\wF\jzFhjzF\eyF`[[l@$FbirC$Fc[[lFhjzF^ey@%/F_dwF`huC)F`[[l-Fas
6$Q>stable~center~separatrice~%a|+F]\wF\jzF]jzF\eyF`[[l@$FbirC$F[\[lF]jzF^ey@%/
F_dwFc\rC)-Fas6#Q;We~have~an~unstable~node.|+F]\wFiizF]jzF\eyFc\[l@$FbirC$FiizF
hjzF^eyC)-Fas6#Q8We~have~a~stable~node.|+F]\wFiizFhjzF\eyFi\[l@$FbirC$FiizFhjzF
^eyFc^zF\eyFc^zF^ey-F\gu6,F[]wF\]wFb`wFffzFc`wFgfzFfcw7$F_dwF,7$F[ewF_ewFfeyF]
\wF]\wF]\wF(,
I*sing_typef*Fedz6&%$jacG%&deltaGFjcyF[dyF]\wF]\wC,>Fh^w-Fg[w6%Fi\w/FYF[]w/FinF
\]w@$F]]x>Fh^w-Fa[n6$Fc[nFh^w>F]`wz'6&Fb`wFc`w&Fh^wF^hw&Fh^w6#Fjgq\[[[[[[[[\[[m
F,[[[\[[\[[[[[mF[v@$F]]x>F]`w-Fc[nFihw>Fdcw,&Fb`wF,Fe^[lF,@$F]]x>Fdcw-Fc[nF_gy>
Ffcw,&*$FdcwFhnF,F]`w!"%@$F]]x>Ffcw-Fc[nFbcz@$FbirC)F\ey-Fas6%Q>(%a,%a)~is~a~si
ngular~point.|+F]\wF[]wF\]w-Fas6'QGJacobian~=~[~[~%a,~%a~],~[~%a,~%a~]~]|+F]\wF
b`wFc`wFd^[lFe^[l-Fas6$Q,Delta~=~%a|+F]\wF]`w-Fas6$Q*Rho~=~%a|+F]\wFdcw-Fas6$Q,
Sigma~=~%a|+F]\wFfcwF^ey@%-F`fm6$F]`wFao-Fgcy6,Fi\wF[]wF\]wFb`wFc`wFd^[lFe^[lFd
cwFfcwFd_w@%-FdgmFi`[l@%-Figm6$FfcwFao-Fi`z6(Fi\wFfcwFdcwF[]wF\]wFd_w@%-F^hm6$F
dcwFao-%+weak_focusG6&Fi\wF[]wF\]wFd_w-F^_z6'FfcwFdcwF[]wF\]wFd_w@%Fda[l-FcdzFh
a[l-Fdez6+Fi\wF[]wF\]wFb`wFc`wFd^[lFe^[lFdcwFd_wF]\wF]\wF]\wF(,
I1separatrice_testf*6'F^auFKFeemFjiw%$dirG6'F[`p%'rndnumG%(exefileG%(sepfileGF'
F]\wF]\wC2>Fdcw-FC6$%,user_bindirG%,user_sepexeG>F]`w-%%iremG6$-%%randGF]\wFdiw
>Ffcw-FC6&%,user_tmpdirGQ'P4SEP_F]\wF]`wQ%.TMPF]\w-F\rFbcz-Fas6$FiemF`\l-Fas6$F
dwFgaw-Fas6$FdwFd_w-F^dlFc]w-Fas6$Fdw,&F\]wF,F[vF,?(FddwFhnF,F\]wF1-Fas6%Q'%d~%
g~F]\wFddw-Fjdm6%Fi\wFYFddw-Fas6#F^y-F`rFbcz-Fas6$Q;Separatrix~test~(n=%d)...~F
]\wF\]w>Fh^w-%(ssystemG6#-FC6'%/user_exeprefixGFdcwQ#~"FjemFfcwQ""Fjem-Fbe[l6#-
FC6&%/user_removecmdGFge[lFfcwFhe[l@%/Fb`wFaoC$-Fas6#Q(not~ok|+F]\wFboC$-Fas6#Q
$ok|+F]\wF1F]\w6(Ffe[lFfc[l%,user_lypexeGF[c[lF]f[lF`\lF]\wF(,
I+weak_focusf*6&F[`mFj^lFa_lF`au6-F_auF]go%%aa10G%%aa01G%%bb10GFcjnF\pFjfn%#ggG
%$lypGFianFjemFjemC,-Fas6%Q:(%a,%a)~is~a~weak~focus.|+Fjem-F_o6#9%-F_o6#9&-F\r6
#FdelFdg[l-F\r6#F^r@%FgdlC*>8.,&-%*integrateG6$&9$6#F,FinF,-Fgh[l6$,&-FU6$Ffh[l
FYF[v&Fjh[l6#FhnF[vFYF,-Fas6#QTSince~the~system~is~hamiltonian,~we~have~a~cente
r.|+Fjem-Fas6$QKThe~Hamiltonian~function~is:|+~H(x,y)~=~%a|+FjemFdh[lF]h[lFci[l
Ffi[lF_h[l>8$FjgqC.>8%-Fj`w6'Fjh[lFYFinFig[lF\h[l>8&-Fjdm6%-Fjdm6%&F]j[lF[i[lFY
F,FinFao>8'-Fjdm6%-Fjdm6%Ffj[lFYFaoFinF,>8(-Fjdm6%-Fjdm6%&F]j[lFbi[lFYF,FinFao>
8)-Fgbr6#,&*&Fhj[lF,F^[\lF,F[v*$Faj[lFhnF[v>8*7$,&*(F^[\lF,-F`gn6$<#/FY,&*(Fe[
\lF,8+F,F^[\lF[vF[v*(Faj[lF,FinF,F^[\lF[vF,Ffj[lF,Fe[\l!"#F,*(Faj[lF,-F`gn6$Fb
\\lFc[\lF,Fe[\lFh\\lF[v,$*&-F`gn6$<#/FY,&*(Fe[\lF,FYF,F^[\lF[vF[vFg\\lF,Fc[\lF,
Fe[\lF[vF[v@%F][l>F\\\l-F_o6#-F`gn6$/Ff\\lFYF\\\l>F\\\lFh]\l-Fas6$Q6The~local~s
ystem:~%a|+FjemF\\\l>8,,&-F`gn6$<$/FY,&F`im#F,Fhn%"wGFg^\l/Fin*&^##F[vFhnF,,&F`
imF,Fh^\lF[vF,&F\\\lF[i[lF,*&^#F,F,-F`gn6$Fd^\l&F\\\lFbi[lF,F,>F`^\l-Fheo6#F`^
\l@$FbirC%F]h[l-Fas6$Q)z'~=~%a|+FjemF`^\lF_h[l@%/Fc^lFaoC%-F\r6$FdelF^r-Fas6#Qe
nLyapunov~constants~are~not~calculated.~(weakness~level=0)|+Fjem>Fji[lFaoC%@%F]
[l>8--%)lyapunovG6%,&F`^\lF,*&^#F[vF,F`imF,F,F`imFh^\l>Fh`\l-%,lyapunovsymGF[a
\l-Fas6$Q:Lyapunov~information:~%a|+FjemFh`\l@%0&Fh`\lF[i[lFaoC'F_`\l-Fas6$Q=Th
e~order~of~weakness~is~%d|+Fjem&Fh`\lFbi[l-Fas6$Q9Lyapunov~constant~is~%g|+Fjem
,$Fga\lF[vF_h[l@%2Fga\lFaoC'-Fas6#QBWe~have~an~unstable~singularity.|+FjemF]h[l
Fdb\lF_h[l>Fji[lF,C'-Fas6#Q?We~have~a~stable~singularity.|+FjemF]h[lFib\lF_h[l>
Fji[lF[v@%/&Fh`\l6#F_tFhnC'-Fas6#QMWe~have~a~center~(the~system~is~quadratic).|
+FjemF]h[lFbc\lF_h[l>Fji[lFjgq@%&Fh`\l6#FjgqC'-Fas6#QPWe~have~a~center~(the~sys
tem~is~linear+cubic).|+FjemF]h[lFjc\lF_h[l>Fji[lFjgqC'-Fas6$QGThe~order~of~weak
ness~is~at~least~%d.|+Fjem,&Fc^lF,F,F,F]h[lF_d\lF_h[l>Fji[lFaoF]h[l-Fas6#Fe^zF_
h[lFdd\l-F\fu6&Fig[lF\h[l9'Fji[lFjem6#FgdlFjemF(,
I)lyapunovf*6%F[`mF`imFh^\l6,Fcfm%'bindirG%'infileG%(outfileGFeb[l%'resultGFdb[
l%#wlG%&linfoG%$auxGFjemFjemC,>F\\\l-F_c[l6$-Fbc[lFjemFdiw>Faj[l-FC6&Ffc[lQ'P4L
YP_FjemF\\\lQ%.INPFjem>Fhj[l-FC6&Ffc[lF]f\lF\\\lQ%.OUTFjem@%/FcrFao>F^[\l-FC6$F
[c[lFif[l>F^[\l-FC6$F[c[l%0user_lypexe_mpfG>F`^\l-%4preparelyapunovfileG6&Faj[l
Fjh[lFig[lF\h[l>Ff\\l&F`^\lF[i[l-Fas6#QDDetermining~lyapunov~constants~...|+Fje
m>Fh`\l-Fbe[l6#-FC6.Ffe[lQ!FjemF^[\lFge[lFaj[lQ$"~"FjemFhj[lQ)"~MAPLE~Fjem%.use
r_platformGFge[l%2user_sumtablepathGFhe[l>Fe[\l-%3readlyapunovresultG6$Fhj[lFf
\\l7%-Fhjl6#Fe[\l&F`^\lFbi[l&F`^\lF`c\lFjem6)Ffe[lFfc[lFif[lF[g\lFcrF[c[lF]f[lF
jemF(,
I3readlyapunovresultf*6$F]ao%*weaklevelG6)%(lypdataG%&VdataGF_pFeem%%wvalG%'lyp
valG%&okvalGFjemFjemC.>Fji[l-%)readdataG6$Fjh[lF,-Fas6$Q4lyapunov~data~=~%a|+Fj
emFji[l>F]j[l7">Fhj[lF,-F\r6$F^rFdel?(Faj[lF,F,Fig[lF1C&@$0&Fji[l6#Fhj[lF[v-Fas
6%Q*V(%d)=%g|+Fjem-Fdbr6#Fdj\l&Fji[l6#,&Fhj[lF,F,F,>F]j[l7$-Fhjl6#F]j[l7$Fij\lF
[[]l@$/Fij\lF[vC$>Fhj[lF][]l[>Fhj[l,&Fhj[lF,FhnF,@$Fd[]l>Fhj[lF][]l>F\\\lFij\l>
F^[\l-Fdbr6#F[[]l>Fe[\l&Fji[l6#Fi[]lF_h[l7$Fe[\lF^[\lFjemFjemFjemF(,
I4preparelyapunovfilef*6&F]aoF``nF`imFh^\l6)F[`m%&cubicGF_imFadnFcfmF_pFbe\lFje
mFjemC.>Fji[l-F_]n6%Fig[lF\h[lFhd\l>F]j[lFbo-F\r6#Fjh[l-Fas6$Fdw,&FcrFhnFhnF,>F
hj[l-F^cn6%Fji[lF\h[lFhd\l@%/Fhj[lFhnC$>F\\\lF_t-Fas6#Q#3|+Fjem@%/Fhj[lF_tC$>F
\\\lFc\r@%33/-Fjdm6%-Fjdm6%Fji[lF\h[lFhnFhd\lFaoFao/-Fjdm6%-Fjdm6%Fji[lF\h[lFao
Fhd\lFhnFao/-Fjdm6%-Fjdm6%Fji[lF\h[lF,Fhd\lF,FaoC$-Fas6#Q#5|+Fjem>F]j[lF1C$>F\\
\lFc^l-Fas6$FdwFc^lC$>F\\\lFc^lFj_]l-Fas6$Fiem)Fagm,$F\wF[v>Faj[l-FiipFe]]l-Fas
6$Fdw-F.6#Faj[l?(Fe[\lF,F,Ff`]lF1C$>F^[\l&Faj[lFeh\l-Fas6'Q/~~%d~%d~%g~%g|+Fjem
&F^[\lF[i[l&F^[\lFbi[l-F_o6#-F^\s6#&F^[\lF`c\l-F_o6#-Fe[sFda]l-F`rF_]]l7%F\\\lF
hj[lF]j[lFjemFjemFjemF(,
I,lyapunovsymf*6%F``nF`imFh^\l6+F[`mFce\lFbe\lF'%"TGFcfqFae\lF[`pF_pFjemFjemC,>
Fji[l-F_]n6%Fjh[lFig[lF\h[l>F]j[l-%3preparelyapunovsymG6%Fji[lFig[lF\h[l>Faj[lF
fj[l>F\\\lF\j\l>Ff\\lFboF^j\l?(Fhj[lF,F,Faj[lF1C(>F^[\l-%)sumtableG6#,$Fhj[lFhn
>Fe[\lFao?(F`^\lF,F,-F.6#F^[\lF1>Fe[\l,&Fe[\lF,-%4part_lyapunov_coeffG6'Fji[lFi
g[lF\h[l&F^[\lFf_\l,&Fhj[lFhnF,F,F[v>F\\\l7$-Fhjl6#F\\\l7$Fe[\lFhj[l-Fas6&Q2k=%
d~V~=~%a~=~%f|+FjemFhj[lFe[\l-F_oFeh\l@$-Fghm6$Fe[\lFaoC$>Ff\\lF1Fg[]lF_h[l@%Ff
\\l>F\\\l&F\\\l6#F[v>F\\\l7$FaoFao7%F_d]lFc[\l&F]j[lF`c\lFjemFjemFjemF(,
I3preparelyapunovsymf*F\e\l6(Fh\]lF_imFadnFcfmF_pFbe\lFjemFjemC'>Fji[lFbo>Faj[l
-F^cnFcb]l@%/Faj[lFhn>Fe[\lF_t@%/Faj[lF_tC$>Fe[\lFc\r@%33/-Fjdm6%-Fjdm6%Fjh[lFi
g[lFhnF\h[lFaoFao/-Fjdm6%-Fjdm6%Fjh[lFig[lFaoF\h[lFhnFao/-Fjdm6%-Fjdm6%Fjh[lFig
[lF,F\h[lF,Fao>Fji[lF1>Fe[\lFc^l>Fe[\lFc^l>F]j[l-FiipFcb]l7%Fe[\lFaj[lFji[lFjem
FjemFjemF(,
I)sumtablef*6#Feem6&F_imF%Fcjn%+st_compareGFjemFjemC&>Fji[l-%*piecewiseG6%/Fjh[
lFao7#7#F,-Fa[n6$Fhjl-Fa[n6$&%)combinatG6#%(permuteG-&F[i]l6#%*partitionG6$Fjh[
lFjh[l>Fhj[lf*6$F%FcjnFjem6$FffmFgfmFjem@%2Fih[l&Fig[lF[i[lF1@%/Fih[lFii]l-T#6$
&Fjh[l6#;FhnF[v&Fig[lF`j]lFboFjemFjem6$F]h]lFhj[l>Fji[l-Fejn6$Fji[lFhj[lOFji[lF
jemFjemFjemF(,
I4part_lyapunov_coefff*6'%)vecfieldGF`imFh^\lF_imF'6(%"RGFMF[`mFgaq%#wwGF`pFjem
FjemC%>Fji[l-Fa[n6$f*6#FMFjemFfi]lFjem-%-lyp_findpolyG6&T$T&T(,&Fjh[lF,F,F,Fjem
Fjem6(F[[^lFjh[lF`imFig[lFh^\lF\h[lFhd\l@%4-F\el6$FaoFji[lC&>Faj[lF[v?(Fe[\lF,F
,,&-F.6#Fji[lF,F[vF,F1@%-Faq6$,&Fe[\lF,F[vF,%$oddG>Faj[l-%)lyp_RegzG6&Faj[l&Fji
[lFeh\lFig[lF\h[l>Faj[l-%)lyp_ImgzGF_]^l>Fe[\lFe\^l@%Fh\^lC%>Faj[l-%/lyp_multc_
polyG6'Faj[lFaoF[vFig[lF\h[l>6$Faj[lFhj[l-Fhjl6#-%'lyp_LLG6'Faj[lF`]^lFig[lF\h[
l,&9(Fg^\lF\_\lF,>F^[\l-Fgbl6#-Fe[sFej\lC$>F\^^lF]^^l>F^[\l-Fgbl6#-F^\sFej\l>F^
[\lFaoOF^[\lFjemFjemFjemF(,
I/lyp_multc_polyf*6'F[`mFcfmFdfmF`imFh^\lFjemFjemFjemO-Fheo6#*&,&Fig[lF,*&F`_\l
F,F\h[lF,F,F,Fjh[lF,FjemFjemFjemF(,
I-lyp_findpolyf*6&FKF`imFh^\lFeem6$F%F'FjemFjemC%>Fji[lFao?(F]j[lFaoF,Fhd\lF1>F
ji[l,&Fji[lF,*(-Fjdm6%-Fjdm6%Fjh[lFig[lF]j[lF\h[l,&Fhd\lF,F]j[lF[vF,)Fig[lF]j[l
F,)F\h[lFg`^lF,F,Fji[lFjemFjemFjemF(,
I)lyp_Regzf*6&F[`mF\pF`imFh^\l6#F%FjemFjemC(>Fji[l-Fheo6#*&Fjh[lF,Fig[lF,>Fji[l
-Fi]^l6'Fji[lFaoF[vF\h[lFhd\l>Fji[l-FU6$Fji[lF\h[l>Fji[l-%&lyp_GGFe]]l>Fji[l,&F
ji[lF,-%.lyp_conj_polyGFe]]lF,O-Fi]^l6%Fji[lFg^\lFaoFjemFjemFjemF(,
I)lyp_Imgzf*F\a^lF]a^lFjemFjemC'>Fji[lF`a^l>Fji[lFga^l>Fji[lFja^l>Fji[l,&Fji[lF
,F^b^lF[vO-Fi]^l6%Fji[lFaoF\_\lFjemFjemFjemF(,
I'lyp_LLf*6'F[`mF\pF`imFh^\lFeemF]a^lFjemFjemC$>Fji[l-FU6$F`a^lF\h[l7$Fji[l-Fjd
m6%-Fjdm6%Fji[lF\h[lFc^^lFhd\lFc^^lFjemFjemFjemF(,
I&lyp_Gf*F\e\l6&F'%#fkGF%F_goFjemFjemC%>Faj[lFao@$1Fao-F`em6$Fjh[lFig[l?(Fji[lF
aoF,Fbd^lF1C$>F]j[l-Fjdm6%Fjh[lFig[lFji[l@$1Fao-F`em6$F]j[lF\h[l?(Fhj[lFaoF,F[e
^lF1@%0Fji[lFhj[l>Faj[l,&Faj[lF,**-Fjdm6%F]j[lF\h[lFhj[lF,,&Fji[lF,Fhj[lF[vF[v)
Fig[lFji[lF,)F\h[lFhj[lF,Fhn>Faj[l,&Faj[lF,*(Fce^lF,Ffe^lF,Fge^lF,F,-FheoFg`]lF
jemFjemFjemF(,
I.lyp_conj_polyf*F\e\l6#%#zbGFjemFjemC$-%)assumingG6$7#-Fheo6#-F[\oF_]]l7$'Fig[
l%%realG'F\h[lFjf^l-F]jm6$-F]jm6$-F]jm6$%"%G<#/Fig[lFji[l/F\h[lFig[l/Fji[lF\h[l
FjemFjemFjemF(,
I5vec_field_diff_chartf*6%F[`mFYFin6*Fadn%%f_U1G%%f_V1G%%f_U2G%%f_V2G%$linG%%si
ngG%(sdegreeGF^gvF^gvC4>8$-Fhjm6$-F^cn6%&9$6#F,9%9&-F^cn6%&Fjh^l6#FhnF\i^lF]i^l
>8%-Fien6%7$*&)FihpFdh^lF,,&*&FhhpF,-F`gn6$<$/F\i^l*$FihpF[v/F]i^l*&FhhpF,FihpF
[vFih^lF,F[v-F`gn6$F]j^lF`i^lF,F,,$*&)Fihp,&Fdh^lF,F,F,F,F[j^lF,F[vFhhpFihp>8&-
Fien6%7$*&Fhi^lF,,&*&FhhpF,-F`gn6$<$/F\i^l,$F_j^lF[vF`j^lFih^lF,F,-F`gn6$Fb[_lF
`i^lF,F,*&Ffj^lF,F`[_lF,FhhpFihp>8'-Fien6%7$*&Fhi^lF,,&-F`gn6$<$/F\i^lFaj^l/F]i
^lF_j^lFih^lF,*&FhhpF,-F`gn6$Fa\_lF`i^lF,F[vF,,$*&Ffj^lF,Fe\_lF,F[vFhhpFihp>8(-
Fien6%7$*&Fhi^lF,,&-F`gn6$<$Fb\_l/F]i^lFd[_lFih^lF,*&FhhpF,-F`gn6$Fb]_lF`i^lF,F
,F,*&Ffj^lF,Fe]_lF,FhhpFihp@$4-F\el6$Fjs<$F,F_tC&-Fas6#QCWe~make~use~of~the~Poi
ncare~disc.|+F^gv-F\r6#Fdel-Fas6#QHWe~make~a~study~on~the~Poincare~disc.|+|+F^g
v-F\r6#F^r>8)7$-F\im6$-F`gn6$/FihpFao&Fci^lF[i^lFhhp-F\im6$-F`gn6$F___l&Fci^lFa
i^lFhhp@%3/&Fi^_lF[i^lFao/&Fi^_lFai^lFaoC(@$Fi]_lC&-Fas6#QFInfinity~is~a~line~o
f~singularities.|+F^gvFa^_lF_`_lFf^_l>Fci^l-Fien6%7$*&F`__lF,FihpF[v*&Fe__lF,Fi
hpF[vFhhpFihp>Fi[_l-Fien6%7$*&&Fi[_lF[i^lF,FihpF[v*&&Fi[_lFai^lF,FihpF[vFhhpFih
p>Fij^l-Fien6%7$*&&Fij^lF[i^lF,FihpF[v*&&Fij^lFai^lF,FihpF[vFhhpFihp>Fj\_l-Fien
6%7$*&&Fj\_lF[i^lF,FihpF[v*&&Fj\_lFai^lF,FihpF[vFhhpFihp>8*F,>Fab_lFao-%,show_c
hartsG6$7&Fci^lFij^lFi[_lFj\_l7&Q#U1F^gvQ#V1F^gvQ#U2F^gvQ#V2F^gv-F\r6#F_s-F^dl6
#-F`gn6%/FhhpF\i^l/FihpF]i^lFci^l-F^dl6#-F`gn6%Fbc_lFcc_lFij^l-F^dl6#-F`gn6%Fbc
_lFcc_lFi[_l-F^dl6#-F`gn6%Fbc_lFcc_lFj\_l-Fas6$FdwFab_l@%-Faq6$,&Fdh^lF,F[vF,Fc
jxC$>8+Fao-Fas6#Q#1|+F^gvC$>Fhd_lF,-Fas6#Q$-1|+F^gvFf^_l@%Fi]_l@%/Fab_lFao-%/fi
nd_inf_rootsG6)Fdh^lFjh^lFci^lFi[_lF\i^lF]i^lFhd_l-%4find_inf_roots_singG6$Fci^
lFi[_l-Fas6#QOSingularities~at~infinity~are~not~determined.|+F^gvF^gvF^gvF^gvF(,
I,show_chartsf*6$%%flstG%(namelstG6$F[`mF'F^gvF^gv?(Fci^lF,F,-F.6#Fjh^lF1C%-Fas
6$QJThe~differential~system~on~the~%s~chart:|+F^gv&F\i^l6#Fci^l>Fdh^l-F]jm6#&Fj
h^lF[g_l-Fas6%Q<~~~~z1'~=~%a|+~~~~z2'~=~%a|+|+F^gv&Fdh^lF[i^l&Fdh^lFai^lF^gvF^g
vF^gvF(,
I.behaviour_inff*6$F[`mFadn64%#p1G%#q1GFjfnF[gnF\pFe][lFf][lFjcyF[dyF^g[lF_g[lF
`g[lFcjn%#zzG%$zzbGFhfwFifwFbg[lF^gvF^gvC,>Fdh^l-F`gn6$<$/FY*&Fij^lF,,&*$Fij^lF
hnF,*$Fi[_lFhnF,F[v/Fin*&Fi[_lF,Fdh_lF[vFih^l>Fci^l-F`gn6$Fah_lF`i^l>Fj\_l7$*&)
Fdh_lF\i^lF,,&*&Fdh_lF,Fdh^lF,F,*&Fij^lF,,&*&Fij^lF,Fdh^lF,F,*&Fi[_lF,Fci^lF,F,
F,Fh\\lF,*&F_i_lF,,&*&Fdh_lF,Fci^lF,F,*&Fi[_lF,Fci_lF,Fh\\lF,>Fj\_l-FQ6%Fj\_lFi
j^lFi[_l>Fj\_l-Fien6%-F`gn6$<$/Fij^lFY/Fi[_lFinFj\_lFYFin>Fi^_l-Fg[w6%Fj\_l/FYF
ao/FinFao>Fab_lz'6&Fi__lF[`_l&Fi^_l6#F_t&Fi^_l6#Fjgq\[[[[[[[[\[[mF,[[[\[[\[[[[[
mF[v>Fhd_l,&Fi__lF,F_[`lF,>8,,&*$Fhd_lFhnF,Fab_lFb_[l@$-F`fm6$Fd[`lFao@%-F^hm6$
Fhd_lFaoC1>8--F_o6#-Fjdm6%-Fjdm6%F]b_lFinFaoFYF,>8.-F_o6#-Fjdm6%-Fjdm6%F]b_lFYF
aoFinF,>8/-F_o6#-Fjdm6%-Fjdm6%F_b_lFinFaoFYF,>80-F_o6#-Fgbr6#,&*&Fg\`lF,F_]`lF,
F[v*$F_\`lFhnF[v>Fj\_l7$,&*(F_]`lF,-F`gn6$<#/FY,&*(Fg]`lF,Fij^lF,F_]`lF[vF[v*(F
_\`lF,Fi[_lF,F_]`lF[vF,F]b_lF,Fg]`lFh\\lF,*(F_\`lF,-F`gn6$Fe^`lF_b_lF,Fg]`lFh\\
lF[v*&-F`gn6$<#/FY,&Fh^`lF[v*(F_\`lF,FinF,F_]`lF[vF,F_b_lF,Fg]`lF[v>Fj\_l-F_o6#
F`j_l>Fj\_l,&-F`gn6$<$/FY,&81#F,Fhn82F_``l/Fin*&^##F[vFhnF,,&F^``lF,F```lF[vF,F
]b_lF,*&^#F,F,-F`gn6$F[``lF_b_lF,F,>Fj\_l-F_o6#-Fheo6#Fj\_l>Fj\_l*&Fj\_lF,-F_o6
#-Fjdm6%-Fjdm6%-Fjdm6%Fj\_lF```lFaoF^``lF,Fg``lF,F[v>85-Fj`\l6%,&Fag[lF,*&^#F[v
F,F^``lF,F,F^``lF```l@%0&Fja`lF[i^lFaoC)-Fas6$Q>The~order~of~weakness~is~%d.|+F
^gv&Fja`lFai^l-Fas6$Q>The~lyapunov~constant~is~%g.|+F^gv,$Fbb`lF[vFa^_lFdb`lFhb
`lFf^_l@%2Fbb`lFaoC&-Fas6#QBThe~equator~is~weakly~repelling.|+F^gvFa^_lF_c`lFf^
_lC&-Fas6#QCThe~equator~is~weakly~attracting.|+F^gvFa^_lFcc`lFf^_l@%5/&Fja`lF^[
`lFhn/&Fja`lF`[`lF,C&-Fas6#QIWe~have~a~center~behaviour~at~infinity.|+F^gvFa^_l
F]d`lFf^_lC&-Fas6$QSThe~order~of~weakness~at~infinity~is~at~least~%d.|+F^gv,&Fc
^lF,F,F,Fa^_lFad`lFf^_lFa^_l-Fas6#QL##########################################|
+F^gvFf^_lFed`lC%>83-F_o6#,&Fhd_lF_``l-Fgbr6#Fd[`lFd``l>84-F_o6#,&Fhd_lF_``lF^e
`lF_``l@%-FdgmF\\`lC&-Fas6#Q;The~equator~is~repelling.|+F^gvFa^_lFhe`lFf^_lC&-F
as6#Q<The~equator~is~attracting.|+F^gvFa^_lF\f`lFf^_lF^gvF^gvF^gvF(,
I)pl_chartf*6#F[`m63F_pF^goFadnFgfnFhfnF\pFianF[h^lF\h^lF]h^lF^h^l%$f_CGF]pF^p%
#t1G%#t2G%#t3GF^gvF^gvC9>Fi[_lF[t>Fj\_lF\t@$30FjsF,0FjsF_tC%-F\r6$FdelF^r-Fas6%
Q^oWe~make~the~study~on~the~Poincare-Lyapunov~disc~of~degree~(%d,%d).|+F^gvFi[_
lFj\_lFf^_l>Fci^l-F`gl6'Fjh^lFYFinFi[_lFj\_l>Fi^_l,&*&)FihpFj\_lF,-F`gn6$<$/FY*
&Fij^lF,)FihpFi[_lF[v/Fin*&FhhpF,Fjg`lF[vF`i^lF,F,*.Fij^lF,Fj\_lF,Fi[_lF[vF`h`l
F,FhhpF,-F`gn6$F]h`lFih^lF,F[v>Fab_l,$**Fij^lF,Fi[_lF[v)Fihp,&Fi[_lF,F,F,F,Fdh`
lF,F[v>Fhd_l-Fien6%-F`gn6$/Fij^lF,7$*&Fi^_lF,)FihpFci^lF,*&Fab_lF,Fci`lF,FhhpFi
hp>Fd[`l-Fien6%-F`gn6$/Fij^lF[vFai`lFhhpFihp>Fi^_l,&*&F`h`lF,-F`gn6$<$/FY*&Fhhp
F,F`h`lF[v/Fin*&Fij^lF,Fjg`lF[vFih^lF,F,*.Fij^lF,Fi[_lF,Fj\_lF[vFjg`lF,FhhpF,-F
`gn6$F`j`lF`i^lF,F[v>Fab_l,$**Fij^lF,Fj\_lF[v)Fihp,&Fj\_lF,F,F,F,Ffj`lF,F[v>F_
\`lF\i`l>Fg\`lFfi`l>Fi^_l,&*()F%Fjh`lF,F]`uF,-F`gn6$<$/FY*&F]`uF,)F%Fi[_lF[v/Fi
n*&F^`uF,)F%Fj\_lF[vFih^lF,F[v*()F%F\[alF,F^`uF,-F`gn6$Fe[alF`i^lF,F[v>Fab_l,&*
*Fj\_lF,Fh[alF,F^`uF,Fc[alF,F[v**Fi[_lF,F[\alF,F]`uF,F^\alF,F,>F_]`l7$-Fcfo6&*&
Fi^_lF,)F%Fci^lF,F%F]`uF^`u-Fcfo6&*&Fab_lF,Fi\alF,F%F]`uF^`uF\c_l-F^dl6#-F`gn6$
<$/FhhpFY/FihpFinFhd_l-F^dl6#-F`gn6$Fa]alFd[`l-F^dl6#-F`gn6$Fa]alF_\`l-F^dl6#-F
`gn6$Fa]alFg\`l-Fg_u6#F_]`lFf^_l@$F[g`lCD>Fi^_l-F_]s6$-F`gn6$F___l&Fhd_lF[i^lFh
hp>Fg]`lFi__l>F^``lF[`_l-F\r6#Fael-Fas6$Fdw,&-F.6#Fg]`lF,-F.6#F^``lF,Ff^_l-Fas6
#QJThe~differential~system~on~the~U1~chart:|+F^gvFa^_l-Fas6%Q]oFirst~we~study~t
he~system~on~the~U1~chart~(x=1/z2^%d,y=z1/z2^%d).|+F^gvFi[_lFj\_lF_g`l-Fas6%Q;~
~~~z1'~=~%a|+~~~~z2'~=~%a|+F^gvFi^al&Fhd_lFai^lFf^_l?(Fdh^lF,F,Fa_alF1C&>F```l-
F]jm6$-FU6$Fi^alFhhp<$/Fhhp&Fg]`l6#Fdh^lF___l>Fjd`l-F]jm6$-FU6$Fi^alFihpFf`al>F
ae`l-F]jm6$-FU6$F^`alFihpFf`al-%)type_infG6)Fhd_lF,Fh`alF```lFjd`lFae`lFao>F[oF
1?(Fdh^lF,F,Fc_alF1C&>F```l-F_o6#-F]jm6$Fd`al<$/Fhhp&F^``lFi`alF___l>Fjd`l-F_o6
#-F]jm6$F]aalF_bal>Fae`l-F_o6#-F]jm6$FbaalF_bal-Feaal6)Fhd_lF,FabalF```lFjd`lFa
e`lFao>F[oF][l>Fi^_l-F_]s6$-F`gn6$F___l&Fd[`lF[i^lFhhp>Fg]`lFi__l>F^``lF[`_lF\_
alF^_alFf^_l-Fas6#QJThe~differential~system~on~the~V1~chart:|+F^gvFa^_l-Fas6%Q
\oNow~we~study~the~system~on~the~V1~chart~(x=-1/z2^%d,y=z1/z2^%d).|+F^gvFi[_lFj
\_lF_g`l-Fas6%F]`alFdcal&Fd[`lFai^lFf^_l?(Fdh^lF,F,Fa_alF1C&>F```l-F]jm6$-FU6$F
dcalFhhpFf`al>Fjd`l-F]jm6$-FU6$FdcalFihpFf`al>Fae`l-F]jm6$-FU6$F_dalFihpFf`al-F
eaal6)Fd[`lF_tFh`alF```lFjd`lFae`lFao>F[oF1?(Fdh^lF,F,Fc_alF1C&>F```l-F]jm6$Fed
alF_bal>Fjd`l-F]jm6$FjdalF_bal>Fae`l-F]jm6$F_ealF_bal-Feaal6)Fd[`lF_tFabalF```l
Fjd`lFae`lFao>F[oF][l@%3-F^hm6$-F`gn6$<$/FhhpFaoF___l&F_\`lF[i^lFao-F^hm6$-F`gn
6$Fhfal&F_\`lFai^lFaoC/F\_alFid_lFf^_l-Fas6#QJThe~differential~system~on~the~U2
~chart:|+F^gvFa^_l-Fas6%Q[oNow~we~study~the~system~on~the~U2~chart~(x=z1/z2^%d,
y=1/z2^%d).|+F^gvFi[_lFj\_lF_g`l-Fas6%F]`alFjfalF_galFf^_l>F```l-F]jm6$-FU6$Fjf
alFhhpFhfal>Fjd`l-F]jm6$-FU6$FjfalFihpFhfal>Fae`l-F]jm6$-FU6$F_galFihpFhfal-Fea
al6)F_\`lFhnFaoF```lFjd`lFae`lFaoC&F\_al-Fas6#F]gvFf^_l-Fas6#QQIn~the~U2~chart,
~no~extra~singularity~is~found.|+F^gv@%3-F^hm6$-F`gn6$Fhfal&Fg\`lF[i^lFao-F^hm6
$-F`gn6$Fhfal&Fg\`lFai^lFaoC/F\_alFid_lFf^_l-Fas6#QJThe~differential~system~on~
the~V2~chart:|+F^gvFa^_l-Fas6%Q\oNow~we~study~the~system~on~the~V2~chart~(x=z1/
z2^%d,y=-1/z2^%d).|+F^gvFi[_lFj\_lF_g`l-Fas6%F]`alFfialF[jalFf^_l>F```l-F]jm6$-
FU6$FfialFhhpFhfal>Fjd`l-F]jm6$-FU6$FfialFihpFhfal>Fae`l-F]jm6$-FU6$F[jalFihpFh
fal-Feaal6)Fg\`lFjgqFaoF```lFjd`lFae`lFaoC&F\_alF[ialFf^_l-Fas6#QQIn~the~V2~cha
rt,~no~extra~singularity~is~found.|+F^gvF^gv6%F[tF\tF[oF^gvF(,
I/find_inf_rootsf*6)FadnF[`mF[h^lF]h^lFYFinFah^l6/%$p_dG%$q_dGFgfnFhfnF\pF]pF^p
%$totGF_pFdf`lFef`lFff`lFianF^gvF^gvCH>Fdh^l-F^dn6&&F\i^lF[i^l9(9)Fjh^l>Fci^l-F
^dn6&&F\i^lFai^lFg\blFh\blFjh^l>Fij^l-F^dn6&Ff\blFg\blFh\bl,&Fjh^lF,F[vF,>Fi[_l
-F^dn6&F\]blFg\blFh\blF`]bl>Fg]`l,&-F`gn6$/Fg\blF,Fci^lF,*&Fh\blF,-F`gn6$Fh]blF
dh^lF,F[v>Fj\_l-F_]s6$Fg]`lFh\bl>Fi^_lF]b_l>Fab_lF_b_lF\_al-Fas6$Fdw,&-F.6#Fi^_
lFhn-F.6#Fab_lFhnFf^_l>Fhd_l,&Fd^blF,Ff^blF,Fe_alFa^_l-Fas6#QgnFirst~we~study~t
he~system~on~the~U1~chart~(x=1/z2,y=z1/z2):|+F^gvF_g`l-Fas6%F]`al&F]i^lF[i^l&F]
i^lFai^lFf^_l@$FbirC%Fa^_l-Fas6#Q9We~change~z1->x,~z2->y.|+F^gvFf^_l?(Fd[`lF,F,
Fd^blF1C&>F_\`l-F]jm6$-FUF^^bl/Fh\bl&Fi^_lF_e`l>Fg\`l-F]jm6$,&Fi[_lF,*&Fh\blF,F
ij^lF,F[v<$Fh]blF\`bl>F_]`l,$-F]jm6$Fdh^lFc`blF[v-Feaal6)F]i^lF,F]`blF_\`lFg\`l
F_]`l9*>F[oF1?(Fd[`lF,F,Ff^blF1C&>F_\`l-F_o6#-F]jm6$F[`bl/Fh\bl&Fab_lF_e`l>Fg\`
l-F_o6#-F]jm6$Fa`bl<$Fh]blFcabl>F_]`l-F_o6#,$-F]jm6$Fdh^lFjablF[v-Feaal6)F]i^lF
,FdablF_\`lFg\`lF_]`lFj`bl>F[oF][l>Fg]`l,&-F`gn6$/Fh\blF,Fdh^lF,*&Fg\blF,-F`gn6
$FhbblFci^lF,F[v@%-F^hm6$-F`gn6$/Fg\blFaoFg]`lFao>Fj\_l<#Fao>Fj\_l<"F\_al-Fas6$
Fdw,$-F.F^a`lFhnFf^_l>Fhd_l,&Fhd_lF,FicblF,FagalFa^_l-Fas6#QgnFirst~we~study~th
e~system~on~the~U2~chart~(x=z1/z2,y=1/z2):|+F^gvF_g`l-Fas6%F]`al&9'F[i^l&FbdblF
ai^lFf^_l@$FbirC%Fa^_lFc_blFf^_l?(Fd[`lF,F,FicblF1C&>F_\`l-F]jm6$-FU6$Fg]`lFg\b
l/Fg\bl&Fj\_lF_e`l>Fg\`l-F]jm6$,&Fij^lF,*&Fg\blF,Fi[_lF,F[v<$F]eblFhbbl>F_]`l,$
-F]jm6$Fci^lFdeblF[v-Feaal6)FbdblFhnF^eblF_\`lFg\`lF_]`lFj`bl@$/Fhd_lFao-Fas6#Q
KNo~singular~points~at~infinity~are~found.|+F^gvF^gv6#F[oF^gvF(,
I4find_inf_roots_singf*6$F[h^lF]h^l6&F\pF]pF^pF_pF^gvF^gvC?>Fdh^l-Fg`t6$7$-F`gn
6$F___lFih^l-F`gn6$F___lF`i^lFhhpF\_al-Fas6$Fdw,&-F.6#Fcg_lF,-F.6#Fdg_lF,Ff^_l-
Fas6%Q^oThe~differential~system~on~the~U1~chart:|+~~~~z1'~=~%a|+~~~~z2'~=~%a|+F
^gvFih^lF`i^lFa^_l-Fas6#Q^oFirst~we~shall~study~the~system~on~the~U1~chart~(x=1
/z2,~y=z1/z2):|+F^gv-Fas6%F]`alFih^lF`i^l@$Fbir-Fas6#Q9~we~change~z1->x,~z2->y|
+F^gvFf^_l>Fci^lFcg_l>Fij^lFdg_l?(Fi[_lF,F,-F.F[g_lF1-Fejl6&-F`gn6%Fb]alFc]alFj
h^l&Fci^l6#Fi[_lFaoF,>F[oF1?(Fi[_lF,F,-F.6#Fij^lF1-Fejl6&Fghbl&Fij^lFjhblFaoF,>
F[oF][l@$/,&FdhblF,F]iblF,FaoC%F_g`l-Fas6#QKNo~singular~points~found~in~the~U1~
chart.|+F^gvFf^_l@%3-F^hm6$-F`gn6%FifalF___lFf\blFao-F^hm6$-F`gn6%FifalF___lF\]
blFao>Fdh^l7#Fao>Fdh^l7"F\_al-Fas6$Fdw-F.Fi`alFf^_l-Fas6%Q^oThe~differential~sy
stem~on~the~U2~chart:|+~~~~z1'~=~%a|+~~~~z2'~=~%a|+F^gvFf\blF\]blFa^_l-Fas6#Qfn
Now~we~study~the~system~on~the~U2~chart~(x=z1/z2,~y=1/z2):|+F^gv-Fas6%F]`alFf\b
lF\]bl@$FbirF^hblFf^_l?(Fi[_lF,F,FjjblF1-Fejl6&-F`gn6%Fb]alFc]alF\i^l&Fdh^lFjhb
lFaoFhn@$/FjjblFaoC%F_g`l-Fas6#QKNo~singular~points~found~in~the~U2~chart.|+F^g
vFf^_lF^gvF`fblF^gvF(,
I+saddle_inff*6)F[`mF`auFj^lFhfwFdfmFifwFah^l6)F^goF]goF\pFianFjiwF^auF_auF^gvF
^gvC5>Fdh^l*&Fg\blF,,&Fh\blF,FbdblF[vF[v>Fci^l-Fj`w6'-F`gn6$Fa]alFjh^lFYFinF]i^
lFao>Fij^l-Fdbw6'Fci^lFdh^lF,F,Fao>Fi[_l-FdfwF^ibl>Fi[_l-Fien6%Fi[_lFYFin@$3/-F
jdm6%-Fb[x6$-F`gn6$Fij_lF]a_lFYFYF,Fao-Fjdm6%-Fb[x6$-F`gn6$Fhj_lF_a_lFinFinF,>F
i[_lFij^l@%FbirF_g`lFf^_l-Fas6#Fajy-Fas6$Q=The~new~vector~field~is~%a.|+6"Fci^l
-Fas6#F_[z-Fas6$Fj^clFij^l-Fas6$QenMake~a~1000~normalization.|+So~the~new~vecto
r~field~is~%a.|+F^gvFi[_lFf^_l-Fas6#QJWe~calculate~the~invariant~separatrices.|
+F^gv@%-F`fm6$Fh\blFaoC$>Fj\_lF,>Fab_lF[vC$>Fj\_lFao>Fab_lF,>Fi^_l-Fgiw6%Fi[_lF
^]lFj\_l@%/Fj\_lF,C&@$FbirF_g`l-Fas6$Fd]z7$F^duFi^_l-Fas6$Fh]z7$FaoF^duFf^_lC&@
$FbirF_g`l-Fas6$Fh]zFh`cl-Fas6$Fd]zF[aclFf^_l-F[au6,F]i^lFaoFdh^lF,F,FaoFi[_l7#
Fi^_l7#Fab_lF\i^l@$3/F[tF,/F\tF,C$@%Fc`cl@$0Fj`blFao>Fab_lF,@$F]bcl>Fab_lF[v@%/
F\i^lF,-F[au6,F]i^lFao,$Fdh^lF[vF,F[vFaoFi[_l7#-F`gn6$/F^du,$F^duF[vFi^_lFeaclF
_t-F[au6,F]i^lFaoFebclF,F[vFaoFi[_lFfbclFeaclFjgqF^gvF^gvF^gvF(,
I'se_inff*Fb\cl6.FianF^goF]goF\pFi_pFb^rFjexF_auFhezF^au%#hhGFjiwF^gvF^gvC:>Fci
^lFf\cl>Fij^lFi\cl>Fi[_l-Fdbw6'Fij^lFci^lF,F,Fao>Fdh^l-FdfwFjhbl>Fdh^l-Fien6%Fd
h^lFYFinF_g`l-Fas6%QOThe~point~(%a,%a)~is~a~semi~hyperbolic~point.|+F^gvF]i^lFa
o@%FbirF_g`lFf^_l-Fas6#F[hzF^_clF\_cl-Fas6$Fj^clFi[_l-Fas6$Fb_clFdh^lFf^_lFc_cl
@%-F^hm6$FbdblFaoC*@%Fg_cl>F_]`lF,>F_]`lFao>F_\`l-Fgiw6%Fdh^lF^]lF_]`l>Fj\_l-F`
gn6$<$/Fhhp,&FYF,F,F,F___lFih^l>Fj\_l-F\im6$Fj\_lFY>Fj\_l-F]`nFhecl>Fi^_l-F`emF
hecl>Fab_l-F[_z6#-F_o6#-F`gn6$/FYF,Fj\_l@%-Faq6$Fi^_lFcjx@%2FaoFab_l@%/F_]`lFao
>Fhd_l7$F,Fao>Fhd_l7$FhnFao@%F[gcl>Fhd_l7$F_tFao>Fhd_l7$FjgqFao@%Fifcl@%F[gcl>F
hd_l7$Fc\rFao>Fhd_l7$F_huFao@%F[gcl>Fhd_l7$F`huFao>Fhd_l7$F]wFaoC&@%-F`fmFhdcl>
F_]`lF,>F_]`lFao>Fd[`l-FgexF_ecl>F_\`l-F`gn6$/FYF^duFdcal>Fhd_l7$&Fd[`lF^[`lF,F
_g`l@$-F\el6$Fi^al<&F,FhnF_tFjgq-Fas6#Q=The~point~is~a~saddle-node.|+F^gv@$/Fi^
alFc\r-Fas6#Q@The~point~is~an~unstable~node.|+F^gv@$/Fi^alF]w-Fas6#Q>The~point~
is~a~~stable~node.|+F^gv@$-F\el6$Fi^al<$F_huF`hu-Fas6#Q8The~point~is~a~saddle.|
+F^gvFf^_l-F\gu6,F]i^lFaoFci^lF,F,FaoFdh^lFhd_l7#F_\`lF\i^l@$FgaclC%@%/Fj`blFao
>Fhd_l7$-Fhjl6$Fi^al7*F_tFjgqF,FhnFc\rF_huF`huF]wF^`al>Fhd_l7$-Fhjl6$Fi^al7*Fhn
F,FjgqF_tF]wF`huF_huFc\rF^`al>Fg\`l7$-F]jm6#*&)F[vFj`blF,Fcg_lF,-F]jm6#*&F\\dlF
,Fdg_lF,@%Fbbcl-F\gu6,F]i^lFaoFci^lF,F,FaoFg\`lFhd_lFhjclF_t-F\gu6,F]i^lFaoFci^
lF,F,FaoFg\`lFhd_lFhjclFjgqF^gvF^gvF^gvF(,
I,change_stabf*6#F^au6(F_pFd^vF'FcfmFdfmF^goF^gvF^gvC%>Fci^lFgjbl?(Fdh^lF,F,Fdf
_lF1C&>Fi[_lFgjbl>Fj\_l&Fjh^lFi`al?(Fij^lF,F,FicblF1@%0Fij^lF_hu>Fi[_l7$-FhjlFj
hbl-Fhjl6$Fij^lFj\_lC%>Fi^_lFf]dl@%-F\el6$Fi^_l<&F,F_tFijuFagm>Fi^_lFhn@%-F\el6
$Fi^_l<&FhnFjgq"#6"#7>Fi^_lF,@%-F\el6$Fi^_l<$Fc\rF`hu>Fi^_lF_hu>Fi^_lFc\r>Fi[_l
7$Fe]dlFi^_l>Fci^l7$-FhjlF[g_lFi[_lFci^lF^gvF^gvF^gvF(,
I'de_inff*6&F[`mF`auFj^lFah^l6#Fd^vF^gvF^gvC'-Fas6%QMThe~point~(%a,%a)~is~a~non
elementary~point.|+F^gvF]i^lFao-Fas6#Q>Blowing~up~the~vector~field.|+F^gv>Fdh^l
-F`ez6&F[]clF]i^lFaoFbo-Fa^v6&F]i^lFaoFcg_lF\i^l@$FgaclC%-Fas6$Q,Degree=%d.|+F^
gvFbdbl@%/FbdblFao>Fdh^lFdg_l>Fdh^l-Fe\dlFdgbl@%Fbbcl-Fa^v6&F]i^lFaoFdh^lF_t-Fa
^v6&F]i^lFaoFdh^lFjgqF^gvF^gvF^gvF(,
I)type_inff*Fb\cl6&F_imF_dyF`dyFadyF^gvF^gv@%3Fgdcl-F^hmFh_clC&F_g`l-Fas6%Q;(%a
,%a)~is~nonelementary.|+F^gvF]i^lFaoFf^_l-Fa_dl6&Fjh^lF\i^lF]i^lFj`bl@%5FgdclFe
adl-F]ccl6)Fjh^lF\i^lF]i^lFbdblFg\blFh\blFj`bl@%-F`fm6$*&FbdblF,Fh\blF,FaoC(F_g
`l-Fas6%Q6(%a,%a)~is~a~saddle.|+F^gvF]i^lFao@%2-Ffhm6#-F_o6#Fh\bl-Ffhm6#-F_o6#F
bdbl>Fci^l*&FbdblF,Fh\blF[v>Fci^l*&Fh\blF,FbdblF[v@%334F[o-Faq6$FbdblFify-Faq6$
Fh\blFifyC)>Fij^l-F[dmF[g_l>Fi[_l-F`dmF[g_lFf^_l-Fas6%FdgyFi[_lFij^lFa^_lFcddlF
f^_lC+>Fci^l-F66$-F_oF[g_lFhim>Fci^lFgddl>Fij^lF`ddl>Fi[_lFbddlFf^_l-Fas6%F_hyF
i[_lFij^lFa^_lF]edlFf^_lFf^_l-F`\clF_bdlC(>Fdh^l-F[_zF[cdl@%2FaoFdh^lC%F_g`l-Fa
s6%F[bzF]i^lFaoFf^_lC%F_g`l-Fas6%FdazF]i^lFaoFf^_l@%Fibdl>Fci^lFccdl>Fci^lFecdl
@%FgcdlC)>Fij^lF`ddl>Fi[_lFbddlFf^_lFcddlFa^_lFcddlFf^_lC+>Fci^lFgddl>Fci^lFgdd
l>Fij^lF`ddl>Fi[_lFbddlFf^_lF]edlFa^_lF]edlFf^_l-Fbeu6&F]i^lFaoFdh^lF\i^l@$Fgac
lC$@$F]bcl>Fdh^lFebcl@%Fbbcl-FbeuF]adl-FbeuF_adlF^gvF^gvF^gvF(,
I-assoc_pointsf*6#FK6&%#LfG%#LgGFMFh^\lF[_clF[_clC'>8$-Fiip6%-F_o6#&9$6#F,FYFin
>Fhgdl-Fa[n6$f*6#FMF[_cl6$FffmFgfmF[_cl7$,&F]hdlF,F[vF,&F^hdl6#FhnF[_clF[_clF[_
clFhgdl>8%-Fiip6%-F_o6#FhhdlFYFin>F[idl-Fa[n6$f*FdhdlF[_clFehdlF[_cl7$F]hdl,&Fh
hdlF,F[vF,F[_clF[_clF[_clF[idl-F66$<$-Fhjl6#Fhgdl-Fhjl6#F[idlFcqF[_clF[_clF[_cl
F(,
I/newton_diagramf*Fbgdl6-%'pointsG%#pkG%#pjG%#pLGF'F_pF_im%%hsetG%"NGFh^\lFgfnF
[_clF[_clC'>8+-F`gdl6#F^hdl>FhgdlFhjdl>8,-F.Fjidl?(8(F,F,,&F][elF,F[vF,F1C$>F[i
dl&Fhgdl6#F`[el@$-F\el6$F[idlFhjdl?(8),&F`[elF,F,F,F,F][elF1C$>8&&Fhgdl6#Fj[el@
$-F\el6$F^\elFhjdl@%31&F[idlF_hdl&F^\elF_hdl1&F[idlFihdl&F^\elFihdl>Fhjdl-%'rem
oveG6$f*6#FgfnF[_clFehdlF[_cl/F^hdlT#F[_clF[_cl6$FbjdlF^\elFhjdl?(8*F,F,F][elF1
C$>8'&Fhgdl6#Ff]el@$33-F\el6$Fi]elFhjdl0Ff]elF`[el0Ff]elFj[el@%531Fg\el&Fi]elF_
hdl1Fj\el&Fi]elFihdl31Fh\elFg^el1F[]elFi^el>Fhjdl-F^]el6$f*Fa]elF[_clFehdlF[_cl
Fb]elF[_clF[_cl6$FcjdlFi]elFhjdl@$532Fg\elFg^el2Fg^elFh\el32Fh\elFg^el2Fg^elFg
\elC$>8-*&,&F[]elF,Fj\elF[vF,,&Fh\elF,Fg\elF[vF[v@$1,&*&F\`elF,,&Fg^elF,Fh\elF[
vF,F,F[]elF,Fi^el>Fhjdl-F^]el6$f*Fa]elF[_clFehdlF[_clFb]elF[_clF[_clFa_elFhjdlF
hjdlF[_clF[_clF[_clF(,
I(GAMMA_1f*6#Fcjn6)F_imFgfnFhfnF%F'%#skG%"GGF[_clF[_clC(>Fhgdl-F.Fjjdl>F[idlF]h
dl>F^\elFhhdl@$1Fh\elFg\elC$>F[idlFhhdl>F^\elF]hdl@%/FhgdlFhn>Ff]el7$F[idlF^\el
C&>Fi]el&F^hdl6#F_t@%Fi_elC%>Fi]elF^\el>F^\elF[idl>F[idlF_bel@$Ff_elC$>Fi]elF^
\el>F^\elF_bel?(F`[elFjgqF,FhgdlF1C$>Fj[el&F^hdlFe[el@%2&Fj[elF_hdlFg\elC%>Fi]e
lF^\el>F^\elF[idl>F[idlFj[el@%2F`celFh\elC$>Fi]elF^\el>F^\elFj[el@$2F`celFg^el>
Fi]elFj[el@%2FaoFh\el>Ff]elF\bel>Ff]el7$F^\elFi]elFf]elF[_clF[_clF[_clF(,
I-quasi_degreef*F[ael6&Fian%&alphaG%%betaGFadnF[_clF[_clC'>Fhgdl,$*&,&-Fhjl6$Fh
nFhhdlF,-Fhjl6$FhnF]hdlF[vF,,&-Fhjl6$F,FhhdlF,-Fhjl6$F,F]hdlF[vF[vF[v>F[idl-F[d
mFjidl>F^\el-F`dmFjidl>Fi]el,&*&F[idlF,FceelF,F,*&F^\elF,F^eelF,F,7%F[idlF^\elF
i]elF[_clF[_clF[_clF(,
I-center_type1f*6&F[`mFYF_imFbb[l6&FcjnF\pFb^rFdfmF[_clF[_clC'>F[idl-F]`n6$F^hd
l9%>F^\el-Fhjm6$Fao-F`em6$F[idlFffel>Fi]el-F[_z6#-F_o6#-F`gn6$/FffelF,F[idl@%-F
aq6$F^\elFcjx>Fhgdl7%Fi]elF,-F[_z6#-F_o6#9&>Fhgdl7%Fi]elF[vFigel@%/9'F,C*@$/Fhg
dl7%F[vF,F,OFagm@$/Fhgdl7%F,F,F,OFiju@$/Fhgdl7%F,F[vF,OF_t@$/Fhgdl7%F[vF[vF,OF,
@$/Fhgdl7%F[vF,F[vOFd^dl@$/Fhgdl7%F,F,F[vOFc^dl@$/Fhgdl7%F,F[vF[vOFhnOFjgqC*@$F
ehelOFiju@$FihelOFagm@$F]ielOF_t@$FaielOF,@$FeielOFc^dl@$FiielOFd^dl@$F]jelOFhn
OFjgqF[_clF[_clF[_clF(,
I-center_type2f*F`felFafelF[_clF[_clC'>F[idlFdfel>F^\elFhfel>Fi]elF]gel@%Fegel>
FhgdlFhgel>FhgdlF_hel@%FahelC*@$FehelOFiju@$FihelOFagm@$F]ielOF_t@$FaielOF,@$Fe
ielOFc^dl@$FiielOFd^dl@$F]jelOFhnOFjgqC*@$FehelOFagm@$FihelOFiju@$F]ielOF_t@$Fa
ielOF,@$FeielOFd^dl@$FiielOFc^dl@$F]jelOFhnOFjgqF[_clF[_clF[_clF(,
I&powerf*6$FcfmFdfmF[_clF[_clF[_cl@%/FffelFaoF,)F^hdlFffelF[_clF[_clF[_clF(,
I-sort_set_posf*6%FcjnFa_lF%6%FcfmF'F_imF[_clF[_clC'>Fhgdl7#-Ffdm6#;F,,&FaaelF,
F,F,>F[idlF,?(F^\elF,F,FaaelF1C%@$3-F`fm6$Fffel-Fhjl6$F,&F^hdl6#F^\el/F[idlF^\e
lC$>&FhgdlF\jdl7$FffelF]hel>F[idl,&F[idlF,F,F,>Fj_flFe_fl>F[idlF]`fl@$Fg_fl>Fj_
flF[`flFhgdlF[_clF[_clF[_clF(,
I-sort_set_negf*Fc^flFd^flF[_clF[_clC'>FhgdlFg^fl>F[idlF,?(F^\elF,F,FaaelF1C%@$
3-FdgmFb_flFg_flC$>Fj_flF[`fl>F[idlF]`fl>Fj_flFe_fl>F[idlF]`fl@$Fg_fl>Fj_flF[`f
lFhgdlF[_clF[_clF[_clF(,
I0put_separatricef*6)%%xposGF_au%0transformationsGFbfrFjiu%*vec_fieldGF^au6#%)n
ewentryGF[_clF[_clC$>Fhgdl7)F]helFbhel9(9)9*FffelF[o@%/F^hdlF,C$>%(NumXPosG,&Fe
bflF,F,F,>%(ManXPosG7$-Fhjl6#FhbflFhgdlC$>%(NumXNegG,&F^cflF,F,F,>%(ManXNegG7$-
Fhjl6#FacflFhgdlF[_cl6&FebflF^cflFhbflFacflF[_clF(,
I2append_trajectorsf*F[_cl6%%%man1G%%man2GF_pF[_clF[_clC,-%&printG6$Q+ManYNeg~=
~F[_cl%(ManYNegG-F]dfl6$Q+ManYPos~=~F[_cl%(ManYPosG-F]dfl6$Q+ManXNeg~=~F[_clFac
fl-F]dfl6$Q+ManXPos~=~F[_clFhbfl>Fhgdl7"@$0%(NumberYGFaoC$>F[idl-%4make_transfo
rmationG6#F`dfl>Fhgdl7$Fiidl7$-FhjlFdeflF[idl?(F^\elF,F,FebflF1C$>F[idl-Fcefl6#
&FhbflFf_fl>Fhgdl7$Fiidl7$-FhjlF]fflF[idl@$F^eflC$>F[idl-Fcefl6#Fddfl>Fhgdl7$Fi
idl7$-FhjlFgfflF[idl?(F^\elF,F,F^cflF1C$>F[idl-Fcefl6#&FacflFf_fl>Fhgdl7$Fiidl7
$-FhjlF`gflF[idlFhgdlF[_clF[_clF[_clF(,
I1split_trajectorsf*6#F^au6'%(sep_posG%(sep_negGF_pFcjnF\pF[_clF[_clC&>FhgdlF\e
fl>F[idlF\efl?(F^\elF,F,FaaelF1C$>Fi]el-Fhjl6$F]wFe_fl@$0Fi^elFaoC$>F`[el-F[_z6
#-F_o6#-F`gn6$/F^duF,-F]`n6$-FU6$Fi^elF^duF^du@%2FaoF`[el>Fhgdl7$FiidlFe_fl>F[i
dl7$F[jdlFe_fl7$FhgdlF[idlF[_clF[_clF[_clF(,
I4make_transformationf*Fhgfl6,F_im%%histGFbfrFjiuFcjnFj^lFa_l%#x1G%#y1GFcfmF[_c
lF[_clC+>F[idlF]hdl>F^\elFhhdl>Fi]elF_bel>F`[el&F^hdl6#Fc\r>Fj[el,(Fh\elF,*&Fg^
elF,F^duF,F,*&Fi^elF,F`[elF,F,>Ff]el,(F[]elF,*&&Fi]elF`belF,F^duF,F,*&&Fi]el6#F
jgqF,F`[elF,F,>Fhgdl-F.F\jdl?(F[_clF,F,F[_cl2FaoFhgdlC(>F\`el&F[idlFjidl>Fhjdl,
&&F\`elF_hdlF,*(&F\`elF`belF,-F[^fl6$Fj[el&F\`elFfjflF,-F[^fl6$Ff]el&F\`el6#F_h
uF,F,>F][el,&&F\`elFihdlF,*(&F\`elFa[glF,-F[^fl6$Fj[el&F\`el6#F`huF,-F[^fl6$Ff]
el&F\`el6#F]wF,F,>Fj[el-F\im6$FhjdlF^du>Ff]el-F\im6$F][elF^du@%3/Fj[elFao/Ff]el
Fao>FhgdlFao>Fhgdl,&FhgdlF,F[vF,7$Fj[elFf]elF[_clF[_clF[_clF(,
I1write_trajectorsf*6%F^auFj^lFa_l6/F_im%#w1GFi_pFj_pF_p%#elG%$hypG%#w2G%$dl1G%
$dl2G%$dl3G%$dl4G%$dl5GF[_clF[_clC9>FhgdlFaael>Fj[elFao>Ff]elFao>F][elFjg\l>F\`
elQ"~F[_cl>8.Fjg\l>8/Fjg\l>80Fjg\l@$0FhgdlFaoC1-F\r6$FdelF^r-Fas6#QI|+|+The~inv
ariant~separatrices~are:~(t>0)|+F[_cl-F\r6#F^r>F[idl<*F,F_tFc\rF`huFijuFagm"#8"
#9>Fhjdl<*FhnFjgqF_huF]wFc^dlFd^dlFhbm"#;>F^\el-Fhjl6$F_huF]hdl-Fas6#-F[hr6$Q&~
[%d]F[_clF^\el@%-F\el6$F^\elF[idlC(F]`gl-Fas6$Q5[01]:~%a~:~unstable|+F[_cl-Fhjl
6$F]wF]hdlFb`gl>F][el-FC6$F][elQ)~~~|gr~~~~F[_cl>F\`el-FC6$F\`elQ&~~^~~F[_cl>Fe
_gl-FC6$Fe_glF_bglC(F]`gl-Fas6$Q3[01]:~%a~:~stable|+F[_clFjaglFb`gl>F][elF]bgl>
F\`el-FC6$F\`elQ&~~v~~F[_cl>Fe_glFebgl@%-F\el6$F^\el<)FhnF_tFc\rF_huFagmFd^dlFf
`gl>Fg_gl-FC6$Fg_glQ%-<-*F[_cl@%-F\el6$F^\el<)F,FjgqF`huF]wFijuFc^dlFhbm>Fg_gl-
FC6$Fg_glQ%->-*F[_cl>Fg_gl-FC6$Fg_glQ%****F[_cl@%-F\el6$F^\el<)F,FjgqF`huF]wFag
mFd^dlFj`gl>Fg_gl-FC6$Fg_glQ%-<-~F[_cl@%-F\el6$F^\el<)FhnF_tFc\rF_huFijuFc^dlFg
`gl>Fg_gl-FC6$Fg_glQ%->-~F[_cl>Fg_gl-FC6$Fg_glQ%***~F[_cl>Fi_gl-FC6$Fi_gl-F[hr6
$Q+~~%02d~~~~F[_clF,?(F`[elFhnF,FhgdlF1C*>Fi]el-Fhjl6$F_huF]cel@%53-F\el6$F^\el
<%F,F`huFagm-F\el6$Fi]el<%FhnF_huFd^dl3-F\el6$F^\el<%FhnF_huFc^dl-F\el6$Fi]el<%
F,F`huFijuC'F]`gl-Fas6#Q3hyperbolic~sector|+F[_clFb`gl>Ff]el,&Ff]elF,F,F,>F\`el
-FC6$F\`elQ$HYPF[_cl@%53-F\el6$F^\el<&F_tFc\rFijuFg`gl-F\el6$Fi]el<&FjgqF]wFc^d
lFhbm3-F\el6$F^\el<&FjgqF]wFd^dlFj`gl-F\el6$Fi]el<&F_tFc\rFagmFf`glC'F]`gl-Fas6
#Q1elliptic~sector|+F[_clFb`gl>Fj[el,&Fj[elF,F,F,>F\`el-FC6$F\`elQ$ELLF[_clC&F]
`gl-Fas6#Q2parabolic~sector|+F[_clFb`gl>F\`el-FC6$F\`elQ$PARF[_cl>F^\elFi]elF^a
gl@%FdaglC(F]`gl-Fas6%Q7[%02d]:~%a~:~unstable|+F[_clF`[el-Fhjl6$F]wF]celFb`gl>F
][elF]bgl>F\`elFabgl>Fe_glFebglC(F]`gl-Fas6%Q5[%02d]:~%a~:~stable|+F[_clF`[elFf
jglFb`gl>F][elF]bgl>F\`elF]cgl>Fe_glFebgl@%Fbcgl>Fg_glFfcgl@%Fjcgl>Fg_glF^dgl>F
g_glFbdgl@%Ffdgl>Fg_glFjdgl@%F^egl>Fg_glFbegl>Fg_glFfegl>Fi_gl-FC6$Fi_gl-F[hr6$
F^fglF`[el>F^\el-Fhjl6$F_hu&F^hdlFjidl>Fi]elF\agl@%FefglC'F]`glFegglFb`gl>Ff]el
Figgl>F\`elF[hgl@%53-F\el6$F^\el<%F_tFc\rFiju-F\el6$Fi]el<%FjgqF]wFc^dl3-F\el6$
F^\el<%FjgqF]wFd^dl-F\el6$Fi]el<%F_tFc\rFagmC'F]`glF_iglFb`gl>Fj[elFcigl>F\`elF
eiglC&F]`glFiiglFb`gl>F\`elF]jglF]`gl-Fas6&QFThe~singularity~(%a,%a)~has~index~
%a|+F[_clFffelF]hel,(F,F,Fj[el#F,FhnFf]el#F[vFhn-Fas6#QKSector~representation~(
counterclockwise):|+F[_cl-Fas6#F][el-Fas6#F^y-Fas6#F\`elFj^hl-Fas6#Fe_glFj^hl-F
as6#Fg_glFj^hl-Fas6#Fi_gl-Fas6#Q#|+|+F[_clFb`glF[_clF[_clF[_clF(,
I1manifold_blow_upf*6$FjfoFeem6*F]dyF^dyF\pF[`mFcfm%$dfxGF'FianF[_clF[_clC*>F^
\el-Fien6%F^hdlFYFin>Fhgdl-Fjdm6%-Fjdm6%Fh\elFYF,FinFao>F[idl-Fjdm6%-Fjdm6%F[]e
lFinF,FYFao>Fi]el-Fc\n6$*&&F`[elF[^elF,)FYFf]elF,/Ff]el;FhnFffel>Fj[el-Fc\n6$*(
Ff]elF,F^ahlF,)FY,&Ff]elF,F[vF,F,F`ahl>Fhjdl-Fheo6#,&-F`gn6$/FinFi]el,&F[]elF,*
&F[idlF,FinF,F[vF,*&Fj[elF,-F`gn6$F^bhl,&Fh\elF,*&FhgdlF,FYF,F[vF,F[v?(Ff]elFhn
F,FffelF1C$>Fhjdl-F]jm6$Fhjdl/F^ahl*&-Fjdm6%FhjdlFYFf]elF,,&*&FhgdlF,Ff]elF,F,F
[idlF[vF[v>Fi]el-F]jm6$Fi]elF[chlO-F`gn6$/FYF^duFi]elF[_clF[_clF[_clF(,
I2manifold2_blow_upf*6$F\pFeem6+FhfwFifwF[`mF[`hlF'F`pFianFcfmFajwF[_clF[_clC+>
Fhgdl-Fjdm6%-Fjdm6%F]hdlFYF,FinFao>F[idl-Fjdm6%-Fjdm6%FhhdlFinF,FYFao>F^\el-Fc
\n6$*&&FhjdlFe[elF,)FYF`[elF,/F`[elFaahl>Fi]el-Fc\n6$*(F`[elF,F[ehlF,)FY,&F`[el
F,F[vF,F,F]ehl>Ff]el,&-F`gn6$/FinF^\el,&FhhdlF,F`bhlF[vF,*&Fi]elF,-F`gn6$Fhehl,
&F]hdlF,FebhlF[vF,F[v>F`[elFhn>F][elFffel?(F[_clF,F,F[_cl2F`[el,&FffelF,F,F,@%-
Fghm6$,&*&F`[elF,FhgdlF,F,F[idlF[vFaoC%>Ff]el-F]jm6$Ff]el/F[ehl*&-Fjdm6%Ff]elFY
F`[elF,FffhlF[v>F^\el-F]jm6$F^\elF\ghl>F`[elF[\elC$>F][elFcehl>F`[elFbfhl-Fc\n6
$*&-Fjdm6%F^\elFYFj[elF,)F^duFj[elF,/Fj[el;FhnF][elF[_clF[_clF[_clF(,
I8center_manifold_blow_upf*Fjchl61F\jwF]jwF^jwF_jwF'FifwF^auF[gnF`jwF[`pFajwF[h
tFdfmFb^rFjexF[_clF[_clC)@%F[oC$>FhgdlF[hdl>F[idlF^idlC$>FhgdlF]hdl>F[idlFhhdl>
Fj[el-Fjdm6%-Fb[x6$-F`gn6$/FYFaoFhhdlFinFinF,>Ff]elFao>Fe_glFffel?(F`[elFhnF,Fe
_glF1C+>F][el,$*&-Fjdm6%-Fb[x6$-F`gn6$/FinFaoF[idlFYFYF`[elF,Fj[elF[vF[v@$34F[o
F^[n>F][el-Fc[nFi^hl>F^\el-Fheo6#-F`gn6$/Fin,&FhjdlF,*&F][elF,F\ehlF,F,Fhgdl>Fi
]el-Fheo6#,&-F`gn6$FjjhlF[idlF,**F][elF,F`[elF,FbehlF,F^\elF,F[v>Fhgdl-F`gn6$/F
hjdlFinF^\el>F[idl-F`gn6$Fg[ilFi]el>Ff]el,&Ff]elF,F\[ilF,>Fg_gl-F\im6$-F`gn6$F_
jhlFhgdlFY@$/Fg_glFao>Fe_gl,&Fe_glF,F,F,>Fg_glF^\il7%Ff]elFg_gl-F]`n6$Fg_glFYF[
_clF[_clF[_clF(,
I+blowing_upf*6&FKFj^lFa_l%-finite_pointG6)F%F]jw%$n_dGF]cm%)q_degreeGF`imFd^vF
[_clF[_clCV@$FbirF]`gl-Fas6&QAblowing~up~%a~in~point~(%a,%a).|+F[_clF^hdlFffelF
]helFb`gl@%50FffelFao0F]helFaoC'>F[idl-Fien6%-Fj`w6'F^hdlFYFinFffelF]helFYFin@$
FbirF]`gl-Fas6%Q?moving~(%a,%a)~to~the~origin.|+F[_clFffelF]hel-Fas6$Q6new~vect
or~field:~%a|+F[_clF[idlFb`gl>F[idlF^`hl>F^\el-F]jdlF\jdl>Fi]el-Fi`elFf_fl>F`[e
l-Fbdel6#Fi]el@$FbirF]`gl-Fas6$Q4Newton~diagram:~%a|+F[_clF^\el-Fas6$Q)g1~=~%a|
+F[_clFi]el-Fas6$Q:[alpha,beta,degree]~=~%a|+F[_clF`[elFj^hl-Fas6#QK1.~Blowing~
up~in~the~positive~x-direction|+F[_cl-Fas6#QK----------------------------------
-------|+F[_clFj^hl-Fas6#Q4blowing~up~level~1|+F[_cl-Fas6#Q4------------------|
+F[_cl-Fas6$Q>blowing~up~%a~in~point~(0,0)|+F[_clF[idlFb`gl>Fj[el-%)blow_upxG6'
F[idlF`[elF,FYFin@$FbirF]`gl-Fas6$Q;blowing~up~vectorfield~%a|+F[_clF`celFb`gl-
%,sing_eigenvG6'Fj[elF,F,7#7+FffelF]helF,F,&F`[elF_hdlFao&F`[elFihdlF,&F`[elF`b
elF,@$FbirF]`gl-Fas6#Qen-------------------------------------------------------
--|+F[_clFj^hl-Fas6#QK2.~Blowing~up~in~the~negative~x-direction|+F[_clF\`ilFj^h
lFj^hlF_`ilFb`ilFe`ilFb`gl>Fj[el-Fj`il6'F[idlF`[elF[vFYFin@$FbirF]`glF]ailFb`gl
-Faail6'Fj[elF[vF,7#7+FffelF]helF[vF,FeailFaoFfailF,FgailF[v@$32F[v-Fhjl6$F,Fg^
el0&Fj[elF`belFaoC.@$FbirF]`gl-Fas6#QK3.~Blowing~up~in~the~positive~y-direction
|+F[_clF\`ilFb`gl>Fddfl-%)blow_upyG6&F[idlF`[elF,7#7+FffelF]helF,F,F,FeailFaoFf
ailFgail>F_eflF,@$FbirF]`glFj^hl-Fas6#QK4.~Blowing~up~in~the~negative~y-directi
on|+F[_clF\`ilFb`gl>F`dfl-Fecil6&F[idlF`[elF[v7#7+FffelF]helF,F[vF,FeailFaoFfai
lFgail>Ff]el-FfcflF[_cl-F`^gl6%Ff]elFffelF]hel@$4Fbhel>Ff]el-FfgflF[^el>FebflFa
o>F^cflFao>F_eflFao>FhbflF\efl>FacflF\efl>FddflF\efl>F`dflF\eflFf]elF[_cl6)Fhbf
lFacflFddflF`dflFebflF^cflF_eflF[_clF(,
I)blow_upxf*6'FKFhfnFbb[lFYFin6/FedelFfdelFadn%#vxG%#vyG%#pgG%#qgG%#tgGF[`mF\pF
%FcjnFf][lF[_clF[_clC/>Fhgdl&FffelF_hdl>F[idl&FffelFihdl>F^\el&FffelF`bel>Fi]el
Fao>F`[elFao>Fj[elFao>Ff]elFao>FhjdlFao>F][el-F_]n6%F]hdlFbhelF^bfl?(F[_clF,F,F
[_cl0F][elFaoC*>F\`el-Ffan6%F][elFbhelF^bfl>Fe_gl,&-Fhjm6$Fao-F`em6$F\`elFbhelF
,F[vF,>Fg_gl-Fhjm6$Fao-F`em6$F\`elF^bfl>Fi_gl,&*&FhgdlF,Fe_glF,F,*&F[idlF,Fg_gl
F,F,>Fi]el,&Fi]elF,*(F]helF,-F`gn6$/FbhelF]helF\`elF,)Fbhel,(Fi_glF,F,F,F^\elF[
vF,F,>F`[el,&F`[elF,*,F]helF,)Fbhel,&Fi_glF,F^\elF[vF,F[idlF,F^bflF,FchilF,F[v@
$/Fi_glF^\elC$>Fj[el,&Fj[elF,*&F]helF,FchilF,F,>Fhjdl,&FhjdlF,**F]helF,F[idlF,F
^bflF,FchilF,F[v>F][el-F_]n6%,&F][elF,F\`elF[vFbhelF^bfl>F][el-F_]n6%FhhdlFbhel
F^bfl?(F[_clF,F,F[_clF\gilC)>F\`elF_gil>Fe_glFcgil>Fg_gl,&FhgilF,F[vF,>Fi_glF]h
il>F`[el,&F`[elF,*(FhgdlF,F[iilF,FchilF,F,@$F^iilC$>Ff]el,&Ff]elF,FchilF,>Fhjdl
,&FhjdlF,*&FhgdlF,FchilF,F,>F][elFgiil7%7$Fi]elF`[elF_^glFhjdlF[_clF[_clF[_clF(,
I)blow_upyf*6&FhaflF`]il%*directionGFgafl6*F`imF]jwF]dyF^dy%$vecGF\p%$manGF^auF
[_clF[_clC->F[idl-Fdbw6'F^hdlFaoF,F,Fao>Fhgdl-Fj`il6'F[idl7%F`filF^filFbfilF]he
lFYFin>F[idl-Fdbw6'&FhgdlF_hdlFaoF,F,Fao@$FbirF]`gl-Fas6$Q<blowing~up~vector~fi
eld~%a|+F[_clF[idl>F^\el-F`gn6$F_jhl-Fhjl6$F,&FhgdlFihdl>Fi]el-F`gn6$F_jhl-FU6$
&FhgdlF`belFin-Fas6%QT(0,0)~is~a~singular~point~with~eigenvalues~%a,~%a.|+F[_cl
Fi]elF^\elFb`gl@%55-F^hm6$F^\elFao-F^hm6$Fi]elFao-Figm6$Fao*&F^\elF,Fi]elF,C)>F
`[el*&-F`gn6%FaihlF_jhl-FU6$-Fhjl6$FhnFc\jlFYF,,&F^\elF,Fi]elF[vF[v>Fj[el-Fdbw6
'Fc\jlF,FaoF`[elF,@$FbirF]`gl-Fas6#Q[oTransform~this~vector~field~so~that~the~l
inear~part~is~diagonal|+F[_cl-Fas6$Fj^cl-Fdbw6'Fj[elFaoF,F,FaoFb`gl@%-FdgmF[^jl
C'>Fhjdl-Fg_hl6$Fj[elF^]l@$FbirF]`gl-Fas6$Q:unstable~separatrice~x=%aF[_cl-F`gn
6$/F^duFinFhjdlFb`gl@%-FghmF]^jl>Ff]el7)Fbhel7$FaoFao7&F`[elF,F,FaoFj[elFhjdlF,
F[o>Ff]el7)FbhelFg`jlFh`jlFj[elFhjdl-Fa[fl6&-F`gn6$F_jhlFg\elFYF^\elF]helF[o@%-
Fdgm6$FaoF^\elC'>FhjdlFj_jl@$FbirF]`gl-Fas6$Q9stable~separatrice~x=%a|+F[_clF``
jlFb`gl@%Fd`jl>Ff]el7)FbhelFg`jlFh`jlFj[elFhjdlFhnF[o>Ff]elFj`jlC(>Fhjdl-F_hhlF
[`jl@$FbirF]`gl-Fas6$Q6center~manifold~x=%a|+F[_cl-F`gn6$/FYFin&FhjdlF_hdl-Fas6
$Q:on~center~manifold~y'=%a|+F[_cl-F`gn6$Febjl&FhjdlFihdlFb`gl@%-FdgmF]^jl@%2Fa
o-F`gn6$/FYF,&Fhjdl6#F[v>Ff]el7)FbhelFg`jlFh`jlFj[el-F`gn6$FgchlFfbjlFc\rF[o>Ff
]el7)FbhelFg`jlFh`jlFj[elFhcjlF_huF[o@%F`cjl>Ff]el7)FbhelFg`jlFh`jlFj[elFhcjlF`
huF[o>Ff]el7)FbhelFg`jlFh`jlFj[elFhcjlF]wF[o@%Fg_jl@%-Fghm6$F^\elFi]elC&>F`[elF
c^jl>Fj[elF\_jl>Fhjdl-FhchlF[`jl>Ff]el7)FbhelFg`jlFh`jlFj[elFhjdlF_tF[o>Ff]el7)
FbhelFg`jl7&FaoF,F,FaoFc\jlFaoF_tF[o@%FcdjlC&>F`[elFc^jl>Fj[elF\_jl>FhjdlFidjl>
Ff]el7)FbhelFg`jlFh`jlFj[elFhjdlFjgqF[o>Ff]el7)FbhelFg`jlF^ejlFc\jlFaoFjgqF[oOF
f]elF[_clF[_clF[_clF(,
I,sing_eigenvf*6'F`imFbb[l%$lvlGFgaflFfafl6.F%FcjnF_imFhfwFifwFianFbfrFf[jlF]go
FjiuF\pF^auF[_clF[_clC$@%0F_belFaoC'>Fj[el-F_]s6$F_belFin>F[idlF\efl?(F^\elF,F,
-F.6#F`celF1@%/F^bflF,>F[idl-Fa^fl6%F[idl-Fhjl6$F^\elF`celFbo>F[idl-Fb`flF]gjl?
(F^\elF,F,-F.6#&Fj[elFihdlF1@%Fjfjl>F[idl-Fa^fl6%F[idl-Fhjl6$F^\elFegjlF1>F[idl
-Fb`flFigjl?(F^\elF,F,Fc[glF1C(>Ff]el-Fhjl6$F,&F[idlFf_fl>Fi]el-F]jm6$Faeel/Fin
Ff]el>F`[el-F]jm6$-FUFdfjlFghjl@$-Fhjl6$FhnFchjlC$>Fi]el-F_oF^_il>F`[el-F_oFe[e
l@$FbirF]`gl@%3F\^jl-F^hm6$F`[elFaoC%-Fas6$QB(0,%a)~is~a~non-elementary~point|+
F[_clFf]elFb`gl-%,blowing_up2G6(F]hdlFf]el,&F]helF,F,F,FbhelF^bflFbo@%55F\^jlFg
ijl-Figm6$Fao*&Fi]elF,F`[elF,C0>Fhjdl-FU6$F^eelFY>Fhjdl-F`gn6%FaihlFghjl*&Fhjdl
F,,&Fi]elF,F`[elF[vF[v@$F]ijl>Fhjdl-F_o6#Fhjdl>F][el-Fj`w6'F]hdlFYFinFaoFf]el@$
F]ijl>F][el-F_oFi^hl>F\`el7&F,FaoFhjdlF,>Fe_gl-Fdbw6'F][elF,FaoFhjdlF,@$F]ijl>F
e_gl-F_oF__hl-Fas6&QS(0,%a)~is~a~singular~point~with~eigenvalues~%a,%a|+F[_clFf
]elFi]elF`[el-Fas6#QAmoving~this~point~to~the~origin|+F[_cl-Fas6$Q<the~new~vect
or~field~is~%a|+F[_clF][el-Fas6#Q[otransform~this~vector~field~so~that~the~line
ar~part~is~diagonal|+F[_cl-Fas6$Fj\[mFe_gl@%F^cjlC%>Fg_gl-Fg_hl6$Fe_glF^]l-Fas6
$Q;unstable~separatrice~y=%a|+F[_cl-F`gn6$/F^duFYFg_gl@%-FghmFhijl-Fcafl6)F^bfl
F,Fbhel7$FaoFf]elF\`elFe_glFg_gl-Fcafl6)F^bfl-F^fel6&-F`gn6$Faihl&Fe_glFihdlFin
Fi]elFffelFbhelF_^[mF\`elFe_glFg_gl@%-Fdgm6$FaoFi]elC%>Fg_glFc][m-Fas6$Q9stable
~separatrice~y=%a|+F[_clFh][m@%F\^[m-Fcafl6)F^bflFhnFbhelF_^[mF\`elFe_glFg_glF`
^[mC&>Fg_gl-F_hhlFd][m-Fas6$Q6center~manifold~y=%a|+F[_cl&Fg_glF_hdl-Fas6$Q=on~
center~manifold~is~x'=%a|+F[_cl&Fg_glFihdl@%-FdgmFhijl@%2Fao-F[_z6#-F_o6#-F`gn6
$Fccjl&Fg_glF`bel-Fcafl6)F^bflFc\rFbhelF_^[mF\`elFe_gl-F`gn6$FgchlFh_[m-Fcafl6)
F^bflF_huFbhelF_^[mF\`elFe_glFj`[m@%F``[m-Fcafl6)F^bflF`huFbhelF_^[mF\`elFe_glF
j`[m-Fcafl6)F^bflF]wFbhelF_^[mF\`elFe_glFj`[m@%F^cjlC$-Fas6&QS(0,%a)~is~an~unst
able~node~with~eigenvalues~%a,%a|+F[_clFf]elFi]elF`[el@%-Fghm6$Fi]elF`[elC+>Fhj
dl*&FijjlF,F_[[mF[v>Fhjdl-F`gn6%FaihlFghjlFhjdl@$F]ijl>FhjdlFb[[m>F][elFe[[m@$F
]ijl>F][elFi[[m>F\`elF[\[m>Fe_glF]\[m>Fg_gl-FhchlFd][m-Fcafl6)F^bflF_tFbhelF_^[
mF\`elFe_glFg_gl-Fcafl6)F^bflF_tFbhelF_^[m7&F,FaoFaoF,Fe[[mFaoC$-Fas6&QP(0,%a)~
is~a~stable~node~with~eigenvalues~%a,%a|+F[_clFf]elFi]elF`[el@%Fia[mC+>FhjdlF]b
[m>FhjdlF_b[m@$F]ijl>FhjdlFb[[m>F][elFe[[m@$F]ijl>F][elFi[[m>F\`elF[\[m>Fe_glF]
\[m>Fg_glFib[m-Fcafl6)F^bflFjgqFbhelF_^[mF\`elFe_glFg_gl-Fcafl6)F^bflFjgqFbhelF
_^[mF^c[mFe[[mFaoC-@$FbirF]`gl-Fas6#QUx=0~is~a~line~of~singularities~-~point~is
~star-like|+F[_cl>Fj[el-F_]s6$FaeelFin>F[idlF\efl?(F^\elF,F,FgfjlF1@%Fjfjl>F[id
lF\gjl>F[idlFagjl?(F^\elF,F,FcgjlF1@%Fjfjl>F[idlFhgjl>F[idlF]hjl-Fas6#QZthe~non
-elementary~singular~points~(contact~points)~are:|+F[_cl?(F^\elF,F,FgfjlF1-Fas6
$Q((0,%a)|+F[_clF^gjl?(F^\elF,F,FcgjlF1-Fas6$Fje[mFjgjlFb`gl?(F^\elF,F,Fc[glF1-
F^jjl6(F]hdlFahjlF`jjlFbhelF^bflF1Fb`glF[_clF[_clF[_clF(,
I-blowing_upy2f*6(FKF`]ilFbb[lFgaflFfaflF`h^l6&F]jwF`im%#sxG%#syGF[_clF[_clC*>F
hgdlFj[jl>F[idl-Fj`il6'FhgdlF_\jlF]helFYFin>Fhgdl-Fdbw6'Fg\elFaoF,F,Fao@$FbirF]
`gl@%/F]helF,-Fas6#QHblowing~up~in~the~positive~y-direction|+F[_cl-Fas6#QHblowi
ng~up~in~the~negative~y-direction|+F[_cl-Fas6$QAblowing~up~the~vector~field~%a.
|+F[_clFhgdlFb`gl@%/F_bflFboC%>F^\el-F[_z6#-F_o6#-F`gn6$Fccjl-F]`n6$-F`gn6$F_jh
lFc\jlFY>Fi]el-F[_z6#-F_o6#-F`gn6$/FinF,-F]`n6$-F`gn6$FaihlF]]jlFin@$/F^\elFi]e
l@%2FaoF^\el-Fcafl6)F^bflF_tFbhelFg`jlF^c[mFhgdlF^du-Fcafl6)F^bflFjgqFbhelFg`jl
F^c[mFhgdlF^duC%@$/Feh[mFaoYQ^pcase~not~treated:~star-like~points~should~become
~non~star-like~after~second~blowup.F[_cl>F^\elF_h[m@%2Fao*&F]helF,F^bflF,-Fcafl
6)F^bfl,&Fg`glF,F^\elF[vFbhelFg`jlF^c[mFhgdlF^du-Fcafl6)F^bfl,&FhbmF,F^\elF[vFb
helFg`jlF^c[mFhgdlF^duF[_clF[_clF[_clF(,
I,blowing_up2f*6(FKFbfrF\fjlFgaflFfaflF`h^l6(F]jwF_]ilF]cmF`]il%$trfGF`imF[_clF
[_clC:@$Fbir-F\r6$F^rFdel-Fas6$Q5Blowing~up~level~%d|+F[_clF]helFb`il-Fas6%Q?bl
owing~up~%a~in~point~(0,%a)|+F[_clF^hdlFffel@%-Fghm6$FffelFaoC%>Fhgdl-Fj`w6'F^h
dlFYFinFaoFffel-Fas6$Q=moving~(0,%a)~to~the~origin|+F[_clFffel-Fas6$Q5new~vecto
r~field~%a|+F[_clFhgdl>FhgdlF^hdl>F[idl-F]jdlFjidl>F^\el-Fi`elF\jdl>Fi]el-Fbdel
Ff_fl-Fas6$Q3Newton~diagram~%a|+F[_clF[idl-Fas6$Q8[alpha,beta,degree]=%a|+F[_cl
Fi]elFb`gl@%F\h[m@%FjfjlC$>F`[el7+FaoFffelF,F[vF,Fg^elFaoFi^elF^[gl-Faf[m6(Fhgd
lFi]elF[v7$-Fhjl6#FbhelF`[elF^bflFboC$>F`[el7+FaoFffelF,F,F,Fg^elFaoFi^elF^[gl-
Faf[m6(FhgdlFi]elF,F\^\mF^bflFbo@%FjfjlC$>F`[elFi]\m-Faf[m6(FhgdlFi]elF[vF\^\mF
^bflF1C$>F`[elFa^\m-Faf[m6(FhgdlFi]elF,F\^\mF^bflF1@$FbirFc[\m-Fas6#QHblowing~u
p~in~the~positive~x~direction|+F[_cl>Fj[el-Fj`il6'FhgdlFi]elF,FYFin-Fas6$Fg\jlF
`celFb`gl>F`[el7+FaoFffelF,F,Fg^elFaoFi^elF,F^[gl-Faail6'Fj[elF,F]helF\^\mF^bfl
@%F\h[m@%FjfjlC$>F`[elFa^\mFb^\mC$Fi]\mFj]\m@%FjfjlC$>F`[elFa^\mF[_\mC$Fi]\mFg^
\m@$FbirFc[\m-Fas6#QI---------------------------------------|+F[_cl-Fas6$Q2Back
~to~level~%d|+F[_cl,&F]helF,F[vF,Fb`glF[_clF[_clF[_clF(,
I(ManXPosF\eflF(,
I(ManXNegF\eflF(,
I(NumXPosFaoF(,
I(NumXNegFaoF(,
I(NumberYFaoF(,
I(ManYPosF\eflF(,
I(ManYNegF\eflF(,
I,user_bindirQ2/usr/local/p4/binF(F(,
I,user_tmpdirQ%/tmpF(F(,
I,user_lypexeQ)lyapunovF(F(,
I0user_lypexe_mpfQ-lyapunov_mpfF(F(,
I/user_removecmdQ#rmF(F(,
I,user_sepexeQ,separatriceF(F(
