M7R0
I(epsilon$"""!"#6",
I)test_sep""!F&,
I-taylor_level"#5F&,
I.numeric_levelF*F&,
I*max_levelF*F&,
I/weakness_level""&F&,
I#x0F(F&,
I#y0F(F&,
I&x_min!""F&,
I&y_minF2F&,
I&x_maxF$F&,
I&y_maxF$F&,
I0all_crit_pointsF(F&,
I)save_all%&falseGF&,
I*vec_tableQ-TEST_VEC.TABF&F&,
I-finite_tableQ-TEST_FIN.TABF&F&,
I+finite_resQ-TEST_FIN.RESF&F&,
I/infinite_tableQ-TEST_INF.TABF&F&,
I-infinite_resQ-TEST_INF.RESF&F&,
I,hamiltonianF8F&,
I.ishamiltonianf*6#%#vfG6#%%exprGF&F&C$>8$-%)norpoly2G6%,&-%%diffG6$&9$6#F$%"xG
F$-FR6$&FU6#""#%"yGF$FWFgn@%%(roundedG@%/-%&evalfG6#FL$F(F(%%trueGF8@%/FLF(F`oF
8F&F&F&F&,
I'p4mainf*F&6*%#gcG%$gcfG%*gcdresultG%'orig_fG%"gG%#geG%#gnG%"jGF&F&C=>%+normal
exitGF(>Fin%-user_numericG@%0%0user_precision0GF(>%'DigitsGFep>Fgp-%&floorG6#-%
'evalhfG6#Fgp@$1Fgp%/user_precisionGC$-%'writefG6%Q\pPlease~increase~precision~
or~decrease~accuracy.~Precision~=~%d~<=~Accuracy~=~%d.|+F&FgpFaq-%%quitGFV@$55/
-%6CheckIfGoodPolynomialG6#&%'user_fGFVF8/-F^r6#&FarFenF8/-F^r6#%)user_gcfGF8C$
-Fdq6#QipThe~system~is~not~well-defined~(not~polynomial,~or~coefficients~do~not
~evaluate~numerically.)|+F&Fgq-Fdq6#QGLET~US~STUDY~THE~DIFFERENTIAL~SYSTEM:|+F&
-Fdq6%Q:~~~~x'~=~%a|+~~~~y'~=~%a|+|+F&F`rFer-%)openfileG6#F9-Fdq6&Q*%d|+%d|+%d|
+F&F6%'user_pG%'user_qG@$/F6""$-Fdq6'Q1~~~~%g~%g~%g~%g|+F&F1F4F3F5-Fes6#%)termi
nalG@%/FirF(C'>8'Far>8&-%'my_gcdG6$F`rFer>FL&F[uFen>Fir&F[u6#F^t>Far-%)simplify
G6#&F[uFVC&>FLFfn>FitFar>Far7$-Ffu6#*&&FitFVF$FirF2-Ffu6#*&&FitFenF$FirF2@$F[rC
$-Fdq6#QNError:~The~given~gcf~is~not~a~common~factor.|+F&Fgq-%*write_gcfGFhrFds
-%0write_vec_fieldG6#FarFbt@%-FDF_wC$-Fdq6#Q<The~system~is~Hamiltonian.|+F&>FCF
`o>FCF8@$4-%'memberG6$F6<$FfnF^tC.>%)log_fileGF;>%,result_fileGF=-Fdq6#QOLET~US
~STUDY~THE~SYSTEM~AT~THE~FINITE~REGION|+|+F&-Fes6#FbxF^s-Fdq6%Q9~~~~x'~=~%a|+~~
~~y'~=~%a|+F&FavFev-Fdq6#Q6AT~THE~FINITE~REGION|+F&@$5/FLF$3/FLFfn0FirF$C%-Fdq6
$QDThe~system~has~a~common~factor:~%a|+F&Fir-Fdq6$QJHence~we~shall~study~the~re
duced~system:|+F&Fir-Fdq6%FjxF`rFerFbt@%4FbpC->8(-%0find_real_rootsG6%FarFWFgn>
8)&FazFV>8*&FazFen-Fes6#F`x-Fdq6$Q$%d|+F&,&-%%nopsG6#FfzF$-Fb[l6#FizF$Fbt-Fdq6#
QZ--------------------------------------------------------|+F&?(8+F$F$Fa[lF`o-%
*sing_typeG6&Far-%#opG6$F$&Ffz6#Fj[l-F_\l6$FfnFa\lF(>FinF`o?(Fj[lF$F$Fd[lF`o-F
\\l6&Far-F_\l6$F$&FizFb\l-F_\l6$FfnF[]lF(>FinFbpC(>Fiz-%8find_real_roots_numeri
cGFdzF[[l-Fdq6$F_[lFd[lFbtFf[l?(Fj[lF$F$Fd[lF`oFg\l-%*closefileGF\[l-Fg]lFgx@$4
-F[x6$F6<$F$F^tC*>F`xF?>FbxFA-Fdq6#QFLET~US~STUDY~THE~SYSTEM~AT~INFINITY|+|+F&F
^s@%Fby-Fdq6%Fjx*&FirF$F`rF$*&FirF$FerF$Fhx-Fdq6#Q-AT~INFINITY|+F&@$F_yC%FeyFhy
F[zFbt@%3/FjsF$/F[tF$-%5vec_field_diff_chartGFdz-%)pl_chartGF_w@$Fj]lC$Ff]lFh]l
-Fg]lFfs@$F]tC/>F`xF;>FbxF=F[[l-Fdq6$F_[lF$Fbt-Fdq6#QIWe~shall~study~the~differ
ential~system:|+F&@%FbyFe^lFhx-Fdq6%Q7in~the~point~(%a,%a).|+F&F/F0@$F_yC%FeyFh
yF[zFbt-F\\l6&FarF/F0F(Ff]lFh]lFbt-Fdq6#QR|+We~have~finished~the~study~of~the~v
ector~field.|+F&-%.closeallfilesGF&>F`pF$F&6+FinFarFirFjsF[tFCF`xFbxF`pF&F&,
I-prepareCurvef*F&F&F&F&C&-Fes6#%,curve_tableG-%,write_curveG6#%+user_curveG-Fd
q6#Qgn|+We~have~finished~writing~the~curve~as~a~C++~readable~list.|+F&>F`pF$F&6
$FjalF`pF&F&,
I1prepareIsoclinesf*F&F&F&F&C&-Fes6#%0isoclines_tableG-%0write_isoclinesG6#%/us
er_isoclinesG-Fdq6#Qjn|+We~have~finished~writing~the~isoclines~as~C++~readable~
lists.|+F&>F`pF$F&6$FiblF`pF&F&,
I6CheckIfGoodPolynomialf*6#%"fGF&F&F&O-%%typeG6$-F]o6#FU-%(polynomG6$%(numericG
7$FWFgnF&F&F&F&,
I+normalexitF(F&,
I(roundedF8F&,
I3Hardware_precision"#:F&,
I-reduce_coefff*6$FbclFW6&Fjo%#g1G%#g2GF]p6"FhdlC&>8$-%(norpolyG6$9$9%>8%-%&num
erG6#F[el>8&-%&denomGFeel@%/FbelF(7#F(7#-%"$G6$*&-%&coeffG6%FbelF`el8'F$FgelF2/
Fefl;F(-%'degreeG6$FbelF`elFhdlFhdlFhdlF&,
I-write_numberf*6#%"nGFhdlFhdlFhdl@%Fin-Fdq6$Q$%g|+6"-F]o6#F_el-Fdq6$Q$%a|+Fhdl
F_elFhdlFhdlFhdlF&,
I+reduce_lltf*6$%"aG%"bGFhdl6$%)operatorG%&arrowGFhdl-%&evalbG6#1-F]o6#,&F_elF$
F`elF2,$)F*,$FaqF2F2FhdlFhdlFhdlF&,
I-reduce_evalfF]oF&,
I*reduce_gtf*F[hlFhdlF^hlFhdl-Fbhl6#1FihlFehlFhdlFhdlFhdlF&,
I,reduce_gteqf*F[hlFhdlF^hlFhdl-Fbhl6#1FhhlFehlFhdlFhdlFhdlF&,
I+reduce_eeqf*F[hlFhdlF^hlFhdl-Fbhl6#2-F]o6#-%$absGFfhlFihlFhdlFhdlFhdlF&,
I,reduce_nneqf*F[hlFhdlF^hlFhdl-Fbhl6#1FihlF[jlFhdlFhdlFhdlF&,
I4optimizepolynomial1f*Fddl6'Fjo%"LGF]p%"kG%"zGFhdlFhdlC(>F[elF\el@%4Fin>F[el-%
(convertG6$F[el%)rationalG>F[el-F]oFeel>Fbel-%%evalG6#7#-F_fl6$.-Fcfl6%F[elF`el
Fgel/Fgel;F(-%$maxG6$F(-Fifl6$F[elF`el@$3F][m%.user_simplifyG>Fbel-%$mapG6$%1us
er_simplifycmdGFbel>Fbel-F[]m6$f*6#FijlFhdlF^hlFhdl@%-Fecl6$FdglF\dl@%1-F^jl6#F
dglFihlF(F_elF_elFhdlFhdlFhdlFbel-Fg[m6#-%$addG6$*&&Fbel6#FeflF$)F`el,&FeflF$F2
F$F$/Fefl;F$-Fb[l6#FbelFhdl6$FaqFinFhdlF&,
I4optimizepolynomial2f*6%FbclFWFgn6&FjoF]pFgjlFijlFhdlFhdlC'>F[el-FN6%F_elF`el9
&@%F][m>F[elF_[m>F[elFd[m>Fgel-Fg[m6#7#-F_fl6$.-Fcfl6%F[elF`elFbel/FbelF`\m>Fge
l-F[]m6$f*Fb]mFhdlF^hlFhdl-Fdjl6$F_elT$FhdlFhdl6$FgnFa_mFgel-F]el6$-Fg[m6#-F]^m
6$*&&Fgel6#FhjlF$)F`el,&FhjlF$F2F$F$/Fhjl;F$-Fb[l6#FgelF`elFhdlFhdlFhdlF&,
I+first_termf*6$%#_fGFW6#FbclFhdlFhdlC$>F[el-FdjlF^el@%/F[elF(F(*&-Fcfl6%F[elF`
el-%(ldegreeGFe\mF$)F`elFcbmF$FhdlFhdlFhdlF&,
I*lleadtermf*FhamFjamFhdlFhdlC$>F[elF]bm@%F_bmF(*&-Fcfl6%F[elF`elFd\mF$)F`elFd
\mF$FhdlFhdlFhdlF&,
I'nltermf*F[_m6$Fjo%"hGFhdlFhdlC$>F[el-F]el6$-FfbmF^elFa_m@%0F[elF(C$>Fbel-Ffbm
6$F[elFa_m@%0FbelF(FbelF[elC$>F[el-F]el6$-Ffbm6$F_elFa_mF`el@%FicmF[elF_elFhdlF
hdlFhdlF&,
I%ddegf*6%FiamFWFgnFjamFhdlFhdlC$>F[el-Fi^mF`_m@%F_bmF(-Fifl6$F[el<$F`elFa_mFhd
lFhdlFhdlF&,
I)low_ddegf*FidmFjamFhdlFhdlC$>F[elF\em@%F_bmF(-FdbmF_emFhdlFhdlFhdlF&,
I&ntermf*6&FiamFWFgn%"dG6%FbclF]pFjoFhdlFhdlC&>F[elF\em>FgelF(?(FbelF(F$9'F`o>F
gel,&FgelF$*(-Fcfl6%F\`mFa_m,&F`fmF$FbelF2F$)F`elFbelF$)Fa_mFffmF$F$FgelFhdlFhd
lFhdlF&,
I)low_deg1f*FhamFjamFhdlFhdlC$>F[el-F]o6$-F]elFeglF`el@%/F[elF_oF(FcbmFhdlFhdlF
hdlF&,
I+optimizevff*F[_mFhdlF^hlFhdl7$-Fi^m6%&F_el6#F$F`elFa_m-Fi^m6%&F_el6#FfnF`elFa
_mFhdlFhdlFhdlF&,
I1quasihom_degree1f*6'FiamFWFgn%"pG%"qG6%%#_xG%#_yGFbclFhdlFhdlC%>FgelF\em>Fgel
-%%subsG6%/F`el)F[elF`fm/Fa_m)Fbel9(Fgel-Fifl6$Fgel<$F[elFbelFhdlFhdlFhdlF&,
I0quasihom_degreef*6'FGFWFgnF`hmFahmFhdlF^hlFhdl-Fb\m6$,&-F]hm6'FggmF`elFa_mF`f
mF_imF$F`fmF2,&-F]hm6'F[hmF`elFa_mF`fmF_imF$F_imF2FhdlFhdlFhdlF&,
I,change_polyf*F[_m6&FjoFbcmFhjlF\hlFhdlFhdlC&>F[elF__m>FbelF(?(FhdlF$F$FhdlFic
mC&>Fgel-F_cm6%F[elF`elFa_m>F[el,&F[elF$FgelF2>Fefl-Fg[m6$-Fg[m6$Fgel/F`elF$/Fa
_mF$@$2Fihl-F^jl6#-F]oFa^m>Fbel,&FbelF$FgelF$FbelFhdlFhdlFhdlF&,
I*sort_listf*6#%"sGFhdlF^hlFhdl-%%sortG6$F_elf*6$%&sle_aG%&sle_bGFhdlF^hlFhdl-F
bhl6#52Fggm&F`elFhgm3/FggmFh\n2F[hm&F`elF\hmFhdlFhdlFhdlFhdlFhdlFhdlF&,
I+reduce_impf*Fb]mFhdlF^hlFhdl-F]o6#-%*reduce_imGFeglFhdlFhdlFhdlF&,
I,reduce_conj%*conjugateGF&,
I*reduce_ref*Fb]mFhdlF^hlFhdl,&F_el#F$Ffn-Fc]nFeglFh]nFhdlFhdlFhdlF&,
I*reduce_imf*Fb]mFhdlF^hlFhdl*&^##F2FfnF$,&F_elF$Fi]nF2F$FhdlFhdlFhdlF&,
I)openfilef*Fhdl6&%#kkGFhjl%#fhG%&fnameGFhdlFhdlC%>%0currentopenfileG<"?(F[elF$
F$9#F`oC$>Fefl-Fg[m6#&9"Feel@%/FeflFdt>Fh^n-%&unionG6$Fh^n<#,$%)infinityGF2C$?(
FbelF$F$-Fb[l6#%-openfilelistGF`o@$/-F_\l6$F$&F_`nFg^mFefl[@%1FbelF]`n>Fh^n-Ff_
n6$Fh^n<#-F_\l6$FfnFd`nC%>Fgel-%&fopenG6%Fefl%&WRITEG%%TEXTG>Fh^n-Ff_n6$Fh^n<#F
gel>F_`n-Ff_n6$F_`n<#7$FeflFgel@$/-Fb[l6#Fh^nF(>Fh^nFh_nFhdl6$Fh^nF_`nFhdlF&,
I*closefilef*6#%)filenameGF_amFhdlFhdl@%0F_elFdtC$?(F[elF$F$F]`nF`o@$/-F_\l6$F$
&F_`nFeelF_elFe`n@$1F[elF]`nC%-%'fcloseG6#-F_\l6$FfnF`cn@$-F[x6$FgcnFh^nC$>Fh^n
-%&minusG6$Fh^n<#Fgcn@$F_bn>Fh^nFh_n>F_`n-F_dn6$F_`n<#F`cn@$3-F[x6$Fi_nFh^n2F$F
`bn>Fh^n-F_dnFg_nFhdlFcbnFhdlF&,
I'writeff*6#%-formatstringG6#F]pFhdlFhdl?(F[elF$F$F`bnF`o@%/&Fh^nFeelFi_n-%'pri
ntfG6$F_el&Fa_n6#;FfnF[_n-%(fprintfG6%FgenF_elF[fnFhdlFhdlFhdlF&,
I0currentopenfileFh_nF&,
I-openfilelistFi^nF&,
I.closeallfilesf*FfbnFhdlFhdlFhdl?(FhdlF$F$Fhdl0F]`nF(-Fg]l6#-F_\l6$F$&F_`nFhgm
FhdlFhdlFhdlF&,
I(norpolyf*6$%"PGFWFhdlF^hlFhdl@%Fh\m-%'expandG6#-F]]m6#-%'normalGFegl-FbgnFegn
FhdlFhdlFhdlF&,
I)norpoly2f*6%F_gnFWFgnFhdlF^hlFhdl@%Fh\mFagnFhgnFhdlFhdlFhdlF&,
I)norpoly3f*6&F_gnFWFgnFijlFhdlF^hlFhdl@%Fh\mFagnFhgnFhdlFhdlFhdlF&,
I'my_gcdf*6$Fiam%#_gG6+FbclFjo%#f2GFgdl%#ffG%"cGFfo%"lG%"rG6"F[inC'>8$-FN6%9$FW
Fgn>8%-FN6%9%FWFgn@$4FinC$>F^in-F`[m6$F^inFb[m>Fcin-F`[m6$FcinFb[m@%3/F^inF(0-F
gdm6%FcinFWFgnF(C%>8(7$F(F$>8)F$>8*Fcin@%3/FcinF(0-Fgdm6%F^inFWFgnF(C%>Fhjn7$F$
F(>F[[oF$>F][oF^in@%33Fhin-%*num_coeffGFc[o-F]\oFejnC'>8+-%$lcmG6$-Fiel6#F^in-F
iel6#Fcin>8&*&F^inF$Fa\oF$>8'*&FcinF$Fa\oF$>F][o-FN6%*&-%$gcdG6$Fj\oF]]oF$Fa\oF
2FWFgn@%0-Fgdm6%F][oFWFgnF(C(-Fdq6$FgyF][o>F[[oF$>Fhjn7$-FN6%*&F^inF$F][oF2FWFg
n-FN6%*&FcinF$F][oF2FWFgn-Fdq6#Fa`l-Fdq6$Q+~~~~x'=%a|+F[in&Fhjn6#F$-Fdq6$Q+~~~~
y'=%a|+F[in&Fhjn6#FfnC%-Fdq6#QCThe~system~has~no~common~factors.|+F[in>Fhjn7$F^
inFcin>F[[oF(C'>8,Fin>FinF`o>F][o-Fd]o6$F^inFcin@%Fg]oC(-Fdq6$QDThe~system~has~
a~comman~factor:~%a|+F[inF][o>Fhjn7$Fb^oFe^o>F[[oF$Ff^oFh^oF]_oC%Fc_o>FhjnFg_o>
F[[oF(>FinF[`o7%FhjnF[[oF][oF[in6#FinF[inF&,
I*num_coefff*6%FiamFWFgn6*FbclF]pFhjl%#l1G%#l2G%#s1G%#s2G%#okG6"FgaoC(@%4Fin>8$
-F`[m6$-FN6%9$9%9&Fb[m>F\boF_bo>8+F`o>8'-Fbdl6$F\boFbbo>8%F(?(FgaoF$F$Fgao3Ffbo
2F\co-Fb[l6#FhboC'>F\co,&F\coF$F$F$>8)&Fhbo6#F\co>8(-Fbdl6$FfcoFcbo>8&F(?(FgaoF
$F$Fgao3Ffbo2F^do-Fb[l6#FjcoC%>F^do,&F^doF$F$F$>8*&Fjco6#F^do@$4-Fecl6$FhdoFb[m
>FfboF8FfboFgaoFgaoFgaoF&,
I)save_allF8F&,
I3real_roots_numericf*6$FbclFW6&%%cplxGF]pFhjlFjo6"FfeoC&>8$7#-%'fsolveG6&9$9%%
(complexG%+fulldigitsG>8'7"?(8%F$F$-Fb[l6#FieoF`o@$1-F^jl6#-%#ImG6#&Fieo6#Fffo)
F*,$FaqF2C%>F`go-%#ReGF_go?(8&F$F$-Fb[l6#FcfoF`o@$-Ffil6$F`go&Fcfo6#Figo[@$2Fjg
oFigo>Fcfo7$-F_\lF[hoF`go-F^\nF[hoFfeoFfeoFfeoF&,
I1find_real_roots1f*Fceo6'FbcmF[pF\pFhjlF]hlFfeoFfeoC$@%FinC$>FffoFdfo>Figo-Fae
o6$F^foF_foC)>%-_EnvExplicitGF`o>%1_EnvAllSolutionsGF`o>%,_EnvTryHardGF`o>Fieo7
#-%&solveGFaio>FffoFdfo>FigoFdfo?(FcfoF$F$FgfoF`oC$>8(&FieoF[ho@%-%$hasG6$Fbjo%
'RootOfGC$>Fbjo-F]o6#Fbjo@$1-F^jl6#-F^goF\[pFbgoC$>Fbjo-FggoF\[p>Figo7$-F_\lF`h
oFbjo@$1-F^jl6#-F]oF`[pFbgoC$>FbjoFd[p>Fffo7$-F_\lFagoFbjo7$-F`[m6$-F`[m6$Fffo%
$setG%%listG-F`[m6$-F`[m6$FigoFg\pFh\pFfeoFfeoFfeoF&,
I8find_real_roots_numericf*6%FbclFWFgn6'FjoFbcmF]pFhjlF\hlFfeoFfeoC*>FdioF`o>Ff
ioF`o>FhioF`o>Fffo-F]o6#-F[]m6$%*allvaluesG7#-F\jo6$-F`[m6$F^foFg\p<$F_fo9&>Fie
oFdfo?(FigoF$F$-Fb[lFagoF`oC$>Fbjo-Fihm6$&FffoF`ho7$F_foFa^p@$32-F^jl6#-F^go6#&
Fbjo6#F$Fbgo2-F^jl6#-F^go6#&Fbjo6#FfnFbgoC%>Fbjo-F[]m6$FggoFbjo?(FcfoF$F$FgfoF`
o@$32-F^jl6#,&-F_\l6$F$FcjoF$Fb_pF2Fbgo2-F^jl6#,&-F_\l6$FfnFcjoF$Fi_pF2FbgoFaho
@$2FgfoFcfoC%>Fieo7$-F_\lFhfoFbjo@$/FgfoF$-Fdq6#Q=Numeric~real~singularities:|+
Ffeo-Fdq6'QC~~(%g,%g)~->~|fr~x'~=~%g,~y'~=~%g~|hr|+FfeoFb_pFi_p-F]o6#-Fihm6$<$/
F_foFb_p/Fa^pFi_p&F^foFc_p-F]o6#-Fihm6$F`bp&F^foFj_p@$/FgfoF(-Fdq6#QENo~numeric
~singularities~are~found.|+FfeoFieoFfeoFfeoFfeoF&,
I0find_real_rootsf*F_]p6,FjoFbcmF]pFhjlF\hl%#anGF\pF\\n%#snG%#bnGFfeoFfeoC2>Fdi
oF`o>FfioF`o>FhioF`o>FffoFh]p>FieoFdfo>8*Fdfo?(FigoF$F$Fd^pF`oC&>FbjoFg^p>8)-F[
]m6$FggoF[[p>8--F[]m6$F^goF[[p@$32-F^jl6#&FddpFc_pFbgo2-F^jl6#&FddpFj_pFbgoC$?(
FcfoF$F$-Fb[l6#F[dpF`o@$32-F^jl6#,&-F_\l6$F$&F[dpF[hoF$&F`dpFc_pF2Fbgo2-F^jl6#,
&-F_\l6$FfnF]fpF$&F`dpFj_pF2FbgoFaho@$2FcepFcfoC$>FieoFbap>F[dp7$-F_\lFdepF`dp>
8+Fdfo>8,Fdfo?(FcfoF$F$FcepF`o@%5-Ffjo6$Ff`pFhjo-Ffjo6$F\apFhjo>F`gp7$-F_\l6#F`
gpF]fp>F^gp7$-F_\l6#F^gpFcjo?(FigoF$F$-Fb[lF_hpF`oC$>&&F^gpF`hoFc_p-Fggo6#Fdhp>
&FehpFj_p-Fggo6#Fihp@%/FahpF(-Fdq6#QKNo~symbolic~real~singularities~are~found.|
+Ffeo-Fdq6#Q>Symbolic~real~singularities:|+Ffeo?(FcfoF$F$FahpF`o-Fdq6'F[bp-F_\l
6$F$&F^gpF[ho-F_\l6$FfnFiip-F]o6#-Fihm6$<$/F_foFgip/Fa^pFjipFcbpF\jp@%/-Fb[lF[h
pF(@%F]ip-Fdq6#QJNo~numeric~real~singularities~are~found.|+Ffeo-Fdq6#QPNo~other
~numeric~real~singularities~are~found.|+FfeoFfap?(FcfoF$F$FejpF`o-Fdq6'F[bp-F_
\l6$F$&F`gpF[ho-F_\l6$FfnFb[q-F]o6#-Fihm6$<$/F_foF`[q/Fa^pFc[qFcbpFe[q7$F^gpF`g
pFfeoFfeoFfeoF&,
I2find_real_roots11f*6$FgjlFW6+%#f1GFfhnFbclFjoF[pF\p%$ge2G%$gn2GF]pFfeoFfeoC,>
Fieo-Fdjl6$FcbpF_fo>Fffo-Fdjl6$FhbpF_fo@%0-Fb\m6$-Fifl6$FieoF_foF(F(C$>Fcfo-Fhh
oF`]q>FigoFffo@%0-Fb\m6$-Fifl6$FffoF_foF(F(C$>Fcfo-FhhoFj]q>FigoFieoC$>Fcfo7$Fd
foFdfo>FigoF(>Fbjo&FcfoFc_p>F`dp&FcfoFj_p>F[dpFdfo>F^gpFdfo?(F`gpF$F$-Fb[lF\[pF
`o@$2-F^jl6#-F]o6#-Fihm6$/F_fo&FbjoF[hpFigoFbgo>F[dp7$F\gpFd_q?(F`gpF$F$-Fb[l6#
F`dpF`o@$2-F^jl6#-F]o6#-Fihm6$/F_fo&F`dpF[hpFigoFbgo>F^gp7$F^hpFc`q7$F[dpF^gpFf
eoFfeoFfeoF&,
I.coeff_degree1f*6$FbclFW6&FjoFjemF]pFgjl6"F[aqC(>8$-Fdjl6$9$9%>8%-Fb\m6$F(-Fif
l6$F^aqFbaq>8'7"?(8&F(F$FdaqF`o@$0-Fcfl6%F^aqFbaqF]bqF(>Fjaq7$-F_\l6#Fjaq7$F]bq
F`bq@$/-Fb[lFebqF(>Fjaq7#7$F(F(FjaqF[aqF[aqF[aqF&,
I.coeff_degree2f*6%FbclFWFgn6)FjoFjemF]pFgjl%#dxGFbcmFhjlF[aqF[aqC(>F^aq-Fi^m6%
FaaqFbaq9&>8(Feaq>FjaqF[bq?(F]bqF(F$FhcqF`oC%>8)F`bq>Fdaq-Fb\m6$F(-Fifl6$F^aqFf
cq?(8*F(F$FdaqF`o@$0-Fcfl6%F]dqFfcqFddqF(>Fjaq7$Fdbq7%F]bqFddqFgdq@$Fhbq>Fjaq7#
7%F(F(F(FjaqF[aqF[aqF[aqF&,
I.coeff_degree3f*6&FbclFWFgnFijl6,Fjo%#d1G%#d2G%#d3G%#j1GFfdlFgdl%#j2G%#j3GFgjl
F[aqF[aqC(>F^aq-F]hn6&FaaqFbaqFfcq9'>FdaqFeaq>8-F[bq?(FhcqF(F$FdaqF`oC%>F]dq-Fi
^m6%-Fcfl6%F^aqFbaqFhcqFfcqF^fq>F]bq-Fb\m6$F(-Fifl6$F]dqFfcq?(8+F(F$F]bqF`oC%>F
ddq-Fcfl6%F]dqFfcqF_gq>Fjaq-Fb\m6$F(-Fifl6$FddqF^fq?(8,F(F$FjaqF`o@$0-Fcfl6%Fdd
qF^fqFjgqF(>Fafq7$-F_\l6#Fafq7&FhcqF_gqFjgqF]hq@$/-Fb[lFbhqF(>Fafq7#7&F(F(F(F(F
afqF[aqF[aqF[aqF&,
I0write_vec_fieldf*6#FG6$FgjlF]pF[aqF[aqC(>F^aq-F]cq6%&Faaq6#F$FWFgn-Fdq6$F_[l-
Fb[l6#F^aq?(FdaqF$F$FfiqF`o-Fdq6&Q*%d~%d~%g|+F[aq-F_\l6$F$&F^aq6#Fdaq-F_\l6$Ffn
F^jq-F]o6#-F_\l6$F^tF^jq>F^aq-F]cq6%&Faaq6#FfnFWFgnFdiq?(FdaqF$F$FfiqF`oFiiqF[a
qF[aqF[aqF&,
I9write_vec_field_cylinderf*F\iqF]iqF[aqF[aqC(>F^aq-F`eq6&FbiqFjhn%$_coG%$_siGF
diq?(FdaqF$F$FfiqF`o-Fdq6'Q-%d~%d~%d~%g|+F[aqF\jqF`jqFdjq-F]o6#-F_\l6$""%F^jq>F
^aq-F`eq6&FijqFjhnFb[rFc[rFdiq?(FdaqF$F$FfiqF`oFe[rF[aqF[aqF[aqF&,
I-write_saddlef*6,F/F0F\hlF]hlFhhnFjemFG%$sepG%&stypeG%&chartG6%FgjlF]pFhjlF[aq
F[aqC*-Fes6#F`x-Fdq6&Q*%d~%g~%g|+F[aqF$-F]o6#Faaq-F]o6#Fbaq-Fdq6'Q/~~%g~%g~%g~%
g|+F[aq-F]o6#Ffcq-F]o6#F^fq-F]o6#9(-F]o6#9)-F^w6#9*-Fdq6$Q&~~%d|+F[aq9-?(FdaqF$
F$-Fb[l6#9+F`oC'-Fdq6$Q&~~%d~F[aq&9,F_jq>F^aq-Fg`q6$&Fi^rF_jq%"tG-Fdq6$Q#%dF[aq
Ffiq?(F]bqF$F$FfiqF`o-Fdq6%Q'~%d~%gF[aq-F_\l6$F$&F^aq6#F]bq-F_\l6$FfnF^`r-Fdq6#
Q"|+6"-Fdq6$Q&~~%g|+F[aqF"-Fes6#FdtF[aqF[aqF[aqF&,
I+write_nodef*6&F/F0%%stabGFf\rF[aqF[aqF[aqC&Fi\r-Fdq6&F]]rFfnF^]rF`]r-Fdq6%Q)~
~%d~%d|+F[aqFfcqF^fqFi`rF[aqF[aqF[aqF&,
I1write_weak_focusf*6&F/F0Ff\rFe\rF[aqF[aqF[aqC&Fi\r-Fdq6&F]]rF^tF^]rF`]r-Fdq6%
FdarF^fqFfcqFi`rF[aqF[aqF[aqF&,
I3write_strong_focusf*F]arF[aqF[aqF[aqC&Fi\r-Fdq6'Q-%d~%d~%g~%g|+F[aqF\\rFfcqF^
]rF`]r-Fdq6$Fd^rF^fqFi`rF[aqF[aqF[aqF&,
I6write_semi_elementaryf*6,F/F0F\hlF]hlFhhnFjemFGFe\rFd\rFf\rFg\rF[aqF[aqC*Fi\r
-Fdq6&F]]rF.F^]rF`]rFb]rF_^r-Fdq6&Q,~~%d~%d~%d|+F[aq&Fi^rFciq&Fi^rFjjqFe^r@$553
/Fe^rF(-F[x6$F^cr<(F$FfnF^tF\\r""'""(330Fe^rF(/F_crF(Fecr33F\dr/F_crF$-F[x6$F^c
r<&FfnF^tFhcrFicr?(FdaqF$F$-Fb[l6#F__rF`oC&>F^aq-Fg`q6$F^_rFd_r-Fdq6$Q%~~%dF[aq
Ffiq?(F]bqF$F$FfiqF`oFi_rFb`rFf`rFi`rF[aqF[aqF[aqF&,
I2write_separatricef*6#Fd\r6(%&transGF]pFhjl%#p2GFgjlF\hlF[aqF[aqC/>F^aqFbiqFe_
r?(FdaqFfiqF2F$F`oC&>F]dqF^jq?(F]bqF$F$FfnF`o-Fdq6$Q$~%gF[aq-F]o6#&F]dqF_`r?(F]
bqF^tF$""*F`o-Fdq6$Q$~%dF[aqF`frFb`r>FjaqFijq-Fdq6%Q'%g~%g|+F[aq-F]o6#&FjaqFciq
-F]o6#&FjaqFjjq>F^aq&Faaq6#F^t-Fdq6'Q-%g~%g~%g~%g|+F[aq-F]o6#&F^aqFciq-F]o6#&F^
aqFjjq-F]o6#&F^aqFbgr-F]o6#&F^aq6#F\\r-F^w6#&FaaqFbhr>Fhcq-Fg`q6$&Faaq6#F.Fd_r-
Fdq6$Fg_r-Fb[l6#Fhcq?(F]bqF$F$F]irF`o-Fdq6%F[`r-F_\l6$F$&FhcqF_`r-F_\l6$FfnFdir
Fb`r-Fdq6$F_[l&Faaq6#FhcrF[aqF[aqF[aqF&,
I1write_degeneratef*6&F/F0%+trajectorsGFf\r6#F]pF[aqF[aqC)Fi\r-Fdq6&F]]rFhcrF^]
rF`]r-Fdq6$FbglF"-Fdq6$F_[l-Fb[lFf]r?(F^aqF$F$FgjrF`o-F_er6#&FfcqFgiq-Fdq6$F_[l
F^fqFi`rF[aqF[aqF[aqF&,
I*write_gcff*6#%%gcffG6-F]pF`hmFahm%#z1G%#z2GF\\nFb[rFc[rFjemFgjlFjoF[aqF[aqC&-
Fes6#F9>Fjgq-Fgdm6%FaaqFWFgn@%/FjgqF(-Fdq6$F_[lF(CE>Fafq-F]cqFj[s-Fdq6%Q&%d~%dF
[aqFjgqFfhq?(F^aqF$F$FfhqF`o-Fdq6&Q*~%d~%d~%gF[aq-F_\l6$F$&FafqFgiq-F_\l6$FfnF[
]s-F]o6#-F_\l6$F^tF[]sFb`r>FdaqFjs>F]bqF[t>8.-Fihm6%/FW*$)FhcqFdaqF2/Fgn*&FjaqF
$)FhcqF]bqF2Faaq>Fe]s-FN6%Fe]sFjaqFhcq>Fe]s-Fdel6#Fe]s>Fafq-F]cqF`^s-Fdq6$Fg_rF
fhq?(F^aqF$F$FfhqF`oFf\sFb`r>Fe]s-Fihm6%/FW*&FjaqF$Fj]sF2/Fgn*$F]^sF2Faaq>Fe]sF
_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r>Fe]s-Fihm6%/FW,$Fi]sF2F[^sFa
aq>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r>Fe]s-Fihm6%F\_s/Fgn,
$F__sF2Faaq>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r@$50FdaqF$0F
]bqF$C)>Fe]s-Fihm6%/FW*&FddqF$)F]dqFdaqF2/Fgn*&F_gqF$)F]dqF]bqF2Faaq>Fe]s-F]hn6
&Fe]sF]dqFddqF_gq>Fe]sFb^s>Fafq-F`eqFfasFf^s?(F^aqF$F$FfhqF`o-Fdq6'Q-~%d~%d~%d~
%gF[aqFi\sF\]sF`]s-F]o6#-F_\l6$F\\rF[]sFb`rFi`rF[aq6$FjsF[tF[aqF&,
I,write_curvef*6#%'curvefGFb[sF[aqF[aqC'-Fes6#Ffal>FjgqFi[s@%F\\sF]\sCE>FafqFa
\sFb\s?(F^aqF$F$FfhqF`oFf\sFb`r>FdaqFjs>F]bqF[t>Fe]sFf]s>Fe]sF_^s>Fe]sFb^s>Fafq
Fe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r>Fe]sFj^s>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aq
F$F$FfhqF`oFf\sFb`r>Fe]sFe_s>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf
\sFb`r>Fe]sF^`s>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r@$Fg`sC)
>Fe]sF\as>Fe]sFeas>Fe]sFb^s>FafqFiasFf^s?(F^aqF$F$FfhqF`oF[bsFb`r-Fg]lFibsFi`rF
[aq6%FjsF[tFfalF[aqF&,
I0write_isoclinesf*6#%+isoclinesfG6.F]pF`hmFahmFc[sFd[sF\\nFb[rFc[rFjemFgjlFjo%
"iGF[aqF[aqC&-Fes6#Febl?(8/F$F$FfnF`oC$>Fjgq-Fgdm6%&Faaq6#FhesFWFgn@%F\\sF]\sCE
>Fafq-F]cqF\fsFb\s?(F^aqF$F$FfhqF`oFf\sFb`r>FdaqFjs>F]bqF[t>Fe]s-Fihm6%Fh]sF[^s
F]fs>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r>Fe]s-Fihm6%F\_sF^_
sF]fs>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r>Fe]s-Fihm6%Fg_sF[
^sF]fs>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r>Fe]s-Fihm6%F\_sF
``sF]fs>Fe]sF_^s>Fe]sFb^s>FafqFe^sFf^s?(F^aqF$F$FfhqF`oFf\sFb`r@$Fg`sC)>Fe]s-Fi
hm6%F^asFaasF]fs>Fe]sFeas>Fe]sFb^s>FafqFiasFf^s?(F^aqF$F$FfhqF`oF[bsFb`r-Fg]lFf
esFi`rF[aq6%FjsF[tFeblF[aqF&,
I)jacobianf*6%Fbcl%$xeqG%$yeqG6#FI6"Fcis-Fg[m6#-F[]m6$f*FbisFcis6$F_hlF`hlFcis-
Fihm6$<$T&T$9$FcisFcis6&F`is9%Fais9&7&-FR6$&F_js6#F$-%$lhsG6#Fajs-FR6$Ffjs-Fijs
6#Fbjs-FR6$&F_js6#FfnFhjs-FR6$Fa[tF][tFcisFcisFcisF&,
I,eigenvectorf*6&F\hlF]hlFhhnFjem6$%#_cGF^glFcisFcisC%@%-F_jl6$FajsF(>8$7$F$,$*
&F_jsF$FajsF2F2@%-F_jl6$F_jsF(>F_\t7$F(F$@%-F_jl6$9'F(>F_\t7$F$,$*&FbjsF$F[]tF2
F2>F_\tFg\t@$FinC$>8%-%%sqrtG6#z'6$&F_\tFgjs&F_\tFb[t[[[[[_[[[[sF$][[[[[[[[[sF$
>F_\t-F]o6#7$*&Fj]tF$Fd]tF2*&F[^tF$Fd]tF2F_\tFcisFcisFcisF&,
I,translationf*6'%"vGFWFgnF/F06$Fa\qFfhnFcisFcisC&>F_\t-Fihm6$<$/Fajs,&FajsF$F[
]tF$/Fbjs,&FbjsF$9(F$Ffjs>Fd]t-Fihm6$F[_tFa[t@$FinC$>F_\t-F^jm6%F_\tFajsFbjs>Fd
]t-F^jm6%Fd]tFajsFbjs7$F_\tFd]tFcisFcisFcisF&,
I/transformationf*6'Fe^tF\hlF]hlFhhnFjem6-Fa\qFfhnFchmFdhm%#_aG%#_bGFi[t%#_dG%"
MGFfdlFgdlFcisFcisC,>F_\t-Fihm6$<$/FW,&*&FajsF$8&F$F$*&FbjsF$8'F$F$/Fgn,&*&F[]t
F$F]atF$F$*&F`_tF$F_atF$F$Ffjs>Fd]t-Fihm6$Fi`tFa[t>8,,&*&FajsF$F`_tF$F$*&FbjsF$
F[]tF$F2>8(*&F`_tF$FhatF2>8),$*&FbjsF$FhatF2F2>8*,$*&F[]tF$FhatF2F2>8+*&FajsF$F
hatF2>8--Fihm6%/F]atFW/F_atFgn,&*&F]btF$F_\tF$F$*&F`btF$Fd]tF$F$>8.-Fihm6%F^ctF
_ct,&*&FdbtF$F_\tF$F$*&FhbtF$Fd]tF$F$-Fbgm6%7$F[ctFdctFWFgnFcisFcisFcisF&,
I.normalizationf*6#Fe^t6%%#L1G%#L2G%"mGFcisFcisC)>F_\t-F]cq6%-Fi^m6%FfjsFWFgnFW
Fgn>Fd]t-F]cq6%-Fi^m6%Fa[tFWFgnFWFgn>F_\t-F[]m6$f*FbisFcisFiisFcis-F]o6#-F^jl6#
&F_js6#F^tFcisFcisFcisF_\t>Fd]t-F[]m6$f*FbisFcisFiisFcisFcetFcisFcisFcisFd]t>F]
at-Fb\m6$-F_\l6#F_\t-F_\l6#Fd]t@$4Fin>F]at-F`[m6$F]atFb[m-Fbgm6%7$,$*&FfjsF$F]a
tF2"%+5,$*&Fa[tF$F]atF2F^gtFWFgnFcisFcisFcisF&,
I)manifoldf*6%FjoF^gl%'stableG6.%$vf1G%$vf2G%#h1G%#h2GFhjlFadtFbdtFd\rFdhm%'lam
bdaGFfao%#n1GFcisFcisC*@%FinC$>F_\t-F]o6#Ffjs>Fd]t-F]o6#Fa[tC$>F_\tFfjs>Fd]tFa[
t>F`bt-Fcfl6%-%(collectG6$-Fihm6$/FgnF(FfjsFWFWF$>Fdbt-Fcfl6%-F\it6$-Fihm6$/FWF
(Fa[tFgnFgnF$>FhbtF(?(F]btFfnF$FajsF`oC)>F[ct*&-Fcfl6%-F\it6$-Fihm6$F`itFd]tFWF
WF]btF$,&*&F`btF$F]btF$F$FdbtF2F2@$3FeftFh\m>F[ct-F]]m6#F[ct>F]at-Fbgn6#-Fihm6$
/Fgn,&FhatF$*&F[ctF$)FWF]btF$F$F_\t>F_at-Fbgn6#,&-Fihm6$F`[uFd]tF$**F[ctF$F]btF
$)FW,&F]btF$F2F$F$F]atF$F2>F_\t-Fihm6$/FhatFgnF]at>Fd]t-Fihm6$F`\uF_at>Fhbt,&Fh
btF$Fb[uF$@$F'C&-Fdq6#Q>Testing~separatrix~for~x~>~0|+Fcis>Fdct-%1separatrice_t
estG6'FhbtF_jsFajsFbjsF$>8/Fajs?(FcisF$F$Fcis34Fdct2F`]uF,C%>F`]u,&F`]uF$F$F$@%
1F+F`]uC)@$/F`]uF+C$>F_\t-F]oFaft>Fd]t-F]oFcft>F[ct-F]o6#*&-Fcfl6%F`jtFWF`]uF$,
&*&F`btF$F`]uF$F$FdbtF2F2>F]at-Fbgn6#-Fihm6$/Fgn,&FhatF$*&F[ctF$)FWF`]uF$F$F_\t
>F_at-Fbgn6#,&-Fihm6$F__uFd]tF$**F[ctF$F`]uF$)FW,&F`]uF$F2F$F$F]atF$F2>F_\tF^\u
>Fd]tFb\u>Fhbt,&FhbtF$Fa_uF$C)>F[ctFe^u@$Fgjt>F[ctFijt>F]atF[_u>F_atFd_u>F_\tF^
\u>Fd]tFb\u>FhbtF_`u>Fdct-F]]u6'FhbtF_jsF`]uFbjsF$@$F'C%-Fdq6#Q>Testing~separat
rix~for~x~<~0|+Fcis>Fdct-F]]u6'FhbtF_jsF`]uFbjsF2?(FcisF$F$FcisFb]uC%>F`]uFg]u@
%Fi]uC)@$F\^uC$>F_\tF_^u>Fd]tFa^u>F[ctFc^u>F]atF[_u>F_atFd_u>F_\tF^\u>Fd]tFb\u>
FhbtF_`uC)>F[ctFe^u@$Fgjt>F[ctFijt>F]atF[_u>F_atFd_u>F_\tF^\u>Fd]tFb\u>FhbtF_`u
>FdctFj`u-Fihm6$/FWFd_rFhbtFcis6#F'FcisF&,
I0center_manifoldf*Fcgt63FfgtFggtFhgtFigtFhjlFbdtFd\rFdhmFjgtFfaoF[htFacqF]hlFc
dt%#amGFe\r%(stable2GFcisFcisC/@%FinC$>F_\tF`ht>Fd]tFchtC$>F_\tFfjs>Fd]tFa[t>F`
btFbit>FdbtF(>FdctFajs?(F]btFfnF$FdctF`oC+>Fhat,$*&F^jtF$F`btF2F2@$Fgjt>Fhat-F]
]m6#Fhat>F]at-Fbgn6#-Fihm6$/Fgn,&FhbtF$*&FhatF$Fc[uF$F$F_\t>F_at-Fbgn6#,&-Fihm6
$F_euFd]tF$**FhatF$F]btF$F[\uF$F]atF$F2>F_\t-Fihm6$/FhbtFgnF]at>Fd]t-Fihm6$F\fu
F_at>Fdbt,&FdbtF$FaeuF$>F`]u-Fdjl6$-Fihm6$F`itF_\tFW@$/F`]uF(>Fdct,&FdctF$F$F$>
80-Ffam6$F`]uFW>81-Fifl6$F\guFW>82-F]o6#-Fihm6$/FWF$F\gu@%-Fecl6$F`gu%%evenG@%1
F(Fdgu@%/FbjsF(>83F$>FchuFfn@%Fahu>FchuF^t>FchuF\\r@%F_hu@%Fahu>FchuF.>FchuFhcr
@%Fahu>FchuFicr>Fchu"")@$F'C$@%-F[x6$Fchu<$FfnFhcr>84F(>FgiuF$@$-F[x6$Fchu<&Ffn
F^tFhcrFicrC%-Fdq6#QETesting~center~separatrix~for~x~>~0|+Fcis>F[ct-F]]u6'FdbtF
_jsFdctFgiuF$?(FcisF$F$Fcis34F[ct2FdctF,C%>FdctFjfu@%1F+FdctC)@$/FdctF+C$>F_\tF
_^u>Fd]tFa^u>Fhat-F]o6#,$*&-Fcfl6%-F\it6$-Fihm6$/FgnFdbtFd]tFWFWFdctF$F`btF2F2>
F]at-Fbgn6#-Fihm6$/Fgn,&FhbtF$*&FhatF$)FWFdctF$F$F_\t>F_at-Fbgn6#,&-Fihm6$Fc\vF
d]tF$**FhatF$FdctF$)FW,&FdctF$F2F$F$F]atF$F2>F_\tFjeu>Fd]tF^fu>Fdbt,&FdbtF$Fe\v
F$C)>FhatFe[v@$Fgjt>FhatFhdu>F]atF_\v>F_atFh\v>F_\tFjeu>Fd]tF^fu>FdbtFc]v>F[ctF
bju@$F'C$@%-F[x6$Fchu<$F\\rFhcr>FgiuF(>FgiuF$@$-F[x6$Fchu<&F$F\\rFhcrFicrC%-Fdq
6#QETesting~center~separatrix~for~x~<~0|+Fcis>F[ct-F]]u6'FdbtF_jsFdctFgiuF2?(Fc
isF$F$FcisFejuC%>FdctFjfu@%F[[vC)@$F^[vC$>F_\tF_^u>Fd]tFa^u>FhatFc[v>F]atF_\v>F
_atFh\v>F_\tFjeu>Fd]tF^fu>FdbtFc]vC)>FhatFe[v@$Fgjt>FhatFhdu>F]atF_\v>F_atFh\v>
F_\tFjeu>Fd]tF^fu>FdbtFc]v>F[ctFbju>F`]u-Fdjl6$-Fihm6$F]\vF_\tFW7%-Fihm6$F_cuFd
btF`]uFchuFcisF`cuFcisF&,
I'saddlef*6,FbclF/F0F\hlF]hlFhhnFjem%$rhoG%&sigmaGFf\r6/%(lambda1G%(lambda2G%-l
ambda_ratioG%1lambda_ratio_numG%1lambda_ratio_denGFghnFjoFfdl%#v1G%#v2GFdgt%%se
p1G%%sep2GFcisFcisCA-Fdq6%Q<(%a,%a)~is~a~saddle~point.|+Fcis-F]oFjjs-F]oF^[t-Fe
s6#FbxFbbv-Fes6#Fdt>F_\t,&9+#F$Ffn-Ff]t6#9,#F2Ffn>Fd]t,&F]cvF^cvF_cvF^cv@%2-F^j
l6#Fa^u-F^jl6#F_^u>F]at*&F_\tF$Fd]tF2>F]at*&Fd]tF$F_\tF2@%33Feft-Fecl6$F_\t%(in
tegerG-Fecl6$Fd]tFddvC(>F_at-Fdel6#F]at>F]bt-FielFjdv-Fdq6%QHThe~ratio~between~
eigenvalues~is~%a:%a|+6"F]btF_atFgbvF]evFibvC*>F]at-F`[m6$-F]oFjdvFb[m>F]atFcev
>F_atFidv>F]btF\ev-Fdq6%QXThe~ratio~between~eigenvalues~is~%a:%a~(approximation
)|+F`evF]btF_atFgbvFievFibv>Fhat-Fe[t6&,&F[]tF$F_\tF2F`_t9),&9*F$F_\tF2>F[ct-Fe
[t6&,&F[]tF$Fd]tF2F`_tF`fv,&FbfvF$Fd]tF2@$F7C&Fgbv-Fdq6%QB~The~eigenvalues~are:
~|fr~%a,~%a~|hr|+FcisF_\tFd]t-Fdq6%QC~The~eigenvectors~are:~|fr~%a,~%a~|hr|+Fci
sFhatF[ctFibv@$F7-Fes6$FdtFbx@%50FajsF(0FbjsF(C%>F`bt-Fb^t6'F_jsFWFgnFajsFbjs-F
dq6#QIMoving~this~saddle~point~to~the~origin.|+F`ev-Fdq6$Q<The~new~vector~field
~is~%a|+FcisF`bt>F`btF_js>Fhbt-F]`t6'F`bt&FhatFgjs&F[ctFgjs&FhatFb[t&F[ctFb[t-F
dq6#Q\oTransform~this~vector~field~so~that~the~linear~part~is~diagonal.|+F`ev-F
dq6$F`hvFhbt>Fdbt-F]dt6#Fhbt-Fdq6#Q;Make~a~1000-normalization|+Fcis-Fdq6$QDso~t
hat~the~new~vector~field~is~%a|+FcisFdbt-Fdq6#QIWe~calculate~the~invariant~sepa
ratrices|+FcisFibv@%2F_^uF(>FdctF$>FdctF(>F`]u-Fagt6%FdbtF)Fdct@%2Fa^uF(>FdctF$
>FdctF(>F\gu-Fagt6%-F]`t6'FdbtF(F$F$F(F)Fdct@%-F\il6$F_\tF(C%-Fdq6$Q?The~stable
~separatrice~is~%a.|+F`ev7$F\guFd_r-Fdq6$QAThe~unstable~separatrice~is~%a.|+F`e
v7$Fd_rF`]u@$F7C&FgbvF^[wFb[wFibvC%-Fdq6$F`[wFe[w-Fdq6$Fd[wFa[w@$F7C&FgbvFi[wF[
\wFibv-Fdq6#QZ########################################################|+FcglFgb
vF_\wFibv-Fa\r6,FajsFbjsFehvFfhvFghvFhhvFdbt7$F`]uF\gu7$-%%signGFjcv-Fg\wFhcv9-
FcisFcisFcisF&,
I-strong_focusf*6'FfavFeavF/F0Ff\r6%FhavFiavFgjlFcisFcisC*>F_\t,&FajsF^cv-Ff]t6
#F_jsFbcv>Fd]t,&FajsF^cvFa]wF^cv@%-F\ilF]\tC'-Fdq6%QE(%a,%a)~is~a~strong~unstab
le~focus.|+FcisFfbv-F]o6#F[]tFgbvFh]wFibv>F]atF$C'-Fdq6%QC(%a,%a)~is~a~strong~s
table~focus.|+FcisFfbvF[^wFgbvF_^wFibv>F]atF2F_\wFgbvF_\wFibv-F]br6&FbjsF[]tF]a
tF`_tFcisFcisFcisF&,
I%nodef*6(FbclFfavFeavF/F0Ff\r6(FgjlFhavFiavFjavF[bvF\bvFcisFcisC,@%-Figl6$Fbjs
F(C'-Fdq6%Q;(%a,%a)~is~a~stable~node.|+F`evF[^w-F]o6#F`_tFgbvF^_wFibv>F_\tF2C'-
Fdq6%Q>(%a,%a)~is~an~unstable~node.|+F`evF[^wFa_wFgbvFe_wFibv>F_\tF$>Fd]t,&Fbjs
F^cv-Ff]tFjjsFbcv>F]at,&FbjsF^cvF[`wF^cv@%2-F^jl6#FeevFgcv>F_at*&Fd]tF$F]atF2>F
_at*&F]atF$Fd]tF2@%33FeftFedv-Fecl6$F]atFddvC(>F]bt-Fdel6#F_at>F`bt-FielF^aw-Fd
q6%F_evF`btF]btFgbvFaawFibvC*>F_at-F`[m6$-F]oF^awFb[m>F_atFeaw>F]btF]aw>F`btF`a
w-Fdq6%F[fvF`btF]btFgbvF[bwFibvF_\wFgbvF_\wFibv-F[ar6&F[]tF`_tF_\tF`fvFcisFcisF
cisF&,
I+degeneratef*6&FbclF/F0Ff\r6#F^jrFcisFcisC--Fdq6%QD(%a,%a)~is~a~non-elementary
~point.|+FcisFebvFfbv-Fdq6#Q@Blowing~up~the~vector~field...|+FcisFgbvFdbwFibv>F
_\t-%+blowing_upG6&F_jsFajsFbjsF`oF_\wFgbvF_\wFibv-F[jr6&FajsFbjsF_\tF[]tFcisFc
isFcisF&,
I0semi_elementaryf*6+FbclF/F0F\hlF]hlFhhnFjemFiavFf\r6,F]bvF^bvFghnFjoFfdl%+cen
ter_sepGF_bvF`bvFe\rFdgtFcisFcisC=>F_\t-Fe[t6&F[]tF`_tF`fvFbfv>Fd]t-Fe[t6&,&F[]
tF$F]cvF2F`_tF`fv,&FbfvF$F]cvF2>F]atFigv>F]bt-F]`t6'F]atFj]t&Fd]tFgjsF[^t&Fd]tF
b[t>F_at-F]dt6#F]bt-Fdq6%Qhn(%a,%a)~is~semi-hyperbolic.|+Moving~this~point~to~t
he~origin.|+FcisFebvFfbv-Fdq6$F`hvF]atFihv-Fdq6$F`hvF]btFaiv-Fdq6$FfivF_atFgivF
gbv-Fdq6%Q=(%a,%a)~is~semi-hyperbolic.|+FcisFebvFfbv@$F7C)-Fdq6#QBMoving~this~p
oint~to~the~origin.|+F`evFjdwFihvF\ewFaivF^ewFgivFibv@%-Figl6$F]cvF(>F[ctF$>F[c
tF(>F`bt-Facu6%F_atF)F[ct>Fdbt-Fihm6$F_cu&F`btFgjs>Fhbt-Fihm6$F_cu-Fagt6%-F]`t6
'F_atF(F$F$F(F)F[ct>Fhat&F`btFhet@%-F[x6$Fhat<$F$F^tC)-Fdq6#Q8We~have~a~saddle-
node.|+Fcis-Fdq6$Q7center~separatrice~%a|+Fcis7$Fd_rFdbt-Fdq6$Q9unstable~separa
trice~%a|+Fcis7$FhbtFd_rFgbvFbgw@$F7C$FegwFigwFibv@%-F[x6$Fhat<$FfnF\\rC)FbgwFe
gw-Fdq6$Q7stable~separatrice~%a|+FcisF\hwFgbvFbgw@$F7C$FegwFdhwFibv@%/FhatFhcrC
)-Fdq6#Q3We~have~a~saddle.|+Fcis-Fdq6$Q@unstable~center~separatrice~%a|+FcisFhg
wFdhwFgbvF\iw@$F7C$F_iwFdhwFibv@%/FhatFicrC)F\iw-Fdq6$Q>stable~center~separatri
ce~%a|+FcisFhgwFigwFgbvF\iw@$F7C$FgiwFigwFibv@%/FhatF.C)-Fdq6#Q;We~have~an~unst
able~node.|+FcisFegwFigwFgbvF_jw@$F7C$FegwFdhwFibvC)-Fdq6#Q8We~have~a~stable~no
de.|+FcisFegwFdhwFgbvFejw@$F7C$FegwFdhwFibvF_\wFgbvF_\wFibv-Febr6,FajsFbjsFj]tF
bdwF[^tFcdwF_at7$FhatF$7$FdbtFhbtFacvFcisFcisFcisF&,
I*sing_typef*Fabw6&%$jacG%&deltaGFeavFfavFcisFcisC,>F_\t-F]is6%F_js/FWFajs/FgnF
bjs@$Fgjt>F_\t-F[]m6$F]]mF_\t>Fd]tz'6&Fj]tF[^t&F_\tFhet&F_\t6#F\\r\[[[[[[[[\[[m
F$[[[\[[\[[[[[mF2@$Fgjt>Fd]t-F]]mFcft>F]at,&Fj]tF$Fa\xF$@$Fgjt>F]at-F]]mFjdv>F_
at,&*$F]atFfnF$Fd]t!"%@$Fgjt>F_at-F]]mF^aw@$F7C)Fgbv-Fdq6%Q>(%a,%a)~is~a~singul
ar~point.|+FcisFajsFbjs-Fdq6'QGJacobian~=~[~[~%a,~%a~],~[~%a,~%a~]~]|+FcisFj]tF
[^tF`\xFa\x-Fdq6$Q,Delta~=~%a|+FcisFd]t-Fdq6$Q*Rho~=~%a|+FcisF]at-Fdq6$Q,Sigma~
=~%a|+FcisF_atFibv@%-Figl6$Fd]tF(-Fbav6,F_jsFajsFbjsFj]tF[^tF`\xFa\xF]atF_atF[]
t@%-F\ilFe^x@%-Fail6$F_atF(-Fe^w6(F_jsF_atF]atFajsFbjsF[]t@%-Ffil6$F]atF(-%+wea
k_focusG6&F_jsFajsFbjsF[]t-Fj\w6'F_atF]atFajsFbjsF[]t@%F`_x-F_bwFd_x-F`cw6+F_js
FajsFbjsFj]tF[^tF`\xFa\xF]atF[]tFcisFcisFcisF&,
I1separatrice_testf*6'Fd\rFGF^glFdgt%$dirG6'Ffao%'rndnumG%(exefileG%(sepfileGFh
jlFcisFcisC2>F]at-%$catG6$%,user_bindirG%,user_sepexeG>Fd]t-%%iremG6$-%%randGFc
isF^gt>F_at-Ff`x6&%,user_tmpdirGQ'P4SEP_FcisFd]tQ%.TMPFcis-FesF^aw-Fdq6$FbglF"-
Fdq6$F_[lF`_t-Fdq6$F_[lF[]t-F^wFjjs-Fdq6$F_[l,&FbjsF$F2F$?(F]btFfnF$FbjsF`o-Fdq
6%Q'%d~%g~FcisF]bt-Fcfl6%F_jsFWF]bt-Fdq6#Fd`r-Fg]lF^aw-Fdq6$Q;Separatrix~test~(
n=%d)...~FcisFbjs>F_\t-%(ssystemG6#-Ff`x6'%/user_exeprefixGF]atQ#~"FcglF_atQ""F
cgl-F_cx6#-Ff`x6&%/user_removecmdGFdcxF_atFecx@%/Fj]tF(C$-Fdq6#Q(not~ok|+FcisF8
C$-Fdq6#Q$ok|+FcisF`oFcis6(FccxFcax%,user_lypexeGFh`xFjcxF"FcisF&,
I+weak_focusf*6&FbclF/F0Ff\r6-Fe\rFghn%%aa10G%%aa01G%%bb10GF\\nFjoFchm%#ggG%$ly
pGFbcmFcglFcglC,-Fdq6%Q:(%a,%a)~is~a~weak~focus.|+Fcgl-F]o6#9%-F]o6#9&-Fes6#Fbx
Faex-Fes6#Fdt@%FCC*>8.,&-%*integrateG6$&9$6#F$FgnF$-Fdfx6$,&-FR6$FcfxFWF2&Fgfx6
#FfnF2FWF$-Fdq6#QTSince~the~system~is~hamiltonian,~we~have~a~center.|+Fcgl-Fdq6
$QKThe~Hamiltonian~function~is:|+~H(x,y)~=~%a|+FcglFafxFjexF`gxFcgxF\fx>8$F\\rC
.>8%-Fb^t6'FgfxFWFgnFfexFiex>8&-Fcfl6%-Fcfl6%&FjgxFhfxFWF$FgnF(>8'-Fcfl6%-Fcfl6
%FchxFWF(FgnF$>8(-Fcfl6%-Fcfl6%&FjgxF_gxFWF$FgnF(>8)-Ff]t6#,&*&FehxF$F[ixF$F2*$
F^hxFfnF2>8*7$,&*(F[ixF$-Fihm6$<#/FW,&*(FbixF$8+F$F[ixF2F2*(F^hxF$FgnF$F[ixF2F$
FchxF$FbixF%F$*(F^hxF$-Fihm6$F_jxF`ixF$FbixF%F2,$*&-Fihm6$<#/FW,&*(FbixF$FWF$F[
ixF2F2FdjxF$F`ixF$FbixF2F2@%Fbp>Fiix-F]o6#-Fihm6$/FcjxFWFiix>FiixFd[y-Fdq6$Q6Th
e~local~system:~%a|+FcglFiix>8,,&-Fihm6$<$/FW,&Fijl#F$Ffn%"wGFc\y/Fgn*&^##F2Ffn
F$,&FijlF$Fd\yF2F$&FiixFhfxF$*&^#F$F$-Fihm6$F`\y&FiixF_gxF$F$>F\\y-Fbgn6#F\\y@$
F7C%Fjex-Fdq6$Q)z'~=~%a|+FcglF\\yF\fx@%/F-F(C%-Fes6$FbxFdt-Fdq6#QenLyapunov~con
stants~are~not~calculated.~(weakness~level=0)|+Fcgl>FggxF(C%@%Fbp>8--%)lyapunov
G6%,&F\\yF$*&^#F2F$FijlF$F$FijlFd\y>Fd^y-%,lyapunovsymGFg^y-Fdq6$Q:Lyapunov~inf
ormation:~%a|+FcglFd^y@%0&Fd^yFhfxF(C'F[^y-Fdq6$Q=The~order~of~weakness~is~%d|+
Fcgl&Fd^yF_gx-Fdq6$Q9Lyapunov~constant~is~%g|+Fcgl,$Fc_yF2F\fx@%2Fc_yF(C'-Fdq6#
QBWe~have~an~unstable~singularity.|+FcglFjexF``yF\fx>FggxF$C'-Fdq6#Q?We~have~a~
stable~singularity.|+FcglFjexFe`yF\fx>FggxF2@%/&Fd^y6#F^tFfnC'-Fdq6#QMWe~have~a
~center~(the~system~is~quadratic).|+FcglFjexF^ayF\fx>FggxF\\r@%&Fd^y6#F\\rC'-Fd
q6#QPWe~have~a~center~(the~system~is~linear+cubic).|+FcglFjexFfayF\fx>FggxF\\rC
'-Fdq6$QGThe~order~of~weakness~is~at~least~%d.|+Fcgl,&F-F$F$F$FjexF[byF\fx>Fggx
F(Fjex-Fdq6#Fa\wF\fxF`by-Fear6&FfexFiex9'FggxFcgl6#FCFcglF&,
I)lyapunovf*6%FbclFijlFd\y6,F\hl%'bindirG%'infileG%(outfileGFa`x%'resultGF``x%#
wlG%&linfoG%$auxGFcglFcglC,>Fiix-F\ax6$-F_axFcglF^gt>F^hx-Ff`x6&FcaxQ'P4LYP_Fcg
lFiixQ%.INPFcgl>Fehx-Ff`x6&FcaxFicyFiixQ%.OUTFcgl@%/FepF(>F[ix-Ff`x6$Fh`xFfdx>F
[ix-Ff`x6$Fh`x%0user_lypexe_mpfG>F\\y-%4preparelyapunovfileG6&F^hxFgfxFfexFiex>
Fcjx&F\\yFhfx-Fdq6#QDDetermining~lyapunov~constants~...|+Fcgl>Fd^y-F_cx6#-Ff`x6
.FccxQ!FcglF[ixFdcxF^hxQ$"~"FcglFehxQ)"~MAPLE~Fcgl%.user_platformGFdcx%2user_su
mtablepathGFecx>Fbix-%3readlyapunovresultG6$FehxFcjx7%-F_\l6#Fbix&F\\yF_gx&F\\y
F\ayFcgl6)FccxFcaxFfdxFgdyFepFh`xFjcxFcglF&,
I3readlyapunovresultf*6$Fgbn%*weaklevelG6)%(lypdataG%&VdataGF]pF^gl%%wvalG%'lyp
valG%&okvalGFcglFcglC.>Fggx-%)readdataG6$FgfxF$-Fdq6$Q4lyapunov~data~=~%a|+Fcgl
Fggx>Fjgx7">FehxF$-Fes6$FdtFbx?(F^hxF$F$FfexF`oC&@$0&Fggx6#FehxF2-Fdq6%Q*V(%d)=
%g|+Fcgl-%&roundG6#F`hy&Fggx6#,&FehxF$F$F$>Fjgx7$-F_\l6#Fjgx7$FehyFhhy@$/FehyF2
C$>FehxFjhy[>Fehx,&FehxF$FfnF$@$Faiy>FehxFjhy>FiixFehy>F[ix-Ffhy6#Fhhy>Fbix&Fgg
x6#FfiyF\fx7$FbixF[ixFcglFcglFcglF&,
I4preparelyapunovfilef*6&FgbnFiamFijlFd\y6)Fbcl%&cubicGFgjlFjemF\hlF]pF^cyFcglF
cglC.>Fggx-Fi^m6%FfexFiexFdby>FjgxF8-Fes6#Fgfx-Fdq6$F_[l,&FepFfnFfnF$>Fehx-Fgdm
6%FggxFiexFdby@%/FehxFfnC$>FiixF^t-Fdq6#Q#3|+Fcgl@%/FehxF^tC$>FiixF.@%33/-Fcfl6
%-Fcfl6%FggxFiexFfnFdbyF(F(/-Fcfl6%-Fcfl6%FggxFiexF(FdbyFfnF(/-Fcfl6%-Fcfl6%Fgg
xFiexF$FdbyF$F(C$-Fdq6#Q#5|+Fcgl>FjgxF`oC$>FiixF--Fdq6$F_[lF-C$>FiixF-Fg]z-Fdq6
$Fbgl)F*,$FaqF2>F^hx-F]cqFb[z-Fdq6$F_[l-Fb[l6#F^hx?(FbixF$F$Fc^zF`oC$>F[ix&F^hx
Fafy-Fdq6'Q/~~%d~%d~%g~%g|+Fcgl&F[ixFhfx&F[ixF_gx-F]o6#-Fggo6#&F[ixF\ay-F]o6#-F
^goFa_z-Fg]lF\[z7%FiixFehxFjgxFcglFcglFcglF&,
I,lyapunovsymf*6%FiamFijlFd\y6+FbclF_cyF^cyFhjl%"TG%"VGF]cyFfaoF]pFcglFcglC,>Fg
gx-Fi^m6%FgfxFfexFiex>Fjgx-%3preparelyapunovsymG6%FggxFfexFiex>F^hxFchx>FiixFhg
y>FcjxF8Fjgy?(FehxF$F$F^hxF`oC(>F[ix-%)sumtableG6#,$FehxFfn>FbixF(?(F\\yF$F$-Fb
[l6#F[ixF`o>Fbix,&FbixF$-%4part_lyapunov_coeffG6'FggxFfexFiex&F[ixFb]y,&FehxFfn
F$F$F2>Fiix7$-F_\l6#Fiix7$FbixFehx-Fdq6&Q2k=%d~V~=~%a~=~%f|+FcglFehxFbix-F]oFaf
y@$-F_jl6$FbixF(C$>FcjxF`oFdiyF\fx@%Fcjx>Fiix&Fiix6#F2>Fiix7$F(F(7%F]bzF`ix&Fjg
xF\ayFcglFcglFcglF&,
I3preparelyapunovsymf*Fhby6(FejyFgjlFjemF\hlF]pF^cyFcglFcglC'>FggxF8>F^hx-FgdmF
a`z@%/F^hxFfn>FbixF^t@%/F^hxF^tC$>FbixF.@%33/-Fcfl6%-Fcfl6%FgfxFfexFfnFiexF(F(/
-Fcfl6%-Fcfl6%FgfxFfexF(FiexFfnF(/-Fcfl6%-Fcfl6%FgfxFfexF$FiexF$F(>FggxF`o>Fbix
F->FbixF->Fjgx-F]cqFa`z7%FbixF^hxFggxFcglFcglFcglF&,
I)sumtablef*6#F^gl6&FgjlFjhnF\\n%+st_compareGFcglFcglC&>Fggx-%*piecewiseG6%/Fgf
xF(7#7#F$-F[]m6$F_\l-F[]m6$&%)combinatG6#%(permuteG-&Fifz6#%*partitionG6$FgfxFg
fx>Fehxf*6$FjhnF\\nFcgl6$F_hlF`hlFcgl@%2Fffx&FfexFhfxF`o@%/FffxFggz-T#6$&Fgfx6#
;FfnF2&FfexF^hzF8FcglFcgl6$F[fzFehx>Fggx-F^\n6$FggxFehxOFggxFcglFcglFcglF&,
I4part_lyapunov_coefff*6'%)vecfieldGFijlFd\yFgjlFhjl6(%"RGFIFbclFe^t%#wwGFcesFc
glFcglC%>Fggx-F[]m6$f*6#FIFcglFdgzFcgl-%-lyp_findpolyG6&T$T&T(,&FgfxF$F$F$FcglF
cgl6(FihzFgfxFijlFfexFd\yFiexFdby@%4-F[x6$F(FggxC&>F^hxF2?(FbixF$F$,&-Fb[l6#Fgg
xF$F2F$F`o@%-Fecl6$,&FbixF$F2F$%$oddG>F^hx-%)lyp_RegzG6&F^hx&FggxFafyFfexFiex>F
^hx-%)lyp_ImgzGF][[l>FbixFcjz@%FfjzC%>F^hx-%/lyp_multc_polyG6'F^hxF(F2FfexFiex>
6$F^hxFehx-F_\l6#-%'lyp_LLG6'F^hxF^[[lFfexFiex,&9(Fc\yFh\yF$>F[ix-Ffu6#-F^goFah
yC$>Fj[[lF[\[l>F[ix-Ffu6#-FggoFahy>F[ixF(OF[ixFcglFcglFcglF&,
I/lyp_multc_polyf*6'FbclF\hlF]hlFijlFd\yFcglFcglFcglO-Fbgn6#*&,&FfexF$*&F\]yF$F
iexF$F$F$FgfxF$FcglFcglFcglF&,
I-lyp_findpolyf*6&FGFijlFd\yF^gl6$FjhnFhjlFcglFcglC%>FggxF(?(FjgxF(F$FdbyF`o>Fg
gx,&FggxF$*(-Fcfl6%-Fcfl6%FgfxFfexFjgxFiex,&FdbyF$FjgxF2F$)FfexFjgxF$)FiexFe^[l
F$F$FggxFcglFcglFcglF&,
I)lyp_Regzf*6&FbclFjoFijlFd\y6#FjhnFcglFcglC(>Fggx-Fbgn6#*&FgfxF$FfexF$>Fggx-Fg
[[l6'FggxF(F2FiexFdby>Fggx-FR6$FggxFiex>Fggx-%&lyp_GGFb[z>Fggx,&FggxF$-%.lyp_co
nj_polyGFb[zF$O-Fg[[l6%FggxFc\yF(FcglFcglFcglF&,
I)lyp_Imgzf*Fj^[lF[_[lFcglFcglC'>FggxF^_[l>FggxFe_[l>FggxFh_[l>Fggx,&FggxF$F\`[
lF2O-Fg[[l6%FggxF(Fh\yFcglFcglFcglF&,
I'lyp_LLf*6'FbclFjoFijlFd\yF^glF[_[lFcglFcglC$>Fggx-FR6$F^_[lFiex7$Fggx-Fcfl6%-
Fcfl6%FggxFiexFa\[lFdbyFa\[lFcglFcglFcglF&,
I&lyp_Gf*Fhby6&Fhjl%#fkGFjhnFihnFcglFcglC%>F^hxF(@$1F(-Fifl6$FgfxFfex?(FggxF(F$
F`b[lF`oC$>Fjgx-Fcfl6%FgfxFfexFggx@$1F(-Fifl6$FjgxFiex?(FehxF(F$Fib[lF`o@%0Fggx
Fehx>F^hx,&F^hxF$**-Fcfl6%FjgxFiexFehxF$,&FggxF$FehxF2F2)FfexFggxF$)FiexFehxF$F
fn>F^hx,&F^hxF$*(Fac[lF$Fdc[lF$Fec[lF$F$-FbgnFd^zFcglFcglFcglF&,
I.lyp_conj_polyf*Fhby6#%#zbGFcglFcglC$-%)assumingG6$7#-Fbgn6#-Fd]nF\[z7$'Ffex%%
realG'FiexFhd[l-Fg[m6$-Fg[m6$-Fg[m6$%"%G<#/FfexFggx/FiexFfex/FggxFiexFcglFcglFc
glF&,
I5vec_field_diff_chartf*6%FbclFWFgn6*Fjem%%f_U1G%%f_V1G%%f_U2G%%f_V2G%$linG%%si
ngG%(sdegreeGF`evF`evC4>8$-Fb\m6$-Fgdm6%&9$6#F$9%9&-Fgdm6%&Fhf[l6#FfnFjf[lF[g[l
>8%-Fbgm6%7$*&)Fd[sFbf[lF$,&*&Fc[sF$-Fihm6$<$/Fjf[l*$Fd[sF2/F[g[l*&Fc[sF$Fd[sF2
Fgf[lF$F2-Fihm6$F[h[lF^g[lF$F$,$*&)Fd[s,&Fbf[lF$F$F$F$Fig[lF$F2Fc[sFd[s>8&-Fbgm
6%7$*&Ffg[lF$,&*&Fc[sF$-Fihm6$<$/Fjf[l,$F]h[lF2F^h[lFgf[lF$F$-Fihm6$F`i[lF^g[lF
$F$*&Fdh[lF$F^i[lF$Fc[sFd[s>8'-Fbgm6%7$*&Ffg[lF$,&-Fihm6$<$/Fjf[lF_h[l/F[g[lF]h
[lFgf[lF$*&Fc[sF$-Fihm6$F_j[lF^g[lF$F2F$,$*&Fdh[lF$Fcj[lF$F2Fc[sFd[s>8(-Fbgm6%7
$*&Ffg[lF$,&-Fihm6$<$F`j[l/F[g[lFbi[lFgf[lF$*&Fc[sF$-Fihm6$F`[\lF^g[lF$F$F$*&Fd
h[lF$Fc[\lF$Fc[sFd[s@$4-F[x6$F6<$F$F^tC&-Fdq6#QCWe~make~use~of~the~Poincare~dis
c.|+F`ev-Fes6#Fbx-Fdq6#QHWe~make~a~study~on~the~Poincare~disc.|+|+F`ev-Fes6#Fdt
>8)7$-Fdjl6$-Fihm6$/Fd[sF(&Fag[lFif[lFc[s-Fdjl6$-Fihm6$F]]\l&Fag[lF_g[lFc[s@%3/
&Fg\\lFif[lF(/&Fg\\lF_g[lF(C(@$Fg[\lC&-Fdq6#QFInfinity~is~a~line~of~singulariti
es.|+F`evF_\\lF]^\lFd\\l>Fag[l-Fbgm6%7$*&F^]\lF$Fd[sF2*&Fc]\lF$Fd[sF2Fc[sFd[s>F
gi[l-Fbgm6%7$*&&Fgi[lFif[lF$Fd[sF2*&&Fgi[lF_g[lF$Fd[sF2Fc[sFd[s>Fgh[l-Fbgm6%7$*
&&Fgh[lFif[lF$Fd[sF2*&&Fgh[lF_g[lF$Fd[sF2Fc[sFd[s>Fhj[l-Fbgm6%7$*&&Fhj[lFif[lF$
Fd[sF2*&&Fhj[lF_g[lF$Fd[sF2Fc[sFd[s>8*F$>F_`\lF(-%,show_chartsG6$7&Fag[lFgh[lFg
i[lFhj[l7&Q#U1F`evQ#V1F`evQ#U2F`evQ#V2F`ev-Fes6#F9-F^w6#-Fihm6%/Fc[sFjf[l/Fd[sF
[g[lFag[l-F^w6#-Fihm6%F`a\lFaa\lFgh[l-F^w6#-Fihm6%F`a\lFaa\lFgi[l-F^w6#-Fihm6%F
`a\lFaa\lFhj[l-Fdq6$F_[lF_`\l@%-Fecl6$,&Fbf[lF$F2F$F]huC$>8+F(-Fdq6#Q#1|+F`evC$
>Ffb\lF$-Fdq6#Q$-1|+F`evFd\\l@%Fg[\l@%/F_`\lF(-%/find_inf_rootsG6)Fbf[lFhf[lFag
[lFgi[lFjf[lF[g[lFfb\l-%4find_inf_roots_singG6$Fag[lFgi[l-Fdq6#QOSingularities~
at~infinity~are~not~determined.|+F`evF`evF`evF`evF&,
I,show_chartsf*6$%%flstG%(namelstG6$FbclFhjlF`evF`ev?(Fag[lF$F$-Fb[l6#Fhf[lF`oC
%-Fdq6$QJThe~differential~system~on~the~%s~chart:|+F`ev&Fjf[l6#Fag[l>Fbf[l-Fg[m
6#&Fhf[lFid\l-Fdq6%Q<~~~~z1'~=~%a|+~~~~z2'~=~%a|+|+F`ev&Fbf[lFif[l&Fbf[lF_g[lF`
evF`evF`evF&,
I.behaviour_inff*6$FbclFjem64%#p1G%#q1GFchmFdhmFjoFa[xFb[xFeavFfavF[exF\exF]exF
\\n%#zzG%$zzbGFadtFbdtF_exF`evF`evC,>Fbf[l-Fihm6$<$/FW*&Fgh[lF$,&*$Fgh[lFfnF$*$
Fgi[lFfnF$F2/Fgn*&Fgi[lF$Fbf\lF2Fgf[l>Fag[l-Fihm6$F_f\lF^g[l>Fhj[l7$*&)Fbf\lFjf
[lF$,&*&Fbf\lF$Fbf[lF$F$*&Fgh[lF$,&*&Fgh[lF$Fbf[lF$F$*&Fgi[lF$Fag[lF$F$F$F%F$*&
F]g\lF$,&*&Fbf\lF$Fag[lF$F$*&Fgi[lF$Fag\lF$F%F$>Fhj[l-FN6%Fhj[lFgh[lFgi[l>Fhj[l
-Fbgm6%-Fihm6$<$/Fgh[lFW/Fgi[lFgnFhj[lFWFgn>Fg\\l-F]is6%Fhj[l/FWF(/FgnF(>F_`\lz
'6&Fg]\lFi]\l&Fg\\l6#F^t&Fg\\l6#F\\r\[[[[[[[[\[[mF$[[[\[[\[[[[[mF2>Ffb\l,&Fg]\l
F$F]i\lF$>8,,&*$Ffb\lFfnF$F_`\lF^]x@$-Figl6$Fbi\lF(@%-Ffil6$Ffb\lF(C1>8--F]o6#-
Fcfl6%-Fcfl6%F[`\lFgnF(FWF$>8.-F]o6#-Fcfl6%-Fcfl6%F[`\lFWF(FgnF$>8/-F]o6#-Fcfl6
%-Fcfl6%F]`\lFgnF(FWF$>80-F]o6#-Ff]t6#,&*&Fej\lF$F][]lF$F2*$F]j\lFfnF2>Fhj[l7$,
&*(F][]lF$-Fihm6$<#/FW,&*(Fe[]lF$Fgh[lF$F][]lF2F2*(F]j\lF$Fgi[lF$F][]lF2F$F[`\l
F$Fe[]lF%F$*(F]j\lF$-Fihm6$Fc\]lF]`\lF$Fe[]lF%F2*&-Fihm6$<#/FW,&Ff\]lF2*(F]j\lF
$FgnF$F][]lF2F$F]`\lF$Fe[]lF2>Fhj[l-F]o6#F^h\l>Fhj[l,&-Fihm6$<$/FW,&81#F$Ffn82F
]^]l/Fgn*&^##F2FfnF$,&F\^]lF$F^^]lF2F$F[`\lF$*&^#F$F$-Fihm6$Fi]]lF]`\lF$F$>Fhj[
l-F]o6#-Fbgn6#Fhj[l>Fhj[l*&Fhj[lF$-F]o6#-Fcfl6%-Fcfl6%-Fcfl6%Fhj[lF^^]lF(F\^]lF
$Fe^]lF$F2>85-Ff^y6%,&F^exF$*&^#F2F$F\^]lF$F$F\^]lF^^]l@%0&Fh_]lFif[lF(C)-Fdq6$
Q>The~order~of~weakness~is~%d.|+F`ev&Fh_]lF_g[l-Fdq6$Q>The~lyapunov~constant~is
~%g.|+F`ev,$F``]lF2F_\\lFb`]lFf`]lFd\\l@%2F``]lF(C&-Fdq6#QBThe~equator~is~weakl
y~repelling.|+F`evF_\\lF]a]lFd\\lC&-Fdq6#QCThe~equator~is~weakly~attracting.|+F
`evF_\\lFaa]lFd\\l@%5/&Fh_]lF\i\lFfn/&Fh_]lF^i\lF$C&-Fdq6#QIWe~have~a~center~be
haviour~at~infinity.|+F`evF_\\lF[b]lFd\\lC&-Fdq6$QSThe~order~of~weakness~at~inf
inity~is~at~least~%d.|+F`ev,&F-F$F$F$F_\\lF_b]lFd\\lF_\\l-Fdq6#QL##############
############################|+F`evFd\\lFcb]lC%>83-F]o6#,&Ffb\lF]^]l-Ff]t6#Fbi\l
Fb^]l>84-F]o6#,&Ffb\lF]^]lF\c]lF]^]l@%-F\ilFji\lC&-Fdq6#Q;The~equator~is~repell
ing.|+F`evF_\\lFfc]lFd\\lC&-Fdq6#Q<The~equator~is~attracting.|+F`evF_\\lFjc]lFd
\\lF`evF`evF`evF&,
I)pl_chartf*6#Fbcl63F]pFhhnFjemF`hmFahmFjoFbcmFie[lFje[lF[f[lF\f[l%$f_CGF[pF\p%
#t1G%#t2G%#t3GF`evF`evC9>Fgi[lFjs>Fhj[lF[t@$30F6F$0F6F^tC%-Fes6$FbxFdt-Fdq6%Q^o
We~make~the~study~on~the~Poincare-Lyapunov~disc~of~degree~(%d,%d).|+F`evFgi[lFh
j[lFd\\l>Fag[l-Fcim6'Fhf[lFWFgnFgi[lFhj[l>Fg\\l,&*&)Fd[sFhj[lF$-Fihm6$<$/FW*&Fg
h[lF$)Fd[sFgi[lF2/Fgn*&Fc[sF$Fhe]lF2F^g[lF$F$*.Fgh[lF$Fhj[lF$Fgi[lF2F^f]lF$Fc[s
F$-Fihm6$F[f]lFgf[lF$F2>F_`\l,$**Fgh[lF$Fgi[lF2)Fd[s,&Fgi[lF$F$F$F$Fbf]lF$F2>Ff
b\l-Fbgm6%-Fihm6$/Fgh[lF$7$*&Fg\\lF$)Fd[sFag[lF$*&F_`\lF$Fag]lF$Fc[sFd[s>Fbi\l-
Fbgm6%-Fihm6$/Fgh[lF2F_g]lFc[sFd[s>Fg\\l,&*&F^f]lF$-Fihm6$<$/FW*&Fc[sF$F^f]lF2/
Fgn*&Fgh[lF$Fhe]lF2Fgf[lF$F$*.Fgh[lF$Fgi[lF$Fhj[lF2Fhe]lF$Fc[sF$-Fihm6$F^h]lF^g
[lF$F2>F_`\l,$**Fgh[lF$Fhj[lF2)Fd[s,&Fhj[lF$F$F$F$Fdh]lF$F2>F]j\lFjf]l>Fej\lFdg
]l>Fg\\l,&*()FjhnFhf]lF$Fb[rF$-Fihm6$<$/FW*&Fb[rF$)FjhnFgi[lF2/Fgn*&Fc[rF$)Fjhn
Fhj[lF2Fgf[lF$F2*()FjhnFjh]lF$Fc[rF$-Fihm6$Fci]lF^g[lF$F2>F_`\l,&**Fhj[lF$Ffi]l
F$Fc[rF$Fai]lF$F2**Fgi[lF$Fii]lF$Fb[rF$F\j]lF$F$>F][]l7$-F]hn6&*&Fg\\lF$)FjhnFa
g[lF$FjhnFb[rFc[r-F]hn6&*&F_`\lF$Fgj]lF$FjhnFb[rFc[rFj`\l-F^w6#-Fihm6$<$/Fc[sFW
/Fd[sFgnFfb\l-F^w6#-Fihm6$F_[^lFbi\l-F^w6#-Fihm6$F_[^lF]j\l-F^w6#-Fihm6$F_[^lFe
j\l-F\[r6#F][]lFd\\l@$Fid]lCD>Fg\\l-Fhho6$-Fihm6$F]]\l&Ffb\lFif[lFc[s>Fe[]lFg]
\l>F\^]lFi]\l-Fes6#F`x-Fdq6$F_[l,&-Fb[l6#Fe[]lF$-Fb[l6#F\^]lF$Fd\\l-Fdq6#QJThe~
differential~system~on~the~U1~chart:|+F`evF_\\l-Fdq6%Q]oFirst~we~study~the~syst
em~on~the~U1~chart~(x=1/z2^%d,y=z1/z2^%d).|+F`evFgi[lFhj[lF]e]l-Fdq6%Q;~~~~z1'~
=~%a|+~~~~z2'~=~%a|+F`evFg\^l&Ffb\lF_g[lFd\\l?(Fbf[lF$F$F_]^lF`oC&>F^^]l-Fg[m6$
-FR6$Fg\^lFc[s<$/Fc[s&Fe[]l6#Fbf[lF]]\l>Fhb]l-Fg[m6$-FR6$Fg\^lFd[sFd^^l>F_c]l-F
g[m6$-FR6$F\^^lFd[sFd^^l-%)type_infG6)Ffb\lF$Ff^^lF^^]lFhb]lF_c]lF(>FinF`o?(Fbf
[lF$F$Fa]^lF`oC&>F^^]l-F]o6#-Fg[m6$Fb^^l<$/Fc[s&F\^]lFg^^lF]]\l>Fhb]l-F]o6#-Fg[
m6$F[_^lF]`^l>F_c]l-F]o6#-Fg[m6$F`_^lF]`^l-Fc_^l6)Ffb\lF$F_`^lF^^]lFhb]lF_c]lF(
>FinFbp>Fg\\l-Fhho6$-Fihm6$F]]\l&Fbi\lFif[lFc[s>Fe[]lFg]\l>F\^]lFi]\lFj\^lF\]^l
Fd\\l-Fdq6#QJThe~differential~system~on~the~V1~chart:|+F`evF_\\l-Fdq6%Q\oNow~we
~study~the~system~on~the~V1~chart~(x=-1/z2^%d,y=z1/z2^%d).|+F`evFgi[lFhj[lF]e]l
-Fdq6%F[^^lFba^l&Fbi\lF_g[lFd\\l?(Fbf[lF$F$F_]^lF`oC&>F^^]l-Fg[m6$-FR6$Fba^lFc[
sFd^^l>Fhb]l-Fg[m6$-FR6$Fba^lFd[sFd^^l>F_c]l-Fg[m6$-FR6$F]b^lFd[sFd^^l-Fc_^l6)F
bi\lF^tFf^^lF^^]lFhb]lF_c]lF(>FinF`o?(Fbf[lF$F$Fa]^lF`oC&>F^^]l-Fg[m6$Fcb^lF]`^
l>Fhb]l-Fg[m6$Fhb^lF]`^l>F_c]l-Fg[m6$F]c^lF]`^l-Fc_^l6)Fbi\lF^tF_`^lF^^]lFhb]lF
_c]lF(>FinFbp@%3-Ffil6$-Fihm6$<$/Fc[sF(F]]\l&F]j\lFif[lF(-Ffil6$-Fihm6$Ffd^l&F]
j\lF_g[lF(C/Fj\^lFgb\lFd\\l-Fdq6#QJThe~differential~system~on~the~U2~chart:|+F`
evF_\\l-Fdq6%Q[oNow~we~study~the~system~on~the~U2~chart~(x=z1/z2^%d,y=1/z2^%d).
|+F`evFgi[lFhj[lF]e]l-Fdq6%F[^^lFhd^lF]e^lFd\\l>F^^]l-Fg[m6$-FR6$Fhd^lFc[sFfd^l
>Fhb]l-Fg[m6$-FR6$Fhd^lFd[sFfd^l>F_c]l-Fg[m6$-FR6$F]e^lFd[sFfd^l-Fc_^l6)F]j\lFf
nF(F^^]lFhb]lF_c]lF(C&Fj\^l-Fdq6#Q#0|+F`evFd\\l-Fdq6#QQIn~the~U2~chart,~no~extr
a~singularity~is~found.|+F`ev@%3-Ffil6$-Fihm6$Ffd^l&Fej\lFif[lF(-Ffil6$-Fihm6$F
fd^l&Fej\lF_g[lF(C/Fj\^lFgb\lFd\\l-Fdq6#QJThe~differential~system~on~the~V2~cha
rt:|+F`evF_\\l-Fdq6%Q\oNow~we~study~the~system~on~the~V2~chart~(x=z1/z2^%d,y=-1
/z2^%d).|+F`evFgi[lFhj[lF]e]l-Fdq6%F[^^lFeg^lFjg^lFd\\l>F^^]l-Fg[m6$-FR6$Feg^lF
c[sFfd^l>Fhb]l-Fg[m6$-FR6$Feg^lFd[sFfd^l>F_c]l-Fg[m6$-FR6$Fjg^lFd[sFfd^l-Fc_^l6
)Fej\lF\\rF(F^^]lFhb]lF_c]lF(C&Fj\^lFif^lFd\\l-Fdq6#QQIn~the~V2~chart,~no~extra
~singularity~is~found.|+F`evF`ev6%FjsF[tFinF`evF&,
I/find_inf_rootsf*6)FjemFbclFie[lF[f[lFWFgnF_f[l6/%$p_dG%$q_dGF`hmFahmFjoF[pF\p
%$totGF]pFbd]lFcd]lFdd]lFbcmF`evF`evCH>Fbf[l-Fgem6&&Fjf[lFif[l9(9)Fhf[l>Fag[l-F
gem6&&Fjf[lF_g[lFfj^lFgj^lFhf[l>Fgh[l-Fgem6&Fej^lFfj^lFgj^l,&Fhf[lF$F2F$>Fgi[l-
Fgem6&F[[_lFfj^lFgj^lF_[_l>Fe[]l,&-Fihm6$/Ffj^lF$Fag[lF$*&Fgj^lF$-Fihm6$Fg[_lFb
f[lF$F2>Fhj[l-Fhho6$Fe[]lFgj^l>Fg\\lF[`\l>F_`\lF]`\lFj\^l-Fdq6$F_[l,&-Fb[l6#Fg
\\lFfn-Fb[l6#F_`\lFfnFd\\l>Ffb\l,&Fc\_lF$Fe\_lF$Fc]^lF_\\l-Fdq6#QgnFirst~we~stu
dy~the~system~on~the~U1~chart~(x=1/z2,y=z1/z2):|+F`evF]e]l-Fdq6%F[^^l&F[g[lFif[
l&F[g[lF_g[lFd\\l@$F7C%F_\\l-Fdq6#Q9We~change~z1->x,~z2->y.|+F`evFd\\l?(Fbi\lF$
F$Fc\_lF`oC&>F]j\l-Fg[m6$-FRF]\_l/Fgj^l&Fg\\lF]c]l>Fej\l-Fg[m6$,&Fgi[lF$*&Fgj^l
F$Fgh[lF$F2<$Fg[_lF[^_l>F][]l,$-Fg[m6$Fbf[lFb^_lF2-Fc_^l6)F[g[lF$F\^_lF]j\lFej
\lF][]l9*>FinF`o?(Fbi\lF$F$Fe\_lF`oC&>F]j\l-F]o6#-Fg[m6$Fj]_l/Fgj^l&F_`\lF]c]l>
Fej\l-F]o6#-Fg[m6$F`^_l<$Fg[_lFb__l>F][]l-F]o6#,$-Fg[m6$Fbf[lFi__lF2-Fc_^l6)F[g
[lF$Fc__lF]j\lFej\lF][]lFi^_l>FinFbp>Fe[]l,&-Fihm6$/Fgj^lF$Fbf[lF$*&Ffj^lF$-Fih
m6$Fg`_lFag[lF$F2@%-Ffil6$-Fihm6$/Ffj^lF(Fe[]lF(>Fhj[l<#F(>Fhj[l<"Fj\^l-Fdq6$F_
[l,$-Fb[lF\_]lFfnFd\\l>Ffb\l,&Ffb\lF$Fha_lF$F_e^lF_\\l-Fdq6#QgnFirst~we~study~t
he~system~on~the~U2~chart~(x=z1/z2,y=1/z2):|+F`evF]e]l-Fdq6%F[^^l&9'Fif[l&Fab_l
F_g[lFd\\l@$F7C%F_\\lFb]_lFd\\l?(Fbi\lF$F$Fha_lF`oC&>F]j\l-Fg[m6$-FR6$Fe[]lFfj^
l/Ffj^l&Fhj[lF]c]l>Fej\l-Fg[m6$,&Fgh[lF$*&Ffj^lF$Fgi[lF$F2<$F\c_lFg`_l>F][]l,$-
Fg[m6$Fag[lFcc_lF2-Fc_^l6)Fab_lFfnF]c_lF]j\lFej\lF][]lFi^_l@$/Ffb\lF(-Fdq6#QKNo
~singular~points~at~infinity~are~found.|+F`evF`ev6#FinF`evF&,
I4find_inf_roots_singf*6$Fie[lF[f[l6&FjoF[pF\pF]pF`evF`evC?>Fbf[l-F]\q6$7$-Fihm
6$F]]\lFgf[l-Fihm6$F]]\lF^g[lFc[sFj\^l-Fdq6$F_[l,&-Fb[l6#Fae\lF$-Fb[l6#Fbe\lF$F
d\\l-Fdq6%Q^oThe~differential~system~on~the~U1~chart:|+~~~~z1'~=~%a|+~~~~z2'~=~
%a|+F`evFgf[lF^g[lF_\\l-Fdq6#Q^oFirst~we~shall~study~the~system~on~the~U1~chart
~(x=1/z2,~y=z1/z2):|+F`ev-Fdq6%F[^^lFgf[lF^g[l@$F7-Fdq6#Q9~we~change~z1->x,~z2-
>y|+F`evFd\\l>Fag[lFae\l>Fgh[lFbe\l?(Fgi[lF$F$-Fb[lFid\lF`o-F\\l6&-Fihm6%F`[^lF
a[^lFhf[l&Fag[l6#Fgi[lF(F$>FinF`o?(Fgi[lF$F$-Fb[l6#Fgh[lF`o-F\\l6&Fff_l&Fgh[lFi
f_lF(F$>FinFbp@$/,&Fcf_lF$F\g_lF$F(C%F]e]l-Fdq6#QKNo~singular~points~found~in~t
he~U1~chart.|+F`evFd\\l@%3-Ffil6$-Fihm6%Fgd^lF]]\lFej^lF(-Ffil6$-Fihm6%Fgd^lF]]
\lF[[_lF(>Fbf[l7#F(>Fbf[l7"Fj\^l-Fdq6$F_[l-Fb[lFg^^lFd\\l-Fdq6%Q^oThe~different
ial~system~on~the~U2~chart:|+~~~~z1'~=~%a|+~~~~z2'~=~%a|+F`evFej^lF[[_lF_\\l-Fd
q6#QfnNow~we~study~the~system~on~the~U2~chart~(x=z1/z2,~y=1/z2):|+F`ev-Fdq6%F[^
^lFej^lF[[_l@$F7F]f_lFd\\l?(Fgi[lF$F$Fih_lF`o-F\\l6&-Fihm6%F`[^lFa[^lFjf[l&Fbf[
lFif_lF(Ffn@$/Fih_lF(C%F]e]l-Fdq6#QKNo~singular~points~found~in~the~U2~chart.|+
F`evFd\\lF`evF_d_lF`evF&,
I+saddle_inff*6)FbclFf\rF/FadtF]hlFbdtF_f[l6)FhhnFghnFjoFbcmFdgtFd\rFe\rF`evF`e
vC4>Fbf[l*&Ffj^lF$,&Fgj^lF$Fab_lF2F2>Fag[l-Fb^t6'-Fihm6$F_[^lFhf[lFWFgnF[g[lF(>
Fgh[l-F]`t6'Fag[lFbf[lF$F$F(>Fgi[l-F]dtF]g_l>Fgi[l-Fbgm6%Fgi[lFWFgn@%F7F]e]lFd
\\l-Fdq6#F]hv-Fdq6$Q=The~new~vector~field~is~%a.|+Fe`rFag[l-Fdq6#F[iv-Fdq6$Fi[`
lFgh[l-Fdq6$QenMake~a~1000~normalization.|+So~the~new~vector~field~is~%a.|+F`ev
Fgi[lFd\\l-Fdq6#QJWe~calculate~the~invariant~separatrices.|+F`ev@%-Figl6$Fgj^lF
(C$>Fhj[lF$>F_`\lF2C$>Fhj[lF(>F_`\lF$>Fg\\l-Fagt6%Fgi[lF)Fhj[l@%/Fhj[lF$C&@$F7F
]e]l-Fdq6$F`[w7$Fd_rFg\\l-Fdq6$Fd[w7$F(Fd_rFd\\lC&@$F7F]e]l-Fdq6$Fd[wFf]`l-Fdq6
$F`[wFi]`lFd\\l-Fa\r6,F[g[lF(Fbf[lF$F$F(Fgi[l7#Fg\\l7#F_`\lFjf[l@$3/FjsF$/F[tF$
C$@%Fa]`l@$0Fi^_lF(>F_`\lF$@$F[_`l>F_`\lF2@%/Fjf[lF$-Fa\r6,F[g[lF(,$Fbf[lF2F$F2
F(Fgi[l7#-Fihm6$/Fd_r,$Fd_rF2Fg\\lFc^`lF^t-Fa\r6,F[g[lF(Fc_`lF$F2F(Fgi[lFd_`lFc
^`lF\\rF`evF`evF`evF&,
I'se_inff*Faj_l6.FbcmFhhnFghnFjoFdaoFcdtFdcuFe\rFdcwFd\r%#hhGFdgtF`evF`evC:>Fag
[lFej_l>Fgh[lFhj_l>Fgi[l-F]`t6'Fgh[lFag[lF$F$F(>Fbf[l-F]dtFif_l>Fbf[l-Fbgm6%Fbf
[lFWFgnF]e]l-Fdq6%QOThe~point~(%a,%a)~is~a~semi~hyperbolic~point.|+F`evF[g[lF(@
%F7F]e]lFd\\l-Fdq6#FgewF\\`lFj[`l-Fdq6$Fi[`lFgi[l-Fdq6$F`\`lFbf[lFd\\lFa\`l@%-F
fil6$Fab_lF(C*@%Fe\`l>F][]lF$>F][]lF(>F]j\l-Fagt6%Fbf[lF)F][]l>Fhj[l-Fihm6$<$/F
c[s,&FWF$F$F$F]]\lFgf[l>Fhj[l-Fdjl6$Fhj[lFW>Fhj[l-FfamFfb`l>Fg\\l-FiflFfb`l>F_`
\l-Fg\w6#-F]o6#-Fihm6$/FWF$Fhj[l@%-Fecl6$Fg\\lF]hu@%2F(F_`\l@%/F][]lF(>Ffb\l7$F
$F(>Ffb\l7$FfnF(@%Fic`l>Ffb\l7$F^tF(>Ffb\l7$F\\rF(@%Fgc`l@%Fic`l>Ffb\l7$F.F(>Ff
b\l7$FhcrF(@%Fic`l>Ffb\l7$FicrF(>Ffb\l7$F_iuF(C&@%-FiglFfa`l>F][]lF$>F][]lF(>Fb
i\l-FacuF]b`l>F]j\l-Fihm6$/FWFd_rFba^l>Ffb\l7$&Fbi\lF\i\lF$F]e]l@$-F[x6$Fg\^l<&
F$FfnF^tF\\r-Fdq6#Q=The~point~is~a~saddle-node.|+F`ev@$/Fg\^lF.-Fdq6#Q@The~poin
t~is~an~unstable~node.|+F`ev@$/Fg\^lF_iu-Fdq6#Q>The~point~is~a~~stable~node.|+F
`ev@$-F[x6$Fg\^l<$FhcrFicr-Fdq6#Q8The~point~is~a~saddle.|+F`evFd\\l-Febr6,F[g[l
F(Fag[lF$F$F(Fbf[lFfb\l7#F]j\lFjf[l@$Fe^`lC%@%/Fi^_lF(>Ffb\l7$-F_\l6$Fg\^l7*F^t
F\\rF$FfnF.FhcrFicrF_iuF\^^l>Ffb\l7$-F_\l6$Fg\^l7*FfnF$F\\rF^tF_iuFicrFhcrF.F\^
^l>Fej\l7$-Fg[m6#*&)F2Fi^_lF$Fae\lF$-Fg[m6#*&Fjh`lF$Fbe\lF$@%F`_`l-Febr6,F[g[lF
(Fag[lF$F$F(Fej\lFfb\lFfg`lF^t-Febr6,F[g[lF(Fag[lF$F$F(Fej\lFfb\lFfg`lF\\rF`evF
`evF`evF&,
I,change_stabf*6#Fd\r6(F]pF^jrFhjlF\hlF]hlFhhnF`evF`evC%>Fag[lFfh_l?(Fbf[lF$F$F
bd\lF`oC&>Fgi[lFfh_l>Fhj[l&Fhf[lFg^^l?(Fgh[lF$F$Fha_lF`o@%0Fgh[lFhcr>Fgi[l7$-F_
\lFif_l-F_\l6$Fgh[lFhj[lC%>Fg\\lFdj`l@%-F[x6$Fg\\l<&F$F^tFbfrF*>Fg\\lFfn@%-F[x6
$Fg\\l<&FfnF\\r"#6"#7>Fg\\lF$@%-F[x6$Fg\\l<$F.Ficr>Fg\\lFhcr>Fg\\lF.>Fgi[l7$Fcj
`lFg\\l>Fag[l7$-F_\lFid\lFgi[lFag[lF`evF`evF`evF&,
I'de_inff*6&FbclFf\rF/F_f[l6#F^jrF`evF`evC'-Fdq6%QMThe~point~(%a,%a)~is~a~nonel
ementary~point.|+F`evF[g[lF(-Fdq6#Q>Blowing~up~the~vector~field.|+F`ev>Fbf[l-F
\cw6&Fjj_lF[g[lF(F8-F[jr6&F[g[lF(Fae\lFjf[l@$Fe^`lC%-Fdq6$Q,Degree=%d.|+F`evFab
_l@%/Fab_lF(>Fbf[lFbe\l>Fbf[l-Fci`lFce_l@%F`_`l-F[jr6&F[g[lF(Fbf[lF^t-F[jr6&F[g
[lF(Fbf[lF\\rF`evF`evF`evF&,
I)type_inff*Faj_l6&FgjlFjavF[bvF\bvF`evF`ev@%3Fea`l-FfilFf\`lC&F]e]l-Fdq6%Q;(%a
,%a)~is~nonelementary.|+F`evF[g[lF(Fd\\l-F_\al6&Fhf[lFjf[lF[g[lFi^_l@%5Fea`lFc^
al-F[``l6)Fhf[lFjf[lF[g[lFab_lFfj^lFgj^lFi^_l@%-Figl6$*&Fab_lF$Fgj^lF$F(C(F]e]l
-Fdq6%Q6(%a,%a)~is~a~saddle.|+F`evF[g[lF(@%2-F^jl6#-F]o6#Fgj^l-F^jl6#-F]o6#Fab_
l>Fag[l*&Fab_lF$Fgj^lF2>Fag[l*&Fgj^lF$Fab_lF2@%334Fin-Fecl6$Fab_lFddv-Fecl6$Fgj
^lFddvC)>Fgh[l-FdelFid\l>Fgi[l-FielFid\lFd\\l-Fdq6%F_evFgi[lFgh[lF_\\lFaaalFd\\
lC+>Fag[l-F`[m6$-F]oFid\lFb[m>Fag[lFeaal>Fgh[lF^aal>Fgi[lF`aalFd\\l-Fdq6%F[fvFg
i[lFgh[lF_\\lF[balFd\\lFd\\l-F_j_lF]_alC(>Fbf[l-Fg\wFi_al@%2F(Fbf[lC%F]e]l-Fdq6
%Fg_wF[g[lF(Fd\\lC%F]e]l-Fdq6%F`_wF[g[lF(Fd\\l@%Fg_al>Fag[lFa`al>Fag[lFc`al@%Fe
`alC)>Fgh[lF^aal>Fgi[lF`aalFd\\lFaaalF_\\lFaaalFd\\lC+>Fag[lFeaal>Fag[lFeaal>Fg
h[lF^aal>Fgi[lF`aalFd\\lF[balF_\\lF[balFd\\l-F[ar6&F[g[lF(Fbf[lFjf[l@$Fe^`lC$@$
F[_`l>Fbf[lFc_`l@%F`_`l-F[arF[^al-F[arF]^alF`evF`evF`evF&,
I-assoc_pointsf*6#FG6&%#LfG%#LgGFIFd\yFe`rFe`rC'>8$-F]cq6%-F]o6#&9$6#F$FWFgn>Ff
dal-F[]m6$f*6#FIFe`r6$F_hlF`hlFe`r7$,&F[ealF$F2F$&F\eal6#FfnFe`rFe`rFe`rFfdal>8
%-F]cq6%-F]o6#FfealFWFgn>Fieal-F[]m6$f*FbealFe`rFcealFe`r7$F[eal,&FfealF$F2F$Fe
`rFe`rFe`rFieal-F`[m6$<$-F_\l6#Ffdal-F_\l6#FiealFh\pFe`rFe`rFe`rF&,
I/newton_diagramf*F`dal6-%'pointsG%#pkG%#pjG%#pLGFhjlF]pFgjl%%hsetG%"NGFd\yF`hm
Fe`rFe`rC'>8+-F^dal6#F\eal>FfdalFfgal>8,-Fb[lFhfal?(8(F$F$,&F[halF$F2F$F`oC$>Fi
eal&Ffdal6#F^hal@$-F[x6$FiealFfgal?(8),&F^halF$F$F$F$F[halF`oC$>8&&Ffdal6#Fhhal
@$-F[x6$F\ialFfgal@%31&FiealF]eal&F\ialF]eal1&FiealFgeal&F\ialFgeal>Ffgal-%'rem
oveG6$f*6#F`hmFe`rFcealFe`r/F\ealT#Fe`rFe`r6$F`galF\ialFfgal?(8*F$F$F[halF`oC$>
8'&Ffdal6#Fdjal@$33-F[x6$FgjalFfgal0FdjalF^hal0FdjalFhhal@%531Feial&FgjalF]eal1
Fhial&FgjalFgeal31FfialFe[bl1FiialFg[bl>Ffgal-F\jal6$f*F_jalFe`rFcealFe`rF`jalF
e`rFe`r6$FagalFgjalFfgal@$532FeialFe[bl2Fe[blFfial32FfialFe[bl2Fe[blFeialC$>8-*
&,&FiialF$FhialF2F$,&FfialF$FeialF2F2@$1,&*&Fj\blF$,&Fe[blF$FfialF2F$F$FiialF$F
g[bl>Ffgal-F\jal6$f*F_jalFe`rFcealFe`rF`jalFe`rFe`rF_\blFfgalFfgalFe`rFe`rFe`rF
&,
I(GAMMA_1f*6#F\\n6)FgjlF`hmFahmFjhnFhjl%#skG%"GGFe`rFe`rC(>Ffdal-Fb[lFhgal>Fiea
lF[eal>F\ialFfeal@$1FfialFeialC$>FiealFfeal>F\ialF[eal@%/FfdalFfn>Fdjal7$FiealF
\ialC&>Fgjal&F\eal6#F^t@%Fg\blC%>FgjalF\ial>F\ialFieal>FiealF]_bl@$Fd\blC$>Fgja
lF\ial>F\ialF]_bl?(F^halF\\rF$FfdalF`oC$>Fhhal&F\ealFchal@%2&FhhalF]ealFeialC%>
FgjalF\ial>F\ialFieal>FiealFhhal@%2F^`blFfialC$>FgjalF\ial>F\ialFhhal@$2F^`blFe
[bl>FgjalFhhal@%2F(Ffial>FdjalFj^bl>Fdjal7$F\ialFgjalFdjalFe`rFe`rFe`rF&,
I-quasi_degreef*Fi]bl6&Fbcm%&alphaG%%betaGFjemFe`rFe`rC'>Ffdal,$*&,&-F_\l6$FfnF
fealF$-F_\l6$FfnF[ealF2F$,&-F_\l6$F$FfealF$-F_\l6$F$F[ealF2F2F2>Fieal-FdelFhfal
>F\ial-FielFhfal>Fgjal,&*&FiealF$FabblF$F$*&F\ialF$F\bblF$F$7%FiealF\ialFgjalFe
`rFe`rFe`rF&,
I-center_type1f*6&FbclFWFgjlF^`x6&F\\nFjoFcdtF]hlFe`rFe`rC'>Fieal-Ffam6$F\eal9%
>F\ial-Fb\m6$F(-Fifl6$FiealFdcbl>Fgjal-Fg\w6#-F]o6#-Fihm6$/FdcblF$Fieal@%-Fecl6
$F\ialF]hu>Ffdal7%FgjalF$-Fg\w6#-F]o6#9&>Ffdal7%FgjalF2Fgdbl@%/9'F$C*@$/Ffdal7%
F2F$F$OF*@$/Ffdal7%F$F$F$OFbfr@$/Ffdal7%F$F2F$OF^t@$/Ffdal7%F2F2F$OF$@$/Ffdal7%
F2F$F2OFb[al@$/Ffdal7%F$F$F2OFa[al@$/Ffdal7%F$F2F2OFfnOF\\rC*@$FceblOFbfr@$Fgeb
lOF*@$F[fblOF^t@$F_fblOF$@$FcfblOFa[al@$FgfblOFb[al@$F[gblOFfnOF\\rFe`rFe`rFe`r
F&,
I-center_type2f*F^cblF_cblFe`rFe`rC'>FiealFbcbl>F\ialFfcbl>FgjalF[dbl@%Fcdbl>Ff
dalFfdbl>FfdalF]ebl@%F_eblC*@$FceblOFbfr@$FgeblOF*@$F[fblOF^t@$F_fblOF$@$FcfblO
Fa[al@$FgfblOFb[al@$F[gblOFfnOF\\rC*@$FceblOF*@$FgeblOFbfr@$F[fblOF^t@$F_fblOF$
@$FcfblOFb[al@$FgfblOFa[al@$F[gblOFfnOF\\rFe`rFe`rFe`rF&,
I&powerf*6$F\hlF]hlFe`rFe`rFe`r@%/FdcblF(F$)F\ealFdcblFe`rFe`rFe`rF&,
I-sort_set_posf*6%F\\nF0Fjhn6%F\hlFhjlFgjlFe`rFe`rC'>Ffdal7#-F_fl6#;F$,&F_^blF$
F$F$>FiealF$?(F\ialF$F$F_^blF`oC%@$3-Figl6$Fdcbl-F_\l6$F$&F\eal6#F\ial/FiealF\i
alC$>&FfdalFjfal7$FdcblF[ebl>Fieal,&FiealF$F$F$>Fh\clFc\cl>FiealF[]cl@$Fe\cl>Fh
\clFi\clFfdalFe`rFe`rFe`rF&,
I-sort_set_negf*Fa[clFb[clFe`rFe`rC'>FfdalFe[cl>FiealF$?(F\ialF$F$F_^blF`oC%@$3
-F\ilF`\clFe\clC$>Fh\clFi\cl>FiealF[]cl>Fh\clFc\cl>FiealF[]cl@$Fe\cl>Fh\clFi\cl
FfdalFe`rFe`rFe`rF&,
I0put_separatricef*6)%%xposGFe\r%0transformationsG%#ptGFcer%*vec_fieldGFd\r6#%)
newentryGFe`rFe`rC$>Ffdal7)F[eblF`ebl9(9)9*FdcblFin@%/F\ealF$C$>%(NumXPosG,&Fd_
clF$F$F$>%(ManXPosG7$-F_\l6#Fg_clFfdalC$>%(NumXNegG,&F]`clF$F$F$>%(ManXNegG7$-F
_\l6#F``clFfdalFe`r6&Fd_clF]`clFg_clF``clFe`rF&,
I2append_trajectorsf*Fe`r6%%%man1G%%man2GF]pFe`rFe`rC,-%&printG6$Q+ManYNeg~=~Fe
`r%(ManYNegG-F\acl6$Q+ManYPos~=~Fe`r%(ManYPosG-F\acl6$Q+ManXNeg~=~Fe`rF``cl-F\a
cl6$Q+ManXPos~=~Fe`rFg_cl>Ffdal7"@$0%(NumberYGF(C$>Fieal-%4make_transformationG
6#F_acl>Ffdal7$Fgfal7$-F_\lFcbclFieal?(F\ialF$F$Fd_clF`oC$>Fieal-Fbbcl6#&Fg_clF
d\cl>Ffdal7$Fgfal7$-F_\lF\cclFieal@$F]bclC$>Fieal-Fbbcl6#Fcacl>Ffdal7$Fgfal7$-F
_\lFfcclFieal?(F\ialF$F$F]`clF`oC$>Fieal-Fbbcl6#&F``clFd\cl>Ffdal7$Fgfal7$-F_\l
F_dclFiealFfdalFe`rFe`rFe`rF&,
I1split_trajectorsf*6#Fd\r6'%(sep_posG%(sep_negGF]pF\\nFjoFe`rFe`rC&>FfdalF[bcl
>FiealF[bcl?(F\ialF$F$F_^blF`oC$>Fgjal-F_\l6$F_iuFc\cl@$0Fg[blF(C$>F^hal-Fg\w6#
-F]o6#-Fihm6$/Fd_rF$-Ffam6$-FR6$Fg[blFd_rFd_r@%2F(F^hal>Ffdal7$FgfalFc\cl>Fieal
7$FifalFc\cl7$FfdalFiealFe`rFe`rFe`rF&,
I4make_transformationf*Fgdcl6,Fgjl%%histGFf^clFcerF\\nF/F0%#x1G%#y1GF\hlFe`rFe`
rC+>FiealF[eal>F\ialFfeal>FgjalF]_bl>F^hal&F\eal6#F.>Fhhal,(FfialF$*&Fe[blF$Fd_
rF$F$*&Fg[blF$F^halF$F$>Fdjal,(FiialF$*&&FgjalF^_blF$Fd_rF$F$*&&Fgjal6#F\\rF$F^
halF$F$>Ffdal-Fb[lFjfal?(Fe`rF$F$Fe`r2F(FfdalC(>Fj\bl&FiealFhfal>Ffgal,&&Fj\blF
]ealF$*(&Fj\blF^_blF$-Fijbl6$Fhhal&Fj\blFegclF$-Fijbl6$Fdjal&Fj\bl6#FhcrF$F$>F[
hal,&&Fj\blFgealF$*(&Fj\blF`hclF$-Fijbl6$Fhhal&Fj\bl6#FicrF$-Fijbl6$Fdjal&Fj\bl
6#F_iuF$F$>Fhhal-Fdjl6$FfgalFd_r>Fdjal-Fdjl6$F[halFd_r@%3/FhhalF(/FdjalF(>Ffdal
F(>Ffdal,&FfdalF$F2F$7$FhhalFdjalFe`rFe`rFe`rF&,
I1write_trajectorsf*6%Fd\rF/F06/Fgjl%#w1GFdaoFeaoF]p%#elG%$hypG%#w2G%$dl1G%$dl2
G%$dl3G%$dl4G%$dl5GFe`rFe`rC9>FfdalF_^bl>FhhalF(>FdjalF(>F[halFfey>Fj\blQ"~Fe`r
>8.Ffey>8/Ffey>80Ffey@$0FfdalF(C1-Fes6$FbxFdt-Fdq6#QI|+|+The~invariant~separatr
ices~are:~(t>0)|+Fe`r-Fes6#Fdt>Fieal<*F$F^tF.FicrFbfrF*"#8"#9>Ffgal<*FfnF\\rFhc
rF_iuFa[alFb[alFadl"#;>F\ial-F_\l6$FhcrF[eal-Fdq6#-%(sprintfG6$Q&~[%d]Fe`rF\ial
@%-F[x6$F\ialFiealC(F\]dl-Fdq6$Q5[01]:~%a~:~unstable|+Fe`r-F_\l6$F_iuF[ealFa]dl
>F[hal-Ff`x6$F[halQ)~~~|gr~~~~Fe`r>Fj\bl-Ff`x6$Fj\blQ&~~^~~Fe`r>Fd\dl-Ff`x6$Fd
\dlF__dlC(F\]dl-Fdq6$Q3[01]:~%a~:~stable|+Fe`rFj^dlFa]dl>F[halF]_dl>Fj\bl-Ff`x6
$Fj\blQ&~~v~~Fe`r>Fd\dlFe_dl@%-F[x6$F\ial<)FfnF^tF.FhcrF*Fb[alFe]dl>Ff\dl-Ff`x6
$Ff\dlQ%-<-*Fe`r@%-F[x6$F\ial<)F$F\\rFicrF_iuFbfrFa[alFadl>Ff\dl-Ff`x6$Ff\dlQ%-
>-*Fe`r>Ff\dl-Ff`x6$Ff\dlQ%****Fe`r@%-F[x6$F\ial<)F$F\\rFicrF_iuF*Fb[alFi]dl>Ff
\dl-Ff`x6$Ff\dlQ%-<-~Fe`r@%-F[x6$F\ial<)FfnF^tF.FhcrFbfrFa[alFf]dl>Ff\dl-Ff`x6$
Ff\dlQ%->-~Fe`r>Ff\dl-Ff`x6$Ff\dlQ%***~Fe`r>Fh\dl-Ff`x6$Fh\dl-F`^dl6$Q+~~%02d~~
~~Fe`rF$?(F^halFfnF$FfdalF`oC*>Fgjal-F_\l6$FhcrF[`bl@%53-F[x6$F\ial<%F$FicrF*-F
[x6$Fgjal<%FfnFhcrFb[al3-F[x6$F\ial<%FfnFhcrFa[al-F[x6$Fgjal<%F$FicrFbfrC'F\]dl
-Fdq6#Q3hyperbolic~sector|+Fe`rFa]dl>Fdjal,&FdjalF$F$F$>Fj\bl-Ff`x6$Fj\blQ$HYPF
e`r@%53-F[x6$F\ial<&F^tF.FbfrFf]dl-F[x6$Fgjal<&F\\rF_iuFa[alFadl3-F[x6$F\ial<&F
\\rF_iuFb[alFi]dl-F[x6$Fgjal<&F^tF.F*Fe]dlC'F\]dl-Fdq6#Q1elliptic~sector|+Fe`rF
a]dl>Fhhal,&FhhalF$F$F$>Fj\bl-Ff`x6$Fj\blQ$ELLFe`rC&F\]dl-Fdq6#Q2parabolic~sect
or|+Fe`rFa]dl>Fj\bl-Ff`x6$Fj\blQ$PARFe`r>F\ialFgjalF]^dl@%Fd^dlC(F\]dl-Fdq6%Q7[
%02d]:~%a~:~unstable|+Fe`rF^hal-F_\l6$F_iuF[`blFa]dl>F[halF]_dl>Fj\blFa_dl>Fd\d
lFe_dlC(F\]dl-Fdq6%Q5[%02d]:~%a~:~stable|+Fe`rF^halFfgdlFa]dl>F[halF]_dl>Fj\blF
]`dl>Fd\dlFe_dl@%Fb`dl>Ff\dlFf`dl@%Fj`dl>Ff\dlF^adl>Ff\dlFbadl@%Ffadl>Ff\dlFjad
l@%F^bdl>Ff\dlFbbdl>Ff\dlFfbdl>Fh\dl-Ff`x6$Fh\dl-F`^dl6$F^cdlF^hal>F\ial-F_\l6$
Fhcr&F\ealFhfal>FgjalF[^dl@%FecdlC'F\]dlFeddlFa]dl>FdjalFiddl>Fj\blF[edl@%53-F[
x6$F\ial<%F^tF.Fbfr-F[x6$Fgjal<%F\\rF_iuFa[al3-F[x6$F\ial<%F\\rF_iuFb[al-F[x6$F
gjal<%F^tF.F*C'F\]dlF_fdlFa]dl>FhhalFcfdl>Fj\blFefdlC&F\]dlFifdlFa]dl>Fj\blF]gd
lF\]dl-Fdq6&QFThe~singularity~(%a,%a)~has~index~%a|+Fe`rFdcblF[ebl,(F$F$Fhhal#F
$FfnFdjal#F2Ffn-Fdq6#QKSector~representation~(counterclockwise):|+Fe`r-Fdq6#F[h
al-Fdq6#Fd`r-Fdq6#Fj\blFj[el-Fdq6#Fd\dlFj[el-Fdq6#Ff\dlFj[el-Fdq6#Fh\dl-Fdq6#Q#
|+|+Fe`rFa]dlFe`rFe`rFe`rF&,
I1manifold_blow_upf*6$FdhnF^gl6*FhavFiavFjoFbclF\hl%$dfxGFhjlFbcmFe`rFe`rC*>F\i
al-Fbgm6%F\ealFWFgn>Ffdal-Fcfl6%-Fcfl6%FfialFWF$FgnF(>Fieal-Fcfl6%-Fcfl6%FiialF
gnF$FWF(>Fgjal-F]^m6$*&&F^halFijalF$)FWFdjalF$/Fdjal;FfnFdcbl>Fhhal-F]^m6$*(Fdj
alF$F^^elF$)FW,&FdjalF$F2F$F$F`^el>Ffgal-Fbgn6#,&-Fihm6$/FgnFgjal,&FiialF$*&Fie
alF$FgnF$F2F$*&FhhalF$-Fihm6$F^_el,&FfialF$*&FfdalF$FWF$F2F$F2?(FdjalFfnF$Fdcbl
F`oC$>Ffgal-Fg[m6$Ffgal/F^^el*&-Fcfl6%FfgalFWFdjalF$,&*&FfdalF$FdjalF$F$FiealF2
F2>Fgjal-Fg[m6$FgjalF[`elO-Fihm6$/FWFd_rFgjalFe`rFe`rFe`rF&,
I2manifold2_blow_upf*6$FjoF^gl6+FadtFbdtFbclF[]elFhjlFcesFbcmF\hlF[htFe`rFe`rC+
>Ffdal-Fcfl6%-Fcfl6%F[ealFWF$FgnF(>Fieal-Fcfl6%-Fcfl6%FfealFgnF$FWF(>F\ial-F]^m
6$*&&FfgalFchalF$)FWF^halF$/F^halFa^el>Fgjal-F]^m6$*(F^halF$F[belF$)FW,&F^halF$
F2F$F$F]bel>Fdjal,&-Fihm6$/FgnF\ial,&FfealF$F`_elF2F$*&FgjalF$-Fihm6$Fhbel,&F[e
alF$Fe_elF2F$F2>F^halFfn>F[halFdcbl?(Fe`rF$F$Fe`r2F^hal,&FdcblF$F$F$@%-F_jl6$,&
*&F^halF$FfdalF$F$FiealF2F(C%>Fdjal-Fg[m6$Fdjal/F[bel*&-Fcfl6%FdjalFWF^halF$Ffc
elF2>F\ial-Fg[m6$F\ialF\del>F^halFihalC$>F[halFcbel>F^halFbcel-F]^m6$*&-Fcfl6%F
\ialFWFhhalF$)Fd_rFhhalF$/Fhhal;FfnF[halFe`rFe`rFe`rF&,
I8center_manifold_blow_upf*Fj`el61FfgtFggtFhgtFigtFhjlFbdtFd\rFdhmFjgtFfaoF[htF
acqF]hlFcdtFdcuFe`rFe`rC)@%FinC$>FfdalFidal>FiealF\falC$>FfdalF[eal>FiealFfeal>
Fhhal-Fcfl6%-F\it6$-Fihm6$/FWF(FfealFgnFgnF$>FdjalF(>Fd\dlFdcbl?(F^halFfnF$Fd\d
lF`oC+>F[hal,$*&-Fcfl6%-F\it6$-Fihm6$/FgnF(FiealFWFWF^halF$FhhalF2F2@$34FinFh\m
>F[hal-F]]mFi[el>F\ial-Fbgn6#-Fihm6$/Fgn,&FfgalF$*&F[halF$F\belF$F$Ffdal>Fgjal-
Fbgn6#,&-Fihm6$FjgelFiealF$**F[halF$F^halF$FbbelF$F\ialF$F2>Ffdal-Fihm6$/FfgalF
gnF\ial>Fieal-Fihm6$FghelFgjal>Fdjal,&FdjalF$F\helF$>Ff\dl-Fdjl6$-Fihm6$F_gelFf
dalFW@$/Ff\dlF(>Fd\dl,&Fd\dlF$F$F$>Ff\dlF^iel7%FdjalFf\dl-Ffam6$Ff\dlFWFe`rFe`r
Fe`rF&,
I+blowing_upf*6&FGF/F0%-finite_pointG6)FjhnFggt%$n_dGFfdl%)q_degreeGFijlF^jrFe`
rFe`rCV@$F7F\]dl-Fdq6&QAblowing~up~%a~in~point~(%a,%a).|+Fe`rF\ealFdcblF[eblFa]
dl@%50FdcblF(0F[eblF(C'>Fieal-Fbgm6%-Fb^t6'F\ealFWFgnFdcblF[eblFWFgn@$F7F\]dl-F
dq6%Q?moving~(%a,%a)~to~the~origin.|+Fe`rFdcblF[ebl-Fdq6$Q6new~vector~field:~%a
|+Fe`rFiealFa]dl>FiealF^]el>F\ial-F[galFjfal>Fgjal-Fg]blFd\cl>F^hal-F`abl6#Fgja
l@$F7F\]dl-Fdq6$Q4Newton~diagram:~%a|+Fe`rF\ial-Fdq6$Q)g1~=~%a|+Fe`rFgjal-Fdq6$
Q:[alpha,beta,degree]~=~%a|+Fe`rF^halFj[el-Fdq6#QK1.~Blowing~up~in~the~positive
~x-direction|+Fe`r-Fdq6#QK-----------------------------------------|+Fe`rFj[el-
Fdq6#Q4blowing~up~level~1|+Fe`r-Fdq6#Q4------------------|+Fe`r-Fdq6$Q>blowing~
up~%a~in~point~(0,0)|+Fe`rFiealFa]dl>Fhhal-%)blow_upxG6'FiealF^halF$FWFgn@$F7F
\]dl-Fdq6$Q;blowing~up~vectorfield~%a|+Fe`rF^`blFa]dl-%,sing_eigenvG6'FhhalF$F$
7#7+FdcblF[eblF$F$&F^halF]ealF(&F^halFgealF$&F^halF^_blF$@$F7F\]dl-Fdq6#Qen----
-----------------------------------------------------|+Fe`rFj[el-Fdq6#QK2.~Blow
ing~up~in~the~negative~x-direction|+Fe`rF\]flFj[elFj[elF_]flFb]flFe]flFa]dl>Fhh
al-Fj]fl6'FiealF^halF2FWFgn@$F7F\]dlF]^flFa]dl-Fa^fl6'FhhalF2F$7#7+FdcblF[eblF2
F$Fe^flF(Ff^flF$Fg^flF2@$32F2-F_\l6$F$Fe[bl0&FhhalF^_blF(C.@$F7F\]dl-Fdq6#QK3.~
Blowing~up~in~the~positive~y-direction|+Fe`rF\]flFa]dl>Fcacl-%)blow_upyG6&Fieal
F^halF$7#7+FdcblF[eblF$F$F$Fe^flF(Ff^flFg^fl>F^bclF$@$F7F\]dlFj[el-Fdq6#QK4.~Bl
owing~up~in~the~negative~y-direction|+Fe`rF\]flFa]dl>F_acl-Fe`fl6&FiealF^halF27
#7+FdcblF[eblF$F2F$Fe^flF(Ff^flFg^fl>Fdjal-Fe`clFe`r-F_[dl6%FdjalFdcblF[ebl@$4F
`ebl>Fdjal-FedclFijal>Fd_clF(>F]`clF(>F^bclF(>Fg_clF[bcl>F``clF[bcl>FcaclF[bcl>
F_aclF[bclFdjalFe`r6)Fg_clF``clFcaclF_aclFd_clF]`clF^bclFe`rF&,
I)blow_upxf*6'FGFahmF^`xFWFgn6/FcablFdablFjem%#vxG%#vyG%#pgG%#qgG%#tgGFbclFjoFj
hnF\\nFb[xFe`rFe`rC/>Ffdal&FdcblF]eal>Fieal&FdcblFgeal>F\ial&FdcblF^_bl>FgjalF(
>F^halF(>FhhalF(>FdjalF(>FfgalF(>F[hal-Fi^m6%F[ealF`eblF]_cl?(Fe`rF$F$Fe`r0F[ha
lF(C*>Fj\bl-F_cm6%F[halF`eblF]_cl>Fd\dl,&-Fb\m6$F(-Fifl6$Fj\blF`eblF$F2F$>Ff\dl
-Fb\m6$F(-Fifl6$Fj\blF]_cl>Fh\dl,&*&FfdalF$Fd\dlF$F$*&FiealF$Ff\dlF$F$>Fgjal,&F
gjalF$*(F[eblF$-Fihm6$/F`eblF[eblFj\blF$)F`ebl,(Fh\dlF$F$F$F\ialF2F$F$>F^hal,&F
^halF$*,F[eblF$)F`ebl,&Fh\dlF$F\ialF2F$FiealF$F]_clF$FceflF$F2@$/Fh\dlF\ialC$>F
hhal,&FhhalF$*&F[eblF$FceflF$F$>Ffgal,&FfgalF$**F[eblF$FiealF$F]_clF$FceflF$F2>
F[hal-Fi^m6%,&F[halF$Fj\blF2F`eblF]_cl>F[hal-Fi^m6%FfealF`eblF]_cl?(Fe`rF$F$Fe`
rF\dflC)>Fj\blF_dfl>Fd\dlFcdfl>Ff\dl,&FhdflF$F2F$>Fh\dlF]efl>F^hal,&F^halF$*(Ff
dalF$F[fflF$FceflF$F$@$F^fflC$>Fdjal,&FdjalF$FceflF$>Ffgal,&FfgalF$*&FfdalF$Fce
flF$F$>F[halFgffl7%7$FgjalF^halF^[dlFfgalFe`rFe`rFe`rF&,
I)blow_upyf*6&Fg^clF`jel%*directionGFe^cl6*FijlFggtFhavFiav%$vecGFjo%$manGFd\rF
e`rFe`rC->Fieal-F]`t6'F\ealF(F$F$F(>Ffdal-Fj]fl6'Fieal7%F`cflF^cflFbcflF[eblFWF
gn>Fieal-F]`t6'&FfdalF]ealF(F$F$F(@$F7F\]dl-Fdq6$Q<blowing~up~vector~field~%a|+
Fe`rFieal>F\ial-Fihm6$F_gel-F_\l6$F$&FfdalFgeal>Fgjal-Fihm6$F_gel-FR6$&FfdalF^_
blFgn-Fdq6%QT(0,0)~is~a~singular~point~with~eigenvalues~%a,~%a.|+Fe`rFgjalF\ial
Fa]dl@%55-Ffil6$F\ialF(-Ffil6$FgjalF(-Fail6$F(*&F\ialF$FgjalF$C)>F^hal*&-Fihm6%
FafelF_gel-FR6$-F_\l6$FfnFciflFWF$,&F\ialF$FgjalF2F2>Fhhal-F]`t6'FciflF$F(F^hal
F$@$F7F\]dl-Fdq6#Q[oTransform~this~vector~field~so~that~the~linear~part~is~diag
onal|+Fe`r-Fdq6$Fi[`l-F]`t6'FhhalF(F$F$F(Fa]dl@%-F\ilF[[glC'>Ffgal-Fg\el6$Fhhal
F)@$F7F\]dl-Fdq6$Q:unstable~separatrice~x=%aFe`r-Fihm6$/Fd_rFgnFfgalFa]dl@%-F_j
lF][gl>Fdjal7)F`ebl7$F(F(7&F^halF$F$F(FhhalFfgalF$Fin>Fdjal7)F`eblFg]glFh]glFhh
alFfgal-F_hbl6&-Fihm6$F_gelFeialFWF\ialF[eblFin@%-F\il6$F(F\ialC'>FfgalFj\gl@$F
7F\]dl-Fdq6$Q9stable~separatrice~x=%a|+Fe`rF`]glFa]dl@%Fd]gl>Fdjal7)F`eblFg]glF
h]glFhhalFfgalFfnFin>FdjalFj]glC(>Ffgal-F_eelF[]gl@$F7F\]dl-Fdq6$Q6center~manif
old~x=%a|+Fe`r-Fihm6$/FWFgn&FfgalF]eal-Fdq6$Q:on~center~manifold~y'=%a|+Fe`r-Fi
hm6$Fe_gl&FfgalFgealFa]dl@%-F\ilF][gl@%2F(-Fihm6$/FWF$&Ffgal6#F2>Fdjal7)F`eblFg
]glFh]glFhhal-Fihm6$Fg`elFf_glF.Fin>Fdjal7)F`eblFg]glFh]glFhhalFh`glFhcrFin@%F`
`gl>Fdjal7)F`eblFg]glFh]glFhhalFh`glFicrFin>Fdjal7)F`eblFg]glFh]glFhhalFh`glF_i
uFin@%Fg\gl@%-F_jl6$F\ialFgjalC&>F^halFc[gl>FhhalF\\gl>Ffgal-Fh`elF[]gl>Fdjal7)
F`eblFg]glFh]glFhhalFfgalF^tFin>Fdjal7)F`eblFg]gl7&F(F$F$F(FciflF(F^tFin@%Fcagl
C&>F^halFc[gl>FhhalF\\gl>FfgalFiagl>Fdjal7)F`eblFg]glFh]glFhhalFfgalF\\rFin>Fdj
al7)F`eblFg]glF^bglFciflF(F\\rFinOFdjalFe`rFe`rFe`rF&,
I,sing_eigenvf*6'FijlF^`x%$lvlGFe^clFd^cl6.FjhnF\\nFgjlFadtFbdtFbcmFf^clFfhflFg
hnFcerFjoFd\rFe`rFe`rC$@%0F]_blF(C'>Fhhal-Fhho6$F]_blFgn>FiealF[bcl?(F\ialF$F$-
Fb[l6#F^`blF`o@%/F]_clF$>Fieal-F_[cl6%Fieal-F_\l6$F\ialF^`blF8>Fieal-F`]clF]dgl
?(F\ialF$F$-Fb[l6#&FhhalFgealF`o@%Fjcgl>Fieal-F_[cl6%Fieal-F_\l6$F\ialFedglF`o>
Fieal-F`]clFidgl?(F\ialF$F$FbhclF`oC(>Fdjal-F_\l6$F$&FiealFd\cl>Fgjal-Fg[m6$F_b
bl/FgnFdjal>F^hal-Fg[m6$-FRFdcglFgegl@$-F_\l6$FfnFceglC$>Fgjal-F]oF^\fl>F^hal-F
]oFchal@$F7F\]dl@%3F\[gl-Ffil6$F^halF(C%-Fdq6$QB(0,%a)~is~a~non-elementary~poin
t|+Fe`rFdjalFa]dl-%,blowing_up2G6(F[ealFdjal,&F[eblF$F$F$F`eblF]_clF8@%55F\[glF
gfgl-Fail6$F(*&FgjalF$F^halF$C0>Ffgal-FR6$F\bblFW>Ffgal-Fihm6%FafelFgegl*&Ffgal
F$,&FgjalF$F^halF2F2@$F]fgl>Ffgal-F]o6#Ffgal>F[hal-Fb^t6'F[ealFWFgnF(Fdjal@$F]f
gl>F[hal-F]oFi[el>Fj\bl7&F$F(FfgalF$>Fd\dl-F]`t6'F[halF$F(FfgalF$@$F]fgl>Fd\dl-
F]oF_\el-Fdq6&QS(0,%a)~is~a~singular~point~with~eigenvalues~%a,%a|+Fe`rFdjalFgj
alF^hal-Fdq6#QAmoving~this~point~to~the~origin|+Fe`r-Fdq6$Q<the~new~vector~fiel
d~is~%a|+Fe`rF[hal-Fdq6#Q[otransform~this~vector~field~so~that~the~linear~part~
is~diagonal|+Fe`r-Fdq6$FjiglFd\dl@%F^`glC%>Ff\dl-Fg\el6$Fd\dlF)-Fdq6$Q;unstable
~separatrice~y=%a|+Fe`r-Fihm6$/Fd_rFWFf\dl@%-F_jlFhfgl-Fa^cl6)F]_clF$F`ebl7$F(F
djalFj\blFd\dlFf\dl-Fa^cl6)F]_cl-F\cbl6&-Fihm6$Fafel&Fd\dlFgealFgnFgjalFdcblF`e
blF_[hlFj\blFd\dlFf\dl@%-F\il6$F(FgjalC%>Ff\dlFcjgl-Fdq6$Q9stable~separatrice~y
=%a|+Fe`rFhjgl@%F\[hl-Fa^cl6)F]_clFfnF`eblF_[hlFj\blFd\dlFf\dlF`[hlC&>Ff\dl-F_e
elFdjgl-Fdq6$Q6center~manifold~y=%a|+Fe`r&Ff\dlF]eal-Fdq6$Q=on~center~manifold~
is~x'=%a|+Fe`r&Ff\dlFgeal@%-F\ilFhfgl@%2F(-Fg\w6#-F]o6#-Fihm6$Fc`gl&Ff\dlF^_bl-
Fa^cl6)F]_clF.F`eblF_[hlFj\blFd\dl-Fihm6$Fg`elFh\hl-Fa^cl6)F]_clFhcrF`eblF_[hlF
j\blFd\dlFj]hl@%F`]hl-Fa^cl6)F]_clFicrF`eblF_[hlFj\blFd\dlFj]hl-Fa^cl6)F]_clF_i
uF`eblF_[hlFj\blFd\dlFj]hl@%F^`glC$-Fdq6&QS(0,%a)~is~an~unstable~node~with~eige
nvalues~%a,%a|+Fe`rFdjalFgjalF^hal@%-F_jl6$FgjalF^halC+>Ffgal*&FigglF$F_hglF2>F
fgal-Fihm6%FafelFgeglFfgal@$F]fgl>FfgalFbhgl>F[halFehgl@$F]fgl>F[halFihgl>Fj\bl
F[igl>Fd\dlF]igl>Ff\dl-Fh`elFdjgl-Fa^cl6)F]_clF^tF`eblF_[hlFj\blFd\dlFf\dl-Fa^c
l6)F]_clF^tF`eblF_[hl7&F$F(F(F$FehglF(C$-Fdq6&QP(0,%a)~is~a~stable~node~with~ei
genvalues~%a,%a|+Fe`rFdjalFgjalF^hal@%Fi^hlC+>FfgalF]_hl>FfgalF__hl@$F]fgl>Ffga
lFbhgl>F[halFehgl@$F]fgl>F[halFihgl>Fj\blF[igl>Fd\dlF]igl>Ff\dlFi_hl-Fa^cl6)F]_
clF\\rF`eblF_[hlFj\blFd\dlFf\dl-Fa^cl6)F]_clF\\rF`eblF_[hlF^`hlFehglF(C-@$F7F\]
dl-Fdq6#QUx=0~is~a~line~of~singularities~-~point~is~star-like|+Fe`r>Fhhal-Fhho6
$F_bblFgn>FiealF[bcl?(F\ialF$F$FgcglF`o@%Fjcgl>FiealF\dgl>FiealFadgl?(F\ialF$F$
FcdglF`o@%Fjcgl>FiealFhdgl>FiealF]egl-Fdq6#QZthe~non-elementary~singular~points
~(contact~points)~are:|+Fe`r?(F\ialF$F$FgcglF`o-Fdq6$Q((0,%a)|+Fe`rF^dgl?(F\ial
F$F$FcdglF`o-Fdq6$FjbhlFjdglFa]dl?(F\ialF$F$FbhclF`o-F^ggl6(F[ealFaeglF`gglF`eb
lF]_clF`oFa]dlFe`rFe`rFe`rF&,
I-blowing_upy2f*6(FGF`jelF^`xFe^clFd^clF^f[l6&FggtFijl%#sxG%#syGFe`rFe`rC*>Ffda
lFjhfl>Fieal-Fj]fl6'FfdalF_iflF[eblFWFgn>Ffdal-F]`t6'FeialF(F$F$F(@$F7F\]dl@%/F
[eblF$-Fdq6#QHblowing~up~in~the~positive~y-direction|+Fe`r-Fdq6#QHblowing~up~in
~the~negative~y-direction|+Fe`r-Fdq6$QAblowing~up~the~vector~field~%a.|+Fe`rFfd
alFa]dl@%/F^_clF8C%>F\ial-Fg\w6#-F]o6#-Fihm6$Fc`gl-Ffam6$-Fihm6$F_gelFciflFW>Fg
jal-Fg\w6#-F]o6#-Fihm6$/FgnF$-Ffam6$-Fihm6$FafelF]jflFgn@$/F\ialFgjal@%2F(F\ial
-Fa^cl6)F]_clF^tF`eblFg]glF^`hlFfdalFd_r-Fa^cl6)F]_clF\\rF`eblFg]glF^`hlFfdalFd
_rC%@$/FeehlF(YQ^pcase~not~treated:~star-like~points~should~become~non~star-lik
e~after~second~blowup.Fe`r>F\ialF_ehl@%2F(*&F[eblF$F]_clF$-Fa^cl6)F]_cl,&Ff]dlF
$F\ialF2F`eblFg]glF^`hlFfdalFd_r-Fa^cl6)F]_cl,&FadlF$F\ialF2F`eblFg]glF^`hlFfda
lFd_rFe`rFe`rFe`rF&,
I,blowing_up2f*6(FGFf^clF\cglFe^clFd^clF^f[l6(FggtF_jelFfdlF`jel%$trfGFijlFe`rF
e`rC:@$F7-Fes6$FdtFbx-Fdq6$Q5Blowing~up~level~%d|+Fe`rF[eblFb]fl-Fdq6%Q?blowing
~up~%a~in~point~(0,%a)|+Fe`rF\ealFdcbl@%-F_jl6$FdcblF(C%>Ffdal-Fb^t6'F\ealFWFgn
F(Fdcbl-Fdq6$Q=moving~(0,%a)~to~the~origin|+Fe`rFdcbl-Fdq6$Q5new~vector~field~%
a|+Fe`rFfdal>FfdalF\eal>Fieal-F[galFhfal>F\ial-Fg]blFjfal>Fgjal-F`ablFd\cl-Fdq6
$Q3Newton~diagram~%a|+Fe`rFieal-Fdq6$Q8[alpha,beta,degree]=%a|+Fe`rFgjalFa]dl@%
F\ehl@%FjcglC$>F^hal7+F(FdcblF$F2F$Fe[blF(Fg[blF]hcl-Fachl6(FfdalFgjalF27$-F_\l
6#F`eblF^halF]_clF8C$>F^hal7+F(FdcblF$F$F$Fe[blF(Fg[blF]hcl-Fachl6(FfdalFgjalF$
F\[ilF]_clF8@%FjcglC$>F^halFijhl-Fachl6(FfdalFgjalF2F\[ilF]_clF`oC$>F^halFa[il-
Fachl6(FfdalFgjalF$F\[ilF]_clF`o@$F7Fchhl-Fdq6#QHblowing~up~in~the~positive~x~d
irection|+Fe`r>Fhhal-Fj]fl6'FfdalFgjalF$FWFgn-Fdq6$FgiflF^`blFa]dl>F^hal7+F(Fdc
blF$F$Fe[blF(Fg[blF$F]hcl-Fa^fl6'FhhalF$F[eblF\[ilF]_cl@%F\ehl@%FjcglC$>F^halFa
[ilFb[ilC$FijhlFjjhl@%FjcglC$>F^halFa[ilF[\ilC$FijhlFg[il@$F7Fchhl-Fdq6#QI-----
----------------------------------|+Fe`r-Fdq6$Q2Back~to~level~%d|+Fe`r,&F[eblF$
F2F$Fa]dlFe`rFe`rFe`rF&,
I(ManXPosF[bclF&,
I(ManXNegF[bclF&,
I(NumXPosF(F&,
I(NumXNegF(F&,
I(NumberYF(F&,
I(ManYPosF[bclF&,
I(ManYNegF[bclF&,
I,user_bindirQ2/usr/local/p4/binF&F&,
I,user_tmpdirQ%/tmpF&F&,
I,user_lypexeQ)lyapunovF&F&,
I0user_lypexe_mpfQ-lyapunov_mpfF&F&,
I/user_removecmdQ#rmF&F&,
I,user_sepexeQ,separatriceF&F&
