M7R0
I3chooseParameterSetf*6#%"rG6#%"kG6"F(C$?(8$"""F,-%%nopsG6#%0user_parametersG%%
trueG-%)unassignG6#-%(convertG6$&F06#F+%%nameG?(F+F,F,F-F1-%'assignG6$F5&-F66$-
%$catG6$F8Q(_piecesF(F:6#9$F(F(F(F(,
I.ishamiltonianf*6#%#vfG6#%%exprGF(F(C$>F+-%)norpoly2G6%,&-%%diffG6$&FG6#F,%"xG
F,-FU6$&FG6#""#%"yGF,FYFin@%%(roundedG@%/-%&evalfGF9$""!FaoF1%&falseG@%/F+FaoF1
FboF(F(F(F(,
I'p4mainf*F(6,%#gcG%$gcfG%*gcdresultG%'orig_fG%"gG%#geG%#gnG%"jG%"iGF%F(F(C7>%*
numpiecesG-F.6#%.user_f_piecesG>%*numcurvesG-F.6#%,user_curvesG@$5/FcpFao4-%%ty
peG6$Ffp%%listGC$>Ffp7#%'user_fG>FcpF,>%+normalexitGFao-%)openfileG6#%)terminal
G-%'writefG6$Q4user_precision0=%a|+F(%0user_precision0G-%*closefileGF]r@%0FcrFa
o>%'DigitsGFcr>Fir-%&floorG6#-%'evalhfG6#Fir-F\r6#%*vec_tableG-F`r6#Q$P5|+F(-F`
r6%Q'%d~%d|+F(FcpFhp-F`r6&Q*%d|+%d|+%d|+F(%0all_crit_pointsG%'user_pG%'user_qG@
$/F]t""$-F`r6'Q1~~~~%g~%g~%g~%g|+F(%&x_minG%&x_maxG%&y_minG%&y_maxGF[r?(8-F,F,F
hpF1C$@$5-Faq6$&F[q6#F[u%)equationG-Faq6$Fau%#<=G>Fau,&-%$lhsG6#FauF,-%$rhsGF[v
!""@$/-%6CheckIfGoodPolynomialGF[vFboC$-F`r6%Q[rThe~separating~curve~#%d:~%a~is
~not~well-defined~(not~polynomial,~or~coefficients~do~not~evaluate~numerically.
)|+F(F[uFau-%%quitGFX@$2FaoFhp?(F[uF,F,FhpF1C&>F[oF1>%/user_precisionG"")Fas-%*
write_gcfGF[v@$FjvC(Fas-F`r6$Q$%d|+F(-F.6#%*vfregionsG@$2FaoFhw?(8+F,F,FhwF1C$-
F`r6$Q#%dF(&&Fjw6#F^xFX?(F[uF,F,FhpF1C$-F`r6$Q$~%dF(&&FdxFgnFbu@$/F[uFhp-F`r6#Q
"|+F(Fas-F`r6$Fgw-F.6#%-curveregionsG@$2FaoFdy?(F^xF,F,FdyF1C$-F`r6$Fbx&&FfyFex
FX?(F[uF,F,FhpF1C$-F`r6$Fjx&&F^zFgnFbu@$F^yF_yF[r?(8,F,F,FcpF1CB-F"6#Fgz@$-Faq6
$%4user_numeric_piecesGFcq>%-user_numericG&F^[lFjz@$-Faq6$%6user_precision_piec
esGFcq>F_w&Fe[lFjz@$1FirF_wC$-F`r6&Q[qPlease~increase~precision~or~decrease~acc
uracy~for~region~#%d.~Precision~=~%d~<=~Accuracy~=~%d.|+F(FgzFirF_wFgv@$-Faq6$%
/epsilon_piecesGFcq>%(epsilonG&Fa\lFjz@$-Faq6$%0test_sep_piecesGFcq>%)test_sepG
&Fh\lFjz@$-Faq6$%4taylor_level_piecesGFcq>%-taylor_levelG&F_]lFjz@$-Faq6$%5nume
ric_level_piecesGFcq>%.numeric_levelG&Ff]lFjz@$-Faq6$%1max_level_piecesGFcq>%*m
ax_levelG&F]^lFjz@$-Faq6$%6weakness_level_piecesGFcq>%/weakness_levelG&Fd^lFjz@
$-Faq6$%*x0_piecesGFcq>%#x0G&F[_lFjz@$-Faq6$%*y0_piecesGFcq>%#y0G&Fb_lFjz@$F`q>
Fgq&FfpFjz@$-Faq6$%0user_gcf_piecesGFcq>%)user_gcfG&F\`lFjz>F[oF`[l@$55/-Fbv6#&
FgqFXFbo/-Fbv6#&FgqFgnFbo/-Fbv6#F^`lFboC$-F`r6$Q]qThe~system~#%d~is~not~well-de
fined~(not~polynomial,~or~coefficients~do~not~evaluate~numerically.)|+F(FgzFgv-
F`r6#QGLET~US~STUDY~THE~DIFFERENTIAL~SYSTEM:|+F(-F`r6%Q:~~~~x'~=~%a|+~~~~y'~=~%
a|+|+F(Fg`lF[al@%/F^`lFaoC'>8'Fgq>8&-%'my_gcdG6$Fg`lF[al>F+&F_blFgn>F^`l&F_bl6#
Fbt>Fgq-%)simplifyG6#&F_blFXC&>F+Fhn>F]blFgq>Fgq7$-Fjbl6#*&&F]blFXF,F^`lF^v-Fjb
l6#*&&F]blFgnF,F^`lF^v@$Fc`lC$-F`r6#QNError:~The~given~gcf~is~not~a~common~fact
or.|+F(Fgv-FbwF^alFas-%0write_vec_fieldG6#FgqF[r@%-FHFbdlC$-F`r6#Q<The~system~i
s~Hamiltonian.|+F(>%,hamiltonianGF1>FjdlFbo@$4-%'memberG6$F]t<$FhnFbtC0>%)log_f
ileG%-finite_tableG>%,result_fileG%+finite_resG@$2F,FcpC'-F\r6#Fgel-F`r6#Q^p|+|
+\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
\/|+F(-F`r6$QE~~~~~~~~~~~~~~~~~~~~~~~~~~PIECE~#%d|+F(Fgz-F`r6#Q]p\/\/\/\/\/\/\/
\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/|+|+F(F[r-F`r
6#QOLET~US~STUDY~THE~SYSTEM~AT~THE~FINITE~REGION|+|+F(F\flFcal-F`r6%Q9~~~~x'~=~
%a|+~~~~y'~=~%a|+F(FeclFicl-F`r6#Q6AT~THE~FINITE~REGION|+F(@$/-%0quasihom_degre
eG6'FgqFYFinF^tF_t,$%)infinityGF^vC%-F\r6$FgelF^r-F`r6#QEError:~The~given~vecto
r~field~is~0!|+F(Fgv@$5/F+F,3/F+Fhn0F^`lF,C%-F`r6$QDThe~system~has~a~common~fac
tor:~%a|+F(F^`l-F`r6$QJHence~we~shall~study~the~reduced~system:|+F(F^`l-F`r6%F
\glFg`lF[alF[r@%4F`[lC->8(-%0find_real_rootsG6%FgqFYFin>8)&F`ilFX>8*&F`ilFgn-F
\r6#Fdel-F`r6$Fgw,&-F.6#FeilF,-F.6#FhilF,F[r-F`r6#QZ---------------------------
-----------------------------|+F(?(F^xF,F,F_jlF1-%*sing_typeG6&Fgq-%#opG6$F,&Fe
ilFex-F[[m6$FhnF][mFao>F[oF1?(F^xF,F,FajlF1-Fhjl6&Fgq-F[[m6$F,&FhilFex-F[[m6$Fh
nFf[mFao>F[oF`[lC(>Fhil-%8find_real_roots_numericGFcilFjil-F`r6$FgwFajlF[rFcjl?
(F^xF,F,FajlF1Fb[m-FerF[jl-FerF]fl@$4-F_el6$F]t<$F,FbtC,>Fdel%/infinite_tableG>
Fgel%-infinite_resG@$FjelC&F\flF^flFaflFdflFhgl-F`r6#QFLET~US~STUDY~THE~SYSTEM~
AT~INFINITY|+|+F(Fcal@%Fahl-F`r6%F\gl*&F^`lF,Fg`lF,*&F^`lF,F[alF,Fjfl-F`r6#Q-AT
~INFINITY|+F(@$F^hlC%FdhlFghlFjhlF[r@%3/F^tF,/F_tF,-%5vec_field_diff_chartGFcil
-%)pl_chartGFbdl@$Fd\mC$Fa\mFb\m-FerFbs@$FatC/>FdelFeel>FgelFhelFjil-F`r6$FgwF,
F[r-F`r6#QIWe~shall~study~the~differential~system:|+F(@%FahlFc]mFjfl-F`r6%Q7in~
the~point~(%a,%a).|+F(F]_lFd_l@$F^hlC%FdhlFghlFjhlF[r-Fhjl6&FgqF]_lFd_lFaoFa\mF
b\mF[r-F`r6#QR|+We~have~finished~the~study~of~the~vector~field.|+F(-%.closeallf
ilesGF(>FjqF,F(6:F[oFgqF^`lF^tF_tFcpFhpFjdlFdelFgelFjqF`[lF_wFcrFc\lFj\lFa]lFh]
lF_^lFf^lF]_lFd_lFfpF[qF(F(,
I6CheckIfGoodPolynomialf*6#%"fGF(F(F(O-Faq6$-F_oFF-%(polynomG6$%(numericG7$FYFi
nF(F(F(F(,
I6prepareArbitraryCurvef*F(F(F(F(C)>F[oF`[l-F\r6#%,curve_tableG-%,write_curveG6
#%+user_curveG-FerFaamF[r-F`r6#Qgn|+We~have~finished~writing~the~curve~as~a~C++
~readable~list.|+F(>FjqF,F(6%FfamFjqF[oF(F(,
I3Hardware_precision"#:F(,
I-reduce_coefff*6$Fb`mFY6&F\p%#g1G%#g2GF_p6"FebmC&>8$-%(norpolyG6$9$9%>8%-%&num
erG6#Fhbm>8&-%&denomGFbcm@%/F_cmFao7#Fao7#-%"$G6$*&-%&coeffG6%F_cmF]cm8'F,FdcmF
^v/Fbdm;Fao-%'degreeG6$F_cmF]cmFebmFebmFebmF(,
I-write_numberf*6#%"nGFebmFebmFebm@%F[o-F`r6$Q$%g|+6"-F_o6#F\cm-F`r6$Q$%a|+Febm
F\cmFebmFebmFebmF(,
I+reduce_lltf*6$%"aG%"bGFebm6$%)operatorG%&arrowGFebm-%&evalbG6#1-F_o6#,&F\cmF,
F]cmF^v,$)"#5,$F_wF^vF^vFebmFebmFebmF(,
I-reduce_evalfF_oF(,
I*reduce_gtf*FhemFebmF[fmFebm-F_fm6#1FffmFbfmFebmFebmFebmF(,
I,reduce_gteqf*FhemFebmF[fmFebm-F_fm6#1FefmFbfmFebmFebmFebmF(,
I+reduce_eeqf*FhemFebmF[fmFebm-F_fm6#2-F_o6#-%$absGFcfmFffmFebmFebmFebmF(,
I,reduce_nneqf*FhemFebmF[fmFebm-F_fm6#1FffmFigmFebmFebmFebmF(,
I4optimizepolynomial1f*Fabm6'F\p%"LGF_pF'%"zGFebmFebmC(>FhbmFibm@%4F[o>Fhbm-F66
$Fhbm%)rationalG>Fhbm-F_oFbcm>F_cm-%%evalG6#7#-F\dm6$.-F`dm6%FhbmF]cmFdcm/Fdcm;
Fao-%$maxG6$Fao-Ffdm6$FhbmF]cm@$3Fjhm%.user_simplifyG>F_cm-%$mapG6$%1user_simpl
ifycmdGF_cm>F_cm-Fgjm6$f*6#FfhmFebmF[fmFebm@%-Faq6$FaemFj`m@%1-F\hm6#FaemFffmFa
oF\cmF\cmFebmFebmFebmF_cm-Fcim6#-%$addG6$*&&F_cm6#FbdmF,)F]cm,&FbdmF,F^vF,F,/Fb
dm;F,-F.6#F_cmFebm6$F_wF[oFebmF(,
I4optimizepolynomial2f*6%Fb`mFYFin6&F\pF_pFehmFfhmFebmFebmC'>Fhbm-FQ6%F\cmF]cm9
&@%Fjhm>FhbmF\im>FhbmF`im>Fdcm-Fcim6#7#-F\dm6$.-F`dm6%FhbmF]cmF_cm/F_cmF\jm>Fdc
m-Fgjm6$f*F^[nFebmF[fmFebm-Fbhm6$F\cmT$FebmFebm6$FinF]]nFdcm-Fjbm6$-Fcim6#-Fi[n
6$*&&Fdcm6#F'F,)F]cm,&F'F,F^vF,F,/F';F,-F.6#FdcmF]cmFebm6#F[oFebmF(,
I+first_termf*6$%#_fGFY6#Fb`mFebmFebmC$>Fhbm-FbhmF[cm@%/FhbmFaoFao*&-F`dm6%Fhbm
F]cm-%(ldegreeGFajmF,)F]cmF``nF,FebmFebmFebmF(,
I*lleadtermf*Fe_nFg_nFebmFebmC$>FhbmFj_n@%F\`nFao*&-F`dm6%FhbmF]cmF`jmF,)F]cmF`
jmF,FebmFebmFebmF(,
I'nltermf*Fg\n6$F\p%"hGFebmFebmC$>Fhbm-Fjbm6$-Fc`nF[cmF]]n@%0FhbmFaoC$>F_cm-Fc`
n6$FhbmF]]n@%0F_cmFaoF_cmFhbmC$>Fhbm-Fjbm6$-Fc`n6$F\cmF]]nF]cm@%FfanFhbmF\cmFeb
mFebmFebmF(,
I%ddegf*6%Ff_nFYFinFg_nFebmFebmC$>Fhbm-Fe\nF\]n@%F\`nFao-Ffdm6$Fhbm<$F]cmF]]nFe
bmFb_nFebmF(,
I)low_ddegf*FfbnFg_nFebmFebmC$>FhbmFibn@%F\`nFao-Fa`nF\cnFebmFebmFebmF(,
I&ntermf*6&Ff_nFYFin%"dG6%Fb`mF_pF\pFebmFebmC&>FhbmFibn>FdcmFao?(F_cmFaoF,9'F1>
Fdcm,&FdcmF,*(-F`dm6%Fh]nF]]n,&F]dnF,F_cmF^vF,)F]cmF_cmF,)F]]nFcdnF,F,FdcmFebmF
ebmFebmF(,
I)low_deg1f*Fe_nFg_nFebmFebmC$>Fhbm-F_o6$-FjbmFbemF]cm@%/FhbmF`oFaoF``nFebmFebm
FebmF(,
I+optimizevff*Fg\nFebmF[fmFebm7$-Fe\n6%&F\cm6#F,F]cmF]]n-Fe\n6%&F\cm6#FhnF]cmF]
]nFebmFebmFebmF(,
I1quasihom_degree1f*6'Ff_nFYFin%"pG%"qG6%%#_xG%#_yGFb`mFebmFebmC%>FdcmFibn>Fdcm
-%%subsG6%/F]cm)FhbmF]dn/F]]n)F_cm9(Fdcm-Ffdm6$Fdcm<$FhbmF_cmFebmFebmFebmF(,
I0quasihom_degreef*6'FKFYFinF]fnF^fnFebmF[fmFebm-F^jm6$,&-Fjen6'FdenF]cmF]]nF]d
nF\gnF,F]dnF^v,&-Fjen6'FhenF]cmF]]nF]dnF\gnF,F\gnF^vFebmFebmFebmF(,
I,change_polyf*Fg\n6&F\pF_anF'FiemFebmFebmC&>FhbmF[]n>F_cmFao?(FebmF,F,FebmFfan
C&>Fdcm-F\an6%FhbmF]cmF]]n>Fhbm,&FhbmF,FdcmF^v>Fbdm-Fcim6$-Fcim6$Fdcm/F]cmF,/F]
]nF,@$2Fffm-F\hm6#-F_oF]\n>F_cm,&F_cmF,FdcmF,F_cmFebmFebmFebmF(,
I*sort_listf*6#%"sGFebmF[fmFebm-%%sortG6$F\cmf*6$%&sle_aG%&sle_bGFebmF[fmFebm-F
_fm6#52Fden&F]cmFeen3/FdenFejn2Fhen&F]cmFienFebmFebmFebmFebmFebmFebmF(,
I+reduce_impf*F^[nFebmF[fmFebm-F_o6#-%*reduce_imGFbemFebmFebmFebmF(,
I,reduce_conj%*conjugateGF(,
I*reduce_ref*F^[nFebmF[fmFebm,&F\cm#F,Fhn-F`[oFbemFe[oFebmFebmFebmF(,
I*reduce_imf*F^[nFebmF[fmFebm*&^##F^vFhnF,,&F\cmF,Ff[oF^vF,FebmFebmFebmF(,
I)openfilef*Febm6&%#kkGF'%#fhG%&fnameGFebmFebmC%>%0currentopenfileG<"?(FhbmF,F,
9#F1C$>Fbdm-Fcim6#&9"Fbcm@%/FbdmF^r>Fe\o-%&unionG6$Fe\o<#,$FfglF^vC$?(F_cmF,F,-
F.6#%-openfilelistGF1@$/-F[[m6$F,&F[^oFc\nFbdm[@%1F_cmFi]o>Fe\o-Fc]o6$Fe\o<#-F[
[m6$FhnF`^oC%>Fdcm-%&fopenG6%Fbdm%&WRITEG%%TEXTG>Fe\o-Fc]o6$Fe\o<#Fdcm>F[^o-Fc]
o6$F[^o<#7$FbdmFdcm@$/-F.6#Fe\oFao>Fe\oFe]oFebm6$Fe\oF[^oFebmF(,
I*closefilef*6#%)filenameGF[_nFebmFebm@%0F\cmF^rC$?(FhbmF,F,Fi]oF1@$/-F[[m6$F,&
F[^oFbcmF\cmFa^o@$1FhbmFi]oC%-%'fcloseG6#-F[[m6$FhnF\ao@$-F_el6$FcaoFe\oC$>Fe\o
-%&minusG6$Fe\o<#Fcao@$F[`o>Fe\oFe]o>F[^o-F[bo6$F[^o<#F\ao@$3-F_el6$Ff]oFe\o2F,
F\`o>Fe\o-F[boFd]oFebmF_`oFebmF(,
I'writeff*6#%-formatstringG6#F_pFebmFebm?(FhbmF,F,F\`oF1@%/&Fe\oFbcmFf]o-%'prin
tfG6$F\cm&F^]o6#;FhnFh\o-%(fprintfG6%FccoF\cmFgcoFebmFebmFebmF(,
I0currentopenfileFe]oF(,
I-openfilelistFf\oF(,
I.closeallfilesf*Fb`oFebmFebmFebm?(FebmF,F,Febm0Fi]oFao-Fer6#-F[[m6$F,&F[^oFeen
FebmFebmFebmF(,
I(norpolyf*6$%"PGFYFebmF[fmFebm@%Fdjm-%'expandG6#-Fijm6#-%'normalGFbem-F^eoFaeo
FebmFebmFebmF(,
I)norpoly2f*6%F[eoFYFinFebmF[fmFebm@%FdjmF]eoFdeoFebmFebmFebmF(,
I)norpoly3f*6&F[eoFYFinFfhmFebmF[fmFebm@%FdjmF]eoFdeoFebmFebmFebmF(,
I'my_gcdf*6$Ff_n%#_gG6+Fb`mF\p%#f2GFdbm%#ffG%"cGFho%"lGF%6"FffoC'>8$-FQ6%9$FYFi
n>8%-FQ6%9%FYFin@$4F[oC$>Fifo-F66$FifoF^im>F^go-F66$F^goF^im@%3/FifoFao0-Fdbn6%
F^goFYFinFaoC%>8(7$FaoF,>8)F,>8*F^go@%3/F^goFao0-Fdbn6%FifoFYFinFaoC%>Fcho7$F,F
ao>FfhoF,>FhhoFifo@%33Fcgo-%*num_coeffGF^io-FhioF`hoC'>8+-%$lcmG6$-Ffcm6#Fifo-F
fcm6#F^go>8&*&FifoF,F\joF,>8'*&F^goF,F\joF,>Fhho-FQ6%*&-%$gcdG6$FejoFhjoF,F\joF
^vFYFin@%0-Fdbn6%FhhoFYFinFaoC(-F`r6$FfhlFhho>FfhoF,>Fcho7$-FQ6%*&FifoF,FhhoF^v
FYFin-FQ6%*&F^goF,FhhoF^vFYFin-F`r6#F__m-F`r6$Q+~~~~x'=%a|+Fffo&Fcho6#F,-F`r6$Q
+~~~~y'=%a|+Fffo&Fcho6#FhnC%-F`r6#QCThe~system~has~no~common~factors.|+Fffo>Fch
o7$FifoF^go>FfhoFaoC'>8,F[o>F[oF1>Fhho-F_[p6$FifoF^go@%Fb[pC(-F`r6$QDThe~system
~has~a~comman~factor:~%a|+FffoFhho>Fcho7$F]\pF`\p>FfhoF,Fa\pFc\pFh\pC%F^]p>Fcho
Fb]p>FfhoFao>F[oFf]p7%FchoFfhoFhhoFffo6#F[oFffoF(,
I*num_coefff*6%Ff_nFYFin6*Fb`mF_pF'%#l1G%#l2G%#s1G%#s2G%#okG6"Fb_pC(@%4F[o>8$-F
66$-FQ6%9$9%9&F^im>Fg_pFj_p>8+F1>8'-F_bm6$Fg_pF]`p>8%Fao?(Fb_pF,F,Fb_p3Fa`p2Fg`
p-F.6#Fc`pC'>Fg`p,&Fg`pF,F,F,>8)&Fc`p6#Fg`p>8(-F_bm6$FaapF^`p>8&Fao?(Fb_pF,F,Fb
_p3Fa`p2Fiap-F.6#FeapC%>Fiap,&FiapF,F,F,>8*&Feap6#Fiap@$4-Faq6$FcbpF^im>Fa`pFbo
Fa`pFb_pFb_pFb_pF(,
I8findAllSeparatingCurvesGF(,
I4findSeparatingCurveGF(,
I;findSeparatingCurveInChartGF(,
I)save_allFboF(,
I3real_roots_numericf*6$Fb`mFY6&%%cplxGF_pF'F\p6"FdcpC'>8$7#-%'fsolveG6&9$9%%(c
omplexG%+fulldigitsG@$/Fgcp7#/F]dpF]dp>Fgcp7">8'Fedp?(8%F,F,-F.6#FgcpF1@$1-F\hm
6#-%#ImG6#&Fgcp6#Fidp)Fgfm,$F_wF^vC%>Fcep-%#ReGFbep?(8&F,F,-F.6#FgdpF1@$-Fdgm6$
Fcep&Fgdp6#F\fp[@$2F]fpF\fp>Fgdp7$-F[[mF^fpFcep-F[jnF^fpFdcpFdcpFdcpF(,
I1find_real_roots1f*Facp6'F_anF]pF^pF'FjemFdcpFdcpC$@%F[oC$>FidpFedp>F\fp-F_cp6
$F\dpF]dpC*>%-_EnvExplicitGF1>%1_EnvAllSolutionsGF1>%,_EnvTryHardGF1>Fgcp7#-%&s
olveGFdgp@$/Fgcp7#F]dp>FgcpFedp>FidpFedp>F\fpFedp?(FgdpF,F,FjdpF1C$>8(&FgcpF^fp
@%-%$hasG6$Fihp%'RootOfGC$>Fihp-F_o6#Fihp@$1-F\hm6#-FaepFcipFeepC$>Fihp-FjepFci
p>F\fp7$-F[[mFcfpFihp@$1-F\hm6#-F_oFgipFeepC$>FihpF[jp>Fidp7$-F[[mFdepFihp7$-F6
6$-F66$Fidp%$setGFcq-F66$-F66$F\fpF^[qFcqFdcpFdcpFdcpF(,
I8find_real_roots_numericf*6%Fb`mFYFin6'F\pF_anF_pF'FiemFdcpFdcpC*>FggpF1>FigpF
1>F[hpF1>Fidp-F_o6#-Fgjm6$%*allvaluesG7#-F_hp6$-F66$F\dpF^[q<$F]dp9&>FgcpFedp?(
F\fpF,F,-F.FdepF1C$>Fihp-Fffn6$&FidpFcfp7$F]dpFg\q@$32-F\hm6#-Faep6#&Fihp6#F,Fe
ep2-F\hm6#-Faep6#&Fihp6#FhnFeepC%>Fihp-Fgjm6$FjepFihp?(FgdpF,F,FjdpF1@$32-F\hm6
#,&-F[[m6$F,FjhpF,Fh]qF^vFeep2-F\hm6#,&-F[[m6$FhnFjhpF,F_^qF^vFeepFdfp@$2FjdpFg
dpC%>Fgcp7$-F[[mF[epFihp@$/FjdpF,-F`r6#Q=Numeric~real~singularities:|+Fdcp-F`r6
'QC~~(%g,%g)~->~|fr~x'~=~%g,~y'~=~%g~|hr|+FdcpFh]qF_^q-F_o6#-Fffn6$<$/F]dpFh]q/
Fg\qF_^q&F\dpFi]q-F_o6#-Fffn6$Ff`q&F\dpF`^q@$/FjdpFao-F`r6#QENo~numeric~singula
rities~are~found.|+FdcpFgcpFdcpFdcpFdcpF(,
I0find_real_rootsf*Fe[q6,F\pF_anF_pF'Fiem%#anGF^pFiin%#snG%#bnGFdcpFdcpC2>FggpF
1>FigpF1>F[hpF1>FidpF^\q>FgcpFedp>8*Fedp?(F\fpF,F,Fj\qF1C&>FihpF]]q>8)-Fgjm6$Fj
epFbip>8--Fgjm6$FaepFbip@$32-F\hm6#&FjbqFi]qFeep2-F\hm6#&FjbqF`^qFeepC$?(FgdpF,
F,-F.6#FabqF1@$32-F\hm6#,&-F[[m6$F,&FabqF^fpF,&FfbqFi]qF^vFeep2-F\hm6#,&-F[[m6$
FhnFcdqF,&FfbqF`^qF^vFeepFdfp@$2FicqFgdpC$>FgcpFh_q>Fabq7$-F[[mFjcqFfbq>8+Fedp>
8,Fedp?(FgdpF,F,FicqF1@%5-F]ip6$F\_qF_ip-F]ip6$Fb_qF_ip>Ffeq7$-F[[m6#FfeqFcdq>F
deq7$-F[[m6#FdeqFjhp?(F\fpF,F,-F.FefqF1C$>&&FdeqFcfpFi]q-Fjep6#Fjfq>&F[gqF`^q-F
jep6#F_gq@%/FgfqFao-F`r6#QKNo~symbolic~real~singularities~are~found.|+Fdcp-F`r6
#Q>Symbolic~real~singularities:|+Fdcp?(FgdpF,F,FgfqF1-F`r6'Fa`q-F[[m6$F,&FdeqF^
fp-F[[m6$FhnF_hq-F_o6#-Fffn6$<$/F]dpF]hq/Fg\qF`hqFi`qFbhq@%/-F.FafqFao@%Fcgq-F`
r6#QJNo~numeric~real~singularities~are~found.|+Fdcp-F`r6#QPNo~other~numeric~rea
l~singularities~are~found.|+FdcpF\`q?(FgdpF,F,F[iqF1-F`r6'Fa`q-F[[m6$F,&FfeqF^f
p-F[[m6$FhnFhiq-F_o6#-Fffn6$<$/F]dpFfiq/Fg\qFiiqFi`qF[jq7$FdeqFfeqFdcpFdcpFdcpF
(,
I2find_real_roots11f*6$FehmFY6+%#f1GFbfoFb`mF\pF]pF^p%$ge2G%$gn2GF_pFdcpFdcpC,>
Fgcp-Fbhm6$Fi`qF]dp>Fidp-Fbhm6$F^aqF]dp@%0-F^jm6$-Ffdm6$FgcpF]dpFaoFaoC$>Fgdp-F
[gpFf[r>F\fpFidp@%0-F^jm6$-Ffdm6$FidpF]dpFaoFaoC$>Fgdp-F[gpF`\r>F\fpFgcpC$>Fgdp
7$FedpFedp>F\fpFao>Fihp&FgdpFi]q>Ffbq&FgdpF`^q>FabqFedp>FdeqFedp?(FfeqF,F,-F.Fc
ipF1@$2-F\hm6#-F_o6#-Fffn6$/F]dp&FihpFafqF\fpFeep>Fabq7$FbeqFj]r?(FfeqF,F,-F.6#
FfbqF1@$2-F\hm6#-F_o6#-Fffn6$/F]dp&FfbqFafqF\fpFeep>Fdeq7$FdfqFi^r7$FabqFdeqFdc
pFdcpFdcpF(,
I.coeff_degree1f*6$Fb`mFY6&F\pFgcnF_pFehm6"Fa_rC(>8$-Fbhm6$9$9%>8%-F^jm6$Fao-Ff
dm6$Fd_rFh_r>8'7"?(8&FaoF,Fj_rF1@$0-F`dm6%Fd_rFh_rFc`rFao>F``r7$-F[[m6#F``r7$Fc
`rFf`r@$/-F.F[arFao>F``r7#7$FaoFaoF``rFa_rFa_rFa_rF(,
I.coeff_degree2f*6%Fb`mFYFin6)F\pFgcnF_pFehm%#dxGF_anF'Fa_rFa_rC(>Fd_r-Fe\n6%Fg
_rFh_r9&>8(F[`r>F``rFa`r?(Fc`rFaoF,F^brF1C%>8)Ff`r>Fj_r-F^jm6$Fao-Ffdm6$Fd_rF\b
r?(8*FaoF,Fj_rF1@$0-F`dm6%FcbrF\brFjbrFao>F``r7$Fj`r7%Fc`rFjbrF]cr@$F^ar>F``r7#
7%FaoFaoFaoF``rFa_r6#F[oFa_rF(,
I.coeff_degree3f*6&Fb`mFYFinFfhm6,F\p%#d1G%#d2G%#d3G%#j1GFcbmFdbm%#j2G%#j3GFehm
Fa_rFa_rC(>Fd_r-Fieo6&Fg_rFh_rF\br9'>Fj_rF[`r>8-Fa`r?(F^brFaoF,Fj_rF1C%>Fcbr-Fe
\n6%-F`dm6%Fd_rFh_rF^brF\brFedr>Fc`r-F^jm6$Fao-Ffdm6$FcbrF\br?(8+FaoF,Fc`rF1C%>
Fjbr-F`dm6%FcbrF\brFfer>F``r-F^jm6$Fao-Ffdm6$FjbrFedr?(8,FaoF,F``rF1@$0-F`dm6%F
jbrFedrFafrFao>Fhdr7$-F[[m6#Fhdr7&F^brFferFafrFdfr@$/-F.FifrFao>Fhdr7#7&FaoFaoF
aoFaoFhdrFa_rFfcrFa_rF(,
I0write_vec_fieldf*6#FK6$FehmF_pFa_rFa_rC(>Fd_r-Fcar6%&Fg_r6#F,FYFin-F`r6$Fgw-F
.6#Fd_r?(Fj_rF,F,F]hrF1-F`r6&Q*%d~%d~%g|+Fa_r-F[[m6$F,&Fd_r6#Fj_r-F[[m6$FhnFehr
-F_o6#-F[[m6$FbtFehr>Fd_r-Fcar6%&Fg_r6#FhnFYFinF[hr?(Fj_rF,F,F]hrF1F`hrFa_rFa_r
Fa_rF(,
I9write_vec_field_cylinderf*FcgrFdgrFa_rFa_rC(>Fd_r-Fgcr6&FigrF%%$_coG%$_siGF[h
r?(Fj_rF,F,F]hrF1-F`r6'Q-%d~%d~%d~%g|+Fa_rFchrFghrF[ir-F_o6#-F[[m6$""%Fehr>Fd_r
-Fgcr6&F`irF%FiirFjirF[hr?(Fj_rF,F,F]hrF1F\jrFa_rFa_rFa_rF(,
I-write_saddlef*6,F]_lFd_lFiemFjemFdfoFgcnFK%$sepG%&stypeG%&chartG6%FehmF_pF'Fa
_rFa_rC*-F\r6#Fdel-F`r6&Q*%d~%g~%g|+Fa_rF,-F_o6#Fg_r-F_o6#Fh_r-F`r6'Q/~~%g~%g~%
g~%g|+Fa_r-F_o6#F\br-F_o6#Fedr-F_o6#9(-F_o6#9)-Fadl6#9*-F`r6$Q&~~%d|+Fa_r9-?(Fj
_rF,F,-F.6#9+F1C'-F`r6$Q&~~%d~Fa_r&9,Ffhr>Fd_r-F]_r6$&F`]sFfhr%"tG-F`r6$FbxF]hr
?(Fc`rF,F,F]hrF1-F`r6%Q'~%d~%gFa_r-F[[m6$F,&Fd_r6#Fc`r-F[[m6$FhnFd^s-F`r6#Fay-F
`r6$Q&~~%g|+Fa_rFc\l-F\r6#F^rFa_rFa_rFa_rF(,
I+write_nodef*6&F]_lFd_l%%stabGF][sFa_rFa_rFa_rC&F`[s-F`r6&Fd[sFhnFe[sFg[s-F`r6
%Q)~~%d~%d|+Fa_rF\brFedrF]_sFa_rFa_rFa_rF(,
I1write_weak_focusf*6&F]_lFd_lF][sF\[sFa_rFa_rFa_rC&F`[s-F`r6&Fd[sFbtFe[sFg[s-F
`r6%Fh_sFedrF\brF]_sFa_rFa_rFa_rF(,
I3write_strong_focusf*Fa_sFa_rFa_rFa_rC&F`[s-F`r6'Q-%d~%d~%g~%g|+Fa_rFcjrF\brFe
[sFg[s-F`r6$F[]sFedrF]_sFa_rFa_rFa_rF(,
I6write_semi_elementaryf*6,F]_lFd_lFiemFjemFdfoFgcnFKF\[sF[[sF][sF^[sFa_rFa_rC*
F`[s-F`r6&Fd[s""&Fe[sFg[sFi[sFf\s-F`r6&Q,~~%d~%d~%d|+Fa_r&F`]sFjgr&F`]sFairF\]s
@$553/F\]sFao-F_el6$Fcas<(F,FhnFbtFcjr""'""(330F\]sFao/FdasFaoFjas33Fabs/FdasF,
-F_el6$Fcas<&FhnFbtF]bsF^bs?(Fj_rF,F,-F.6#Ff]sF1C&>Fd_r-F]_r6$Fe]sF[^s-F`r6$Q%~
~%dFa_rF]hr?(Fc`rF,F,F]hrF1F_^sFh^sFj^sF]_sFa_rFa_rFa_rF(,
I2write_separatricef*6#F[[s6(%&transGF_pF'%#p2GFehmFiemFa_rFa_rC/>Fd_rFigrF\^s?
(Fj_rF]hrF^vF,F1C&>FcbrFehr?(Fc`rF,F,FhnF1-F`r6$Q$~%gFa_r-F_o6#&FcbrFe^s?(Fc`rF
btF,""*F1-F`r6$FjxFedsFh^s>F``rF`ir-F`r6%Q'%g~%g|+Fa_r-F_o6#&F``rFjgr-F_o6#&F``
rFair>Fd_r&Fg_r6#Fbt-F`r6'Q-%g~%g~%g~%g|+Fa_r-F_o6#&Fd_rFjgr-F_o6#&Fd_rFair-F_o
6#&Fd_rFfes-F_o6#&Fd_r6#Fcjr-Fadl6#&Fg_rFffs>F^br-F]_r6$&Fg_r6#F_asF[^s-F`r6$Fb
x-F.6#F^br?(Fc`rF,F,FagsF1-F`r6%Fa^s-F[[m6$F,&F^brFe^s-F[[m6$FhnFhgsFh^s-F`r6$F
gw&Fg_r6#F]bsFa_rFa_rFa_rF(,
I1write_degeneratef*6&F]_lFd_l%+trajectorsGF][s6#F_pFa_rFa_rC)F`[s-F`r6&Fd[sF]b
sFe[sFg[s-F`r6$F_emFc\l-F`r6$Fgw-F.F]\s?(Fd_rF,F,F[isF1-Fdcs6#&F\brF^hr-F`r6$Fg
wFedrF]_sFa_rFa_rFa_rF(,
I*write_gcff*6#%%gcffG6-F_pF]fnF^fn%#z1G%#z2GFiinFiirFjirFgcnFehmF\pFa_rFa_rC&-
F\r6#Fcs>Fafr-Fdbn6%Fg_rFYFin@%/FafrFao-F`r6$FgwFaoCE>Fhdr-FcarF^js-F`r6%Q&%d~%
dFa_rFafrF]gr?(Fd_rF,F,F]grF1-F`r6&Q*~%d~%d~%gFa_r-F[[m6$F,&FhdrF^hr-F[[m6$FhnF
_[t-F_o6#-F[[m6$FbtF_[tFh^s>Fj_rF^t>Fc`rF_t>8.-Fffn6%/FY*$)F^brFj_rF^v/Fin*&F``
rF,)F^brFc`rF^vFg_r>Fi[t-FQ6%Fi[tF``rF^br>Fi[t-Facm6#Fi[t>Fhdr-FcarFd\t-F`r6$Fb
xF]gr?(Fd_rF,F,F]grF1FjjsFh^s>Fi[t-Fffn6%/FY*&F``rF,F^\tF^v/Fin*$Fa\tF^vFg_r>Fi
[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd_rF,F,F]grF1FjjsFh^s>Fi[t-Fffn6%/FY,$F]\tF^vF_
\tFg_r>Fi[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd_rF,F,F]grF1FjjsFh^s>Fi[t-Fffn6%F`]t/F
in,$Fc]tF^vFg_r>Fi[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd_rF,F,F]grF1FjjsFh^s@$50Fj_rF
,0Fc`rF,C)>Fi[t-Fffn6%/FY*&FjbrF,)FcbrFj_rF^v/Fin*&FferF,)FcbrFc`rF^vFg_r>Fi[t-
Fieo6&Fi[tFcbrFjbrFfer>Fi[tFf\t>Fhdr-FgcrFj_tFj\t?(Fd_rF,F,F]grF1-F`r6'Q-~%d~%d
~%d~%gFa_rF][tF`[tFd[t-F_o6#-F[[m6$FcjrF_[tFh^sF]_sFa_r6$F^tF_tFa_rF(,
I,write_curvef*6#%'curvefGFfisFa_rFa_rC$>FafrF]js@%F`jsFajsCE>FhdrFejsFfjs?(Fd_
rF,F,F]grF1FjjsFh^s>Fj_rF^t>Fc`rF_t>Fi[tFj[t>Fi[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd
_rF,F,F]grF1FjjsFh^s>Fi[tF^]t>Fi[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd_rF,F,F]grF1Fjj
sFh^s>Fi[tFi]t>Fi[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd_rF,F,F]grF1FjjsFh^s>Fi[tFb^t>
Fi[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd_rF,F,F]grF1FjjsFh^s@$F[_tC)>Fi[tF`_t>Fi[tFi_
t>Fi[tFf\t>FhdrF]`tFj\t?(Fd_rF,F,F]grF1F_`tFh^sFa_r6%F^tF_tF[oFa_rF(,
I0write_isoclinesf*6#%+isoclinesfGFfisFa_rFa_rC'-F\r6#%0isoclines_tableG>FafrF]
js@%F`jsFajsCE>FhdrFejsFfjs?(Fd_rF,F,F]grF1FjjsFh^s>Fj_rF^t>Fc`rF_t>Fi[tFj[t>Fi
[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd_rF,F,F]grF1FjjsFh^s>Fi[tF^]t>Fi[tFc\t>Fi[tFf\t
>FhdrFi\tFj\t?(Fd_rF,F,F]grF1FjjsFh^s>Fi[tFi]t>Fi[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(
Fd_rF,F,F]grF1FjjsFh^s>Fi[tFb^t>Fi[tFc\t>Fi[tFf\t>FhdrFi\tFj\t?(Fd_rF,F,F]grF1F
jjsFh^s@$F[_tC)>Fi[tF`_t>Fi[tFi_t>Fi[tFf\t>FhdrF]`tFj\t?(Fd_rF,F,F]grF1F_`tFh^s
-FerFectF]_sFa_r6%F^tF_tFfctFa_rF(,
I)jacobianf*6%Fb`m%$xeqG%$yeqG6#FM6"Faft-Fcim6#-Fgjm6$f*F`ftFaft6$F\fmF]fmFaft-
Fffn6$<$T&T$9$FaftFaft6&F^ft9%F_ft9&7&-FU6$&F]gt6#F,-Fju6#F_gt-FU6$Fdgt-Fju6#F`
gt-FU6$&F]gt6#FhnFfgt-FU6$F^htFjgtFaftFaftFaftF(,
I,eigenvectorf*6&FiemFjemFdfoFgcn6$%#_cGF[emFaftFaftC%@%-F]hm6$F_gtFao>8$7$F,,$
*&F]gtF,F_gtF^vF^v@%-F]hm6$F]gtFao>F\it7$FaoF,@%-F]hm6$9'Fao>F\it7$F,,$*&F`gtF,
FhitF^vF^v>F\itFdit@$F[oC$>8%-%%sqrtG6#z'6$&F\itFegt&F\itF_ht[[[[[_[[[[sF,][[[[
[[[[[sF,>F\it-F_o6#7$*&FgjtF,FajtF^v*&FhjtF,FajtF^vF\itFaftFaftFaftF(,
I,translationf*6'%"vGFYFinF]_lFd_l6$FgjqFbfoFaftFaftC&>F\it-Fffn6$<$/F_gt,&F_gt
F,FhitF,/F`gt,&F`gtF,9(F,Fdgt>Fajt-Fffn6$Fh[uF^ht@$F[oC$>F\it-F[hn6%F\itF_gtF`g
t>Fajt-F[hn6%FajtF_gtF`gt7$F\itFajtFaftFaftFaftF(,
I/transformationf*6'Fb[uFiemFjemFdfoFgcn6-FgjqFbfoF`fnFafn%#_aG%#_bGFfht%#_dG%"
MGFcbmFdbmFaftFaftC,>F\it-Fffn6$<$/FY,&*&F_gtF,8&F,F,*&F`gtF,8'F,F,/Fin,&*&Fhit
F,Fj]uF,F,*&F]\uF,F\^uF,F,Fdgt>Fajt-Fffn6$Ff]uF^ht>8,,&*&F_gtF,F]\uF,F,*&F`gtF,
FhitF,F^v>8(*&F]\uF,Fe^uF^v>8),$*&F`gtF,Fe^uF^vF^v>8*,$*&FhitF,Fe^uF^vF^v>8+*&F
_gtF,Fe^uF^v>8--Fffn6%/Fj]uFY/F\^uFin,&*&Fj^uF,F\itF,F,*&F]_uF,FajtF,F,>8.-Fffn
6%F[`uF\`u,&*&Fa_uF,F\itF,F,*&Fe_uF,FajtF,F,-F_en6%7$Fh_uFa`uFYFinFaftFaftFaftF
(,
I.normalizationf*6#Fb[u6%%#L1G%#L2G%"mGFaftFaftC)>F\it-Fcar6%-Fe\n6%FdgtFYFinFY
Fin>Fajt-Fcar6%-Fe\n6%F^htFYFinFYFin>F\it-Fgjm6$f*F`ftFaftFgftFaft-F_o6#-F\hm6#
&F]gt6#FbtFaftFaftFaftF\it>Fajt-Fgjm6$f*F`ftFaftFgftFaftF`buFaftFaftFaftFajt>Fj
]u-F^jm6$-F[[m6#F\it-F[[m6#Fajt@$4F[o>Fj]u-F66$Fj]uF^im-F_en6%7$,$*&FdgtF,Fj]uF
^v"%+5,$*&F^htF,Fj]uF^vF[duFYFinFaftFaftFaftF(,
I)manifoldf*6%F\pF[em%'stableG6.%$vf1G%$vf2G%#h1G%#h2GF'F^auF_auF[[sFafn%'lambd
aGFa_p%#n1GFaftFaftC*@%F[oC$>F\it-F_o6#Fdgt>Fajt-F_o6#F^htC$>F\itFdgt>FajtF^ht>
F]_u-F`dm6%-%(collectG6$-Fffn6$/FinFaoFdgtFYFYF,>Fa_u-F`dm6%-Fieu6$-Fffn6$/FYFa
oF^htFinFinF,>Fe_uFao?(Fj^uFhnF,F_gtF1C)>Fh_u*&-F`dm6%-Fieu6$-Fffn6$F]fuFajtFYF
YFj^uF,,&*&F]_uF,Fj^uF,F,Fa_uF^vF^v@$3FbcuFdjm>Fh_u-Fijm6#Fh_u>Fj]u-F^eo6#-Fffn
6$/Fin,&Fe^uF,*&Fh_uF,)FYFj^uF,F,F\it>F\^u-F^eo6#,&-Fffn6$F]huFajtF,**Fh_uF,Fj^
uF,)FY,&Fj^uF,F^vF,F,Fj]uF,F^v>F\it-Fffn6$/Fe^uFinFj]u>Fajt-Fffn6$F]iuF\^u>Fe_u
,&Fe_uF,F_huF,@$Fj\lC&-F`r6#Q>Testing~separatrix~for~x~>~0|+Faft>Fa`u-%1separat
rice_testG6'Fe_uF]gtF_gtF`gtF,>8/F_gt?(FaftF,F,Faft34Fa`u2F]juF_^lC%>F]ju,&F]ju
F,F,F,@%1Fh]lF]juC)@$/F]juFh]lC$>F\it-F_oF^cu>Fajt-F_oF`cu>Fh_u-F_o6#*&-F`dm6%F
]guFYF]juF,,&*&F]_uF,F]juF,F,Fa_uF^vF^v>Fj]u-F^eo6#-Fffn6$/Fin,&Fe^uF,*&Fh_uF,)
FYF]juF,F,F\it>F\^u-F^eo6#,&-Fffn6$F\\vFajtF,**Fh_uF,F]juF,)FY,&F]juF,F^vF,F,Fj
]uF,F^v>F\itF[iu>FajtF_iu>Fe_u,&Fe_uF,F^\vF,C)>Fh_uFb[v@$Fdgu>Fh_uFfgu>Fj]uFh[v
>F\^uFa\v>F\itF[iu>FajtF_iu>Fe_uF\]v>Fa`u-Fjiu6'Fe_uF]gtF]juF`gtF,@$Fj\lC%-F`r6
#Q>Testing~separatrix~for~x~<~0|+Faft>Fa`u-Fjiu6'Fe_uF]gtF]juF`gtF^v?(FaftF,F,F
aftF_juC%>F]juFdju@%FfjuC)@$FijuC$>F\itF\[v>FajtF^[v>Fh_uF`[v>Fj]uFh[v>F\^uFa\v
>F\itF[iu>FajtF_iu>Fe_uF\]vC)>Fh_uFb[v@$Fdgu>Fh_uFfgu>Fj]uFh[v>F\^uFa\v>F\itF[i
u>FajtF_iu>Fe_uF\]v>Fa`uFg]v-Fffn6$/FYF[^sFe_uFaft6#Fj\lFaftF(,
I0center_manifoldf*F`du63FcduFdduFeduFfduF'F_auF[[sFafnFgduFa_pFhduFgarFjemF`au
%#amGF\[s%(stable2GFaftFaftC/@%F[oC$>F\itF]eu>FajtF`euC$>F\itFdgt>FajtF^ht>F]_u
F_fu>Fa_uFao>Fa`uF_gt?(Fj^uFhnF,Fa`uF1C+>Fe^u,$*&F[guF,F]_uF^vF^v@$Fdgu>Fe^u-Fi
jm6#Fe^u>Fj]u-F^eo6#-Fffn6$/Fin,&Fe_uF,*&Fe^uF,F`huF,F,F\it>F\^u-F^eo6#,&-Fffn6
$F\bvFajtF,**Fe^uF,Fj^uF,FhhuF,Fj]uF,F^v>F\it-Fffn6$/Fe_uFinFj]u>Fajt-Fffn6$Fib
vF\^u>Fa_u,&Fa_uF,F^bvF,>F]ju-Fbhm6$-Fffn6$F]fuF\itFY@$/F]juFao>Fa`u,&Fa`uF,F,F
,>80-Fc_n6$F]juFY>81-Ffdm6$FicvFY>82-F_o6#-Fffn6$/FYF,Ficv@%-Faq6$F]dv%%evenG@%
1FaoFadv@%/F`gtFao>83F,>F`evFhn@%F^ev>F`evFbt>F`evFcjr@%F\ev@%F^ev>F`evF_as>F`e
vF]bs@%F^ev>F`evF^bs>F`evF`w@$Fj\lC$@%-F_el6$F`ev<$FhnF]bs>84Fao>FcfvF,@$-F_el6
$F`ev<&FhnFbtF]bsF^bsC%-F`r6#QETesting~center~separatrix~for~x~>~0|+Faft>Fh_u-F
jiu6'Fa_uF]gtFa`uFcfvF,?(FaftF,F,Faft34Fh_u2Fa`uF_^lC%>Fa`uFgcv@%1Fh]lFa`uC)@$/
Fa`uFh]lC$>F\itF\[v>FajtF^[v>Fe^u-F_o6#,$*&-F`dm6%-Fieu6$-Fffn6$/FinFa_uFajtFYF
YFa`uF,F]_uF^vF^v>Fj]u-F^eo6#-Fffn6$/Fin,&Fe_uF,*&Fe^uF,)FYFa`uF,F,F\it>F\^u-F^
eo6#,&-Fffn6$F_ivFajtF,**Fe^uF,Fa`uF,)FY,&Fa`uF,F^vF,F,Fj]uF,F^v>F\itFgbv>FajtF
[cv>Fa_u,&Fa_uF,FaivF,C)>Fe^uFahv@$Fdgu>Fe^uFeav>Fj]uF[iv>F\^uFdiv>F\itFgbv>Faj
tF[cv>Fa_uF_jv>Fh_uF^gv@$Fj\lC$@%-F_el6$F`ev<$FcjrF]bs>FcfvFao>FcfvF,@$-F_el6$F
`ev<&F,FcjrF]bsF^bsC%-F`r6#QETesting~center~separatrix~for~x~<~0|+Faft>Fh_u-Fji
u6'Fa_uF]gtFa`uFcfvF^v?(FaftF,F,FaftFagvC%>Fa`uFgcv@%FggvC)@$FjgvC$>F\itF\[v>Fa
jtF^[v>Fe^uF_hv>Fj]uF[iv>F\^uFdiv>F\itFgbv>FajtF[cv>Fa_uF_jvC)>Fe^uFahv@$Fdgu>F
e^uFeav>Fj]uF[iv>F\^uFdiv>F\itFgbv>FajtF[cv>Fa_uF_jv>Fh_uF^gv>F]ju-Fbhm6$-Fffn6
$FihvF\itFY7%-Fffn6$F\`vFa_uF]juF`evFaftF]`vFaftF(,
I'saddlef*6,Fb`mF]_lFd_lFiemFjemFdfoFgcn%$rhoG%&sigmaGF][s6/%(lambda1G%(lambda2
G%-lambda_ratioG%1lambda_ratio_numG%1lambda_ratio_denGFcfoF\pFcbm%#v1G%#v2GFadu
%%sep1G%%sep2GFaftFaftCA-F`r6%Q<(%a,%a)~is~a~saddle~point.|+Faft-F_oFggt-F_oF[h
t-F\r6#FgelF^_w-F\r6#F^r>F\it,&9+#F,Fhn-Fcjt6#9,#F^vFhn>Fajt,&Fi_wFj_wF[`wFj_w@
%2-F\hm6#F^[v-F\hm6#F\[v>Fj]u*&F\itF,FajtF^v>Fj]u*&FajtF,F\itF^v@%33Fbcu-Faq6$F
\it%(integerG-Faq6$FajtF`awC(>F\^u-Facm6#Fj]u>Fj^u-FfcmFfaw-F`r6%QHThe~ratio~be
tween~eigenvalues~is~%a:%a|+6"Fj^uF\^uFc_wFiawFe_wC*>Fj]u-F66$-F_oFfawF^im>Fj]u
F_bw>F\^uFeaw>Fj^uFhaw-F`r6%QXThe~ratio~between~eigenvalues~is~%a:%a~(approxima
tion)|+F\bwFj^uF\^uFc_wFebwFe_w>Fe^u-Fbht6&,&FhitF,F\itF^vF]\u9),&9*F,F\itF^v>F
h_u-Fbht6&,&FhitF,FajtF^vF]\uF\cw,&F^cwF,FajtF^v@$F^cpC&Fc_w-F`r6%QB~The~eigenv
alues~are:~|fr~%a,~%a~|hr|+FaftF\itFajt-F`r6%QC~The~eigenvectors~are:~|fr~%a,~%
a~|hr|+FaftFe^uFh_uFe_w@$F^cp-F\r6$F^rFgel@%50F_gtFao0F`gtFaoC%>F]_u-F_[u6'F]gt
FYFinF_gtF`gt-F`r6#QIMoving~this~saddle~point~to~the~origin.|+F\bw-F`r6$Q<The~n
ew~vector~field~is~%a|+FaftF]_u>F]_uF]gt>Fe_u-Fj\u6'F]_u&Fe^uFegt&Fh_uFegt&Fe^u
F_ht&Fh_uF_ht-F`r6#Q\oTransform~this~vector~field~so~that~the~linear~part~is~di
agonal.|+F\bw-F`r6$F\ewFe_u>Fa_u-Fj`u6#Fe_u-F`r6#Q;Make~a~1000-normalization|+F
aft-F`r6$QDso~that~the~new~vector~field~is~%a|+FaftFa_u-F`r6#QIWe~calculate~the
~invariant~separatrices|+FaftFe_w@%2F\[vFao>Fa`uF,>Fa`uFao>F]ju-F^du6%Fa_uFa]lF
a`u@%2F^[vFao>Fa`uF,>Fa`uFao>Ficv-F^du6%-Fj\u6'Fa_uFaoF,F,FaoFa]lFa`u@%-Fjfm6$F
\itFaoC%-F`r6$Q?The~stable~separatrice~is~%a.|+F\bw7$FicvF[^s-F`r6$QAThe~unstab
le~separatrice~is~%a.|+F\bw7$F[^sF]ju@$F^cpC&Fc_wFjgwF^hwFe_wC%-F`r6$F\hwFahw-F
`r6$F`hwF]hw@$F^cpC&Fc_wFehwFghwFe_w-F`r6#QZ###################################
#####################|+F`emFc_wF[iwFe_w-Fhjr6,F_gtF`gtFaewFbewFcewFdewFa_u7$F]j
uFicv7$-%%signGFf`w-FciwFd`w9-FaftFaftFaftF(,
I-strong_focusf*6'Fb^wFa^wF]_lFd_lF][s6%Fd^wFe^wFehmFaftFaftC*>F\it,&F_gtFj_w-F
cjt6#F]gtF^`w>Fajt,&F_gtFj_wF]jwFj_w@%-FjfmFjhtC'-F`r6%QE(%a,%a)~is~a~strong~un
stable~focus.|+FaftFb_w-F_o6#FhitFc_wFdjwFe_w>Fj]uF,C'-F`r6%QC(%a,%a)~is~a~stro
ng~stable~focus.|+FaftFb_wFgjwFc_wF[[xFe_w>Fj]uF^vF[iwFc_wF[iwFe_w-Fa`s6&F`gtFh
itFj]uF]\uFaftFaftFaftF(,
I%nodef*6(Fb`mFb^wFa^wF]_lFd_lF][s6(FehmFd^wFe^wFf^wFg^wFh^wFaftFaftC,@%-Ffem6$
F`gtFaoC'-F`r6%Q;(%a,%a)~is~a~stable~node.|+F\bwFgjw-F_o6#F]\uFc_wFj[xFe_w>F\it
F^vC'-F`r6%Q>(%a,%a)~is~an~unstable~node.|+F\bwFgjwF]\xFc_wFa\xFe_w>F\itF,>Fajt
,&F`gtFj_w-FcjtFggtF^`w>Fj]u,&F`gtFj_wFg\xFj_w@%2-F\hm6#FabwFc`w>F\^u*&FajtF,Fj
]uF^v>F\^u*&Fj]uF,FajtF^v@%33FbcuFaaw-Faq6$Fj]uF`awC(>Fj^u-Facm6#F\^u>F]_u-Ffcm
Fj]x-F`r6%F[bwF]_uFj^uFc_wF]^xFe_wC*>F\^u-F66$-F_oFj]xF^im>F\^uFa^x>Fj^uFi]x>F]
_uF\^x-F`r6%FgbwF]_uFj^uFc_wFg^xFe_wF[iwFc_wF[iwFe_w-F__s6&FhitF]\uF\itF\cwFaft
FaftFaftF(,
I+degeneratef*6&Fb`mF]_lFd_lF][s6#FbhsFaftFaftC--F`r6%QD(%a,%a)~is~a~non-elemen
tary~point.|+FaftFa_wFb_w-F`r6#Q@Blowing~up~the~vector~field...|+FaftFc_wF`_xFe
_w>F\it-%+blowing_upG6&F]gtF_gtF`gtF1F[iwFc_wF[iwFe_w-F_hs6&F_gtF`gtF\itFhitFaf
tFaftFaftF(,
I0semi_elementaryf*6+Fb`mF]_lFd_lFiemFjemFdfoFgcnFe^wF][s6,Fi^wFj^wFcfoF\pFcbm%
+center_sepGF[_wF\_wF\[sFaduFaftFaftC=>F\it-Fbht6&FhitF]\uF\cwF^cw>Fajt-Fbht6&,
&FhitF,Fi_wF^vF]\uF\cw,&F^cwF,Fi_wF^v>Fj]uFedw>Fj^u-Fj\u6'Fj]uFgjt&FajtFegtFhjt
&FajtF_ht>F\^u-Fj`u6#Fj^u-F`r6%Qhn(%a,%a)~is~semi-hyperbolic.|+Moving~this~poin
t~to~the~origin.|+FaftFa_wFb_w-F`r6$F\ewFj]uFeew-F`r6$F\ewFj^uF]fw-F`r6$FbfwF\^
uFcfwFc_w-F`r6%Q=(%a,%a)~is~semi-hyperbolic.|+FaftFa_wFb_w@$F^cpC)-F`r6#QBMovin
g~this~point~to~the~origin.|+F\bwFfaxFeewFhaxF]fwFjaxFcfwFe_w@%-Ffem6$Fi_wFao>F
h_uF,>Fh_uFao>F]_u-F^`v6%F\^uFa]lFh_u>Fa_u-Fffn6$F\`v&F]_uFegt>Fe_u-Fffn6$F\`v-
F^du6%-Fj\u6'F\^uFaoF,F,FaoFa]lFh_u>Fe^u&F]_uFebu@%-F_el6$Fe^u<$F,FbtC)-F`r6#Q8
We~have~a~saddle-node.|+Faft-F`r6$Q7center~separatrice~%a|+Faft7$F[^sFa_u-F`r6$
Q9unstable~separatrice~%a|+Faft7$Fe_uF[^sFc_wF^dx@$F^cpC$FadxFedxFe_w@%-F_el6$F
e^u<$FhnFcjrC)F^dxFadx-F`r6$Q7stable~separatrice~%a|+FaftFhdxFc_wF^dx@$F^cpC$Fa
dxF`exFe_w@%/Fe^uF]bsC)-F`r6#Q3We~have~a~saddle.|+Faft-F`r6$Q@unstable~center~s
eparatrice~%a|+FaftFddxF`exFc_wFhex@$F^cpC$F[fxF`exFe_w@%/Fe^uF^bsC)Fhex-F`r6$Q
>stable~center~separatrice~%a|+FaftFddxFedxFc_wFhex@$F^cpC$FcfxFedxFe_w@%/Fe^uF
_asC)-F`r6#Q;We~have~an~unstable~node.|+FaftFadxFedxFc_wF[gx@$F^cpC$FadxF`exFe_
wC)-F`r6#Q8We~have~a~stable~node.|+FaftFadxF`exFc_wFagx@$F^cpC$FadxF`exFe_wF[iw
Fc_wF[iwFe_w-Fi`s6,F_gtF`gtFgjtF^axFhjtF_axF\^u7$Fe^uF,7$Fa_uFe_uF]`wFaftFaftFa
ftF(,
I*sing_typef*F]_x6&%$jacG%&deltaGFa^wFb^wFaftFaftC,>F\it-F[ft6%F]gt/FYF_gt/FinF
`gt@$Fdgu>F\it-Fgjm6$FijmF\it>Fajtz'6&FgjtFhjt&F\itFebu&F\it6#Fcjr\[[[[[[[[\[[m
F,[[[\[[\[[[[[mF^v@$Fdgu>Fajt-FijmF`cu>Fj]u,&FgjtF,F]ixF,@$Fdgu>Fj]u-FijmFfaw>F
\^u,&*$Fj]uFhnF,Fajt!"%@$Fdgu>F\^u-FijmFj]x@$F^cpC)Fc_w-F`r6%Q>(%a,%a)~is~a~sin
gular~point.|+FaftF_gtF`gt-F`r6'QGJacobian~=~[~[~%a,~%a~],~[~%a,~%a~]~]|+FaftFg
jtFhjtF\ixF]ix-F`r6$Q,Delta~=~%a|+FaftFajt-F`r6$Q*Rho~=~%a|+FaftFj]u-F`r6$Q,Sig
ma~=~%a|+FaftF\^uFe_w@%-Ffem6$FajtFao-F^^w6,F]gtF_gtF`gtFgjtFhjtF\ixF]ixFj]uF\^
uFhit@%-FjfmFa[y@%-F_gm6$F\^uFao-Fa[x6(F]gtF\^uFj]uF_gtF`gtFhit@%-Fdgm6$Fj]uFao
-%+weak_focusG6&F]gtF_gtF`gtFhit-Ffiw6'F\^uFj]uF_gtF`gtFhit@%F\\y-F[_xF`\y-F\`x
6+F]gtF_gtF`gtFgjtFhjtF\ixF]ixFj]uFhitFaftFaftFaftF(,
I1separatrice_testf*6'F[[sFKF[emFadu%$dirG6'Fa_p%'rndnumG%(exefileG%(sepfileGF'
FaftFaftC2>Fj]u-FC6$%,user_bindirG%,user_sepexeG>Fajt-%%iremG6$-%%randGFaftF[du
>F\^u-FC6&%,user_tmpdirGQ'P4SEP_FaftFajtQ%.TMPFaft-F\rFj]x-F`r6$F_emFc\l-F`r6$F
gwF]\u-F`r6$FgwFhit-FadlFggt-F`r6$Fgw,&F`gtF,F^vF,?(Fj^uFhnF,F`gtF1-F`r6%Q'%d~%
g~FaftFj^u-F`dm6%F]gtFYFj^u-F`r6#Fay-FerFj]x-F`r6$Q;Separatrix~test~(n=%d)...~F
aftF`gt>F\it-%(ssystemG6#-FC6'%/user_exeprefixGFj]uQ#~"F`emF\^uQ""F`em-Fj_y6#-F
C6&%/user_removecmdGF_`yF\^uF``y@%/FgjtFaoC$-F`r6#Q(not~ok|+FaftFboC$-F`r6#Q$ok
|+FaftF1Faft6(F^`yF^^y%,user_lypexeGFc]yFe`yFc\lFaftF(,
I+weak_focusf*6&Fb`mF]_lFd_lF][s6-F\[sFcfo%%aa10G%%aa01G%%bb10GFiinF\pF`fn%#ggG
%$lypGF_anF`emF`emC,-F`r6%Q:(%a,%a)~is~a~weak~focus.|+F`em-F_o6#9%-F_o6#9&-F\r6
#FgelF\by-F\r6#F^r@%FjdlC*>8.,&-%*integrateG6$&9$6#F,FinF,-F_cy6$,&-FU6$F^cyFYF
^v&Fbcy6#FhnF^vFYF,-F`r6#QTSince~the~system~is~hamiltonian,~we~have~a~center.|+
F`em-F`r6$QKThe~Hamiltonian~function~is:|+~H(x,y)~=~%a|+F`emF\cyFebyF[dyF^dyFgb
y>8$FcjrC.>8%-F_[u6'FbcyFYFinFabyFdby>8&-F`dm6%-F`dm6%&FedyFccyFYF,FinFao>8'-F`
dm6%-F`dm6%F^eyFYFaoFinF,>8(-F`dm6%-F`dm6%&FedyFjcyFYF,FinFao>8)-Fcjt6#,&*&F`ey
F,FfeyF,F^v*$FidyFhnF^v>8*7$,&*(FfeyF,-Fffn6$<#/FY,&*(F]fyF,8+F,FfeyF^vF^v*(Fid
yF,FinF,FfeyF^vF,F^eyF,F]fy!"#F,*(FidyF,-Fffn6$FjfyF[fyF,F]fyF`gyF^v,$*&-Fffn6$
<#/FY,&*(F]fyF,FYF,FfeyF^vF^vF_gyF,F[fyF,F]fyF^vF^v@%F`[l>Fdfy-F_o6#-Fffn6$/F^g
yFYFdfy>FdfyF`hy-F`r6$Q6The~local~system:~%a|+F`emFdfy>8,,&-Fffn6$<$/FY,&Ffhm#F
,Fhn%"wGF_iy/Fin*&^##F^vFhnF,,&FfhmF,F`iyF^vF,&FdfyFccyF,*&^#F,F,-Fffn6$F\iy&Fd
fyFjcyF,F,>Fhhy-F^eo6#Fhhy@$F^cpC%Feby-F`r6$Q)z'~=~%a|+F`emFhhyFgby@%/Ff^lFaoC%
-F\r6$FgelF^r-F`r6#QenLyapunov~constants~are~not~calculated.~(weakness~level=0)
|+F`em>FbdyFaoC%@%F`[l>8--%)lyapunovG6%,&FhhyF,*&^#F^vF,FfhmF,F,FfhmF`iy>F`[z-%
,lyapunovsymGFc[z-F`r6$Q:Lyapunov~information:~%a|+F`emF`[z@%0&F`[zFccyFaoC'Fgj
y-F`r6$Q=The~order~of~weakness~is~%d|+F`em&F`[zFjcy-F`r6$Q9Lyapunov~constant~is
~%g|+F`em,$F_\zF^vFgby@%2F_\zFaoC'-F`r6#QBWe~have~an~unstable~singularity.|+F`e
mFebyF\]zFgby>FbdyF,C'-F`r6#Q?We~have~a~stable~singularity.|+F`emFebyFa]zFgby>F
bdyF^v@%/&F`[z6#FbtFhnC'-F`r6#QMWe~have~a~center~(the~system~is~quadratic).|+F`
emFebyFj]zFgby>FbdyFcjr@%&F`[z6#FcjrC'-F`r6#QPWe~have~a~center~(the~system~is~l
inear+cubic).|+F`emFebyFb^zFgby>FbdyFcjrC'-F`r6$QGThe~order~of~weakness~is~at~l
east~%d.|+F`em,&Ff^lF,F,F,FebyFg^zFgby>FbdyFaoFeby-F`r6#F]iwFgbyF\_z-Fi_s6&Faby
Fdby9'FbdyF`em6#FjdlF`emF(,
I)lyapunovf*6%Fb`mFfhmF`iy6,Fiem%'bindirG%'infileG%(outfileGF]]y%'resultGF\]y%#
wlG%&linfoG%$auxGF`emF`emC,>Fdfy-Fg]y6$-Fj]yF`emF[du>Fidy-FC6&F^^yQ'P4LYP_F`emF
dfyQ%.INPF`em>F`ey-FC6&F^^yFe`zFdfyQ%.OUTF`em@%/FcrFao>Ffey-FC6$Fc]yFaay>Ffey-F
C6$Fc]y%0user_lypexe_mpfG>Fhhy-%4preparelyapunovfileG6&FidyFbcyFabyFdby>F^gy&Fh
hyFccy-F`r6#QDDetermining~lyapunov~constants~...|+F`em>F`[z-Fj_y6#-FC6.F^`yQ!F`
emFfeyF_`yFidyQ$"~"F`emF`eyQ)"~MAPLE~F`em%.user_platformGF_`y%2user_sumtablepat
hGF``y>F]fy-%3readlyapunovresultG6$F`eyF^gy7%-F[[m6#F]fy&FhhyFjcy&FhhyFh]zF`em6
)F^`yF^^yFaayFcazFcrFc]yFe`yF`emF(,
I3readlyapunovresultf*6$Fc`o%*weaklevelG6)%(lypdataG%&VdataGF_pF[em%%wvalG%'lyp
valG%&okvalGF`emF`emC.>Fbdy-%)readdataG6$FbcyF,-F`r6$Q4lyapunov~data~=~%a|+F`em
Fbdy>Fedy7">F`eyF,-F\r6$F^rFgel?(FidyF,F,FabyF1C&@$0&Fbdy6#F`eyF^v-F`r6%Q*V(%d)
=%g|+F`em-%&roundG6#F\ez&Fbdy6#,&F`eyF,F,F,>Fedy7$-F[[m6#Fedy7$FaezFdez@$/FaezF
^vC$>F`eyFfez[>F`ey,&F`eyF,FhnF,@$F]fz>F`eyFfez>FdfyFaez>Ffey-Fbez6#Fdez>F]fy&F
bdy6#FbfzFgby7$F]fyFfeyF`emF`emF`emF(,
I4preparelyapunovfilef*6&Fc`oFf_nFfhmF`iy6)Fb`m%&cubicGFehmFgcnFiemF_pFj_zF`emF
`emC.>Fbdy-Fe\n6%FabyFdbyF`_z>FedyFbo-F\r6#Fbcy-F`r6$Fgw,&FcrFhnFhnF,>F`ey-Fdbn
6%FbdyFdbyF`_z@%/F`eyFhnC$>FdfyFbt-F`r6#Q#3|+F`em@%/F`eyFbtC$>FdfyF_as@%33/-F`d
m6%-F`dm6%FbdyFdbyFhnF`_zFaoFao/-F`dm6%-F`dm6%FbdyFdbyFaoF`_zFhnFao/-F`dm6%-F`d
m6%FbdyFdbyF,F`_zF,FaoC$-F`r6#Q#5|+F`em>FedyF1C$>FdfyFf^l-F`r6$FgwFf^lC$>FdfyFf
^lFcjz-F`r6$F_em)Fgfm,$F_wF^v>Fidy-FcarF^hz-F`r6$Fgw-F.6#Fidy?(F]fyF,F,F_[[lF1C
$>Ffey&FidyF]cz-F`r6'Q/~~%d~%d~%g~%g|+F`em&FfeyFccy&FfeyFjcy-F_o6#-Fjep6#&FfeyF
h]z-F_o6#-FaepF]\[l-FerFhgz7%FdfyF`eyFedyF`emF`emF`emF(,
I,lyapunovsymf*6%Ff_nFfhmF`iy6+Fb`mF[`zFj_zF'%"TG%"VGFi_zFa_pF_pF`emF`emC,>Fbdy
-Fe\n6%FbcyFabyFdby>Fedy-%3preparelyapunovsymG6%FbdyFabyFdby>FidyF^ey>FdfyFddz>
F^gyFboFfdz?(F`eyF,F,FidyF1C(>Ffey-%)sumtableG6#,$F`eyFhn>F]fyFao?(FhhyF,F,-F.6
#FfeyF1>F]fy,&F]fyF,-%4part_lyapunov_coeffG6'FbdyFabyFdby&FfeyF^jy,&F`eyFhnF,F,
F^v>Fdfy7$-F[[m6#Fdfy7$F]fyF`ey-F`r6&Q2k=%d~V~=~%a~=~%f|+F`emF`eyF]fy-F_oF]cz@$
-F]hm6$F]fyFaoC$>F^gyF1F`fzFgby@%F^gy>Fdfy&Fdfy6#F^v>Fdfy7$FaoFao7%Fi^[lF[fy&Fe
dyFh]zF`emF`emF`emF(,
I3preparelyapunovsymf*Fd_z6(FagzFehmFgcnFiemF_pFj_zF`emF`emC'>FbdyFbo>Fidy-Fdbn
F]][l@%/FidyFhn>F]fyFbt@%/FidyFbtC$>F]fyF_as@%33/-F`dm6%-F`dm6%FbcyFabyFhnFdbyF
aoFao/-F`dm6%-F`dm6%FbcyFabyFaoFdbyFhnFao/-F`dm6%-F`dm6%FbcyFabyF,FdbyF,Fao>Fbd
yF1>F]fyFf^l>F]fyFf^l>Fedy-FcarF]][l7%F]fyFidyFbdyF`emF`emF`emF(,
I)sumtablef*6#F[em6&FehmF%Fiin%+st_compareGF`emF`emC&>Fbdy-%*piecewiseG6%/FbcyF
ao7#7#F,-Fgjm6$F[[m-Fgjm6$&%)combinatG6#%(permuteG-&Fec[l6#%*partitionG6$FbcyFb
cy>F`eyf*6$F%FiinF`em6$F\fmF]fmF`em@%2Facy&FabyFccyF1@%/FacyFcd[l-T#6$&Fbcy6#;F
hnF^v&FabyFjd[lFboF`emF`em6$Fgb[lF`ey>Fbdy-F[jn6$FbdyF`eyOFbdyF`emF`emF`emF(,
I4part_lyapunov_coefff*6'%)vecfieldGFfhmF`iyFehmF'6(%"RGFMFb`mFb[u%#wwGF`pF`emF
`emC%>Fbdy-Fgjm6$f*6#FMF`emF`d[lF`em-%-lyp_findpolyG6&T$T&T(,&FbcyF,F,F,F`emF`e
m6(Fee[lFbcyFfhmFabyF`iyFdbyF`_z@%4-F_el6$FaoFbdyC&>FidyF^v?(F]fyF,F,,&-F.6#Fbd
yF,F^vF,F1@%-Faq6$,&F]fyF,F^vF,%$oddG>Fidy-%)lyp_RegzG6&Fidy&FbdyF]czFabyFdby>F
idy-%)lyp_ImgzGFig[l>F]fyF_g[l@%Fbg[lC%>Fidy-%/lyp_multc_polyG6'FidyFaoF^vFabyF
dby>6$FidyF`ey-F[[m6#-%'lyp_LLG6'FidyFjg[lFabyFdby,&9(F_iyFdiyF,>Ffey-Fjbl6#-Fa
epF]ezC$>Ffh[lFgh[l>Ffey-Fjbl6#-FjepF]ez>FfeyFaoOFfeyF`emF`emF`emF(,
I/lyp_multc_polyf*6'Fb`mFiemFjemFfhmF`iyF`emF`emF`emO-F^eo6#*&,&FabyF,*&FhiyF,F
dbyF,F,F,FbcyF,F`emF`emF`emF(,
I-lyp_findpolyf*6&FKFfhmF`iyF[em6$F%F'F`emF`emC%>FbdyFao?(FedyFaoF,F`_zF1>Fbdy,
&FbdyF,*(-F`dm6%-F`dm6%FbcyFabyFedyFdby,&F`_zF,FedyF^vF,)FabyFedyF,)FdbyFa[\lF,
F,FbdyF`emF`emF`emF(,
I)lyp_Regzf*6&Fb`mF\pFfhmF`iy6#F%F`emF`emC(>Fbdy-F^eo6#*&FbcyF,FabyF,>Fbdy-Fch[
l6'FbdyFaoF^vFdbyF`_z>Fbdy-FU6$FbdyFdby>Fbdy-%&lyp_GGF^hz>Fbdy,&FbdyF,-%.lyp_co
nj_polyGF^hzF,O-Fch[l6%FbdyF_iyFaoF`emF`emF`emF(,
I)lyp_Imgzf*Ff[\lFg[\lF`emF`emC'>FbdyFj[\l>FbdyFa\\l>FbdyFd\\l>Fbdy,&FbdyF,Fh\\
lF^vO-Fch[l6%FbdyFaoFdiyF`emF`emF`emF(,
I'lyp_LLf*6'Fb`mF\pFfhmF`iyF[emFg[\lF`emF`emC$>Fbdy-FU6$Fj[\lFdby7$Fbdy-F`dm6%-
F`dm6%FbdyFdbyF]i[lF`_zF]i[lF`emF`emF`emF(,
I&lyp_Gf*Fd_z6&F'%#fkGF%FefoF`emF`emC%>FidyFao@$1Fao-Ffdm6$FbcyFaby?(FbdyFaoF,F
\_\lF1C$>Fedy-F`dm6%FbcyFabyFbdy@$1Fao-Ffdm6$FedyFdby?(F`eyFaoF,Fe_\lF1@%0FbdyF
`ey>Fidy,&FidyF,**-F`dm6%FedyFdbyF`eyF,,&FbdyF,F`eyF^vF^v)FabyFbdyF,)FdbyF`eyF,
Fhn>Fidy,&FidyF,*(F]`\lF,F``\lF,Fa`\lF,F,-F^eoF`[[lF`emF`emF`emF(,
I.lyp_conj_polyf*Fd_z6#%#zbGF`emF`emC$-%)assumingG6$7#-F^eo6#-Fa[oFhgz7$'Faby%%
realG'FdbyFda\l-Fcim6$-Fcim6$-Fcim6$%"%G<#/FabyFbdy/FdbyFaby/FbdyFdbyF`emF`emF`
emF(,
I5vec_field_diff_chartf*6%Fb`mFYFin6*Fgcn%%f_U1G%%f_V1G%%f_U2G%%f_V2G%$linG%%si
ngG%(sdegreeGF\bwF\bwC4>8$-F^jm6$-Fdbn6%&9$6#F,9%9&-Fdbn6%&Fdc\l6#FhnFfc\lFgc\l
>8%-F_en6%7$*&)FhisF^c\lF,,&*&FgisF,-Fffn6$<$/Ffc\l*$FhisF^v/Fgc\l*&FgisF,FhisF
^vFcc\lF,F^v-Fffn6$Fgd\lFjc\lF,F,,$*&)Fhis,&F^c\lF,F,F,F,Fed\lF,F^vFgisFhis>8&-
F_en6%7$*&Fbd\lF,,&*&FgisF,-Fffn6$<$/Ffc\l,$Fid\lF^vFjd\lFcc\lF,F,-Fffn6$F\f\lF
jc\lF,F,*&F`e\lF,Fje\lF,FgisFhis>8'-F_en6%7$*&Fbd\lF,,&-Fffn6$<$/Ffc\lF[e\l/Fgc
\lFid\lFcc\lF,*&FgisF,-Fffn6$F[g\lFjc\lF,F^vF,,$*&F`e\lF,F_g\lF,F^vFgisFhis>8(-
F_en6%7$*&Fbd\lF,,&-Fffn6$<$F\g\l/Fgc\lF^f\lFcc\lF,*&FgisF,-Fffn6$F\h\lFjc\lF,F
,F,*&F`e\lF,F_h\lF,FgisFhis@$4-F_el6$F]t<$F,FbtC&-F`r6#QCWe~make~use~of~the~Poi
ncare~disc.|+F\bw-F\r6#Fgel-F`r6#QHWe~make~a~study~on~the~Poincare~disc.|+|+F\b
w-F\r6#F^r>8)7$-Fbhm6$-Fffn6$/FhisFao&F]d\lFec\lFgis-Fbhm6$-Fffn6$Fii\l&F]d\lF[
d\lFgis@%3/&Fci\lFec\lFao/&Fci\lF[d\lFaoC(@$Fch\lC&-F`r6#QFInfinity~is~a~line~o
f~singularities.|+F\bwF[i\lFij\lF`i\l>F]d\l-F_en6%7$*&Fji\lF,FhisF^v*&F_j\lF,Fh
isF^vFgisFhis>Fcf\l-F_en6%7$*&&Fcf\lFec\lF,FhisF^v*&&Fcf\lF[d\lF,FhisF^vFgisFhi
s>Fce\l-F_en6%7$*&&Fce\lFec\lF,FhisF^v*&&Fce\lF[d\lF,FhisF^vFgisFhis>Fdg\l-F_en
6%7$*&&Fdg\lFec\lF,FhisF^v*&&Fdg\lF[d\lF,FhisF^vFgisFhis>8*F,>F[]]lFao-%,show_c
hartsG6$7&F]d\lFce\lFcf\lFdg\l7&Q#U1F\bwQ#V1F\bwQ#U2F\bwQ#V2F\bw-F\r6#Fcs-Fadl6
#-Fffn6%/FgisFfc\l/FhisFgc\lF]d\l-Fadl6#-Fffn6%F\^]lF]^]lFce\l-Fadl6#-Fffn6%F\^
]lF]^]lFcf\l-Fadl6#-Fffn6%F\^]lF]^]lFdg\l-F`r6$FgwF[]]l@%-Faq6$,&F^c\lF,F^vF,Fj
dvC$>8+Fao-F`r6#Q#1|+F\bwC$>Fb_]lF,-F`r6#Q$-1|+F\bwF`i\l@%Fch\l@%/F[]]lFao-%/fi
nd_inf_rootsG6)F^c\lFdc\lF]d\lFcf\lFfc\lFgc\lFb_]l-%4find_inf_roots_singG6$F]d
\lFcf\l-F`r6#QOSingularities~at~infinity~are~not~determined.|+F\bwF\bwF\bwF\bwF
(,
I,show_chartsf*6$%%flstG%(namelstG6$Fb`mF'F\bwF\bw?(F]d\lF,F,-F.6#Fdc\lF1C%-F`r
6$QJThe~differential~system~on~the~%s~chart:|+F\bw&Ffc\l6#F]d\l>F^c\l-Fcim6#&Fd
c\lFea]l-F`r6%Q<~~~~z1'~=~%a|+~~~~z2'~=~%a|+|+F\bw&F^c\lFec\l&F^c\lF[d\lF\bwF\b
wF\bwF(,
I.behaviour_inff*6$Fb`mFgcn64%#p1G%#q1GF`fnFafnF\pF]hxF^hxFa^wFb^wFfayFgayFhayF
iin%#zzG%$zzbGF^auF_auFjayF\bwF\bwC,>F^c\l-Fffn6$<$/FY*&Fce\lF,,&*$Fce\lFhnF,*$
Fcf\lFhnF,F^v/Fin*&Fcf\lF,F^c]lF^vFcc\l>F]d\l-Fffn6$F[c]lFjc\l>Fdg\l7$*&)F^c]lF
fc\lF,,&*&F^c]lF,F^c\lF,F,*&Fce\lF,,&*&Fce\lF,F^c\lF,F,*&Fcf\lF,F]d\lF,F,F,F`gy
F,*&Fic]lF,,&*&F^c]lF,F]d\lF,F,*&Fcf\lF,F]d]lF,F`gyF,>Fdg\l-FQ6%Fdg\lFce\lFcf\l
>Fdg\l-F_en6%-Fffn6$<$/Fce\lFY/Fcf\lFinFdg\lFYFin>Fci\l-F[ft6%Fdg\l/FYFao/FinFa
o>F[]]lz'6&Fcj\lFej\l&Fci\l6#Fbt&Fci\l6#Fcjr\[[[[[[[[\[[mF,[[[\[[\[[[[[mF^v>Fb_
]l,&Fcj\lF,Fie]lF,>8,,&*$Fb_]lFhnF,F[]]lFjix@$-Ffem6$F^f]lFao@%-Fdgm6$Fb_]lFaoC
1>8--F_o6#-F`dm6%-F`dm6%Fg\]lFinFaoFYF,>8.-F_o6#-F`dm6%-F`dm6%Fg\]lFYFaoFinF,>8
/-F_o6#-F`dm6%-F`dm6%Fi\]lFinFaoFYF,>80-F_o6#-Fcjt6#,&*&Fag]lF,Fig]lF,F^v*$Fif]
lFhnF^v>Fdg\l7$,&*(Fig]lF,-Fffn6$<#/FY,&*(Fah]lF,Fce\lF,Fig]lF^vF^v*(Fif]lF,Fcf
\lF,Fig]lF^vF,Fg\]lF,Fah]lF`gyF,*(Fif]lF,-Fffn6$F_i]lFi\]lF,Fah]lF`gyF^v*&-Fffn
6$<#/FY,&Fbi]lF^v*(Fif]lF,FinF,Fig]lF^vF,Fi\]lF,Fah]lF^v>Fdg\l-F_o6#Fjd]l>Fdg\l
,&-Fffn6$<$/FY,&81#F,Fhn82Fij]l/Fin*&^##F^vFhnF,,&Fhj]lF,Fjj]lF^vF,Fg\]lF,*&^#F
,F,-Fffn6$Fej]lFi\]lF,F,>Fdg\l-F_o6#-F^eo6#Fdg\l>Fdg\l*&Fdg\lF,-F_o6#-F`dm6%-F`
dm6%-F`dm6%Fdg\lFjj]lFaoFhj]lF,Fa[^lF,F^v>85-Fb[z6%,&FiayF,*&^#F^vF,Fhj]lF,F,Fh
j]lFjj]l@%0&Fd\^lFec\lFaoC)-F`r6$Q>The~order~of~weakness~is~%d.|+F\bw&Fd\^lF[d
\l-F`r6$Q>The~lyapunov~constant~is~%g.|+F\bw,$F\]^lF^vF[i\lF^]^lFb]^lF`i\l@%2F
\]^lFaoC&-F`r6#QBThe~equator~is~weakly~repelling.|+F\bwF[i\lFi]^lF`i\lC&-F`r6#Q
CThe~equator~is~weakly~attracting.|+F\bwF[i\lF]^^lF`i\l@%5/&Fd\^lFhe]lFhn/&Fd\^
lFje]lF,C&-F`r6#QIWe~have~a~center~behaviour~at~infinity.|+F\bwF[i\lFg^^lF`i\lC
&-F`r6$QSThe~order~of~weakness~at~infinity~is~at~least~%d.|+F\bw,&Ff^lF,F,F,F[i
\lF[_^lF`i\lF[i\l-F`r6#QL##########################################|+F\bwF`i\lF
__^lC%>83-F_o6#,&Fb_]lFij]l-Fcjt6#F^f]lF^[^l>84-F_o6#,&Fb_]lFij]lFh_^lFij]l@%-F
jfmFff]lC&-F`r6#Q;The~equator~is~repelling.|+F\bwF[i\lFb`^lF`i\lC&-F`r6#Q<The~e
quator~is~attracting.|+F\bwF[i\lFf`^lF`i\lF\bwF\bwF\bwF(,
I)pl_chartf*6#Fb`m63F_pFdfoFgcnF]fnF^fnF\pF_anFeb\lFfb\lFgb\lFhb\l%$f_CGF]pF^p%
#t1G%#t2G%#t3GF\bwF\bwC9>Fcf\lF^t>Fdg\lF_t@$30F]tF,0F]tFbtC%-F\r6$FgelF^r-F`r6%
Q^oWe~make~the~study~on~the~Poincare-Lyapunov~disc~of~degree~(%d,%d).|+F\bwFcf
\lFdg\lF`i\l>F]d\l-Fcgl6'Fdc\lFYFinFcf\lFdg\l>Fci\l,&*&)FhisFdg\lF,-Fffn6$<$/FY
*&Fce\lF,)FhisFcf\lF^v/Fin*&FgisF,Fdb^lF^vFjc\lF,F,*.Fce\lF,Fdg\lF,Fcf\lF^vFjb^
lF,FgisF,-Fffn6$Fgb^lFcc\lF,F^v>F[]]l,$**Fce\lF,Fcf\lF^v)Fhis,&Fcf\lF,F,F,F,F^c
^lF,F^v>Fb_]l-F_en6%-Fffn6$/Fce\lF,7$*&Fci\lF,)FhisF]d\lF,*&F[]]lF,F]d^lF,FgisF
his>F^f]l-F_en6%-Fffn6$/Fce\lF^vF[d^lFgisFhis>Fci\l,&*&Fjb^lF,-Fffn6$<$/FY*&Fgi
sF,Fjb^lF^v/Fin*&Fce\lF,Fdb^lF^vFcc\lF,F,*.Fce\lF,Fcf\lF,Fdg\lF^vFdb^lF,FgisF,-
Fffn6$Fjd^lFjc\lF,F^v>F[]]l,$**Fce\lF,Fdg\lF^v)Fhis,&Fdg\lF,F,F,F,F`e^lF,F^v>Fi
f]lFfc^l>Fag]lF`d^l>Fci\l,&*()F%Fdc^lF,FiirF,-Fffn6$<$/FY*&FiirF,)F%Fcf\lF^v/Fi
n*&FjirF,)F%Fdg\lF^vFcc\lF,F^v*()F%Ffe^lF,FjirF,-Fffn6$F_f^lFjc\lF,F^v>F[]]l,&*
*Fdg\lF,Fbf^lF,FjirF,F]f^lF,F^v**Fcf\lF,Fef^lF,FiirF,Fhf^lF,F,>Fig]l7$-Fieo6&*&
Fci\lF,)F%F]d\lF,F%FiirFjir-Fieo6&*&F[]]lF,Fcg^lF,F%FiirFjirFf]]l-Fadl6#-Fffn6$
<$/FgisFY/FhisFinFb_]l-Fadl6#-Fffn6$F[h^lF^f]l-Fadl6#-Fffn6$F[h^lFif]l-Fadl6#-F
ffn6$F[h^lFag]l-Fcir6#Fig]lF`i\l@$Fea^lCD>Fci\l-F[gp6$-Fffn6$Fii\l&Fb_]lFec\lFg
is>Fah]lFcj\l>Fhj]lFej\l-F\r6#Fdel-F`r6$Fgw,&-F.6#Fah]lF,-F.6#Fhj]lF,F`i\l-F`r6
#QJThe~differential~system~on~the~U1~chart:|+F\bwF[i\l-F`r6%Q]oFirst~we~study~t
he~system~on~the~U1~chart~(x=1/z2^%d,y=z1/z2^%d).|+F\bwFcf\lFdg\lFia^l-F`r6%Q;~
~~~z1'~=~%a|+~~~~z2'~=~%a|+F\bwFci^l&Fb_]lF[d\lF`i\l?(F^c\lF,F,F[j^lF1C&>Fjj]l-
Fcim6$-FU6$Fci^lFgis<$/Fgis&Fah]l6#F^c\lFii\l>Fd_^l-Fcim6$-FU6$Fci^lFhisF`[_l>F
[`^l-Fcim6$-FU6$Fhj^lFhisF`[_l-%)type_infG6)Fb_]lF,Fb[_lFjj]lFd_^lF[`^lFao>F[oF
1?(F^c\lF,F,F]j^lF1C&>Fjj]l-F_o6#-Fcim6$F^[_l<$/Fgis&Fhj]lFc[_lFii\l>Fd_^l-F_o6
#-Fcim6$Fg[_lFi\_l>F[`^l-F_o6#-Fcim6$F\\_lFi\_l-F_\_l6)Fb_]lF,F[]_lFjj]lFd_^lF[
`^lFao>F[oF`[l>Fci\l-F[gp6$-Fffn6$Fii\l&F^f]lFec\lFgis>Fah]lFcj\l>Fhj]lFej\lFfi
^lFhi^lF`i\l-F`r6#QJThe~differential~system~on~the~V1~chart:|+F\bwF[i\l-F`r6%Q
\oNow~we~study~the~system~on~the~V1~chart~(x=-1/z2^%d,y=z1/z2^%d).|+F\bwFcf\lFd
g\lFia^l-F`r6%Fgj^lF^^_l&F^f]lF[d\lF`i\l?(F^c\lF,F,F[j^lF1C&>Fjj]l-Fcim6$-FU6$F
^^_lFgisF`[_l>Fd_^l-Fcim6$-FU6$F^^_lFhisF`[_l>F[`^l-Fcim6$-FU6$Fi^_lFhisF`[_l-F
_\_l6)F^f]lFbtFb[_lFjj]lFd_^lF[`^lFao>F[oF1?(F^c\lF,F,F]j^lF1C&>Fjj]l-Fcim6$F__
_lFi\_l>Fd_^l-Fcim6$Fd__lFi\_l>F[`^l-Fcim6$Fi__lFi\_l-F_\_l6)F^f]lFbtF[]_lFjj]l
Fd_^lF[`^lFao>F[oF`[l@%3-Fdgm6$-Fffn6$<$/FgisFaoFii\l&Fif]lFec\lFao-Fdgm6$-Fffn
6$Fba_l&Fif]lF[d\lFaoC/Ffi^lFc_]lF`i\l-F`r6#QJThe~differential~system~on~the~U2
~chart:|+F\bwF[i\l-F`r6%Q[oNow~we~study~the~system~on~the~U2~chart~(x=z1/z2^%d,
y=1/z2^%d).|+F\bwFcf\lFdg\lFia^l-F`r6%Fgj^lFda_lFia_lF`i\l>Fjj]l-Fcim6$-FU6$Fda
_lFgisFba_l>Fd_^l-Fcim6$-FU6$Fda_lFhisFba_l>F[`^l-Fcim6$-FU6$Fia_lFhisFba_l-F_
\_l6)Fif]lFhnFaoFjj]lFd_^lF[`^lFaoC&Ffi^l-F`r6#Q#0|+F\bwF`i\l-F`r6#QQIn~the~U2~
chart,~no~extra~singularity~is~found.|+F\bw@%3-Fdgm6$-Fffn6$Fba_l&Fag]lFec\lFao
-Fdgm6$-Fffn6$Fba_l&Fag]lF[d\lFaoC/Ffi^lFc_]lF`i\l-F`r6#QJThe~differential~syst
em~on~the~V2~chart:|+F\bwF[i\l-F`r6%Q\oNow~we~study~the~system~on~the~V2~chart~
(x=z1/z2^%d,y=-1/z2^%d).|+F\bwFcf\lFdg\lFia^l-F`r6%Fgj^lFad_lFfd_lF`i\l>Fjj]l-F
cim6$-FU6$Fad_lFgisFba_l>Fd_^l-Fcim6$-FU6$Fad_lFhisFba_l>F[`^l-Fcim6$-FU6$Ffd_l
FhisFba_l-F_\_l6)Fag]lFcjrFaoFjj]lFd_^lF[`^lFaoC&Ffi^lFec_lF`i\l-F`r6#QQIn~the~
V2~chart,~no~extra~singularity~is~found.|+F\bwF\bw6%F^tF_tF[oF\bwF(,
I/find_inf_rootsf*6)FgcnFb`mFeb\lFgb\lFYFinF[c\l6/%$p_dG%$q_dGF]fnF^fnF\pF]pF^p
%$totGF_pF^a^lF_a^lF`a^lF_anF\bwF\bwCH>F^c\l-Fdcn6&&Ffc\lFec\l9(9)Fdc\l>F]d\l-F
dcn6&&Ffc\lF[d\lFbg_lFcg_lFdc\l>Fce\l-Fdcn6&Fag_lFbg_lFcg_l,&Fdc\lF,F^vF,>Fcf\l
-Fdcn6&Fgg_lFbg_lFcg_lF[h_l>Fah]l,&-Fffn6$/Fbg_lF,F]d\lF,*&Fcg_lF,-Fffn6$Fch_lF
^c\lF,F^v>Fdg\l-F[gp6$Fah]lFcg_l>Fci\lFg\]l>F[]]lFi\]lFfi^l-F`r6$Fgw,&-F.6#Fci
\lFhn-F.6#F[]]lFhnF`i\l>Fb_]l,&F_i_lF,Fai_lF,F_j^lF[i\l-F`r6#QgnFirst~we~study~
the~system~on~the~U1~chart~(x=1/z2,y=z1/z2):|+F\bwFia^l-F`r6%Fgj^l&Fgc\lFec\l&F
gc\lF[d\lF`i\l@$F^cpC%F[i\l-F`r6#Q9We~change~z1->x,~z2->y.|+F\bwF`i\l?(F^f]lF,F
,F_i_lF1C&>Fif]l-Fcim6$-FUFih_l/Fcg_l&Fci\lFi_^l>Fag]l-Fcim6$,&Fcf\lF,*&Fcg_lF,
Fce\lF,F^v<$Fch_lFgj_l>Fig]l,$-Fcim6$F^c\lF^[`lF^v-F_\_l6)Fgc\lF,Fhj_lFif]lFag]
lFig]l9*>F[oF1?(F^f]lF,F,Fai_lF1C&>Fif]l-F_o6#-Fcim6$Ffj_l/Fcg_l&F[]]lFi_^l>Fag
]l-F_o6#-Fcim6$F\[`l<$Fch_lF^\`l>Fig]l-F_o6#,$-Fcim6$F^c\lFe\`lF^v-F_\_l6)Fgc\l
F,F_\`lFif]lFag]lFig]lFe[`l>F[oF`[l>Fah]l,&-Fffn6$/Fcg_lF,F^c\lF,*&Fbg_lF,-Fffn
6$Fc]`lF]d\lF,F^v@%-Fdgm6$-Fffn6$/Fbg_lFaoFah]lFao>Fdg\l<#Fao>Fdg\l<"Ffi^l-F`r6
$Fgw,$-F.Fh[^lFhnF`i\l>Fb_]l,&Fb_]lF,Fd^`lF,F[b_lF[i\l-F`r6#QgnFirst~we~study~t
he~system~on~the~U2~chart~(x=z1/z2,y=1/z2):|+F\bwFia^l-F`r6%Fgj^l&9'Fec\l&F]_`l
F[d\lF`i\l@$F^cpC%F[i\lF^j_lF`i\l?(F^f]lF,F,Fd^`lF1C&>Fif]l-Fcim6$-FU6$Fah]lFbg
_l/Fbg_l&Fdg\lFi_^l>Fag]l-Fcim6$,&Fce\lF,*&Fbg_lF,Fcf\lF,F^v<$Fh_`lFc]`l>Fig]l,
$-Fcim6$F]d\lF_``lF^v-F_\_l6)F]_`lFhnFi_`lFif]lFag]lFig]lFe[`l@$/Fb_]lFao-F`r6#
QKNo~singular~points~at~infinity~are~found.|+F\bwF\bw6#F[oF\bwF(,
I4find_inf_roots_singf*6$Feb\lFgb\l6&F\pF]pF^pF_pF\bwF\bwC?>F^c\l-Fcjq6$7$-Fffn
6$Fii\lFcc\l-Fffn6$Fii\lFjc\lFgisFfi^l-F`r6$Fgw,&-F.6#F]b]lF,-F.6#F^b]lF,F`i\l-
F`r6%Q^oThe~differential~system~on~the~U1~chart:|+~~~~z1'~=~%a|+~~~~z2'~=~%a|+F
\bwFcc\lFjc\lF[i\l-F`r6#Q^oFirst~we~shall~study~the~system~on~the~U1~chart~(x=1
/z2,~y=z1/z2):|+F\bw-F`r6%Fgj^lFcc\lFjc\l@$F^cp-F`r6#Q9~we~change~z1->x,~z2->y|
+F\bwF`i\l>F]d\lF]b]l>Fce\lF^b]l?(Fcf\lF,F,-F.Fea]lF1-Fhjl6&-Fffn6%F\h^lF]h^lFd
c\l&F]d\l6#Fcf\lFaoF,>F[oF1?(Fcf\lF,F,-F.6#Fce\lF1-Fhjl6&Fbc`l&Fce\lFec`lFaoF,>
F[oF`[l@$/,&F_c`lF,Fhc`lF,FaoC%Fia^l-F`r6#QKNo~singular~points~found~in~the~U1~
chart.|+F\bwF`i\l@%3-Fdgm6$-Fffn6%Fca_lFii\lFag_lFao-Fdgm6$-Fffn6%Fca_lFii\lFgg
_lFao>F^c\l7#Fao>F^c\l7"Ffi^l-F`r6$Fgw-F.Fc[_lF`i\l-F`r6%Q^oThe~differential~sy
stem~on~the~U2~chart:|+~~~~z1'~=~%a|+~~~~z2'~=~%a|+F\bwFag_lFgg_lF[i\l-F`r6#Qfn
Now~we~study~the~system~on~the~U2~chart~(x=z1/z2,~y=1/z2):|+F\bw-F`r6%Fgj^lFag_
lFgg_l@$F^cpFib`lF`i\l?(Fcf\lF,F,Fee`lF1-Fhjl6&-Fffn6%F\h^lF]h^lFfc\l&F^c\lFec`
lFaoFhn@$/Fee`lFaoC%Fia^l-F`r6#QKNo~singular~points~found~in~the~U2~chart.|+F\b
wF`i\lF\bwF[a`lF\bwF(,
I+saddle_inff*6)Fb`mF][sF]_lF^auFjemF_auF[c\l6)FdfoFcfoF\pF_anFaduF[[sF\[sF\bwF
\bwC4>F^c\l*&Fbg_lF,,&Fcg_lF,F]_`lF^vF^v>F]d\l-F_[u6'-Fffn6$F[h^lFdc\lFYFinFgc
\lFao>Fce\l-Fj\u6'F]d\lF^c\lF,F,Fao>Fcf\l-Fj`uFic`l>Fcf\l-F_en6%Fcf\lFYFin@%F^c
pFia^lF`i\l-F`r6#Fidw-F`r6$Q=The~new~vector~field~is~%a.|+6"F]d\l-F`r6#Fgew-F`r
6$Feh`lFce\l-F`r6$QenMake~a~1000~normalization.|+So~the~new~vector~field~is~%a.
|+F\bwFcf\lF`i\l-F`r6#QJWe~calculate~the~invariant~separatrices.|+F\bw@%-Ffem6$
Fcg_lFaoC$>Fdg\lF,>F[]]lF^vC$>Fdg\lFao>F[]]lF,>Fci\l-F^du6%Fcf\lFa]lFdg\l@%/Fdg
\lF,C&@$F^cpFia^l-F`r6$F\hw7$F[^sFci\l-F`r6$F`hw7$FaoF[^sF`i\lC&@$F^cpFia^l-F`r
6$F`hwFcj`l-F`r6$F\hwFfj`lF`i\l-Fhjr6,Fgc\lFaoF^c\lF,F,FaoFcf\l7#Fci\l7#F[]]lFf
c\l@$3/F^tF,/F_tF,C$@%F^j`l@$0Fe[`lFao>F[]]lF,@$Fh[al>F[]]lF^v@%/Ffc\lF,-Fhjr6,
Fgc\lFao,$F^c\lF^vF,F^vFaoFcf\l7#-Fffn6$/F[^s,$F[^sF^vFci\lF`[alFbt-Fhjr6,Fgc\l
FaoF`\alF,F^vFaoFcf\lFa\alF`[alFcjrF\bwF\bwF\bwF(,
I'se_inff*F]g`l6.F_anFdfoFcfoF\pF__pF`auFa`vF\[sF``xF[[s%#hhGFaduF\bwF\bwC:>F]d
\lFag`l>Fce\lFdg`l>Fcf\l-Fj\u6'Fce\lF]d\lF,F,Fao>F^c\l-Fj`uFec`l>F^c\l-F_en6%F^
c\lFYFinFia^l-F`r6%QOThe~point~(%a,%a)~is~a~semi~hyperbolic~point.|+F\bwFgc\lFa
o@%F^cpFia^lF`i\l-F`r6#FcbxFih`lFgh`l-F`r6$Feh`lFcf\l-F`r6$F]i`lF^c\lF`i\lF^i`l
@%-Fdgm6$F]_`lFaoC*@%Fbi`l>Fig]lF,>Fig]lFao>Fif]l-F^du6%F^c\lFa]lFig]l>Fdg\l-Ff
fn6$<$/Fgis,&FYF,F,F,Fii\lFcc\l>Fdg\l-Fbhm6$Fdg\lFY>Fdg\l-Fc_nFc_al>Fci\l-FfdmF
c_al>F[]]l-Fciw6#-F_o6#-Fffn6$/FYF,Fdg\l@%-Faq6$Fci\lFjdv@%2FaoF[]]l@%/Fig]lFao
>Fb_]l7$F,Fao>Fb_]l7$FhnFao@%Ff`al>Fb_]l7$FbtFao>Fb_]l7$FcjrFao@%Fd`al@%Ff`al>F
b_]l7$F_asFao>Fb_]l7$F]bsFao@%Ff`al>Fb_]l7$F^bsFao>Fb_]l7$F`wFaoC&@%-FfemFc^al>
Fig]lF,>Fig]lFao>F^f]l-F^`vFj^al>Fif]l-Fffn6$/FYF[^sF^^_l>Fb_]l7$&F^f]lFhe]lF,F
ia^l@$-F_el6$Fci^l<&F,FhnFbtFcjr-F`r6#Q=The~point~is~a~saddle-node.|+F\bw@$/Fci
^lF_as-F`r6#Q@The~point~is~an~unstable~node.|+F\bw@$/Fci^lF`w-F`r6#Q>The~point~
is~a~~stable~node.|+F\bw@$-F_el6$Fci^l<$F]bsF^bs-F`r6#Q8The~point~is~a~saddle.|
+F\bwF`i\l-Fi`s6,Fgc\lFaoF]d\lF,F,FaoF^c\lFb_]l7#Fif]lFfc\l@$Fb[alC%@%/Fe[`lFao
>Fb_]l7$-F[[m6$Fci^l7*FbtFcjrF,FhnF_asF]bsF^bsF`wFhj^l>Fb_]l7$-F[[m6$Fci^l7*Fhn
F,FcjrFbtF`wF^bsF]bsF_asFhj^l>Fag]l7$-Fcim6#*&)F^vFe[`lF,F]b]lF,-Fcim6#*&FgealF
,F^b]lF,@%F]\al-Fi`s6,Fgc\lFaoF]d\lF,F,FaoFag]lFb_]lFcdalFbt-Fi`s6,Fgc\lFaoF]d
\lF,F,FaoFag]lFb_]lFcdalFcjrF\bwF\bwF\bwF(,
I,change_stabf*6#F[[s6(F_pFbhsF'FiemFjemFdfoF\bwF\bwC%>F]d\lFbe`l?(F^c\lF,F,F^a
]lF1C&>Fcf\lFbe`l>Fdg\l&Fdc\lFc[_l?(Fce\lF,F,Fd^`lF1@%0Fce\lF]bs>Fcf\l7$-F[[mFe
c`l-F[[m6$Fce\lFdg\lC%>Fci\lFagal@%-F_el6$Fci\l<&F,FbtFgdsFgfm>Fci\lFhn@%-F_el6
$Fci\l<&FhnFcjr"#6"#7>Fci\lF,@%-F_el6$Fci\l<$F_asF^bs>Fci\lF]bs>Fci\lF_as>Fcf\l
7$F`galFci\l>F]d\l7$-F[[mFea]lFcf\lF]d\lF\bwF\bwF\bwF(,
I'de_inff*6&Fb`mF][sF]_lF[c\l6#FbhsF\bwF\bwC'-F`r6%QMThe~point~(%a,%a)~is~a~non
elementary~point.|+F\bwFgc\lFao-F`r6#Q>Blowing~up~the~vector~field.|+F\bw>F^c\l
-Fh_x6&Ffg`lFgc\lFaoFbo-F_hs6&Fgc\lFaoF]b]lFfc\l@$Fb[alC%-F`r6$Q,Degree=%d.|+F
\bwF]_`l@%/F]_`lFao>F^c\lF^b]l>F^c\l-F`falF_b`l@%F]\al-F_hs6&Fgc\lFaoF^c\lFbt-F
_hs6&Fgc\lFaoF^c\lFcjrF\bwF\bwF\bwF(,
I)type_inff*F]g`l6&FehmFf^wFg^wFh^wF\bwF\bw@%3Fb^al-FdgmFci`lC&Fia^l-F`r6%Q;(%a
,%a)~is~nonelementary.|+F\bwFgc\lFaoF`i\l-F\ial6&Fdc\lFfc\lFgc\lFe[`l@%5Fb^alF`
[bl-Fh\al6)Fdc\lFfc\lFgc\lF]_`lFbg_lFcg_lFe[`l@%-Ffem6$*&F]_`lF,Fcg_lF,FaoC(Fia
^l-F`r6%Q6(%a,%a)~is~a~saddle.|+F\bwFgc\lFao@%2-F\hm6#-F_o6#Fcg_l-F\hm6#-F_o6#F
]_`l>F]d\l*&F]_`lF,Fcg_lF^v>F]d\l*&Fcg_lF,F]_`lF^v@%334F[o-Faq6$F]_`lF`aw-Faq6$
Fcg_lF`awC)>Fce\l-FacmFea]l>Fcf\l-FfcmFea]lF`i\l-F`r6%F[bwFcf\lFce\lF[i\lF^^blF
`i\lC+>F]d\l-F66$-F_oFea]lF^im>F]d\lFb^bl>Fce\lF[^bl>Fcf\lF]^blF`i\l-F`r6%FgbwF
cf\lFce\lF[i\lFh^blF`i\lF`i\l-F[g`lFj[blC(>F^c\l-FciwFf\bl@%2FaoF^c\lC%Fia^l-F`
r6%Fc\xFgc\lFaoF`i\lC%Fia^l-F`r6%F\\xFgc\lFaoF`i\l@%Fd\bl>F]d\lF^]bl>F]d\lF`]bl
@%Fb]blC)>Fce\lF[^bl>Fcf\lF]^blF`i\lF^^blF[i\lF^^blF`i\lC+>F]d\lFb^bl>F]d\lFb^b
l>Fce\lF[^bl>Fcf\lF]^blF`i\lFh^blF[i\lFh^blF`i\l-F__s6&Fgc\lFaoF^c\lFfc\l@$Fb[a
lC$@$Fh[al>F^c\lF`\al@%F]\al-F__sFhjal-F__sFjjalF\bwF\bwF\bwF(,
I-assoc_pointsf*6#FK6&%#LfG%#LgGFMF`iyFfh`lFfh`lC'>8$-Fcar6%-F_o6#&9$6#F,FYFin>
Fcabl-Fgjm6$f*6#FMFfh`l6$F\fmF]fmFfh`l7$,&FhablF,F^vF,&Fiabl6#FhnFfh`lFfh`lFfh`
lFcabl>8%-Fcar6%-F_o6#FcbblFYFin>Ffbbl-Fgjm6$f*F_bblFfh`lF`bblFfh`l7$Fhabl,&Fcb
blF,F^vF,Ffh`lFfh`lFfh`lFfbbl-F66$<$-F[[m6#Fcabl-F[[m6#FfbblFcqFfh`lFfh`lFfh`lF
(,
I/newton_diagramf*F]abl6-%'pointsG%#pkG%#pjG%#pLGF'F_pFehm%%hsetG%"NGF`iyF]fnFf
h`lFfh`lC'>8+-F[abl6#Fiabl>FcablFcdbl>8,-F.Fecbl?(8(F,F,,&FhdblF,F^vF,F1C$>Ffbb
l&Fcabl6#F[ebl@$-F_el6$FfbblFcdbl?(8),&F[eblF,F,F,F,FhdblF1C$>8&&Fcabl6#Feebl@$
-F_el6$FieblFcdbl@%31&FfbblFjabl&FieblFjabl1&FfbblFdbbl&FieblFdbbl>Fcdbl-%'remo
veG6$f*6#F]fnFfh`lF`bblFfh`l/FiablT#Ffh`lFfh`l6$F]dblFieblFcdbl?(8*F,F,FhdblF1C
$>8'&Fcabl6#Fagbl@$33-F_el6$FdgblFcdbl0FagblF[ebl0FagblFeebl@%531Fbfbl&FdgblFja
bl1Fefbl&FdgblFdbbl31FcfblFbhbl1FffblFdhbl>Fcdbl-Fifbl6$f*F\gblFfh`lF`bblFfh`lF
]gblFfh`lFfh`l6$F^dblFdgblFcdbl@$532FbfblFbhbl2FbhblFcfbl32FcfblFbhbl2FbhblFbfb
lC$>8-*&,&FffblF,FefblF^vF,,&FcfblF,FbfblF^vF^v@$1,&*&FgiblF,,&FbhblF,FcfblF^vF
,F,FffblF,Fdhbl>Fcdbl-Fifbl6$f*F\gblFfh`lF`bblFfh`lF]gblFfh`lFfh`lF\iblFcdblFcd
blFfh`lFfh`lFfh`lF(,
I(GAMMA_1f*6#Fiin6)FehmF]fnF^fnF%F'%#skG%"GGFfh`lFfh`lC(>Fcabl-F.Fedbl>FfbblFha
bl>FieblFcbbl@$1FcfblFbfblC$>FfbblFcbbl>FieblFhabl@%/FcablFhn>Fagbl7$FfbblFiebl
C&>Fdgbl&Fiabl6#Fbt@%FdiblC%>FdgblFiebl>FieblFfbbl>FfbblFj[cl@$FaiblC$>FdgblFie
bl>FieblFj[cl?(F[eblFcjrF,FcablF1C$>Feebl&FiablF`ebl@%2&FeeblFjablFbfblC%>Fdgbl
Fiebl>FieblFfbbl>FfbblFeebl@%2F[]clFcfblC$>FdgblFiebl>FieblFeebl@$2F[]clFbhbl>F
dgblFeebl@%2FaoFcfbl>FagblFg[cl>Fagbl7$FieblFdgblFagblFfh`lFfh`lFfh`lF(,
I-quasi_degreef*Ffjbl6&F_an%&alphaG%%betaGFgcnFfh`lFfh`lC'>Fcabl,$*&,&-F[[m6$Fh
nFcbblF,-F[[m6$FhnFhablF^vF,,&-F[[m6$F,FcbblF,-F[[m6$F,FhablF^vF^vF^v>Ffbbl-Fac
mFecbl>Fiebl-FfcmFecbl>Fdgbl,&*&FfbblF,F^_clF,F,*&FieblF,Fi^clF,F,7%FfbblFieblF
dgblFfh`lFfh`lFfh`lF(,
I-center_type1f*6&Fb`mFYFehmFj\y6&FiinF\pF`auFjemFfh`lFfh`lC'>Ffbbl-Fc_n6$Fiabl
9%>Fiebl-F^jm6$Fao-Ffdm6$FfbblFa`cl>Fdgbl-Fciw6#-F_o6#-Fffn6$/Fa`clF,Ffbbl@%-Fa
q6$FieblFjdv>Fcabl7%FdgblF,-Fciw6#-F_o6#9&>Fcabl7%FdgblF^vFdacl@%/9'F,C*@$/Fcab
l7%F^vF,F,OFgfm@$/Fcabl7%F,F,F,OFgds@$/Fcabl7%F,F^vF,OFbt@$/Fcabl7%F^vF^vF,OF,@
$/Fcabl7%F^vF,F^vOF_hal@$/Fcabl7%F,F,F^vOF^hal@$/Fcabl7%F,F^vF^vOFhnOFcjrC*@$F`
bclOFgds@$FdbclOFgfm@$FhbclOFbt@$F\cclOF,@$F`cclOF^hal@$FdcclOF_hal@$FhcclOFhnO
FcjrFfh`lFfh`lFfh`lF(,
I-center_type2f*F[`clF\`clFfh`lFfh`lC'>FfbblF_`cl>FieblFc`cl>FdgblFh`cl@%F`acl>
FcablFcacl>FcablFjacl@%F\bclC*@$F`bclOFgds@$FdbclOFgfm@$FhbclOFbt@$F\cclOF,@$F`
cclOF^hal@$FdcclOF_hal@$FhcclOFhnOFcjrC*@$F`bclOFgfm@$FdbclOFgds@$FhbclOFbt@$F
\cclOF,@$F`cclOF_hal@$FdcclOF^hal@$FhcclOFhnOFcjrFfh`lFfh`lFfh`lF(,
I&powerf*6$FiemFjemFfh`lFfh`lFfh`l@%/Fa`clFaoF,)FiablFa`clFfh`lFfh`lFfh`lF(,
I-sort_set_posf*6%FiinFd_lF%6%FiemF'FehmFfh`lFfh`lC'>Fcabl7#-F\dm6#;F,,&F\[clF,
F,F,>FfbblF,?(FieblF,F,F\[clF1C%@$3-Ffem6$Fa`cl-F[[m6$F,&Fiabl6#Fiebl/FfbblFieb
lC$>&FcablFgcbl7$Fa`clFhacl>Ffbbl,&FfbblF,F,F,>FeiclF`icl>FfbblFhicl@$Fbicl>Fei
clFficlFcablFfh`lFfh`lFfh`lF(,
I-sort_set_negf*F^hclF_hclFfh`lFfh`lC'>FcablFbhcl>FfbblF,?(FieblF,F,F\[clF1C%@$
3-FjfmF]iclFbiclC$>FeiclFficl>FfbblFhicl>FeiclF`icl>FfbblFhicl@$Fbicl>FeiclFfic
lFcablFfh`lFfh`lFfh`lF(,
I0put_separatricef*6)%%xposGF\[s%0transformationsG%#ptGFhcs%*vec_fieldGF[[s6#%)
newentryGFfh`lFfh`lC$>Fcabl7)FhaclF]bcl9(9)9*Fa`clF[o@%/FiablF,C$>%(NumXPosG,&F
a\dlF,F,F,>%(ManXPosG7$-F[[m6#Fd\dlFcablC$>%(NumXNegG,&Fj\dlF,F,F,>%(ManXNegG7$
-F[[m6#F]]dlFcablFfh`l6&Fa\dlFj\dlFd\dlF]]dlFfh`lF(,
I2append_trajectorsf*Ffh`l6%%%man1G%%man2GF_pFfh`lFfh`lC,-%&printG6$Q+ManYNeg~=
~Ffh`l%(ManYNegG-Fi]dl6$Q+ManYPos~=~Ffh`l%(ManYPosG-Fi]dl6$Q+ManXNeg~=~Ffh`lF]]
dl-Fi]dl6$Q+ManXPos~=~Ffh`lFd\dl>Fcabl7"@$0%(NumberYGFaoC$>Ffbbl-%4make_transfo
rmationG6#F\^dl>Fcabl7$Fdcbl7$-F[[mF`_dlFfbbl?(FieblF,F,Fa\dlF1C$>Ffbbl-F__dl6#
&Fd\dlFaicl>Fcabl7$Fdcbl7$-F[[mFi_dlFfbbl@$Fj^dlC$>Ffbbl-F__dl6#F`^dl>Fcabl7$Fd
cbl7$-F[[mFc`dlFfbbl?(FieblF,F,Fj\dlF1C$>Ffbbl-F__dl6#&F]]dlFaicl>Fcabl7$Fdcbl7
$-F[[mF\adlFfbblFcablFfh`lFfh`lFfh`lF(,
I1split_trajectorsf*6#F[[s6'%(sep_posG%(sep_negGF_pFiinF\pFfh`lFfh`lC&>FcablFh^
dl>FfbblFh^dl?(FieblF,F,F\[clF1C$>Fdgbl-F[[m6$F`wF`icl@$0FdhblFaoC$>F[ebl-Fciw6
#-F_o6#-Fffn6$/F[^sF,-Fc_n6$-FU6$FdhblF[^sF[^s@%2FaoF[ebl>Fcabl7$FdcblF`icl>Ffb
bl7$FfcblF`icl7$FcablFfbblFfh`lFfh`lFfh`lF(,
I4make_transformationf*Fdadl6,Fehm%%histGFc[dlFhcsFiinF]_lFd_l%#x1G%#y1GFiemFfh
`lFfh`lC+>FfbblFhabl>FieblFcbbl>FdgblFj[cl>F[ebl&Fiabl6#F_as>Feebl,(FcfblF,*&Fb
hblF,F[^sF,F,*&FdhblF,F[eblF,F,>Fagbl,(FffblF,*&&FdgblF[\clF,F[^sF,F,*&&Fdgbl6#
FcjrF,F[eblF,F,>Fcabl-F.Fgcbl?(Ffh`lF,F,Ffh`l2FaoFcablC(>Fgibl&FfbblFecbl>Fcdbl
,&&FgiblFjablF,*(&FgiblF[\clF,-Ffgcl6$Feebl&FgiblFbddlF,-Ffgcl6$Fagbl&Fgibl6#F]
bsF,F,>Fhdbl,&&FgiblFdbblF,*(&FgiblF]edlF,-Ffgcl6$Feebl&Fgibl6#F^bsF,-Ffgcl6$Fa
gbl&Fgibl6#F`wF,F,>Feebl-Fbhm6$FcdblF[^s>Fagbl-Fbhm6$FhdblF[^s@%3/FeeblFao/Fagb
lFao>FcablFao>Fcabl,&FcablF,F^vF,7$FeeblFagblFfh`lFfh`lFfh`lF(,
I1write_trajectorsf*6%F[[sF]_lFd_l6/Fehm%#w1GF__pF`_pF_p%#elG%$hypG%#w2G%$dl1G%
$dl2G%$dl3G%$dl4G%$dl5GFfh`lFfh`lC9>FcablF\[cl>FeeblFao>FagblFao>FhdblFbbz>Fgib
lQ"~Ffh`l>8.Fbbz>8/Fbbz>80Fbbz@$0FcablFaoC1-F\r6$FgelF^r-F`r6#QI|+|+The~invaria
nt~separatrices~are:~(t>0)|+Ffh`l-F\r6#F^r>Ffbbl<*F,FbtF_asF^bsFgdsFgfm"#8"#9>F
cdbl<*FhnFcjrF]bsF`wF^halF_halF^bm"#;>Fiebl-F[[m6$F]bsFhabl-F`r6#-%(sprintfG6$Q
&~[%d]Ffh`lFiebl@%-F_el6$FieblFfbblC(Fiidl-F`r6$Q5[01]:~%a~:~unstable|+Ffh`l-F[
[m6$F`wFhablF^jdl>Fhdbl-FC6$FhdblQ)~~~|gr~~~~Ffh`l>Fgibl-FC6$FgiblQ&~~^~~Ffh`l>
Faidl-FC6$FaidlF\\elC(Fiidl-F`r6$Q3[01]:~%a~:~stable|+Ffh`lFg[elF^jdl>FhdblFj[e
l>Fgibl-FC6$FgiblQ&~~v~~Ffh`l>FaidlFb\el@%-F_el6$Fiebl<)FhnFbtF_asF]bsFgfmF_hal
Fbjdl>Fcidl-FC6$FcidlQ%-<-*Ffh`l@%-F_el6$Fiebl<)F,FcjrF^bsF`wFgdsF^halF^bm>Fcid
l-FC6$FcidlQ%->-*Ffh`l>Fcidl-FC6$FcidlQ%****Ffh`l@%-F_el6$Fiebl<)F,FcjrF^bsF`wF
gfmF_halFfjdl>Fcidl-FC6$FcidlQ%-<-~Ffh`l@%-F_el6$Fiebl<)FhnFbtF_asF]bsFgdsF^hal
Fcjdl>Fcidl-FC6$FcidlQ%->-~Ffh`l>Fcidl-FC6$FcidlQ%***~Ffh`l>Feidl-FC6$Feidl-F][
el6$Q+~~%02d~~~~Ffh`lF,?(F[eblFhnF,FcablF1C*>Fdgbl-F[[m6$F]bsFh\cl@%53-F_el6$Fi
ebl<%F,F^bsFgfm-F_el6$Fdgbl<%FhnF]bsF_hal3-F_el6$Fiebl<%FhnF]bsF^hal-F_el6$Fdgb
l<%F,F^bsFgdsC'Fiidl-F`r6#Q3hyperbolic~sector|+Ffh`lF^jdl>Fagbl,&FagblF,F,F,>Fg
ibl-FC6$FgiblQ$HYPFfh`l@%53-F_el6$Fiebl<&FbtF_asFgdsFcjdl-F_el6$Fdgbl<&FcjrF`wF
^halF^bm3-F_el6$Fiebl<&FcjrF`wF_halFfjdl-F_el6$Fdgbl<&FbtF_asFgfmFbjdlC'Fiidl-F
`r6#Q1elliptic~sector|+Ffh`lF^jdl>Feebl,&FeeblF,F,F,>Fgibl-FC6$FgiblQ$ELLFfh`lC
&Fiidl-F`r6#Q2parabolic~sector|+Ffh`lF^jdl>Fgibl-FC6$FgiblQ$PARFfh`l>FieblFdgbl
Fjjdl@%Fa[elC(Fiidl-F`r6%Q7[%02d]:~%a~:~unstable|+Ffh`lF[ebl-F[[m6$F`wFh\clF^jd
l>FhdblFj[el>FgiblF^\el>FaidlFb\elC(Fiidl-F`r6%Q5[%02d]:~%a~:~stable|+Ffh`lF[eb
lFcdelF^jdl>FhdblFj[el>FgiblFj\el>FaidlFb\el@%F_]el>FcidlFc]el@%Fg]el>FcidlF[^e
l>FcidlF_^el@%Fc^el>FcidlFg^el@%F[_el>FcidlF__el>FcidlFc_el>Feidl-FC6$Feidl-F][
el6$F[`elF[ebl>Fiebl-F[[m6$F]bs&FiablFecbl>FdgblFhjdl@%Fb`elC'FiidlFbaelF^jdl>F
agblFfael>FgiblFhael@%53-F_el6$Fiebl<%FbtF_asFgds-F_el6$Fdgbl<%FcjrF`wF^hal3-F_
el6$Fiebl<%FcjrF`wF_hal-F_el6$Fdgbl<%FbtF_asFgfmC'FiidlF\celF^jdl>FeeblF`cel>Fg
iblFbcelC&FiidlFfcelF^jdl>FgiblFjcelFiidl-F`r6&QFThe~singularity~(%a,%a)~has~in
dex~%a|+Ffh`lFa`clFhacl,(F,F,Feebl#F,FhnFagbl#F^vFhn-F`r6#QKSector~representati
on~(counterclockwise):|+Ffh`l-F`r6#Fhdbl-F`r6#Fay-F`r6#FgiblFghel-F`r6#FaidlFgh
el-F`r6#FcidlFghel-F`r6#Feidl-F`r6#Q#|+|+Ffh`lF^jdlFfh`lFfh`lFfh`lF(,
I1manifold_blow_upf*6$F`foF[em6*Fd^wFe^wF\pFb`mFiem%$dfxGF'F_anFfh`lFfh`lC*>Fie
bl-F_en6%FiablFYFin>Fcabl-F`dm6%-F`dm6%FcfblFYF,FinFao>Ffbbl-F`dm6%-F`dm6%Fffbl
FinF,FYFao>Fdgbl-Fi[n6$*&&F[eblFfgblF,)FYFagblF,/Fagbl;FhnFa`cl>Feebl-Fi[n6$*(F
agblF,F[[flF,)FY,&FagblF,F^vF,F,F][fl>Fcdbl-F^eo6#,&-Fffn6$/FinFdgbl,&FffblF,*&
FfbblF,FinF,F^vF,*&FeeblF,-Fffn6$F[\fl,&FcfblF,*&FcablF,FYF,F^vF,F^v?(FagblFhnF
,Fa`clF1C$>Fcdbl-Fcim6$Fcdbl/F[[fl*&-F`dm6%FcdblFYFagblF,,&*&FcablF,FagblF,F,Ff
bblF^vF^v>Fdgbl-Fcim6$FdgblFh\flO-Fffn6$/FYF[^sFdgblFfh`lFfh`lFfh`lF(,
I2manifold2_blow_upf*6$F\pF[em6+F^auF_auFb`mFhielF'F`pF_anFiemFhduFfh`lFfh`lC+>
Fcabl-F`dm6%-F`dm6%FhablFYF,FinFao>Ffbbl-F`dm6%-F`dm6%FcbblFinF,FYFao>Fiebl-Fi[
n6$*&&FcdblF`eblF,)FYF[eblF,/F[eblF^[fl>Fdgbl-Fi[n6$*(F[eblF,Fh^flF,)FY,&F[eblF
,F^vF,F,Fj^fl>Fagbl,&-Fffn6$/FinFiebl,&FcbblF,F]\flF^vF,*&FdgblF,-Fffn6$Fe_fl,&
FhablF,Fb\flF^vF,F^v>F[eblFhn>FhdblFa`cl?(Ffh`lF,F,Ffh`l2F[ebl,&Fa`clF,F,F,@%-F
]hm6$,&*&F[eblF,FcablF,F,FfbblF^vFaoC%>Fagbl-Fcim6$Fagbl/Fh^fl*&-F`dm6%FagblFYF
[eblF,Fc`flF^v>Fiebl-Fcim6$FieblFi`fl>F[eblFfeblC$>FhdblF`_fl>F[eblF_`fl-Fi[n6$
*&-F`dm6%FieblFYFeeblF,)F[^sFeeblF,/Feebl;FhnFhdblFfh`lFfh`lFfh`lF(,
I8center_manifold_blow_upf*Fg]fl61FcduFdduFeduFfduF'F_auF[[sFafnFgduFa_pFhduFga
rFjemF`auFa`vFfh`lFfh`lC)@%F[oC$>FcablFfabl>FfbblFibblC$>FcablFhabl>FfbblFcbbl>
Feebl-F`dm6%-Fieu6$-Fffn6$/FYFaoFcbblFinFinF,>FagblFao>FaidlFa`cl?(F[eblFhnF,Fa
idlF1C+>Fhdbl,$*&-F`dm6%-Fieu6$-Fffn6$/FinFaoFfbblFYFYF[eblF,FeeblF^vF^v@$34F[o
Fdjm>Fhdbl-FijmFfhel>Fiebl-F^eo6#-Fffn6$/Fin,&FcdblF,*&FhdblF,Fi^flF,F,Fcabl>Fd
gbl-F^eo6#,&-Fffn6$FgdflFfbblF,**FhdblF,F[eblF,F__flF,FieblF,F^v>Fcabl-Fffn6$/F
cdblFinFiebl>Ffbbl-Fffn6$FdeflFdgbl>Fagbl,&FagblF,FidflF,>Fcidl-Fbhm6$-Fffn6$F
\dflFcablFY@$/FcidlFao>Faidl,&FaidlF,F,F,>FcidlF[ffl7%FagblFcidl-Fc_n6$FcidlFYF
fh`lFfh`lFfh`lF(,
I+blowing_upf*6&FKF]_lFd_l%-finite_pointG6)F%Fddu%$n_dGFcbm%)q_degreeGFfhmFbhsF
fh`lFfh`lCV@$F^cpFiidl-F`r6&QAblowing~up~%a~in~point~(%a,%a).|+Ffh`lFiablFa`clF
haclF^jdl@%50Fa`clFao0FhaclFaoC'>Ffbbl-F_en6%-F_[u6'FiablFYFinFa`clFhaclFYFin@$
F^cpFiidl-F`r6%Q?moving~(%a,%a)~to~the~origin.|+Ffh`lFa`clFhacl-F`r6$Q6new~vect
or~field:~%a|+Ffh`lFfbblF^jdl>FfbblF[jel>Fiebl-FhcblFgcbl>Fdgbl-FdjblFaicl>F[eb
l-F]^cl6#Fdgbl@$F^cpFiidl-F`r6$Q4Newton~diagram:~%a|+Ffh`lFiebl-F`r6$Q)g1~=~%a|
+Ffh`lFdgbl-F`r6$Q:[alpha,beta,degree]~=~%a|+Ffh`lF[eblFghel-F`r6#QK1.~Blowing~
up~in~the~positive~x-direction|+Ffh`l-F`r6#QK----------------------------------
-------|+Ffh`lFghel-F`r6#Q4blowing~up~level~1|+Ffh`l-F`r6#Q4------------------|
+Ffh`l-F`r6$Q>blowing~up~%a~in~point~(0,0)|+Ffh`lFfbblF^jdl>Feebl-%)blow_upxG6'
FfbblF[eblF,FYFin@$F^cpFiidl-F`r6$Q;blowing~up~vectorfield~%a|+Ffh`lF[]clF^jdl-
%,sing_eigenvG6'FeeblF,F,7#7+Fa`clFhaclF,F,&F[eblFjablFao&F[eblFdbblF,&F[eblF[
\clF,@$F^cpFiidl-F`r6#Qen------------------------------------------------------
---|+Ffh`lFghel-F`r6#QK2.~Blowing~up~in~the~negative~x-direction|+Ffh`lFiiflFgh
elFghelF\jflF_jflFbjflF^jdl>Feebl-Fgjfl6'FfbblF[eblF^vFYFin@$F^cpFiidlFjjflF^jd
l-F^[gl6'FeeblF^vF,7#7+Fa`clFhaclF^vF,Fb[glFaoFc[glF,Fd[glF^v@$32F^v-F[[m6$F,Fb
hbl0&FeeblF[\clFaoC.@$F^cpFiidl-F`r6#QK3.~Blowing~up~in~the~positive~y-directio
n|+Ffh`lFiiflF^jdl>F`^dl-%)blow_upyG6&FfbblF[eblF,7#7+Fa`clFhaclF,F,F,Fb[glFaoF
c[glFd[gl>F[_dlF,@$F^cpFiidlFghel-F`r6#QK4.~Blowing~up~in~the~negative~y-direct
ion|+Ffh`lFiiflF^jdl>F\^dl-Fb]gl6&FfbblF[eblF^v7#7+Fa`clFhaclF,F^vF,Fb[glFaoFc[
glFd[gl>Fagbl-Fb]dlFfh`l-F\hdl6%FagblFa`clFhacl@$4F]bcl>Fagbl-FbadlFfgbl>Fa\dlF
ao>Fj\dlFao>F[_dlFao>Fd\dlFh^dl>F]]dlFh^dl>F`^dlFh^dl>F\^dlFh^dlFagblFfh`l6)Fd
\dlF]]dlF`^dlF\^dlFa\dlFj\dlF[_dlFfh`lF(,
I)blow_upxf*6'FKF^fnFj\yFYFin6/F`^clFa^clFgcn%#vxG%#vyG%#pgG%#qgG%#tgGFb`mF\pF%
FiinF^hxFfh`lFfh`lC/>Fcabl&Fa`clFjabl>Ffbbl&Fa`clFdbbl>Fiebl&Fa`clF[\cl>FdgblFa
o>F[eblFao>FeeblFao>FagblFao>FcdblFao>Fhdbl-Fe\n6%FhablF]bclFj[dl?(Ffh`lF,F,Ffh
`l0FhdblFaoC*>Fgibl-F\an6%FhdblF]bclFj[dl>Faidl,&-F^jm6$Fao-Ffdm6$FgiblF]bclF,F
^vF,>Fcidl-F^jm6$Fao-Ffdm6$FgiblFj[dl>Feidl,&*&FcablF,FaidlF,F,*&FfbblF,FcidlF,
F,>Fdgbl,&FdgblF,*(FhaclF,-Fffn6$/F]bclFhaclFgiblF,)F]bcl,(FeidlF,F,F,FieblF^vF
,F,>F[ebl,&F[eblF,*,FhaclF,)F]bcl,&FeidlF,FieblF^vF,FfbblF,Fj[dlF,F`bglF,F^v@$/
FeidlFieblC$>Feebl,&FeeblF,*&FhaclF,F`bglF,F,>Fcdbl,&FcdblF,**FhaclF,FfbblF,Fj[
dlF,F`bglF,F^v>Fhdbl-Fe\n6%,&FhdblF,FgiblF^vF]bclFj[dl>Fhdbl-Fe\n6%FcbblF]bclFj
[dl?(Ffh`lF,F,Ffh`lFi`glC)>FgiblF\agl>FaidlF`agl>Fcidl,&FeaglF,F^vF,>FeidlFjagl
>F[ebl,&F[eblF,*(FcablF,FhbglF,F`bglF,F,@$F[cglC$>Fagbl,&FagblF,F`bglF,>Fcdbl,&
FcdblF,*&FcablF,F`bglF,F,>FhdblFdcgl7%7$FdgblF[eblF[hdlFcdblFfh`lFfh`lFfh`lF(,
I)blow_upyf*6&Fd[dlF]gfl%*directionGFb[dl6*FfhmFdduFd^wFe^w%$vecGF\p%$manGF[[sF
fh`lFfh`lC->Ffbbl-Fj\u6'FiablFaoF,F,Fao>Fcabl-Fgjfl6'Ffbbl7%F]`glF[`glF_`glFhac
lFYFin>Ffbbl-Fj\u6'&FcablFjablFaoF,F,Fao@$F^cpFiidl-F`r6$Q<blowing~up~vector~fi
eld~%a|+Ffh`lFfbbl>Fiebl-Fffn6$F\dfl-F[[m6$F,&FcablFdbbl>Fdgbl-Fffn6$F\dfl-FU6$
&FcablF[\clFin-F`r6%QT(0,0)~is~a~singular~point~with~eigenvalues~%a,~%a.|+Ffh`l
FdgblFieblF^jdl@%55-Fdgm6$FieblFao-Fdgm6$FdgblFao-F_gm6$Fao*&FieblF,FdgblF,C)>F
[ebl*&-Fffn6%F^cflF\dfl-FU6$-F[[m6$FhnF`fglFYF,,&FieblF,FdgblF^vF^v>Feebl-Fj\u6
'F`fglF,FaoF[eblF,@$F^cpFiidl-F`r6#Q[oTransform~this~vector~field~so~that~the~l
inear~part~is~diagonal|+Ffh`l-F`r6$Feh`l-Fj\u6'FeeblFaoF,F,FaoF^jdl@%-FjfmFhggl
C'>Fcdbl-Fdiel6$FeeblFa]l@$F^cpFiidl-F`r6$Q:unstable~separatrice~x=%aFfh`l-Fffn
6$/F[^sFinFcdblF^jdl@%-F]hmFjggl>Fagbl7)F]bcl7$FaoFao7&F[eblF,F,FaoFeeblFcdblF,
F[o>Fagbl7)F]bclFdjglFejglFeeblFcdbl-F\ecl6&-Fffn6$F\dflFbfblFYFieblFhaclF[o@%-
Fjfm6$FaoFieblC'>FcdblFgigl@$F^cpFiidl-F`r6$Q9stable~separatrice~x=%a|+Ffh`lF]j
glF^jdl@%Fajgl>Fagbl7)F]bclFdjglFejglFeeblFcdblFhnF[o>FagblFgjglC(>Fcdbl-F\bflF
higl@$F^cpFiidl-F`r6$Q6center~manifold~x=%a|+Ffh`l-Fffn6$/FYFin&FcdblFjabl-F`r6
$Q:on~center~manifold~y'=%a|+Ffh`l-Fffn6$Fb\hl&FcdblFdbblF^jdl@%-FjfmFjggl@%2Fa
o-Fffn6$/FYF,&Fcdbl6#F^v>Fagbl7)F]bclFdjglFejglFeebl-Fffn6$Fd]flFc\hlF_asF[o>Fa
gbl7)F]bclFdjglFejglFeeblFe]hlF]bsF[o@%F]]hl>Fagbl7)F]bclFdjglFejglFeeblFe]hlF^
bsF[o>Fagbl7)F]bclFdjglFejglFeeblFe]hlF`wF[o@%Fdigl@%-F]hm6$FieblFdgblC&>F[eblF
`hgl>FeeblFihgl>Fcdbl-Fe]flFhigl>Fagbl7)F]bclFdjglFejglFeeblFcdblFbtF[o>Fagbl7)
F]bclFdjgl7&FaoF,F,FaoF`fglFaoFbtF[o@%F`^hlC&>F[eblF`hgl>FeeblFihgl>FcdblFf^hl>
Fagbl7)F]bclFdjglFejglFeeblFcdblFcjrF[o>Fagbl7)F]bclFdjglF[_hlF`fglFaoFcjrF[oOF
agblFfh`lFfh`lFfh`lF(,
I,sing_eigenvf*6'FfhmFj\y%$lvlGFb[dlFa[dl6.F%FiinFehmF^auF_auF_anFc[dlFceglFcfo
FhcsF\pF[[sFfh`lFfh`lC$@%0Fj[clFaoC'>Feebl-F[gp6$Fj[clFin>FfbblFh^dl?(FieblF,F,
-F.6#F[]clF1@%/Fj[dlF,>Ffbbl-F\hcl6%Ffbbl-F[[m6$FieblF[]clFbo>Ffbbl-F]jclFj`hl?
(FieblF,F,-F.6#&FeeblFdbblF1@%Fg`hl>Ffbbl-F\hcl6%Ffbbl-F[[m6$FieblFbahlF1>Ffbbl
-F]jclFfahl?(FieblF,F,F_edlF1C(>Fagbl-F[[m6$F,&FfbblFaicl>Fdgbl-Fcim6$F\_cl/Fin
Fagbl>F[ebl-Fcim6$-FUFa`hlFdbhl@$-F[[m6$FhnF`bhlC$>Fdgbl-F_oF[ifl>F[ebl-F_oF`eb
l@$F^cpFiidl@%3Figgl-Fdgm6$F[eblFaoC%-F`r6$QB(0,%a)~is~a~non-elementary~point|+
Ffh`lFagblF^jdl-%,blowing_up2G6(FhablFagbl,&FhaclF,F,F,F]bclFj[dlFbo@%55FigglFd
chl-F_gm6$Fao*&FdgblF,F[eblF,C0>Fcdbl-FU6$Fi^clFY>Fcdbl-Fffn6%F^cflFdbhl*&Fcdbl
F,,&FdgblF,F[eblF^vF^v@$Fjbhl>Fcdbl-F_o6#Fcdbl>Fhdbl-F_[u6'FhablFYFinFaoFagbl@$
Fjbhl>Fhdbl-F_oFfhel>Fgibl7&F,FaoFcdblF,>Faidl-Fj\u6'FhdblF,FaoFcdblF,@$Fjbhl>F
aidl-F_oF\iel-F`r6&QS(0,%a)~is~a~singular~point~with~eigenvalues~%a,%a|+Ffh`lFa
gblFdgblF[ebl-F`r6#QAmoving~this~point~to~the~origin|+Ffh`l-F`r6$Q<the~new~vect
or~field~is~%a|+Ffh`lFhdbl-F`r6#Q[otransform~this~vector~field~so~that~the~line
ar~part~is~diagonal|+Ffh`l-F`r6$FgfhlFaidl@%F[]hlC%>Fcidl-Fdiel6$FaidlFa]l-F`r6
$Q;unstable~separatrice~y=%a|+Ffh`l-Fffn6$/F[^sFYFcidl@%-F]hmFechl-F^[dl6)Fj[dl
F,F]bcl7$FaoFagblFgiblFaidlFcidl-F^[dl6)Fj[dl-Fi_cl6&-Fffn6$F^cfl&FaidlFdbblFin
FdgblFa`clF]bclF\hhlFgiblFaidlFcidl@%-Fjfm6$FaoFdgblC%>FcidlF`ghl-F`r6$Q9stable
~separatrice~y=%a|+Ffh`lFeghl@%Fighl-F^[dl6)Fj[dlFhnF]bclF\hhlFgiblFaidlFcidlF]
hhlC&>Fcidl-F\bflFaghl-F`r6$Q6center~manifold~y=%a|+Ffh`l&FcidlFjabl-F`r6$Q=on~
center~manifold~is~x'=%a|+Ffh`l&FcidlFdbbl@%-FjfmFechl@%2Fao-Fciw6#-F_o6#-Fffn6
$F`]hl&FcidlF[\cl-F^[dl6)Fj[dlF_asF]bclF\hhlFgiblFaidl-Fffn6$Fd]flFeihl-F^[dl6)
Fj[dlF]bsF]bclF\hhlFgiblFaidlFgjhl@%F]jhl-F^[dl6)Fj[dlF^bsF]bclF\hhlFgiblFaidlF
gjhl-F^[dl6)Fj[dlF`wF]bclF\hhlFgiblFaidlFgjhl@%F[]hlC$-F`r6&QS(0,%a)~is~an~unst
able~node~with~eigenvalues~%a,%a|+Ffh`lFagblFdgblF[ebl@%-F]hm6$FdgblF[eblC+>Fcd
bl*&FfdhlF,F\ehlF^v>Fcdbl-Fffn6%F^cflFdbhlFcdbl@$Fjbhl>FcdblF_ehl>FhdblFbehl@$F
jbhl>FhdblFfehl>FgiblFhehl>FaidlFjehl>Fcidl-Fe]flFaghl-F^[dl6)Fj[dlFbtF]bclF\hh
lFgiblFaidlFcidl-F^[dl6)Fj[dlFbtF]bclF\hhl7&F,FaoFaoF,FbehlFaoC$-F`r6&QP(0,%a)~
is~a~stable~node~with~eigenvalues~%a,%a|+Ffh`lFagblFdgblF[ebl@%Ff[ilC+>FcdblFj[
il>FcdblF\\il@$Fjbhl>FcdblF_ehl>FhdblFbehl@$Fjbhl>FhdblFfehl>FgiblFhehl>FaidlFj
ehl>FcidlFf\il-F^[dl6)Fj[dlFcjrF]bclF\hhlFgiblFaidlFcidl-F^[dl6)Fj[dlFcjrF]bclF
\hhlF[]ilFbehlFaoC-@$F^cpFiidl-F`r6#QUx=0~is~a~line~of~singularities~-~point~is
~star-like|+Ffh`l>Feebl-F[gp6$F\_clFin>FfbblFh^dl?(FieblF,F,Fd`hlF1@%Fg`hl>Ffbb
lFi`hl>FfbblF^ahl?(FieblF,F,F`ahlF1@%Fg`hl>FfbblFeahl>FfbblFjahl-F`r6#QZthe~non
-elementary~singular~points~(contact~points)~are:|+Ffh`l?(FieblF,F,Fd`hlF1-F`r6
$Q((0,%a)|+Ffh`lF[ahl?(FieblF,F,F`ahlF1-F`r6$Fg_ilFgahlF^jdl?(FieblF,F,F_edlF1-
F[dhl6(FhablF^bhlF]dhlF]bclFj[dlF1F^jdlFfh`lFfh`lFfh`lF(,
I-blowing_upy2f*6(FKF]gflFj\yFb[dlFa[dlFjb\l6&FdduFfhm%#sxG%#syGFfh`lFfh`lC*>Fc
ablFgegl>Ffbbl-Fgjfl6'FcablF\fglFhaclFYFin>Fcabl-Fj\u6'FbfblFaoF,F,Fao@$F^cpFii
dl@%/FhaclF,-F`r6#QHblowing~up~in~the~positive~y-direction|+Ffh`l-F`r6#QHblowin
g~up~in~the~negative~y-direction|+Ffh`l-F`r6$QAblowing~up~the~vector~field~%a.|
+Ffh`lFcablF^jdl@%/F[\dlFboC%>Fiebl-Fciw6#-F_o6#-Fffn6$F`]hl-Fc_n6$-Fffn6$F\dfl
F`fglFY>Fdgbl-Fciw6#-F_o6#-Fffn6$/FinF,-Fc_n6$-Fffn6$F^cflFjfglFin@$/FieblFdgbl
@%2FaoFiebl-F^[dl6)Fj[dlFbtF]bclFdjglF[]ilFcablF[^s-F^[dl6)Fj[dlFcjrF]bclFdjglF
[]ilFcablF[^sC%@$/FbbilFaoYQ^pcase~not~treated:~star-like~points~should~become~
non~star-like~after~second~blowup.Ffh`l>FieblF\bil@%2Fao*&FhaclF,Fj[dlF,-F^[dl6
)Fj[dl,&FcjdlF,FieblF^vF]bclFdjglF[]ilFcablF[^s-F^[dl6)Fj[dl,&F^bmF,FieblF^vF]b
clFdjglF[]ilFcablF[^sFfh`lFfh`lFfh`lF(,
I,blowing_up2f*6(FKFc[dlFi_hlFb[dlFa[dlFjb\l6(FdduF\gflFcbmF]gfl%$trfGFfhmFfh`l
Ffh`lC:@$F^cp-F\r6$F^rFgel-F`r6$Q5Blowing~up~level~%d|+Ffh`lFhaclF_jfl-F`r6%Q?b
lowing~up~%a~in~point~(0,%a)|+Ffh`lFiablFa`cl@%-F]hm6$Fa`clFaoC%>Fcabl-F_[u6'Fi
ablFYFinFaoFa`cl-F`r6$Q=moving~(0,%a)~to~the~origin|+Ffh`lFa`cl-F`r6$Q5new~vect
or~field~%a|+Ffh`lFcabl>FcablFiabl>Ffbbl-FhcblFecbl>Fiebl-FdjblFgcbl>Fdgbl-F]^c
lFaicl-F`r6$Q3Newton~diagram~%a|+Ffh`lFfbbl-F`r6$Q8[alpha,beta,degree]=%a|+Ffh`
lFdgblF^jdl@%Fiail@%Fg`hlC$>F[ebl7+FaoFa`clF,F^vF,FbhblFaoFdhblFjddl-F^`il6(Fca
blFdgblF^v7$-F[[m6#F]bclF[eblFj[dlFboC$>F[ebl7+FaoFa`clF,F,F,FbhblFaoFdhblFjddl
-F^`il6(FcablFdgblF,FigilFj[dlFbo@%Fg`hlC$>F[eblFfgil-F^`il6(FcablFdgblF^vFigil
Fj[dlF1C$>F[eblF^hil-F^`il6(FcablFdgblF,FigilFj[dlF1@$F^cpF`eil-F`r6#QHblowing~
up~in~the~positive~x~direction|+Ffh`l>Feebl-Fgjfl6'FcablFdgblF,FYFin-F`r6$Fdfgl
F[]clF^jdl>F[ebl7+FaoFa`clF,F,FbhblFaoFdhblF,Fjddl-F^[gl6'FeeblF,FhaclFigilFj[d
l@%Fiail@%Fg`hlC$>F[eblF^hilF_hilC$FfgilFggil@%Fg`hlC$>F[eblF^hilFhhilC$FfgilFd
hil@$F^cpF`eil-F`r6#QI---------------------------------------|+Ffh`l-F`r6$Q2Bac
k~to~level~%d|+Ffh`l,&FhaclF,F^vF,F^jdlFfh`lFfh`lFfh`lF(,
I(ManXPosFh^dlF(,
I(ManXNegFh^dlF(,
I(NumXPosFaoF(,
I(NumXNegFaoF(,
I(NumberYFaoF(,
I(ManYPosFh^dlF(,
I(ManYNegFh^dlF(,
I,user_bindirQ2/usr/local/p4/binF(F(,
I,user_tmpdirQ%/tmpF(F(,
I,user_lypexeQ)lyapunovF(F(,
I0user_lypexe_mpfQ-lyapunov_mpfF(F(,
I/user_removecmdQ#rmF(F(,
I,user_sepexeQ,separatriceF(F(
