M7R0
I)save_all%&falseG6",
I3real_roots_numericf*6$%"fG%"xG6&%%cplxG%"jG%"kG%"gGF$F$C'>8$7#-%'fsolveG6&9$9
%%(complexG%+fulldigitsG@$/F17#/F7F7>F17">8'F??(8%"""FD-%%nopsG6#F1%%trueG@$1-%
$absG6#-%#ImG6#&F16#FC)"#5,$%/user_precisionG!""C%>FQ-%#ReGFP?(8&FDFD-FF6#FAFH@
$-%+reduce_eeqG6$FQ&FA6#Fgn[@$2FhnFgn>FA7$-%#opGFinFQ-%%sortGFinF$F$F$F$,
I1find_real_roots1f*F'6'%"hG%#geG%#gnGF-%"bGF$F$C$@%%(roundedGC$>FCF?>Fgn-F%6$F
6F7C*>%-_EnvExplicitGFH>%1_EnvAllSolutionsGFH>%,_EnvTryHardGFH>F17#-%&solveGFgp
@$/F17#F7>F1F?>FCF?>FgnF??(FAFDFDFEFHC$>8(&F1Fin@%-%$hasG6$F\r%'RootOfGC$>F\r-%
&evalfG6#F\r@$1-FL6#-FOFgrFSC$>F\r-FenFgr>Fgn7$-FfoF_oF\r@$1-FL6#-FfrF[sFSC$>F
\rF_s>FC7$-FfoFRF\r7$-%(convertG6$-F_t6$FC%$setG%%listG-F_t6$-F_t6$FgnFctFdtF$F
$F$F$,
I8find_real_roots_numericf*6%F(F)%"yG6'F.F\pF,F-%"aGF$F$C*>FjpFH>F\qFH>F^qFH>FC
-Ffr6#-%$mapG6$%*allvaluesG7#-Fbq6$-F_t6$F6Fct<$F79&>F1F??(FgnFDFD-FFFRFHC$>F\r
-%%subsG6$&FCF_o7$F7F`v@$32-FL6#-FO6#&F\r6#FDFS2-FL6#-FO6#&F\r6#""#FSC%>F\r-Fgu
6$FenF\r?(FAFDFDFEFH@$32-FL6#,&-Ffo6$FDF]rFDFbwFWFS2-FL6#,&-Ffo6$F[xF]rFDFiwFWF
SF`o@$2FEFAC%>F17$-FfoFGF\r@$/FEFD-%'writefG6#Q=Numeric~real~singularities:|+F$
-Fhy6'QC~~(%g,%g)~->~|fr~x'~=~%g,~y'~=~%g~|hr|+F$FbwFiw-Ffr6#-Fgv6$<$/F7Fbw/F`v
Fiw&F6Fcw-Ffr6#-Fgv6$Fbz&F6Fjw@$/FE""!-Fhy6#QENo~numeric~singularities~are~foun
d.|+F$F1F$F$F$F$,
I0find_real_rootsf*F[u6,F.F\pF,F-F^u%#anGF^p%"sG%#snG%#bnGF$F$C2>FjpFH>F\qFH>F^
qFH>FCFfu>F1F?>8*F??(FgnFDFDFcvFHC&>F\rFfv>8)-Fgu6$FenFer>8--Fgu6$FOFer@$32-FL6
#&Fh\lFcwFS2-FL6#&Fh\lFjwFSC$?(FAFDFD-FF6#F_\lFH@$32-FL6#,&-Ffo6$FD&F_\lFinFD&F
d\lFcwFWFS2-FL6#,&-Ffo6$F[xFa^lFD&Fd\lFjwFWFSF`o@$2Fg]lFAC$>F1Fcy>F_\l7$-FfoFh]
lFd\l>8+F?>8,F??(FAFDFDFg]lFH@%5-F`r6$FgxFbr-F`r6$F]yFbr>Fd_l7$-Ffo6#Fd_lFa^l>F
b_l7$-Ffo6#Fb_lF]r?(FgnFDFD-FFFc`lFHC$>&&Fb_lF_oFcw-Fen6#Fh`l>&Fi`lFjw-Fen6#F]a
l@%/Fe`lF][l-Fhy6#QKNo~symbolic~real~singularities~are~found.|+F$-Fhy6#Q>Symbol
ic~real~singularities:|+F$?(FAFDFDFe`lFH-Fhy6'F]z-Ffo6$FD&Fb_lFin-Ffo6$F[xF]bl-
Ffr6#-Fgv6$<$/F7F[bl/F`vF^blFezF`bl@%/-FFF_`lF][l@%Faal-Fhy6#QJNo~numeric~real~
singularities~are~found.|+F$-Fhy6#QPNo~other~numeric~real~singularities~are~fou
nd.|+F$Fgy?(FAFDFDFiblFH-Fhy6'F]z-Ffo6$FD&Fd_lFin-Ffo6$F[xFfcl-Ffr6#-Fgv6$<$/F7
Fdcl/F`vFgclFezFicl7$Fb_lFd_lF$F$F$F$,
I2find_real_roots11f*6$%"LGF)6+%#f1G%#f2GF(F.F]pF^p%$ge2G%$gn2GF,F$F$C,>F1-%4op
timizepolynomial1G6$FezF7>FC-F]el6$FjzF7@%0-%$maxG6$-%'degreeG6$F1F7F][lF][lC$>
FA-FioFiel>FgnFC@%0-Feel6$-Fhel6$FCF7F][lF][lC$>FA-FioFcfl>FgnF1C$>FA7$F?F?>Fgn
F][l>F\r&FAFcw>Fd\l&FAFjw>F_\lF?>Fb_lF??(Fd_lFDFD-FFFgrFH@$2-FL6#-Ffr6#-Fgv6$/F
7&F\rF_`lFgnFS>F_\l7$F`_lF]hl?(Fd_lFDFD-FF6#Fd\lFH@$2-FL6#-Ffr6#-Fgv6$/F7&Fd\lF
_`lFgnFS>Fb_l7$Fb`lF\il7$F_\lFb_lF$F$F$F$
