M7R0
I)save_all%&falseG6",
I3real_roots_numericf*6$%"fG%"xG6&%%cplxG%"jG%"kG%"gGF$F$C&>8$7#-%'fsolveG6&9$9
%%(complexG%+fulldigitsG>8'7"?(8%"""F?-%%nopsG6#F1%%trueG@$1-%$absG6#-%#ImG6#&F
16#F>)"#5,$%/user_precisionG!""C%>FL-%#ReGFK?(8&F?F?-FA6#F;FC@$-%+reduce_eeqG6$
FL&F;6#FX[@$2FYFX>F;7$-%#opGFZFL-%%sortGFZF$F$F$F$,
I1find_real_roots1f*F'6'%"hG%#geG%#gnGF-%"bGF$F$C$@%%(roundedGC$>F>F<>FX-F%6$F6
F7C)>%-_EnvExplicitGFC>%1_EnvAllSolutionsGFC>%,_EnvTryHardGFC>F17#-%&solveGFbp>
F>F<>FXF<?(F;F?F?F@FCC$>8(&F1FZ@%-%$hasG6$Fcq%'RootOfGC$>Fcq-%&evalfG6#Fcq@$1-F
G6#-FJF^rFNC$>Fcq-FVF^r>FX7$-FaoFjnFcq@$1-FG6#-F]rFbrFNC$>FcqFfr>F>7$-FaoFMFcq7
$-%(convertG6$-Ffs6$F>%$setG%%listG-Ffs6$-Ffs6$FXFjsF[tF$F$F$F$,
I8find_real_roots_numericf*6%F(F)%"yG6'F.FgoF,F-%"aGF$F$C*>FepFC>FgpFC>FipFC>F>
-F]r6#-%$mapG6$%*allvaluesG7#-F]q6$-Ffs6$F6Fjs<$F79&>F1F<?(FXF?F?-FAFMFCC$>Fcq-
%%subsG6$&F>Fjn7$F7Fgu@$32-FG6#-FJ6#&Fcq6#F?FN2-FG6#-FJ6#&Fcq6#""#FNC%>Fcq-F^u6
$FVFcq?(F;F?F?F@FC@$32-FG6#,&-Fao6$F?FdqF?FivFRFN2-FG6#,&-Fao6$FbwFdqF?F`wFRFNF
[o@$2F@F;C%>F17$-FaoFBFcq@$/F@F?-%'writefG6#Q=Numeric~real~singularities:|+F$-F
_y6'QC~~(%g,%g)~->~|fr~x'~=~%g,~y'~=~%g~|hr|+F$FivF`w-F]r6#-F^v6$<$/F7Fiv/FguF`
w&F6Fjv-F]r6#-F^v6$Fiy&F6Faw@$/F@""!-F_y6#QENo~numeric~singularities~are~found.
|+F$F1F$F$F$F$,
I0find_real_rootsf*Fbt6,F.FgoF,F-Fet%#anGFio%"sG%#snG%#bnGF$F$C2>FepFC>FgpFC>Fi
pFC>F>F]u>F1F<>8*F<?(FXF?F?FjuFCC&>FcqF]v>8)-F^u6$FVF\r>8--F^u6$FJF\r@$32-FG6#&
F_\lFjvFN2-FG6#&F_\lFawFNC$?(F;F?F?-FA6#Ff[lFC@$32-FG6#,&-Fao6$F?&Ff[lFZF?&F[\l
FjvFRFN2-FG6#,&-Fao6$FbwFh]lF?&F[\lFawFRFNF[o@$2F^]lF;C$>F1Fjx>Ff[l7$-FaoF_]lF[
\l>8+F<>8,F<?(F;F?F?F^]lFC@%5-Fgq6$F^xFiq-Fgq6$FdxFiq>F[_l7$-Fao6#F[_lFh]l>Fi^l
7$-Fao6#Fi^lFdq?(FXF?F?-FAFj_lFCC$>&&Fi^lFjnFjv-FV6#F_`l>&F``lFaw-FV6#Fd`l@%/F
\`lFdz-F_y6#QKNo~symbolic~real~singularities~are~found.|+F$-F_y6#Q>Symbolic~rea
l~singularities:|+F$?(F;F?F?F\`lFC-F_y6'Fdy-Fao6$F?&Fi^lFZ-Fao6$FbwFdal-F]r6#-F
^v6$<$/F7Fbal/FguFealF\zFgal@%/-FAFf_lFdz@%Fh`l-F_y6#QJNo~numeric~real~singular
ities~are~found.|+F$-F_y6#QPNo~other~numeric~real~singularities~are~found.|+F$F
^y?(F;F?F?F`blFC-F_y6'Fdy-Fao6$F?&F[_lFZ-Fao6$FbwF]cl-F]r6#-F^v6$<$/F7F[cl/FguF
^clF\zF`cl7$Fi^lF[_lF$F$F$F$,
I2find_real_roots11f*6$%"LGF)6+%#f1G%#f2GF(F.FhoFio%$ge2G%$gn2GF,F$F$C,>F1-%4op
timizepolynomial1G6$F\zF7>F>-Fddl6$FazF7@%0-%$maxG6$-%'degreeG6$F1F7FdzFdzC$>F;
-FdoF`el>FXF>@%0-F\el6$-F_el6$F>F7FdzFdzC$>F;-FdoFjel>FXF1C$>F;7$F<F<>FXFdz>Fcq
&F;Fjv>F[\l&F;Faw>Ff[lF<>Fi^lF<?(F[_lF?F?-FAF^rFC@$2-FG6#-F]r6#-F^v6$/F7&FcqFf_
lFXFN>Ff[l7$Fg^lFdgl?(F[_lF?F?-FA6#F[\lFC@$2-FG6#-F]r6#-F^v6$/F7&F[\lFf_lFXFN>F
i^l7$Fi_lFchl7$Ff[lFi^lF$F$F$F$
