M7R0
I,returnvalue""!6",
I8findAllSeparatingCurvesf*F$6'%#fpG%"kG%"rG%*numcurvesG%0numcurveregionsGF$F$C
.>%-user_numericG%%trueG>%(roundedGF0>8'-%%nopsG6#%,user_curvesG>8(-F66#%-curve
regionsG-%'printfG6$Q7The~curves~file~is~%a|+F$%0user_curvesfileG>8$-%&fopenG6%
FB%&WRITEG%%TEXTG?(8&"""FLF4F0C$@$5-%%typeG6$&F86#FK%)equationG-FQ6$FS%#<=G>FS,
&-%$lhsG6#FSFL-%$rhsGFgn!""@$/-%6CheckIfGoodPolynomialGFgn%&falseGC'-F?6%Q[rThe
~separating~curve~#%d:~%a~is~not~well-defined~(not~polynomial,~or~coefficients~
do~not~evaluate~numerically.)|+F$FKFS-%'fcloseG6#FD>F"F#%%NULLGOF$-%(fprintfG6(
FDQ0p5|+%d~%d~%d~%d|+F$%'user_pG%'user_qG%/user_precisionGF4?(FKFLFLF4F0C%>%/us
er_numpointsG&%5user_numpointscurvesGFT>%'user_fGFS@$4-%4findSeparatingCurveGFf
oC'Fdo-Feo6#-FF6%%*user_fileGFHFI>F"F#FhoOF$Fdo>F"FLFhoF$6(FhpFdpF8F2F/F"F$F$,
I4findSeparatingCurvef*6#F(6.%"fG%$fU1G%$fV1G%$fU2G%$fV2G%#fCG%#z1G%#z2G%"sG%"L
G%"jG%"dGF$F$CG>FDFhp>8/-%%ddegG6%FD%"xG%"yG@%/FjrF#-F[p6%9$Q$%d|+F$F#C$>8--%.c
oeff_degree2G6%%%gcffGF^sF_s-F[p6%FdsFesFjr>Fhs-FjsF]s-F[p6%FdsQ#%dF$-F66#Fhs?(
8.FLFLFdtF0-F[p6'FdsQ*~%d~%d~%gF$-%#opG6$FL&Fhs6#Fgt-F\u6$""#F^u-%&evalfG6#-F\u
6$""$F^u-F[p6$FdsQ"|+F$>8%-%%subsG6%/F^s*$)8+F^pFjn/F_s*&8*FL)FdvF_pFjnFD>F]v-%
)norpoly2G6%F]vFgvFdv>F]v-F_v6%/FgvF^s/FdvF_s-%&numerG6#F]v>Fhs-Fjs6%F]vF^sF_sF
at?(FgtFLFLFdtF0FhtFiu>F4-F_v6%/F^s*&FgvFLFcvFjn/F_s*$FhvFjnFD>F4-F[w6%F4FgvFdv
>F4-F_v6%F`wFaw-Fcw6#F4>Fhs-Fjs6%F4F^sF_sFat?(FgtFLFLFdtF0FhtFiu>FK-F_v6%/F^s,$
FbvFjnFevFD>FK-F[w6%FKFgvFdv>FK-F_v6%F`wFaw-FcwFT>Fhs-Fjs6%FKF^sF_sFat?(FgtFLFL
FdtF0FhtFiu>F:-F_v6%F\x/F_s,$F_xFjnFD>F:-F[w6%F:FgvFdv>F:-F_v6%F`wFaw-Fcw6#F:>F
hs-Fjs6%F:F^sF_sFat?(FgtFLFLFdtF0FhtFiu@%3/F^pFL/F_pFLCO>FhpFD>%(user_x1G,$$"#5
FjnFjn>%(user_x2GFf[l>%(user_y1G,$Ff[lFjn>%(user_y2GFf[l>%"uGF^s>%"vGF_s-F?6#Q+
Chart~R2:~F$@$4-%;findSeparatingCurveInChartG6#FdsOF_o>FhpF]v>Fd[l,$Ff[lFjn>Fi[
lFf[l>F[\l$F#F#>F^\lFf[l>F`\lF^s>Fb\lF_s-F?6#Q+Chart~U1:~F$@$Fg\lOF_o>FhpF4>Fd[
l,$Ff[lFjn>Fi[lFf[l>F[\lFa]l>F^\lFf[l>F`\lF^s>Fb\lF_s-F?6#Q+Chart~U2:~F$@$Fg\lO
F_o>FhpF]v>Fd[l,$Ff[lFjn>Fi[lFf[l>F[\l,$Ff[lFjn>F^\lFa]l>F`\lF^s>Fb\lF_s-F?6#Q,
Chart~V1':~F$@$Fg\lOF_o>FhpF4>Fd[l,$Ff[lFjn>Fi[lFf[l>F[\l,$Ff[lFjn>F^\lFa]l>F`
\lF^s>Fb\lF_s-F?6#Q,Chart~V2':~F$@$Fg\lOF_oCV>8)-F_v6%/F^s*&%"UGFL)8,F^pFjn/F_s
*&%"VGFL)F\alF_pFjnFD>Fe`l-%)norpoly3G6&Fe`lF\alFj`lF_al>Fe`l-F_v6$/F\alF^s-Fcw
6#Fe`l>Fhs-%.coeff_degree3G6&Fe`lF^sFj`lF_alFat?(FgtFLFLFdtF0-F[p6(FdsQ-~%d~%d~
%d~%gF$F[uF`uFfu-Fdu6#-F\u6$""%F^uFiu>Fhp-%%evalG6$FD<$/F^sFj`l/F_sF_al>Fd[lFa]
l>Fi[lFf[l>F[\lFa]l>F^\l-Fdu6#,$%#PiGFbu>F`\l*&F^sFL-%$cosG6#F_sFL>Fb\l*&F^sFL-
%$sinGF[dlFL-F?6#Q>Chart~R2~(Lyapunov-weights):~F$@$Fg\lOF_o>Fd[lFa]l>Fi[lFf[l>
F[\l-Fdu6#,$Ffcl#FjnFgbl>F^\l-Fdu6#,$Ffcl#FLFgbl>FhpFe`l>F`\lFicl>Fb\lF^dl-F?6#
Q>Chart~U1~(Lyapunov-weights):~F$@$Fg\lOF_o>Fd[lFa]l>Fi[lFf[l>F[\lF]el>F^\l-Fdu
6#,$Ffcl#FhuFgbl>FhpFe`l>F`\lFicl>Fb\lF^dl-F?6#Q>Chart~U2~(Lyapunov-weights):~F
$@$Fg\lOF_o>Fd[lFa]l>Fi[lFf[l>F[\lF]fl>F^\l-Fdu6#,$Ffcl#""&Fgbl>FhpFe`l>F`\lFic
l>Fb\lF^dl-F?6#Q>Chart~V1~(Lyapunov-weights):~F$@$Fg\lOF_o>Fd[lFa]l>Fi[lFf[l>F[
\l-Fdu6#,$Ffcl#!"$Fgbl>F^\lFhdl>FhpFe`l>F`\lFicl>Fb\lF^dl-F?6#Q>Chart~V2~(Lyapu
nov-weights):~F$@$Fg\lOF_oOF0F$6)Fd[lFi[lF[\lF^\lF`\lFb\lFhpF$F$,
I;findSeparatingCurveInChartf*Fiq6,%"mG%"nG%"PGF)%"iGFerFcrF[r%9CURVES_ARRAY_TO
_LISTLISTG%-SimplifyPlotGF$F$C(>F\alf*F$6$%#ssGF)F$F$C%>FD7#-%"$G6#;FL9#?(F]vFL
FLFbjlF0C$>&FDFdw&9"Fdw@$-FQ6$Ffjl%&ArrayG@&/-%-ArrayNumDimsG6#FfjlFbu>Ffjl-%(c
onvertG6$Ffjl%)listlistG/F_[mFL>Ffjl-Fd[m6$Ffjl%%listG-%'CURVESG6#-F\uFfoF$F$F$
>Fhsf*6#FbilF$6$%)operatorG%&arrowGF$-Fjbl6$Fds/F]\mT#F$F$6$FdilF\al>F"FL@%1-%'
degreeG6$Fhp7&F^sF_sFj`lF_alF#C%-F?6$Q@%a:~Level~curve~is~a~constant.|+F$FhpFbs
OF0C.>FD,&-%&roundG6#-%%sqrtG6#FdpFLFLFL>F]vFD>%%facsG&-%(factorsG6#-F_v6$<$/Fj
`lF`\l/F_alFb\lFhp6#Fbu>FK-%$mapG6$f*6#%$facGF$Fc\mF$-&%&plotsG6#%-implicitplot
G6)Fds/F^s;Fd[lFi[l/F_s;F[\lF^\l/%%axesG%%noneG/%%viewG7$F[`mF]`m/%%gridG7$Fi\m
T%/%&colorG%&blackGF$F$6&F`ilFDFailF]vFb^m>FK-F__m6$FhsFK>FK-F__m6$f*Fb_mF$Fc\m
F$-F\u6#-%'selectG6$f*6#%#ptGF$Fc\mF$-FQ6$FdsF[\mF$F$F$7#-F\u6#-F\u6$FLFdsF$F$F
$FK>F4F#?(F:FLFL-F6FTF0>F4,&F4FL-F66#&FKFhzFL-F[p6%FdsFesF4>F4F#?(F:FLFLFdbmF0C
$?(Fe`lFLFLFgbmF0C%>Fgv-%(sprintfG6%Q'%g~%g~F$&FK6%F:Fe`lFL&FK6%F:Fe`lFbu-F[p6%
FdsQ#%sF$Fgv>F4,&F4FLFLFL@%0F:Fdbm-F[p6$FdsQ#,|+F$Fiu-F?6%Q9%a:~%d~points~retur
ned.|+F$FhpF4>F"F#OF0F$6)F`\lFb\lF"Fb^mFc_mFhpFdpF$F$
