M7R0
I,returnvalue""!6",
I8findAllSeparatingCurvesf*F$6'%#fpG%"kG%"rG%*numcurvesG%0numcurveregionsGF$F$C
->%-user_numericG%%trueG>%(roundedGF0>8'-%%nopsG6#%,user_curvesG>8(-F66#%-curve
regionsG>8$-%&fopenG6%%0user_curvesfileG%&WRITEG%%TEXTG?(8&"""FHF4F0C$@$5-%%typ
eG6$&F86#FG%)equationG-FM6$FO%#<=G>FO,&-%$lhsG6#FOFH-%$rhsGFY!""@$/-%6CheckIfGo
odPolynomialGFY%&falseGC'-%'printfG6%Q[rThe~separating~curve~#%d:~%a~is~not~wel
l-defined~(not~polynomial,~or~coefficients~do~not~evaluate~numerically.)|+F$FGF
O-%'fcloseG6#F?>F"F#%%NULLGOF$-%(fprintfG6(F?Q0p5|+%d~%d~%d~%d|+F$%'user_pG%'us
er_qG%/user_precisionGF4?(FGFHFHF4F0C%>%/user_numpointsG&%5user_numpointscurves
GFP>%'user_fGFO@$4-%4findSeparatingCurveGFcoC'Fao-Fbo6#-FA6%%*user_fileGFDFE>F"
F#FeoOF$Fao>F"FHFeoF$6(FepFapF8F2F/F"F$F$,
I4findSeparatingCurvef*6#F(6.%"fG%$fU1G%$fV1G%$fU2G%$fV2G%#fCG%#z1G%#z2G%"sG%"L
G%"jG%"dGF$F$CG>F?Fep>8/-%%ddegG6%F?%"xG%"yG@%/FgrF#-Fho6%9$Q$%d|+F$F#C$>8--%.c
oeff_degree2G6%%%gcffGF[sF\s-Fho6%FasFbsFgr>Fes-FgsFjr-Fho6%FasQ#%dF$-F66#Fes?(
8.FHFHFatF0-Fho6'FasQ*~%d~%d~%gF$-%#opG6$FH&Fes6#Fdt-Fit6$""#F[u-%&evalfG6#-Fit
6$""$F[u-Fho6$FasQ"|+F$>8%-%%subsG6%/F[s*$)8+F[pFfn/F\s*&8*FH)FavF\pFfnF?>Fju-%
)norpoly2G6%FjuFdvFav>Fju-F\v6%/FdvF[s/FavF\s-%&numerG6#Fju>Fes-Fgs6%FjuF[sF\sF
^t?(FdtFHFHFatF0FetFfu>F4-F\v6%/F[s*&FdvFHF`vFfn/F\s*$FevFfnF?>F4-Fhv6%F4FdvFav
>F4-F\v6%F]wF^w-F`w6#F4>Fes-Fgs6%F4F[sF\sF^t?(FdtFHFHFatF0FetFfu>FG-F\v6%/F[s,$
F_vFfnFbvF?>FG-Fhv6%FGFdvFav>FG-F\v6%F]wF^w-F`wFP>Fes-Fgs6%FGF[sF\sF^t?(FdtFHFH
FatF0FetFfu>F:-F\v6%Fiw/F\s,$F\xFfnF?>F:-Fhv6%F:FdvFav>F:-F\v6%F]wF^w-F`w6#F:>F
es-Fgs6%F:F[sF\sF^t?(FdtFHFHFatF0FetFfu@%3/F[pFH/F\pFHCO>FepF?>%(user_x1G,$$"#5
FfnFfn>%(user_x2GFc[l>%(user_y1G,$Fc[lFfn>%(user_y2GFc[l>%"uGF[s>%"vGF\s-F^o6#Q
+Chart~R2:~F$@$4-%;findSeparatingCurveInChartG6#FasOF[o>FepFju>Fa[l,$Fc[lFfn>Ff
[lFc[l>Fh[l$F#F#>F[\lFc[l>F]\lF[s>F_\lF\s-F^o6#Q+Chart~U1:~F$@$Fd\lOF[o>FepF4>F
a[l,$Fc[lFfn>Ff[lFc[l>Fh[lF^]l>F[\lFc[l>F]\lF[s>F_\lF\s-F^o6#Q+Chart~U2:~F$@$Fd
\lOF[o>FepFju>Fa[l,$Fc[lFfn>Ff[lFc[l>Fh[l,$Fc[lFfn>F[\lF^]l>F]\lF[s>F_\lF\s-F^o
6#Q,Chart~V1':~F$@$Fd\lOF[o>FepF4>Fa[l,$Fc[lFfn>Ff[lFc[l>Fh[l,$Fc[lFfn>F[\lF^]l
>F]\lF[s>F_\lF\s-F^o6#Q,Chart~V2':~F$@$Fd\lOF[oCV>8)-F\v6%/F[s*&%"UGFH)8,F[pFfn
/F\s*&%"VGFH)Fi`lF\pFfnF?>Fb`l-%)norpoly3G6&Fb`lFi`lFg`lF\al>Fb`l-F\v6$/Fi`lF[s
-F`w6#Fb`l>Fes-%.coeff_degree3G6&Fb`lF[sFg`lF\alF^t?(FdtFHFHFatF0-Fho6(FasQ-~%d
~%d~%d~%gF$FhtF]uFcu-Fau6#-Fit6$""%F[uFfu>Fep-%%evalG6$F?<$/F[sFg`l/F\sF\al>Fa[
lF^]l>Ff[lFc[l>Fh[lF^]l>F[\l-Fau6#,$%#PiGF_u>F]\l*&F[sFH-%$cosG6#F\sFH>F_\l*&F[
sFH-%$sinGFhclFH-F^o6#Q>Chart~R2~(Lyapunov-weights):~F$@$Fd\lOF[o>Fa[lF^]l>Ff[l
Fc[l>Fh[l-Fau6#,$Fccl#FfnFdbl>F[\l-Fau6#,$Fccl#FHFdbl>FepFb`l>F]\lFfcl>F_\lF[dl
-F^o6#Q>Chart~U1~(Lyapunov-weights):~F$@$Fd\lOF[o>Fa[lF^]l>Ff[lFc[l>Fh[lFjdl>F[
\l-Fau6#,$Fccl#FeuFdbl>FepFb`l>F]\lFfcl>F_\lF[dl-F^o6#Q>Chart~U2~(Lyapunov-weig
hts):~F$@$Fd\lOF[o>Fa[lF^]l>Ff[lFc[l>Fh[lFjel>F[\l-Fau6#,$Fccl#""&Fdbl>FepFb`l>
F]\lFfcl>F_\lF[dl-F^o6#Q>Chart~V1~(Lyapunov-weights):~F$@$Fd\lOF[o>Fa[lF^]l>Ff[
lFc[l>Fh[l-Fau6#,$Fccl#!"$Fdbl>F[\lFedl>FepFb`l>F]\lFfcl>F_\lF[dl-F^o6#Q>Chart~
V2~(Lyapunov-weights):~F$@$Fd\lOF[oOF0F$6)Fa[lFf[lFh[lF[\lF]\lF_\lFepF$F$,
I;findSeparatingCurveInChartf*Ffq6,%"mG%"nG%"PGF)%"iGFbrF`rFhq%9CURVES_ARRAY_TO
_LISTLISTG%-SimplifyPlotGF$F$C(>Fi`lf*F$6$%#ssGF)F$F$C%>F?7#-%"$G6#;FH9#?(FjuFH
FHF_jlF0C$>&F?Faw&9"Faw@$-FM6$Fcjl%&ArrayG@&/-%-ArrayNumDimsG6#FcjlF_u>Fcjl-%(c
onvertG6$Fcjl%)listlistG/F\[mFH>Fcjl-Fa[m6$Fcjl%%listG-%'CURVESG6#-FitFcoF$F$F$
>Fesf*6#F_ilF$6$%)operatorG%&arrowGF$-Fgbl6$Fas/Fj[mT#F$F$6$FailFi`l>F"FH@%1-%'
degreeG6$Fep7&F[sF\sFg`lF\alF#C%-F^o6$Q@%a:~Level~curve~is~a~constant.|+F$FepF_
sOF0C.>F?,&-%&roundG6#-%%sqrtG6#FapFHFHFH>FjuF?>%%facsG&-%(factorsG6#-F\v6$<$/F
g`lF]\l/F\alF_\lFep6#F_u>FG-%$mapG6$f*6#%$facGF$F`\mF$-&%&plotsG6#%-implicitplo
tG6)Fas/F[s;Fa[lFf[l/F\s;Fh[lF[\l/%%axesG%%noneG/%%viewG7$Fh_mFj_m/%%gridG7$Ff
\mT%/%&colorG%&blackGF$F$6&F]ilF?F^ilFjuF_^m>FG-F\_m6$FesFG>FG-F\_m6$f*F__mF$F`
\mF$-Fit6#-%'selectG6$f*6#%#ptGF$F`\mF$-FM6$FasFh[mF$F$F$7#-Fit6#-Fit6$FHFasF$F
$F$FG>F4F#?(F:FHFH-F6FPF0>F4,&F4FH-F66#&FGFezFH-Fho6%FasFbsF4>F4F#?(F:FHFHFabmF
0C$?(Fb`lFHFHFdbmF0C%>Fdv-%(sprintfG6%Q'%g~%g~F$&FG6%F:Fb`lFH&FG6%F:Fb`lF_u-Fho
6%FasQ#%sF$Fdv>F4,&F4FHFHFH@%0F:Fabm-Fho6$FasQ#,|+F$Ffu-F^o6%Q9%a:~%d~points~re
turned.|+F$FepF4>F"F#OF0F$6)F]\lF_\lF"F_^mF`_mFepFapF$F$
