M7R0
I(rounded%&falseG6",
I3Hardware_precision"#:F$,
I/user_precisionF&F$,
I-reduce_coefff*6$%"fG%"xG6&%"gG%#g1G%#g2G%"jGF$F$C&>8$-%(norpolyG6$9$9%>8%-%&n
umerG6#F4>8&-%&denomGF>@%/F;""!7#FE7#-%"$G6$*&-%&coeffG6%F;F98'"""F@!""/FO;FE-%
'degreeG6$F;F9F$F$F$F$,
I-write_numberf*6#%"nGF$F$F$@%F"-%'writefG6$Q$%g|+F$-%&evalfG6#F8-Fgn6$Q$%a|+F$
F8F$F$F$F$,
I-reduce_evalfF[oF$,
I+reduce_lltf*6$%"aG%"bGF$6$%)operatorG%&arrowGF$-%&evalbG6#1-F[o6#,&F8FPF9FQ,$
)"#5,$F'FQFQF$F$F$F$,
I*reduce_gtf*FcoF$FfoF$-Fjo6#1FapF]pF$F$F$F$,
I,reduce_gteqf*FcoF$FfoF$-Fjo6#1F`pF]pF$F$F$F$,
I+reduce_eeqf*FcoF$FfoF$-Fjo6#2-F[o6#-%$absGF^pFapF$F$F$F$,
I,reduce_nneqf*FcoF$FfoF$-Fjo6#1FapFcqF$F$F$F$,
I4optimizepolynomial1f*F*6'F.%"LGF1%"kG%"zGF$F$C(>F4F5@%4F">F4-%(convertG6$F4%)
rationalG>F4-F[oF>>F;-%%evalG6#7#-FI6$.-FM6%F4F9F@/F@;FE-%$maxG6$FE-FU6$F4F9@$3
Fer%.user_simplifyG>F;-%$mapG6$%1user_simplifycmdGF;>F;-Fct6$f*6#FarF$FfoF$@%-%
%typeG6$Fjn%(numericG@%1-Ffq6#FjnFapFEF8F8F$F$F$F;-F_s6#-%$addG6$*&&F;6#FOFP)F9
,&FOFPFQFPFP/FO;FP-%%nopsG6#F;F$6$F'F"F$F$,
I4optimizepolynomial2f*6%F+F,%"yG6&F.F1F_rFarF$F$C'>F4-%)norpoly2G6%F8F99&@%Fer
>F4Fgr>F4F\s>F@-F_s6#7#-FI6$.-FM6%F4F9F;/F;Fhs>F@-Fct6$f*FjtF$FfoF$-F\r6$F8T$F$
F$6$FgvF^wF@-F66$-F_s6#-Fgu6$*&&F@6#F`rFP)F9,&F`rFPFQFPFP/F`r;FP-Fav6#F@F9F$F$F
$F$,
I+first_termf*6$%#_fGF,6#F+F$F$C$>F4-F\rF7@%/F4FEFE*&-FM6%F4F9-%(ldegreeGF]tFP)
F9F`zFPF$F$F$F$,
I*lleadtermf*FeyFgyF$F$C$>F4Fjy@%F\zFE*&-FM6%F4F9F\tFP)F9F\tFPF$F$F$F$,
I'nltermf*Ffv6$F.%"hGF$F$C$>F4-F66$-FczF7F^w@%0F4FEC$>F;-Fcz6$F4F^w@%0F;FEF;F4C
$>F4-F66$-Fcz6$F8F^wF9@%Ff[lF4F8F$F$F$F$,
I%ddegf*6%FfyF,FgvFgyF$F$C$>F4-FdvF]w@%F\zFE-FU6$F4<$F9F^wF$F$F$F$,
I)low_ddegf*Ff\lFgyF$F$C$>F4Fi\l@%F\zFE-FazF\]lF$F$F$F$,
I&ntermf*6&FfyF,Fgv%"dG6%F+F1F.F$F$C&>F4Fi\l>F@FE?(F;FEFP9'%%trueG>F@,&F@FP*(-F
M6%FiwF^w,&F]^lFPF;FQFP)F9F;FP)F^wFd^lFPFPF@F$F$F$F$,
I)low_deg1f*FeyFgyF$F$C$>F4-F[o6$-F6F\oF9@%/F4$FEFEFEF`zF$F$F$F$,
I+optimizevff*FfvF$FfoF$7$-Fdv6%&F86#FPF9F^w-Fdv6%&F86#""#F9F^wF$F$F$F$,
I1quasihom_degree1f*6'FfyF,Fgv%"pG%"qG6%%#_xG%#_yGF+F$F$C%>F@Fi\l>F@-%%subsG6%/
F9)F4F]^l/F^w)F;9(F@-FU6$F@<$F4F;F$F$F$F$,
I0quasihom_degreef*6'%#vfGF,FgvF``lFa`lF$FfoF$-Fjs6$,&-F]`l6'Ff_lF9F^wF]^lF_alF
PF]^lFQ,&-F]`l6'Fj_lF9F^wF]^lF_alFPF_alFQF$F$F$F$,
I,change_polyf*Ffv6&F.F_[lF`rFdoF$F$C&>F4F[w>F;FE?(F$FPFPF$Ff[lC&>F@-F\[l6%F4F9
F^w>F4,&F4FPF@FQ>FO-F_s6$-F_s6$F@/F9FP/F^wFP@$2Fap-Ffq6#-F[oF[v>F;,&F;FPF@FPF;F
$F$F$F$,
I*sort_listf*6#%"sGF$FfoF$-%%sortG6$F8f*6$%&sle_aG%&sle_bGF$FfoF$-Fjo6#52Ff_l&F
9Fg_l3/Ff_lFidl2Fj_l&F9F[`lF$F$F$F$F$F$F$,
I+reduce_impf*FjtF$FfoF$-F[o6#-%*reduce_imGF\oF$F$F$F$,
I,reduce_conj%*conjugateGF$,
I*reduce_ref*FjtF$FfoF$,&F8#FPF\`l-FdelF\oFielF$F$F$F$,
I*reduce_imf*FjtF$FfoF$*&^##FQF\`lFP,&F8FPFjelFQFPF$F$F$F$,
I)openfilef*F$6&%#kkGF`r%#fhG%&fnameGF$F$C%>%0currentopenfileG<"?(F4FPFP9#F^^lC
$>FO-F_s6#&9"F>@%/FO%)terminalG>Fifl-%&unionG6$Fifl<#,$%)infinityGFQC$?(F;FPFP-
Fav6#%-openfilelistGF^^l@$/-%#opG6$FP&FahlFbvFO[@%1F;F_hl>Fifl-Fhgl6$Fifl<#-Feh
l6$F\`lFghlC%>F@-%&fopenG6%FO%&WRITEG%%TEXTG>Fifl-Fhgl6$Fifl<#F@>Fahl-Fhgl6$Fah
l<#7$FOF@@$/-Fav6#FiflFE>FiflFjglF$6$FiflFahlF$F$,
I*closefilef*6#%)filenameGF\yF$F$@%0F8FeglC$?(F4FPFPF_hlF^^l@$/-Fehl6$FP&FahlF>
F8Fhhl@$1F4F_hlC%-%'fcloseG6#-Fehl6$F\`lFc[m@$-%'memberG6$Fj[mFiflC$>Fifl-%&min
usG6$Fifl<#Fj[m@$Fbjl>FiflFjgl>Fahl-Fc\m6$Fahl<#Fc[m@$3-F^\m6$F[hlFifl2FPFcjl>F
ifl-Fc\mFiglF$FfjlF$F$,
I'writeff*6#%-formatstringG6#F1F$F$?(F4FPFPFcjlF^^l@%/&FiflF>F[hl-%'printfG6$F8
&Fbgl6#;F\`lF\gl-%(fprintfG6%F[^mF8F_^mF$F$F$F$,
I0currentopenfileFjglF$,
I-openfilelistFjflF$,
I.closeallfilesf*FijlF$F$F$?(F$FPFPF$0F_hlFE-Fgjl6#-Fehl6$FP&FahlFg_lF$F$F$F$,
I(norpolyf*6$%"PGF,F$FfoF$@%F`t-%'expandG6#-Fet6#-%'normalGF\o-Ff_mFi_mF$F$F$F$,
I)norpoly2f*6%Fc_mF,FgvF$FfoF$@%F`tFe_mF\`mF$F$F$F$,
I)norpoly3f*6&Fc_mF,FgvFarF$FfoF$@%F`tFe_mF\`mF$F$F$F$
