M7R0
I(rounded%&falseG6",
I3Hardware_precision"#:F$,
I/user_precisionF&F$,
I-reduce_coefff*6$%"fG%"xG6&%"gG%#g1G%#g2G%"jGF$F$C&>8$-%(norpolyG6$9$9%>8%-%&n
umerG6#F4>8&-%&denomGF>@%/F;""!7#FE7#-%"$G6$*&-%&coeffG6%F;F98'"""F@!""/FO;FE-%
'degreeG6$F;F9F$F$F$F$,
I-write_numberf*6#%"nGF$F$F$@%F"-%'writefG6$Q$%g|+F$-%&evalfG6#F8-Fgn6$Q$%a|+F$
F8F$F$F$F$,
I-reduce_evalfF[oF$,
I+reduce_lltf*6$%"aG%"bGF$6$%)operatorG%&arrowGF$-%&evalbG6#1-F[o6#,&F8FPF9FQ,$
)"#5,$F'FQFQF$F$F$F$,
I*reduce_gtf*FcoF$FfoF$-Fjo6#1FapF]pF$F$F$F$,
I,reduce_gteqf*FcoF$FfoF$-Fjo6#1F`pF]pF$F$F$F$,
I+reduce_eeqf*FcoF$FfoF$-Fjo6#2-F[o6#-%$absGF^pFapF$F$F$F$,
I,reduce_nneqf*FcoF$FfoF$-Fjo6#1FapFcqF$F$F$F$,
I4optimizepolynomial1f*F*6'F.%"LGF1%"kG%"zGF$F$C(>F4F5@%4F">F4-%(convertG6$F4%)
rationalG>F4-F[oF>>F;-%%evalG6#7#-FI6$.-FM6%F4F9F@/F@;FE-%$maxG6$FE-FU6$F4F9@$3
Fer%.user_simplifyG>F;-%$mapG6$%1user_simplifycmdGF;>F;-Fct6$f*6#FarF$FfoF$@%-%
%typeG6$Fjn%(numericG@%1-Ffq6#FjnFapFEF8F8F$F$F$F;-F_s6#-%$addG6$*&&F;6#FOFP)F9
,&FOFPFQFPFP/FO;FP-%%nopsG6#F;F$6$F'F"F$F$,
I4optimizepolynomial2f*6%F+F,%"yG6&F.F1F_rFarF$F$C'>F4-%)norpoly2G6%F8F99&@%Fer
>F4Fgr>F4F\s>F@-F_s6#7#-FI6$.-FM6%F4F9F;/F;Fhs>F@-Fct6$f*FjtF$FfoF$-F\r6$F8T$F$
F$6$FgvF^wF@-F66$-F_s6#-Fgu6$*&&F@6#F`rFP)F9,&F`rFPFQFPFP/F`r;FP-Fav6#F@F9F$Fcv
F$F$,
I+first_termf*6$%#_fGF,6#F+F$F$C$>F4-F\rF7@%/F4FEFE*&-FM6%F4F9-%(ldegreeGF]tFP)
F9F`zFPF$F$F$F$,
I*lleadtermf*FeyFgyF$F$C$>F4Fjy@%F\zFE*&-FM6%F4F9F\tFP)F9F\tFPF$F$F$F$,
I'nltermf*Ffv6$F.%"hGF$F$C$>F4-F66$-FczF7F^w@%0F4FEC$>F;-Fcz6$F4F^w@%0F;FEF;F4C
$>F4-F66$-Fcz6$F8F^wF9@%Ff[lF4F8F$F$F$F$,
I%ddegf*6%FfyF,FgvFgyF$F$C$>F4-FdvF]w@%F\zFE-FU6$F4<$F9F^wF$6#F"F$F$,
I)low_ddegf*Ff\lFgyF$F$C$>F4Fi\l@%F\zFE-FazF\]lF$F$F$F$,
I&ntermf*6&FfyF,Fgv%"dG6%F+F1F.F$F$C&>F4Fi\l>F@FE?(F;FEFP9'%%trueG>F@,&F@FP*(-F
M6%FiwF^w,&F^^lFPF;FQFP)F9F;FP)F^wFe^lFPFPF@F$F$F$F$,
I)low_deg1f*FeyFgyF$F$C$>F4-F[o6$-F6F\oF9@%/F4$FEFEFEF`zF$F$F$F$,
I+optimizevff*FfvF$FfoF$7$-Fdv6%&F86#FPF9F^w-Fdv6%&F86#""#F9F^wF$F$F$F$,
I1quasihom_degree1f*6'FfyF,Fgv%"pG%"qG6%%#_xG%#_yGF+F$F$C%>F@Fi\l>F@-%%subsG6%/
F9)F4F^^l/F^w)F;9(F@-FU6$F@<$F4F;F$F$F$F$,
I0quasihom_degreef*6'%#vfGF,FgvFa`lFb`lF$FfoF$-Fjs6$,&-F^`l6'Fg_lF9F^wF^^lF`alF
PF^^lFQ,&-F^`l6'F[`lF9F^wF^^lF`alFPF`alFQF$F$F$F$,
I,change_polyf*Ffv6&F.F_[lF`rFdoF$F$C&>F4F[w>F;FE?(F$FPFPF$Ff[lC&>F@-F\[l6%F4F9
F^w>F4,&F4FPF@FQ>FO-F_s6$-F_s6$F@/F9FP/F^wFP@$2Fap-Ffq6#-F[oF[v>F;,&F;FPF@FPF;F
$F$F$F$,
I*sort_listf*6#%"sGF$FfoF$-%%sortG6$F8f*6$%&sle_aG%&sle_bGF$FfoF$-Fjo6#52Fg_l&F
9Fh_l3/Fg_lFjdl2F[`l&F9F\`lF$F$F$F$F$F$F$,
I+reduce_impf*FjtF$FfoF$-F[o6#-%*reduce_imGF\oF$F$F$F$,
I,reduce_conj%*conjugateGF$,
I*reduce_ref*FjtF$FfoF$,&F8#FPF]`l-FeelF\oFjelF$F$F$F$,
I*reduce_imf*FjtF$FfoF$*&^##FQF]`lFP,&F8FPF[flFQFPF$F$F$F$,
I)openfilef*F$6&%#kkGF`r%#fhG%&fnameGF$F$C%>%0currentopenfileG<"?(F4FPFP9#F_^lC
$>FO-F_s6#&9"F>@%/FO%)terminalG>Fjfl-%&unionG6$Fjfl<#,$%)infinityGFQC$?(F;FPFP-
Fav6#%-openfilelistGF_^l@$/-%#opG6$FP&FbhlFbvFO[@%1F;F`hl>Fjfl-Figl6$Fjfl<#-Ffh
l6$F]`lFhhlC%>F@-%&fopenG6%FO%&WRITEG%%TEXTG>Fjfl-Figl6$Fjfl<#F@>Fbhl-Figl6$Fbh
l<#7$FOF@@$/-Fav6#FjflFE>FjflF[hlF$6$FjflFbhlF$F$,
I*closefilef*6#%)filenameGF\yF$F$@%0F8FfglC$?(F4FPFPF`hlF_^l@$/-Ffhl6$FP&FbhlF>
F8Fihl@$1F4F`hlC%-%'fcloseG6#-Ffhl6$F]`lFd[m@$-%'memberG6$F[\mFjflC$>Fjfl-%&min
usG6$Fjfl<#F[\m@$Fcjl>FjflF[hl>Fbhl-Fd\m6$Fbhl<#Fd[m@$3-F_\m6$F\hlFjfl2FPFdjl>F
jfl-Fd\mFjglF$FgjlF$F$,
I'writeff*6#%-formatstringG6#F1F$F$?(F4FPFPFdjlF_^l@%/&FjflF>F\hl-%'printfG6$F8
&Fcgl6#;F]`lF]gl-%(fprintfG6%F\^mF8F`^mF$F$F$F$,
I0currentopenfileF[hlF$,
I-openfilelistF[glF$,
I.closeallfilesf*FjjlF$F$F$?(F$FPFPF$0F`hlFE-Fhjl6#-Ffhl6$FP&FbhlFh_lF$F$F$F$,
I(norpolyf*6$%"PGF,F$FfoF$@%F`t-%'expandG6#-Fet6#-%'normalGF\o-Fg_mFj_mF$F$F$F$,
I)norpoly2f*6%Fd_mF,FgvF$FfoF$@%F`tFf_mF]`mF$F$F$F$,
I)norpoly3f*6&Fd_mF,FgvFarF$FfoF$@%F`tFf_mF]`mF$F$F$F$
