M7R0
I(rounded%&falseG6",
I3Hardware_precision"#:F$,
I/user_precisionF&F$,
I-reduce_coefff*6$%"fG%"xG6&%"gG%#g1G%#g2G%"jGF$F$C&>8$-%(norpolyG6$9$9%>8%-%&n
umerG6#F4>8&-%&denomGF>@%/F;""!7#FE7#-%"$G6$*&-%&coeffG6%F;F98'"""F@!""/FO;FE-%
'degreeG6$F;F9F$F$F$F$,
I-write_numberf*6#%"nGF$F$F$@%F"-%'writefG6$Q$%g|+F$-%&evalfG6#F8-Fgn6$Q$%a|+F$
F8F$F$F$F$,
I-reduce_evalfF[oF$,
I+reduce_lltf*6$%"aG%"bGF$6$%)operatorG%&arrowGF$-%&evalbG6#1-F[o6#,&F8FPF9FQ,$
)"#5,$F'FQFQF$F$F$F$,
I*reduce_gtf*FcoF$FfoF$-Fjo6#1FapF]pF$F$F$F$,
I,reduce_gteqf*FcoF$FfoF$-Fjo6#1F`pF]pF$F$F$F$,
I+reduce_eeqf*FcoF$FfoF$-Fjo6#2-F[o6#-%$absGF^pFapF$F$F$F$,
I,reduce_nneqf*FcoF$FfoF$-Fjo6#1FapFcqF$F$F$F$,
I4optimizepolynomial1f*F*6'F.%"LGF1%"kG%"zGF$F$C(>F4F5@%4F">F4-%(convertG6$F4%)
rationalG>F4-F[oF>>F;-%%evalG6#7#-FI6$.-FM6%F4F9F@/F@;FE-%$maxG6$FE-FU6$F4F9@$3
Fer%.user_simplifyG>F;-%$mapG6$%1user_simplifycmdGF;>F;-Fct6$f*6#FarF$FfoF$@%-%
%typeG6$Fjn%(numericG@%1-Ffq6#FjnFapFEF8F8F$F$F$F;-F_s6#-%$addG6$*&&F;6#FOFP)F9
,&FOFPFQFPFP/FO;FP-%%nopsG6#F;F$6$F'F"F$F$,
I4optimizepolynomial2f*6%F+F,%"yG6&F.F1F_rFarF$F$C*>F4-%)norpoly2G6%F8F99&-%)op
enfileG6#%)terminalG-Fgn6#Q(up~hereF$-%*closefileGFaw@%Fer>F4Fgr>F4F\s>F@-F_s6#
7#-FI6$.-FM6%F4F9F;/F;Fhs>F@-Fct6$f*FjtF$FfoF$-F\r6$F8T$F$F$6$FgvF^wF@-F66$-F_s
6#-Fgu6$*&&F@6#F`rFP)F9,&F`rFPFQFPFP/F`r;FP-Fav6#F@F9F$6#F"F$F$,
I+first_termf*6$%#_fGF,6#F+F$F$C$>F4-F\rF7@%/F4FEFE*&-FM6%F4F9-%(ldegreeGF]tFP)
F9FjzFPF$F$F$F$,
I*lleadtermf*F_zFazF$F$C$>F4Fdz@%FfzFE*&-FM6%F4F9F\tFP)F9F\tFPF$F$F$F$,
I'nltermf*Ffv6$F.%"hGF$F$C$>F4-F66$-F][lF7F^w@%0F4FEC$>F;-F][l6$F4F^w@%0F;FEF;F
4C$>F4-F66$-F][l6$F8F^wF9@%F`\lF4F8F$F$F$F$,
I%ddegf*6%F`zF,FgvFazF$F$C$>F4-FdvF]w@%FfzFE-FU6$F4<$F9F^wF$F\zF$F$,
I)low_ddegf*F`]lFazF$F$C$>F4Fc]l@%FfzFE-F[[lFf]lF$F$F$F$,
I&ntermf*6&F`zF,Fgv%"dG6%F+F1F.F$F$C&>F4Fc]l>F@FE?(F;FEFP9'%%trueG>F@,&F@FP*(-F
M6%FbxF^w,&Fg^lFPF;FQFP)F9F;FP)F^wF^_lFPFPF@F$F$F$F$,
I)low_deg1f*F_zFazF$F$C$>F4-F[o6$-F6F\oF9@%/F4$FEFEFEFjzF$F$F$F$,
I+optimizevff*FfvF$FfoF$7$-Fdv6%&F86#FPF9F^w-Fdv6%&F86#""#F9F^wF$F$F$F$,
I1quasihom_degree1f*6'F`zF,Fgv%"pG%"qG6%%#_xG%#_yGF+F$F$C%>F@Fc]l>F@-%%subsG6%/
F9)F4Fg^l/F^w)F;9(F@-FU6$F@<$F4F;F$F$F$F$,
I0quasihom_degreef*6'%#vfGF,FgvFj`lF[alF$FfoF$-Fjs6$,&-Fg`l6'F``lF9F^wFg^lFialF
PFg^lFQ,&-Fg`l6'Fd`lF9F^wFg^lFialFPFialFQF$F$F$F$,
I,change_polyf*Ffv6&F.Fi[lF`rFdoF$F$C&>F4F[w>F;FE?(F$FPFPF$F`\lC&>F@-Ff[l6%F4F9
F^w>F4,&F4FPF@FQ>FO-F_s6$-F_s6$F@/F9FP/F^wFP@$2Fap-Ffq6#-F[oF[v>F;,&F;FPF@FPF;F
$F$F$F$,
I*sort_listf*6#%"sGF$FfoF$-%%sortG6$F8f*6$%&sle_aG%&sle_bGF$FfoF$-Fjo6#52F``l&F
9Fa`l3/F``lFcel2Fd`l&F9Fe`lF$F$F$F$F$F$F$,
I+reduce_impf*FjtF$FfoF$-F[o6#-%*reduce_imGF\oF$F$F$F$,
I,reduce_conj%*conjugateGF$,
I*reduce_ref*FjtF$FfoF$,&F8#FPFf`l-F^flF\oFcflF$F$F$F$,
I*reduce_imf*FjtF$FfoF$*&^##FQFf`lFP,&F8FPFdflFQFPF$F$F$F$,
I)openfilef*F$6&%#kkGF`r%#fhG%&fnameGF$F$C%>%0currentopenfileG<"?(F4FPFP9#Fh^lC
$>FO-F_s6#&9"F>@%/FOFbw>Fcgl-%&unionG6$Fcgl<#,$%)infinityGFQC$?(F;FPFP-Fav6#%-o
penfilelistGFh^l@$/-%#opG6$FP&FjhlFbvFO[@%1F;Fhhl>Fcgl-Fahl6$Fcgl<#-F^il6$Ff`lF
`ilC%>F@-%&fopenG6%FO%&WRITEG%%TEXTG>Fcgl-Fahl6$Fcgl<#F@>Fjhl-Fahl6$Fjhl<#7$FOF
@@$/-Fav6#FcglFE>FcglFchlF$6$FcglFjhlF$F$,
I*closefilef*6#%)filenameGFeyF$F$@%0F8FbwC$?(F4FPFPFhhlFh^l@$/-F^il6$FP&FjhlF>F
8Fail@$1F4FhhlC%-%'fcloseG6#-F^il6$Ff`lF\\m@$-%'memberG6$Fc\mFcglC$>Fcgl-%&minu
sG6$Fcgl<#Fc\m@$F[[m>FcglFchl>Fjhl-F\]m6$Fjhl<#F\\m@$3-Fg\m6$FdhlFcgl2FPF\[m>Fc
gl-F\]mFbhlF$F_[mF$F$,
I'writeff*6#%-formatstringG6#F1F$F$?(F4FPFPF\[mFh^l@%/&FcglF>Fdhl-%'printfG6$F8
&F\hl6#;Ff`lFfgl-%(fprintfG6%Fd^mF8Fh^mF$F$F$F$,
I0currentopenfileFchlF$,
I-openfilelistFdglF$,
I.closeallfilesf*Fb[mF$F$F$?(F$FPFPF$0FhhlFE-Fgw6#-F^il6$FP&FjhlFa`lF$F$F$F$,
I(norpolyf*6$%"PGF,F$FfoF$@%F`t-%'expandG6#-Fet6#-%'normalGF\o-F_`mFb`mF$F$F$F$,
I)norpoly2f*6%F\`mF,FgvF$FfoF$@%F`tF^`mFe`mF$F$F$F$,
I)norpoly3f*6&F\`mF,FgvFarF$FfoF$@%F`tF^`mFe`mF$F$F$F$
