M7R0
I)jacobianf*6%%"fG%$xeqG%$yeqG6#%%exprG6"F*-%%evalG6#-%$mapG6$f*F(F*6$%)operato
rG%&arrowGF*-%%subsG6$<$T&T$9$F*F*6&F&9%F'9&7&-%%diffG6$&F;6#"""-%$lhsG6#F=-FA6
$FC-FG6#F>-FA6$&F;6#""#FF-FA6$FOFKF*F*F*F*,
I,eigenvectorf*6&%"aG%"bG%"cG%"dG6$%#_cG%"nGF*F*C%@%-%,reduce_nneqG6$F=""!>8$7$
FE,$*&F;FEF=!""Fco@%-F[o6$F;F]o>F_o7$F]oFE@%-F[o6$9'F]o>F_o7$FE,$*&F>FEF\pFcoFc
o>F_oFho@$%(roundedGC$>8%-%%sqrtG6#z'6$&F_oFD&F_oFP[[[[[_[[[[sFE][[[[[[[[[sFE>F
_o-%&evalfG6#7$*&F\qFEFfpFco*&F]qFEFfpFcoF_oF*F*F*F*,
I,translationf*6'%"vG%"xG%"yG%#x0G%#y0G6$%#f1G%#f2GF*F*C&>F_o-F66$<$/F=,&F=FEF
\pFE/F>,&F>FE9(FEFC>Ffp-F66$FdrFO@$FcpC$>F_o-%,change_polyG6%F_oF=F>>Ffp-Fas6%F
fpF=F>7$F_oFfpF*F*F*F*,
I/transformationf*6'FhqFWFXFYFZ6-F^rF_r%#_xG%#_yG%#_aG%#_bGFfn%#_dG%"MG%#g1G%#g
2GF*F*C,>F_o-F66$<$/Fiq,&*&F=FE8&FEFE*&F>FE8'FEFE/Fjq,&*&F\pFEF[uFEFE*&FirFEF]u
FEFEFC>Ffp-F66$FgtFO>8,,&*&F=FEFirFEFE*&F>FEF\pFEFco>8(*&FirFEFfuFco>8),$*&F>FE
FfuFcoFco>8*,$*&F\pFEFfuFcoFco>8+*&F=FEFfuFco>8--F66%/F[uFiq/F]uFjq,&*&F[vFEF_o
FEFE*&F^vFEFfpFEFE>8.-F66%F\wF]w,&*&FbvFEF_oFEFE*&FfvFEFfpFEFE-%+optimizevfG6%7
$FivFbwFiqFjqF*F*F*F*,
I.normalizationf*6#Fhq6%%#L1G%#L2G%"mGF*F*C)>F_o-%.coeff_degree2G6%-%4optimizep
olynomial2G6%FCFiqFjqFiqFjq>Ffp-Ffx6%-Fix6%FOFiqFjqFiqFjq>F_o-F/6$f*F(F*F2F*-F`
q6#-%$absG6#&F;6#""$F*F*F*F_o>Ffp-F/6$f*F(F*F2F*FdyF*F*F*Ffp>F[u-%$maxG6$-%#opG
6#F_o-Fez6#Ffp@$4Fcp>F[u-%(convertG6$F[u%)rationalG-Fiw6%7$,$*&FCFEF[uFco"%+5,$
*&FOFEF[uFcoFe[lFiqFjqF*F*F*F*,
I)manifoldf*6%%"gGFgn%'stableG6.%$vf1G%$vf2G%#h1G%#h2G%"kGF`xFax%$sepGF\t%'lamb
daG%#okG%#n1GF*F*C*@%FcpC$>F_o-F`q6#FC>Ffp-F`q6#FOC$>F_oFC>FfpFO>F^v-%&coeffG6%
-%(collectG6$-F66$/FjqF]oFCFiqFiqFE>Fbv-Fe]l6%-Fh]l6$-F66$/FiqF]oFOFjqFjqFE>Ffv
F]o?(F[vFQFEF=%%trueGC)>Fiv*&-Fe]l6%-Fh]l6$-F66$F\^lFfpFiqFiqF[vFE,&*&F^vFEF[vF
EFEFbvFcoFco@$3Fjz%.user_simplifyG>Fiv-%1user_simplifycmdG6#Fiv>F[u-%'expandG6#
-F66$/Fjq,&FfuFE*&FivFE)FiqF[vFEFEF_o>F]u-F\`l6#,&-F66$F``lFfpFE**FivFEF[vFE)Fi
q,&F[vFEFcoFEFEF[uFEFco>F_o-F66$/FfuFjqF[u>Ffp-F66$F`alF]u>Ffv,&FfvFEFb`lFE@$%)
test_sepGC&-%'writefG6#Q>Testing~separatrix~for~x~>~0|+F*>Fbw-%1separatrice_tes
tG6'FfvF;F=F>FE>8/F=?(F*FEFEF*34Fbw2Fbbl%*max_levelGC%>Fbbl,&FbblFEFEFE@%1%.num
eric_levelGFbblC)@$/FbblF]clC$>F_o-F`qFfz>Ffp-F`qFhz>Fiv-F`q6#*&-Fe]l6%F]_lFiqF
bblFE,&*&F^vFEFbblFEFEFbvFcoFco>F[u-F\`l6#-F66$/Fjq,&FfuFE*&FivFE)FiqFbblFEFEF_
o>F]u-F\`l6#,&-F66$FcdlFfpFE**FivFEFbblFE)Fiq,&FbblFEFcoFEFEF[uFEFco>F_oF^al>Ff
pFbal>Ffv,&FfvFEFedlFEC)>FivFicl@$Fd_l>FivFg_l>F[uF_dl>F]uFhdl>F_oF^al>FfpFbal>
FfvFcel>Fbw-F_bl6'FfvF;FbblF>FE@$FgalC%-Fjal6#Q>Testing~separatrix~for~x~<~0|+F
*>Fbw-F_bl6'FfvF;FbblF>Fco?(F*FEFEF*FdblC%>FbblFjbl@%F\clC)@$F`clC$>F_oFccl>Ffp
Fecl>FivFgcl>F[uF_dl>F]uFhdl>F_oF^al>FfpFbal>FfvFcelC)>FivFicl@$Fd_l>FivFg_l>F[
uF_dl>F]uFhdl>F_oF^al>FfpFbal>FfvFcel>FbwF^fl-F66$/Fiq%"tGFfvF*6#FgalF*F*,
I0center_manifoldf*Fj[l63F^\lF_\lF`\lFa\lFb\lFaxFc\lF\tFd\lFe\lFf\l%#dxGFXFbx%#
amG%&stypeG%(stable2GF*F*C/@%FcpC$>F_oF[]l>FfpF^]lC$>F_oFC>FfpFO>F^vF^^l>FbvF]o
>FbwF=?(F[vFQFEFbwFg^lC+>Ffu,$*&F[_lFEF^vFcoFco@$Fd_l>Ffu-Fh_l6#Ffu>F[u-F\`l6#-
F66$/Fjq,&FfvFE*&FfuFEFc`lFEFEF_o>F]u-F\`l6#,&-F66$FfjlFfpFE**FfuFEF[vFEF[alFEF
[uFEFco>F_o-F66$/FfvFjqF[u>Ffp-F66$Fc[mF]u>Fbv,&FbvFEFhjlFE>Fbbl-%4optimizepoly
nomial1G6$-F66$F\^lF_oFiq@$/FbblF]o>Fbw,&FbwFEFEFE>80-%+first_termG6$FbblFiq>81
-%'degreeG6$Fd\mFiq>82-F`q6#-F66$/FiqFEFd\m@%-%%typeG6$Fi\m%%evenG@%1F]oF^]m@%/
F>F]o>83FE>F^^mFQ@%F\^m>F^^mF[z>F^^m""%@%Fj]m@%F\^m>F^^m""&>F^^m""'@%F\^m>F^^m"
"(>F^^m"")@$FgalC$@%-%'memberG6$F^^m<$FQFi^m>84F]o>Fg_mFE@$-Fc_m6$F^^m<&FQF[zFi
^mF\_mC%-Fjal6#QETesting~center~separatrix~for~x~>~0|+F*>Fiv-F_bl6'FbvF;FbwFg_m
FE?(F*FEFEF*34Fiv2FbwFgblC%>FbwFb\m@%1F]clFbwC)@$/FbwF]clC$>F_oFccl>FfpFecl>Ffu
-F`q6#,$*&-Fe]l6%-Fh]l6$-F66$/FjqFbvFfpFiqFiqFbwFEF^vFcoFco>F[u-F\`l6#-F66$/Fjq
,&FfvFE*&FfuFE)FiqFbwFEFEF_o>F]u-F\`l6#,&-F66$FcbmFfpFE**FfuFEFbwFE)Fiq,&FbwFEF
coFEFEF[uFEFco>F_oFa[m>FfpFe[m>Fbv,&FbvFEFebmFEC)>FfuFeam@$Fd_l>FfuF_jl>F[uF_bm
>F]uFhbm>F_oFa[m>FfpFe[m>FbvFccm>FivFb`m@$FgalC$@%-Fc_m6$F^^m<$Fc^mFi^m>Fg_mF]o
>Fg_mFE@$-Fc_m6$F^^m<&FEFc^mFi^mF\_mC%-Fjal6#QETesting~center~separatrix~for~x~
<~0|+F*>Fiv-F_bl6'FbvF;FbwFg_mFco?(F*FEFEF*Fe`mC%>FbwFb\m@%F[amC)@$F^amC$>F_oFc
cl>FfpFecl>FfuFcam>F[uF_bm>F]uFhbm>F_oFa[m>FfpFe[m>FbvFccmC)>FfuFeam@$Fd_l>FfuF
_jl>F[uF_bm>F]uFhbm>F_oFa[m>FfpFe[m>FbvFccm>FivFb`m>Fbbl-F[\m6$-F66$F]bmF_oFiq7
%-F66$FchlFbvFbblF^^mF*FehlF*F*,
I'saddlef*6,F%F[rF\rFWFXFYFZ%$rhoG%&sigmaG%&chartG6/%(lambda1G%(lambda2G%-lambd
a_ratioG%1lambda_ratio_numG%1lambda_ratio_denG%#ffGF[\lFat%#v1G%#v2GF\\l%%sep1G
%%sep2GF*F*CA-Fjal6%Q<(%a,%a)~is~a~saddle~point.|+F*-F`qFH-F`qFL-%)openfileG6#%
,result_fileGFdhm-Fjhm6#%)terminalG>F_o,&9+#FEFQ-Fhp6#9,#FcoFQ>Ffp,&FbimFcimFdi
mFcim@%2-FgyFhz-FgyFfz>F[u*&F_oFEFfpFco>F[u*&FfpFEF_oFco@%FcpC)>F[uF\[l>F]u-%&n
umerG6#F[u>F[v-%&denomGFhjm-Fjal6%QXThe~ratio~between~eigenvalues~is~%a:%a~(app
roximation)|+F*F[vF]uFihmF\[nF]imC(>F]uFfjm>F[vFjjm-Fjal6%QHThe~ratio~between~e
igenvalues~is~%a:%a|+F*F[vF]uFihmFb[nF]im>Ffu-FT6&,&F\pFEF_oFcoFir9),&9*FEF_oFc
o>Fiv-FT6&,&F\pFEFfpFcoFirFi[n,&F[\nFEFfpFco@$%)save_allGC&Fihm-Fjal6%QB~The~ei
genvalues~are:~|fr~%a,~%a~|hr|+F*F_oFfp-Fjal6%QC~The~eigenvectors~are:~|fr~%a,~
%a~|hr|+F*FfuFivF]im@$Fb\n-Fjhm6$F_imF\im@%50F=F]o0F>F]oC%>F^v-Feq6'F;FiqFjqF=F
>-Fjal6#QIMoving~this~saddle~point~to~the~origin.|+F*-Fjal6$Q<The~new~vector~fi
eld~is~%a|+F*F^v>F^vF;>Ffv-Fgs6'F^v&FfuFD&FivFD&FfuFP&FivFP-Fjal6#Q\oTransform~
this~vector~field~so~that~the~linear~part~is~diagonal.|+F*-Fjal6$Fj]nFfv>Fbv-F
\x6#Ffv-Fjal6#Q;Make~a~1000-normalization|+F*-Fjal6$QDso~that~the~new~vector~fi
eld~is~%a|+F*Fbv-Fjal6#QIWe~calculate~the~invariant~separatrices|+F*F]im@%2Fccl
F]o>FbwFE>FbwF]o>Fbbl-Fh[l6%Fbv%-taylor_levelGFbw@%2FeclF]o>FbwFE>FbwF]o>Fd\m-F
h[l6%-Fgs6'FbvF]oFEFEF]oF[`nFbw@%-%*reduce_gtG6$F_oF]oC%-Fjal6$Q?The~stable~sep
aratrice~is~%a.|+F*7$Fd\mFdhl-Fjal6$QAThe~unstable~separatrice~is~%a.|+F*7$Fdhl
Fbbl@$Fb\nC&FihmFj`nF^anF]imC%-Fjal6$F\anFaan-Fjal6$F`anF]an@$Fb\nC&FihmFeanFga
nF]im-Fjal6#QZ########################################################|+F*FihmF
[bnF]im-%-write_saddleG6,F=F>F_^nF`^nFa^nFb^nFbv7$FbblFd\m7$-%%signG6#Fccl-Fdbn
6#Fecl9-F*F*F*F*,
I-strong_focusf*6'FfgmFegmF[rF\rFggm6%FigmFjgm%"LGF*F*C*>F_o,&F=Fcim-Fhp6#F;Fgi
m>Ffp,&F=FcimFacnFcim@%-Fg`nF\oC'-Fjal6%QE(%a,%a)~is~a~strong~unstable~focus.|+
F*Fhhm-F`q6#F\pFihmFhcnF]im>F[uFEC'-Fjal6%QC(%a,%a)~is~a~strong~stable~focus.|+
F*FhhmF[dnFihmF_dnF]im>F[uFcoF[bnFihmF[bnF]im-%3write_strong_focusG6&F>F\pF[uFi
rF*F*F*F*,
I%nodef*6(F%FfgmFegmF[rF\rFggm6(F]cnFigmFjgmF[hmF\hmF]hmF*F*C,@%-%+reduce_lltG6
$F>F]oC'-Fjal6%Q;(%a,%a)~is~a~stable~node.|+F*F[dn-F`q6#FirFihmF`enF]im>F_oFcoC
'-Fjal6%Q>(%a,%a)~is~an~unstable~node.|+F*F[dnFcenFihmFgenF]im>F_oFE>Ffp,&F>Fci
m-FhpFHFgim>F[u,&F>FcimF]fnFcim@%2-FgyFhjmF\jm>F]u*&FfpFEF[uFco>F]u*&F[uFEFfpFc
o@%FcpC)>F]u-F][l6$F]uF_[l>F[v-Fgjm6#F]u>F^v-F[[nF^gn-Fjal6%F^[nF^vF[vFihmFagnF
]imC(>F[vF]gn>F^vF`gn-Fjal6%Fd[nF^vF[vFihmFfgnF]imF[bnFihmF[bnF]im-%+write_node
G6&F\pFirF_oFi[nF*F*F*F*,
I+degeneratef*6&F%F[rF\rFggm6#%+trajectorsGF*F*C--Fjal6%QD(%a,%a)~is~a~non-elem
entary~point.|+F*FghmFhhm-Fjal6#Q@Blowing~up~the~vector~field...|+F*FihmFahnF]i
m>F_o-%+blowing_upG6&F;F=F>Fg^lF[bnFihmF[bnF]im-%1write_degenerateG6&F=F>F_oF\p
F*F*F*F*,
I0semi_elementaryf*6+F%F[rF\rFWFXFYFZFjgmFggm6,F_hmF`hmF^hmF[\lFat%+center_sepG
FahmFbhmF[ilF\\lF*F*C=>F_o-FT6&F\pFirFi[nF[\n>Ffp-FT6&,&F\pFEFbimFcoFirFi[n,&F[
\nFEFbimFco>F[uFc]n>F[v-Fgs6'F[uF\q&FfpFDF]q&FfpFP>F]u-F\x6#F[v-Fjal6%Qhn(%a,%a
)~is~semi-hyperbolic.|+Moving~this~point~to~the~origin.|+F*FghmFhhm-Fjal6$Fj]nF
[uFc^n-Fjal6$Fj]nF[vF[_n-Fjal6$F`_nF]uFa_nFihm-Fjal6%Q=(%a,%a)~is~semi-hyperbol
ic.|+F*FghmFhhm@$Fb\nC)-Fjal6#QBMoving~this~point~to~the~origin.|+F*FhjnFc^nFjj
nF[_nF\[oFa_nF]im@%-F]en6$FbimF]o>FivFE>FivF]o>F^v-Ffhl6%F]uF[`nFiv>Fbv-F66$Fch
l&F^vFD>Ffv-F66$Fchl-Fh[l6%-Fgs6'F]uF]oFEFEF]oF[`nFiv>Ffu&F^vFjy@%-Fc_m6$Ffu<$F
EF[zC)-Fjal6#Q8We~have~a~saddle-node.|+F*-Fjal6$Q7center~separatrice~%a|+F*7$Fd
hlFbv-Fjal6$Q9unstable~separatrice~%a|+F*7$FfvFdhlFihmF`]o@$Fb\nC$Fc]oFg]oF]im@
%-Fc_m6$Ffu<$FQFc^mC)F`]oFc]o-Fjal6$Q7stable~separatrice~%a|+F*Fj]oFihmF`]o@$Fb
\nC$Fc]oFb^oF]im@%/FfuFi^mC)-Fjal6#Q3We~have~a~saddle.|+F*-Fjal6$Q@unstable~cen
ter~separatrice~%a|+F*Ff]oFb^oFihmFj^o@$Fb\nC$F]_oFb^oF]im@%/FfuF\_mC)Fj^o-Fjal
6$Q>stable~center~separatrice~%a|+F*Ff]oFg]oFihmFj^o@$Fb\nC$Fe_oFg]oF]im@%/FfuF
g^mC)-Fjal6#Q;We~have~an~unstable~node.|+F*Fc]oFg]oFihmF]`o@$Fb\nC$Fc]oFb^oF]im
C)-Fjal6#Q8We~have~a~stable~node.|+F*Fc]oFb^oFihmFc`o@$Fb\nC$Fc]oFb^oF]imF[bnFi
hmF[bnF]im-%6write_semi_elementaryG6,F=F>F\qF`jnF]qFajnF]u7$FfuFE7$FbvFfvFfimF*
F*F*F*,
I*sing_typef*F]hn6&%$jacG%&deltaGFegmFfgmF*F*C,>F_o-F"6%F;/FiqF=/FjqF>@$Fd_l>F_
o-F/6$Fh_lF_o>Ffpz'6&F\qF]q&F_oFjy&F_o6#Fc^m\[[[[[[[[\[[mFE[[[\[[\[[[[[mFco@$Fd
_l>Ffp-Fh_lFhz>F[u,&F\qFEF`boFE@$Fd_l>F[u-Fh_lFhjm>F]u,&*$F[uFQFEFfp!"%@$Fd_l>F
]u-Fh_lF^gn@$Fb\nC)Fihm-Fjal6%Q>(%a,%a)~is~a~singular~point.|+F*F=F>-Fjal6'QGJa
cobian~=~[~[~%a,~%a~],~[~%a,~%a~]~]|+F*F\qF]qF_boF`bo-Fjal6$Q,Delta~=~%a|+F*Ffp
-Fjal6$Q*Rho~=~%a|+F*F[u-Fjal6$Q,Sigma~=~%a|+F*F]uF]im@%-F]en6$FfpF]o-Fbgm6,F;F
=F>F\qF]qF_boF`boF[uF]uF\p@%-Fg`nFddo@%-%,reduce_gteqG6$F]uF]o-Ffdn6(F;F]uF[uF=
F>F\p@%-%+reduce_eeqG6$F[uF]o-%+weak_focusG6&F;F=F>F\p-Fibn6'F]uF[uF=F>F\p@%F`e
o-F[hnFeeo-F^in6+F;F=F>F\qF]qF_boF`boF[uF\pF*F*F*F*,
I1separatrice_testf*6'Fc\l%#vfGFgnF\\l%$dirG6'Fe\l%'rndnumG%(exefileG%(sepfileG
Fb\lF*F*C2>F[u-%$catG6$%,user_bindirG%,user_sepexeG>Ffp-%%iremG6$-%%randGF*Fe[l
>F]u-Fhfo6&%,user_tmpdirGQ'P4SEP_F*FfpQ%.TMPF*-FjhmF^gn-Fjal6$Q$%g|+F*%(epsilon
G-Fjal6$Q$%d|+F*Fir-Fjal6$F_hoF\p-%0write_vec_fieldGFH-Fjal6$F_ho,&F>FEFcoFE?(F
[vFQFEF>Fg^l-Fjal6%Q'%d~%g~F*F[v-Fe]l6%F;FiqF[v-Fjal6#Q"|+F*-%*closefileGF^gn-F
jal6$Q;Separatrix~test~(n=%d)...~F*F>>F_o-%(ssystemG6#-Fhfo6'%/user_exeprefixGF
[uQ#~"F*F]uQ""F*-Fgio6#-Fhfo6&%/user_removecmdGF\joF]uF]jo@%/F\qF]oC$-Fjal6#Q(n
ot~ok|+F*%&falseGC$-Fjal6#Q$ok|+F*Fg^lF*6(F[joFego%,user_lypexeGFjfoFbjoF\hoF*F
*
