M7R0
I)jacobianf*6%%"fG%$xeqG%$yeqG6#%%exprG6"F*-%%evalG6#-%$mapG6$f*F(F*6$%)operato
rG%&arrowGF*-%%subsG6$<$T&T$9$F*F*6&F&9%F'9&7&-%%diffG6$&F;6#"""-%$lhsG6#F=-FA6
$FC-FG6#F>-FA6$&F;6#""#FF-FA6$FOFKF*F*F*F*,
I,eigenvectorf*6&%"aG%"bG%"cG%"dG6$%#_cG%"nGF*F*C%@%-%,reduce_nneqG6$F=""!>8$7$
FE,$*&F;FEF=!""Fco@%-F[o6$F;F]o>F_o7$F]oFE@%-F[o6$9'F]o>F_o7$FE,$*&F>FEF\pFcoFc
o>F_oFho@$%(roundedGC$>8%-%%sqrtG6#z'6$&F_oFD&F_oFP[[[[[_[[[[sFE][[[[[[[[[sFE>F
_o-%&evalfG6#7$*&F\qFEFfpFco*&F]qFEFfpFcoF_oF*F*F*F*,
I,translationf*6'%"vG%"xG%"yG%#x0G%#y0G6$%#f1G%#f2GF*F*C&>F_o-F66$<$/F=,&F=FEF
\pFE/F>,&F>FE9(FEFC>Ffp-F66$FdrFO@$FcpC$>F_o-%,change_polyG6%F_oF=F>>Ffp-Fas6%F
fpF=F>7$F_oFfpF*F*F*F*,
I/transformationf*6'FhqFWFXFYFZ6-F^rF_r%#_xG%#_yG%#_aG%#_bGFfn%#_dG%"MG%#g1G%#g
2GF*F*C,>F_o-F66$<$/Fiq,&*&F=FE8&FEFE*&F>FE8'FEFE/Fjq,&*&F\pFEF[uFEFE*&FirFEF]u
FEFEFC>Ffp-F66$FgtFO>8,,&*&F=FEFirFEFE*&F>FEF\pFEFco>8(*&FirFEFfuFco>8),$*&F>FE
FfuFcoFco>8*,$*&F\pFEFfuFcoFco>8+*&F=FEFfuFco>8--F66%/F[uFiq/F]uFjq,&*&F[vFEF_o
FEFE*&F^vFEFfpFEFE>8.-F66%F\wF]w,&*&FbvFEF_oFEFE*&FfvFEFfpFEFE-%+optimizevfG6%7
$FivFbwFiqFjqF*F*F*F*,
I.normalizationf*6#Fhq6%%#L1G%#L2G%"mGF*F*C)>F_o-%.coeff_degree2G6%-%4optimizep
olynomial2G6%FCFiqFjqFiqFjq>Ffp-Ffx6%-Fix6%FOFiqFjqFiqFjq>F_o-F/6$f*F(F*F2F*-F`
q6#-%$absG6#&F;6#""$F*F*F*F_o>Ffp-F/6$f*F(F*F2F*FdyF*F*F*Ffp>F[u-%$maxG6$-%#opG
6#F_o-Fez6#Ffp@$4Fcp>F[u-%(convertG6$F[u%)rationalG-Fiw6%7$,$*&FCFEF[uFco"%+5,$
*&FOFEF[uFcoFe[lFiqFjqF*F*F*F*,
I)manifoldf*6%%"gGFgn%'stableG6.%$vf1G%$vf2G%#h1G%#h2G%"kGF`xFax%$sepGF\t%'lamb
daG%#okG%#n1GF*F*C*@%FcpC$>F_o-F`q6#FC>Ffp-F`q6#FOC$>F_oFC>FfpFO>F^v-%&coeffG6%
-%(collectG6$-F66$/FjqF]oFCFiqFiqFE>Fbv-Fe]l6%-Fh]l6$-F66$/FiqF]oFOFjqFjqFE>Ffv
F]o?(F[vFQFEF=%%trueGC)>Fiv*&-Fe]l6%-Fh]l6$-F66$F\^lFfpFiqFiqF[vFE,&*&F^vFEF[vF
EFEFbvFcoFco@$3Fjz%.user_simplifyG>Fiv-%1user_simplifycmdG6#Fiv>F[u-%'expandG6#
-F66$/Fjq,&FfuFE*&FivFE)FiqF[vFEFEF_o>F]u-F\`l6#,&-F66$F``lFfpFE**FivFEF[vFE)Fi
q,&F[vFEFcoFEFEF[uFEFco>F_o-F66$/FfuFjqF[u>Ffp-F66$F`alF]u>Ffv,&FfvFEFb`lFE@$%)
test_sepGC&-%'writefG6#Q>Testing~separatrix~for~x~>~0|+F*>Fbw-%1separatrice_tes
tG6'FfvF;F=F>FE>8/F=?(F*FEFEF*34Fbw2Fbbl%*max_levelGC%>Fbbl,&FbblFEFEFE@%1%.num
eric_levelGFbblC)@$/FbblF]clC$>F_o-F`qFfz>Ffp-F`qFhz>Fiv-F`q6#*&-Fe]l6%F]_lFiqF
bblFE,&*&F^vFEFbblFEFEFbvFcoFco>F[u-F\`l6#-F66$/Fjq,&FfuFE*&FivFE)FiqFbblFEFEF_
o>F]u-F\`l6#,&-F66$FcdlFfpFE**FivFEFbblFE)Fiq,&FbblFEFcoFEFEF[uFEFco>F_oF^al>Ff
pFbal>Ffv,&FfvFEFedlFEC)>FivFicl@$Fd_l>FivFg_l>F[uF_dl>F]uFhdl>F_oF^al>FfpFbal>
FfvFcel>Fbw-F_bl6'FfvF;FbblF>FE@$FgalC%-Fjal6#Q>Testing~separatrix~for~x~<~0|+F
*>Fbw-F_bl6'FfvF;FbblF>Fco?(F*FEFEF*FdblC%>FbblFjbl@%F\clC)@$F`clC$>F_oFccl>Ffp
Fecl>FivFgcl>F[uF_dl>F]uFhdl>F_oF^al>FfpFbal>FfvFcelC)>FivFicl@$Fd_l>FivFg_l>F[
uF_dl>F]uFhdl>F_oF^al>FfpFbal>FfvFcel>FbwF^fl-F66$/Fiq%"tGFfvF*6#FgalF*F*,
I0center_manifoldf*Fj[l63F^\lF_\lF`\lFa\lFb\lFaxFc\lF\tFd\lFe\lFf\l%#dxGFXFbx%#
amG%&stypeG%(stable2GF*F*C/@%FcpC$>F_oF[]l>FfpF^]lC$>F_oFC>FfpFO>F^vF^^l>FbvF]o
>FbwF=?(F[vFQFEFbwFg^lC+>Ffu,$*&F[_lFEF^vFcoFco@$Fd_l>Ffu-Fh_l6#Ffu>F[u-F\`l6#-
F66$/Fjq,&FfvFE*&FfuFEFc`lFEFEF_o>F]u-F\`l6#,&-F66$FfjlFfpFE**FfuFEF[vFEF[alFEF
[uFEFco>F_o-F66$/FfvFjqF[u>Ffp-F66$Fc[mF]u>Fbv,&FbvFEFhjlFE>Fbbl-%4optimizepoly
nomial1G6$-F66$F\^lF_oFiq@$/FbblF]o>Fbw,&FbwFEFEFE>80-%+first_termG6$FbblFiq>81
-%'degreeG6$Fd\mFiq>82-F`q6#-F66$/FiqFEFd\m@%-%%typeG6$Fi\m%%evenG@%1F]oF^]m@%/
F>F]o>83FE>F^^mFQ@%F\^m>F^^mF[z>F^^m""%@%Fj]m@%F\^m>F^^m""&>F^^m""'@%F\^m>F^^m"
"(>F^^m"")@$FgalC$@%-%'memberG6$F^^m<$FQFi^m>84F]o>Fg_mFE@$-Fc_m6$F^^m<&FQF[zFi
^mF\_mC%-Fjal6#QETesting~center~separatrix~for~x~>~0|+F*>Fiv-F_bl6'FbvF;FbwFg_m
FE?(F*FEFEF*34Fiv2FbwFgblC%>FbwFb\m@%1F]clFbwC)@$/FbwF]clC$>F_oFccl>FfpFecl>Ffu
-F`q6#,$*&-Fe]l6%-Fh]l6$-F66$/FjqFbvFfpFiqFiqFbwFEF^vFcoFco>F[u-F\`l6#-F66$/Fjq
,&FfvFE*&FfuFE)FiqFbwFEFEF_o>F]u-F\`l6#,&-F66$FcbmFfpFE**FfuFEFbwFE)Fiq,&FbwFEF
coFEFEF[uFEFco>F_oFa[m>FfpFe[m>Fbv,&FbvFEFebmFEC)>FfuFeam@$Fd_l>FfuF_jl>F[uF_bm
>F]uFhbm>F_oFa[m>FfpFe[m>FbvFccm>FivFb`m@$FgalC$@%-Fc_m6$F^^m<$Fc^mFi^m>Fg_mF]o
>Fg_mFE@$-Fc_m6$F^^m<&FEFc^mFi^mF\_mC%-Fjal6#QETesting~center~separatrix~for~x~
<~0|+F*>Fiv-F_bl6'FbvF;FbwFg_mFco?(F*FEFEF*Fe`mC%>FbwFb\m@%F[amC)@$F^amC$>F_oFc
cl>FfpFecl>FfuFcam>F[uF_bm>F]uFhbm>F_oFa[m>FfpFe[m>FbvFccmC)>FfuFeam@$Fd_l>FfuF
_jl>F[uF_bm>F]uFhbm>F_oFa[m>FfpFe[m>FbvFccm>FivFb`m>Fbbl-F[\m6$-F66$F]bmF_oFiq7
%-F66$FchlFbvFbblF^^mF*FehlF*F*,
I'saddlef*6,F%F[rF\rFWFXFYFZ%$rhoG%&sigmaG%&chartG6/%(lambda1G%(lambda2G%-lambd
a_ratioG%1lambda_ratio_numG%1lambda_ratio_denG%#ffGF[\lFat%#v1G%#v2GF\\l%%sep1G
%%sep2GF*F*CA-Fjal6%Q<(%a,%a)~is~a~saddle~point.|+F*-F`qFH-F`qFL-%)openfileG6#%
,result_fileGFdhm-Fjhm6#%)terminalG>F_o,&9+#FEFQ-Fhp6#9,#FcoFQ>Ffp,&FbimFcimFdi
mFcim@%2-Fgy6#Fecl-Fgy6#Fccl>F[u*&F_oFEFfpFco>F[u*&FfpFEF_oFco@%33Fjz-Ff]m6$F_o
%(integerG-Ff]m6$FfpFijmC(>F]u-%&numerG6#F[u>F[v-%&denomGF`[n-Fjal6%QHThe~ratio
~between~eigenvalues~is~%a:%a|+F*F[vF]uFihmFd[nF]imC)>F[u-F][l6$-F`qF`[nF_[l>F]
uF^[n>F[vFb[n-Fjal6%QXThe~ratio~between~eigenvalues~is~%a:%a~(approximation)|+F
*F[vF]uFihmF^\nF]im>Ffu-FT6&,&F\pFEF_oFcoFir9),&9*FEF_oFco>Fiv-FT6&,&F\pFEFfpFc
oFirFe\n,&Fg\nFEFfpFco@$%)save_allGC&Fihm-Fjal6%QB~The~eigenvalues~are:~|fr~%a,
~%a~|hr|+F*F_oFfp-Fjal6%QC~The~eigenvectors~are:~|fr~%a,~%a~|hr|+F*FfuFivF]im@$
F^]n-Fjhm6$F_imF\im@%50F=F]o0F>F]oC%>F^v-Feq6'F;FiqFjqF=F>-Fjal6#QIMoving~this~
saddle~point~to~the~origin.|+F*-Fjal6$Q<The~new~vector~field~is~%a|+F*F^v>F^vF;
>Ffv-Fgs6'F^v&FfuFD&FivFD&FfuFP&FivFP-Fjal6#Q\oTransform~this~vector~field~so~t
hat~the~linear~part~is~diagonal.|+F*-Fjal6$Ff^nFfv>Fbv-F\x6#Ffv-Fjal6#Q;Make~a~
1000-normalization|+F*-Fjal6$QDso~that~the~new~vector~field~is~%a|+F*Fbv-Fjal6#
QIWe~calculate~the~invariant~separatrices|+F*F]im@%2FcclF]o>FbwFE>FbwF]o>Fbbl-F
h[l6%Fbv%-taylor_levelGFbw@%2FeclF]o>FbwFE>FbwF]o>Fd\m-Fh[l6%-Fgs6'FbvF]oFEFEF]
oFg`nFbw@%-%*reduce_gtG6$F_oF]oC%-Fjal6$Q?The~stable~separatrice~is~%a.|+F*7$Fd
\mFdhl-Fjal6$QAThe~unstable~separatrice~is~%a.|+F*7$FdhlFbbl@$F^]nC&FihmFfanFja
nF]imC%-Fjal6$FhanF]bn-Fjal6$F\bnFian@$F^]nC&FihmFabnFcbnF]im-Fjal6#QZ#########
###############################################|+F*FihmFgbnF]im-%-write_saddleG
6,F=F>F[_nF\_nF]_nF^_nFbv7$FbblFd\m7$-%%signGF_jm-F`cnF]jm9-F*F*F*F*,
I-strong_focusf*6'FfgmFegmF[rF\rFggm6%FigmFjgm%"LGF*F*C*>F_o,&F=Fcim-Fhp6#F;Fgi
m>Ffp,&F=FcimF[dnFcim@%-FcanF\oC'-Fjal6%QE(%a,%a)~is~a~strong~unstable~focus.|+
F*Fhhm-F`q6#F\pFihmFbdnF]im>F[uFEC'-Fjal6%QC(%a,%a)~is~a~strong~stable~focus.|+
F*FhhmFednFihmFidnF]im>F[uFcoFgbnFihmFgbnF]im-%3write_strong_focusG6&F>F\pF[uFi
rF*F*F*F*,
I%nodef*6(F%FfgmFegmF[rF\rFggm6(FgcnFigmFjgmF[hmF\hmF]hmF*F*C,@%-%+reduce_lltG6
$F>F]oC'-Fjal6%Q;(%a,%a)~is~a~stable~node.|+F*Fedn-F`q6#FirFihmFjenF]im>F_oFcoC
'-Fjal6%Q>(%a,%a)~is~an~unstable~node.|+F*FednF]fnFihmFafnF]im>F_oFE>Ffp,&F>Fci
m-FhpFHFgim>F[u,&F>FcimFgfnFcim@%2-Fgy6#F[\nF\jm>F]u*&FfpFEF[uFco>F]u*&F[uFEFfp
Fco@%33FjzFjjm-Ff]m6$F[uFijmC(>F[v-F_[n6#F]u>F^v-Fc[nFjgn-Fjal6%Ff[nF^vF[vFihmF
]hnF]imC)>F]u-F][l6$-F`qFjgnF_[l>F[vFign>F^vF\hn-Fjal6%F`\nF^vF[vFihmFfhnF]imFg
bnFihmFgbnF]im-%+write_nodeG6&F\pFirF_oFe\nF*F*F*F*,
I+degeneratef*6&F%F[rF\rFggm6#%+trajectorsGF*F*C--Fjal6%QD(%a,%a)~is~a~non-elem
entary~point.|+F*FghmFhhm-Fjal6#Q@Blowing~up~the~vector~field...|+F*FihmFainF]i
m>F_o-%+blowing_upG6&F;F=F>Fg^lFgbnFihmFgbnF]im-%1write_degenerateG6&F=F>F_oF\p
F*F*F*F*,
I0semi_elementaryf*6+F%F[rF\rFWFXFYFZFjgmFggm6,F_hmF`hmF^hmF[\lFat%+center_sepG
FahmFbhmF[ilF\\lF*F*C=>F_o-FT6&F\pFirFe\nFg\n>Ffp-FT6&,&F\pFEFbimFcoFirFe\n,&Fg
\nFEFbimFco>F[uF_^n>F[v-Fgs6'F[uF\q&FfpFDF]q&FfpFP>F]u-F\x6#F[v-Fjal6%Qhn(%a,%a
)~is~semi-hyperbolic.|+Moving~this~point~to~the~origin.|+F*FghmFhhm-Fjal6$Ff^nF
[uF__n-Fjal6$Ff^nF[vFg_n-Fjal6$F\`nF]uF]`nFihm-Fjal6%Q=(%a,%a)~is~semi-hyperbol
ic.|+F*FghmFhhm@$F^]nC)-Fjal6#QBMoving~this~point~to~the~origin.|+F*Fh[oF__nFj[
oFg_nF\\oF]`nF]im@%-Fgen6$FbimF]o>FivFE>FivF]o>F^v-Ffhl6%F]uFg`nFiv>Fbv-F66$Fch
l&F^vFD>Ffv-F66$Fchl-Fh[l6%-Fgs6'F]uF]oFEFEF]oFg`nFiv>Ffu&F^vFjy@%-Fc_m6$Ffu<$F
EF[zC)-Fjal6#Q8We~have~a~saddle-node.|+F*-Fjal6$Q7center~separatrice~%a|+F*7$Fd
hlFbv-Fjal6$Q9unstable~separatrice~%a|+F*7$FfvFdhlFihmF`^o@$F^]nC$Fc^oFg^oF]im@
%-Fc_m6$Ffu<$FQFc^mC)F`^oFc^o-Fjal6$Q7stable~separatrice~%a|+F*Fj^oFihmF`^o@$F^
]nC$Fc^oFb_oF]im@%/FfuFi^mC)-Fjal6#Q3We~have~a~saddle.|+F*-Fjal6$Q@unstable~cen
ter~separatrice~%a|+F*Ff^oFb_oFihmFj_o@$F^]nC$F]`oFb_oF]im@%/FfuF\_mC)Fj_o-Fjal
6$Q>stable~center~separatrice~%a|+F*Ff^oFg^oFihmFj_o@$F^]nC$Fe`oFg^oF]im@%/FfuF
g^mC)-Fjal6#Q;We~have~an~unstable~node.|+F*Fc^oFg^oFihmF]ao@$F^]nC$Fc^oFb_oF]im
C)-Fjal6#Q8We~have~a~stable~node.|+F*Fc^oFb_oFihmFcao@$F^]nC$Fc^oFb_oF]imFgbnFi
hmFgbnF]im-%6write_semi_elementaryG6,F=F>F\qF`[oF]qFa[oF]u7$FfuFE7$FbvFfvFfimF*
F*F*F*,
I*sing_typef*F]in6&%$jacG%&deltaGFegmFfgmF*F*C,>F_o-F"6%F;/FiqF=/FjqF>@$Fd_l>F_
o-F/6$Fh_lF_o>Ffpz'6&F\qF]q&F_oFjy&F_o6#Fc^m\[[[[[[[[\[[mFE[[[\[[\[[[[[mFco@$Fd
_l>Ffp-Fh_lFhz>F[u,&F\qFEF`coFE@$Fd_l>F[u-Fh_lF`[n>F]u,&*$F[uFQFEFfp!"%@$Fd_l>F
]u-Fh_lFjgn@$F^]nC)Fihm-Fjal6%Q>(%a,%a)~is~a~singular~point.|+F*F=F>-Fjal6'QGJa
cobian~=~[~[~%a,~%a~],~[~%a,~%a~]~]|+F*F\qF]qF_coF`co-Fjal6$Q,Delta~=~%a|+F*Ffp
-Fjal6$Q*Rho~=~%a|+F*F[u-Fjal6$Q,Sigma~=~%a|+F*F]uF]im@%-Fgen6$FfpF]o-Fbgm6,F;F
=F>F\qF]qF_coF`coF[uF]uF\p@%-FcanFdeo@%-%,reduce_gteqG6$F]uF]o-F`en6(F;F]uF[uF=
F>F\p@%-%+reduce_eeqG6$F[uF]o-%+weak_focusG6&F;F=F>F\p-Fccn6'F]uF[uF=F>F\p@%F`f
o-F[inFefo-F^jn6+F;F=F>F\qF]qF_coF`coF[uF\pF*F*F*F*,
I1separatrice_testf*6'Fc\l%#vfGFgnF\\l%$dirG6'Fe\l%'rndnumG%(exefileG%(sepfileG
Fb\lF*F*C2>F[u-%$catG6$%,user_bindirG%,user_sepexeG>Ffp-%%iremG6$-%%randGF*Fe[l
>F]u-Fhgo6&%,user_tmpdirGQ'P4SEP_F*FfpQ%.TMPF*-FjhmFjgn-Fjal6$Q$%g|+F*%(epsilon
G-Fjal6$Q$%d|+F*Fir-Fjal6$F_ioF\p-%0write_vec_fieldGFH-Fjal6$F_io,&F>FEFcoFE?(F
[vFQFEF>Fg^l-Fjal6%Q'%d~%g~F*F[v-Fe]l6%F;FiqF[v-Fjal6#Q"|+F*-%*closefileGFjgn-F
jal6$Q;Separatrix~test~(n=%d)...~F*F>>F_o-%(ssystemG6#-Fhgo6'%/user_exeprefixGF
[uQ#~"F*F]uQ""F*-Fgjo6#-Fhgo6&%/user_removecmdGF\[pF]uF][p@%/F\qF]oC$-Fjal6#Q(n
ot~ok|+F*%&falseGC$-Fjal6#Q$ok|+F*Fg^lF*6(F[[pFeho%,user_lypexeGFjgoFb[pF\ioF*F
*
