M7R0
I+weak_focusf*6&%"fG%#x0G%#y0G%&chartG6,%&stypeG%#ffG%%aa10G%%aa01G%%bb10G%"sG%
"gG%#_xG%#ggG%$lypG6"F4C,-%'writefG6%Q:(%a,%a)~is~a~weak~focus.|+F4-%&evalfG6#9
%-F;6#9&-%)openfileG6#%,result_fileGF6-FB6#%)terminalG@%%,hamiltonianGC'-F76#QT
Since~the~system~is~hamiltonian,~we~have~a~center.|+F4FAFKFE>8$""%C.>8%-%,trans
lationG6'9$%"xG%"yGF=F@>8&-%&coeffG6%-Fgn6%&FS6#"""FXF]oFY""!>8'-Fgn6%-Fgn6%F[o
FXF^oFYF]o>8(-Fgn6%-Fgn6%&FS6#""#FXF]oFYF^o>8)-%%sqrtG6#,&*&F`oF]oFfoF]o!""*$Fe
nF]pFep>8*7$,&*(FfoF]o-%%subsG6$<#/FX,&*(F_pF]o8+F]oFfoFepFep*(FenF]oFYF]oFfoFe
pF]oF[oF]oF_p!"#F]o*(FenF]o-F]q6$F_qF[pF]oF_pFeqFep,$*&-F]q6$<#/FX,&*(F_pF]oFXF
]oFfoFepFepFdqF]oF[pF]oF_pFepFep@%%-user_numericG>Fhp-F;6#-F]q6$/FcqFXFhp>FhpFf
r-F76$Q6The~local~system:~%a|+F4Fhp>8,,&-F]q6$<$/FX,&%"zG#F]oF]p%"wGFfs/FY*&^##
FepF]pF]o,&FesF]oFgsFepF]o&FhpF\oF]o*&^#F]oF]o-F]q6$Fbs&FhpF\pF]oF]o>F^s-%'expa
ndG6#F^s@$%)save_allGC%FA-F76$Q)z'~=~%a|+F4F^sFE@%/%/weakness_levelGF^oC%-FB6$F
DFG-F76#QenLyapunov~constants~are~not~calculated.~(weakness~level=0)|+F4>FOF^oC
%@%Fbr>8--%)lyapunovG6%,&F^sF]o*&^#FepF]oFesF]oF]oFesFgs>Fju-%,lyapunovsymGF]v-
F76$Q:Lyapunov~information:~%a|+F4Fju@%0&FjuF\oF^oC'Fau-F76$Q=The~order~of~weak
ness~is~%d|+F4&FjuF\p-F76$Q9Lyapunov~constant~is~%g|+F4,$FivFepFE@%2FivF^oC'-F7
6#QBWe~have~an~unstable~singularity.|+F4FAFfwFE>FOF]oC'-F76#Q?We~have~a~stable~
singularity.|+F4FAF[xFE>FOFep@%/&Fju6#""$F]pC'-F76#QMWe~have~a~center~(the~syst
em~is~quadratic).|+F4FAFexFE>FOFP@%&Fju6#FPC'-F76#QPWe~have~a~center~(the~syste
m~is~linear+cubic).|+F4FAF]yFE>FOFPC'-F76$QGThe~order~of~weakness~is~at~least~%
d.|+F4,&F_uF]oF]oF]oFAFbyFE>FOF^oFA-F76#QZ#####################################
###################|+F4FEFgy-%1write_weak_focusG6&F=F@9'FOF46#FIF4F4,
I)lyapunovf*6%F%FesFgs6,%"aG%'bindirG%'infileG%(outfileG%(exefileG%'resultG%'rn
dnumG%#wlG%&linfoG%$auxGF4F4C,>Fhp-%%iremG6$-%%randGF4"%+5>Fen-%$catG6&%,user_t
mpdirGQ'P4LYP_F4FhpQ%.INPF4>F`o-Fg[l6&Fi[lFj[lFhpQ%.OUTF4@%/%0user_precision0GF
^o>Ffo-Fg[l6$%,user_bindirG%,user_lypexeG>Ffo-Fg[l6$Ff\l%0user_lypexe_mpfG>F^s-
%4preparelyapunovfileG6&FenFWF=F@>Fcq&F^sF\o-F76#QDDetermining~lyapunov~constan
ts~...|+F4>Fju-%(ssystemG6#-Fg[l6.%/user_exeprefixGQ!F4FfoQ#~"F4FenQ$"~"F4F`oQ)
"~MAPLE~F4%.user_platformGF]^l%2user_sumtablepathGQ""F4>F_p-%3readlyapunovresul
tG6$F`oFcq7%-%#opG6#F_p&F^sF\p&F^sFbxF46)F[^lFi[lFg\lF[]lFb\lFf\l%/user_removec
mdGF4F4,
I3readlyapunovresultf*6$%)filenameG%*weaklevelG6)%(lypdataG%&VdataG%"jG%"nG%%wv
alG%'lypvalG%&okvalGF4F4C.>FO-%)readdataG6$FWF]o-F76$Q4lyapunov~data~=~%a|+F4FO
>FS7">F`oF]o-FB6$FGFD?(FenF]oF]oF=%%trueGC&@$0&FO6#F`oFep-F76%Q*V(%d)=%g|+F4-%&
roundG6#F^al&FO6#,&F`oF]oF]oF]o>FS7$-Fi^l6#FS7$FcalFfal@$/FcalFepC$>F`oFhal[>F`
o,&F`oF]oF]pF]o@$F_bl>F`oFhal>FhpFcal>Ffo-Fdal6#Ffal>F_p&FO6#FdblFE7$F_pFfoF4F4
F4F4,
I4preparelyapunovfilef*6&Fb_l%#_fGFesFgs6)F%%&cubicG%"LG%"dGFczFg_lFjzF4F4C.>FO
-%4optimizepolynomial2G6%F=F@F]z>FS%&falseG-FB6#FW-F76$Q$%d|+F4,&Fb\lF]pF]pF]o>
F`o-%%ddegG6%FOF@F]z@%/F`oF]pC$>FhpFcx-F76#Q#3|+F4@%/F`oFcxC$>Fhp""&@%33/-Fgn6%
-Fgn6%FOF@F]pF]zF^oF^o/-Fgn6%-Fgn6%FOF@F^oF]zF]pF^o/-Fgn6%-Fgn6%FOF@F]oF]zF]oF^
oC$-F76#Q#5|+F4>FSFj`lC$>FhpF_u-F76$FbdlF_uC$>FhpF_uF]gl-F76$Q$%g|+F4)"#5,$%/us
er_precisionGFep>Fen-%.coeff_degree2GFgdl-F76$Fbdl-%%nopsG6#Fen?(F_pF]oF]oF]hlF
j`lC$>Ffo&FenFj^l-F76'Q/~~%d~%d~%g~%g|+F4&FfoF\o&FfoF\p-F;6#-%#ReG6#&FfoFbx-F;6
#-%#ImGF]il-%*closefileGF_dl7%FhpF`oFSF4F4F4F4,
I,lyapunovsymf*6%FbclFesFgs6+F%F[[lFjz%"kG%"TG%"VGFhz%#okGFg_lF4F4C,>FO-Fjcl6%F
WF=F@>FS-%3preparelyapunovsymG6%FOF=F@>FenF[o>FhpFe`l>FcqF]dlFg`l?(F`oF]oF]oFen
Fj`lC(>Ffo-%)sumtableG6#,$F`oF]p>F_pF^o?(F^sF]oF]o-F^hl6#FfoFj`l>F_p,&F_pF]o-%4
part_lyapunov_coeffG6'FOF=F@&FfoFft,&F`oF]pF]oF]oFep>Fhp7$-Fi^l6#Fhp7$F_pF`o-F7
6&Q2k=%d~V~=~%a~=~%f|+F4F`oF_p-F;Fj^l@$-%,reduce_nneqG6$F_pF^oC$>FcqFj`lFbblFE@
%Fcq>Fhp&Fhp6#Fep>Fhp7$F^oF^o7%F]\mF[p&FSFbxF4F4F4F4,
I3preparelyapunovsymf*Faz6(FdclFeclFfclFczFg_lFjzF4F4C'>FOF]dl>Fen-FfdlFajl@%/F
enF]p>F_pFcx@%/FenFcxC$>F_pFcel@%33/-Fgn6%-Fgn6%FWF=F]pF@F^oF^o/-Fgn6%-Fgn6%FWF
=F^oF@F]pF^o/-Fgn6%-Fgn6%FWF=F]oF@F]oF^o>FOFj`l>F_pF_u>F_pF_u>FS-FjglFajl7%F_pF
enFOF4F4F4F4,
I)sumtablef*6#Fh_l6&Fecl%"rGF/%+st_compareGF4F4C&>FO-%*piecewiseG6%/FWF^o7#7#F]
o-%$mapG6$Fi^l-Fg`m6$&%)combinatG6#%(permuteG-&F\am6#%*partitionG6$FWFW>F`of*6$
F\`mF/F46$%)operatorG%&arrowGF4@%2&FWF\o&F=F\oFj`l@%/F\bmF]bm-T#6$&FW6#;F]pFep&
F=FdbmF]dlF4F46$F]`mF`o>FO-%%sortG6$FOF`oOFOF4F4F4F4,
I4part_lyapunov_coefff*6'%)vecfieldGFesFgsFeclFjil6(%"RG%%exprGF%%"vG%#wwG%"iGF
4F4C%>FO-Fg`m6$f*6#FccmF4FgamF4-%-lyp_findpolyG6&T$T&T(,&FWF]oF]oF]oF4F46(F`cmF
WFesF=FgsF@F]z@%4-%'memberG6$F^oFOC&>FenFep?(F_pF]oF]o,&-F^hl6#FOF]oFepF]oFj`l@
%-%%typeG6$,&F_pF]oFepF]o%$oddG>Fen-%)lyp_RegzG6&Fen&FOFj^lF=F@>Fen-%)lyp_ImgzG
Fiem>F_pF^em@%FaemC%>Fen-%/lyp_multc_polyG6'FenF^oFepF=F@>6$FenF`o-Fi^l6#-%'lyp
_LLG6'FenFjemF=F@,&9(FfsF[tF]o>Ffo-%)simplifyG6#-FbilF_alC$>FffmFgfm>Ffo-F`gm6#
-F\ilF_al>FfoF^oOFfoF4F4F4F4,
I/lyp_multc_polyf*6'F%Fcz%"bGFesFgsF4F4F4O-Fet6#*&,&F=F]o*&F_tF]oF@F]oF]oF]oFWF
]oF4F4F4F4,
I-lyp_findpolyf*6&%#vfGFesFgsFh_l6$F\`mFjilF4F4C%>FOF^o?(FSF^oF]oF]zFj`l>FO,&FO
F]o*(-Fgn6%-Fgn6%FWF=FSF@,&F]zF]oFSFepF]o)F=FSF]o)F@FdimF]oF]oFOF4F4F4F4,
I)lyp_Regzf*6&F%F0FesFgs6#F\`mF4F4C(>FO-Fet6#*&FWF]oF=F]o>FO-Fcfm6'FOF^oFepF@F]
z>FO-%%diffG6$FOF@>FO-%&lyp_GGFgdl>FO,&FOF]o-%.lyp_conj_polyGFgdlF]oO-Fcfm6%FOF
fsF^oF4F4F4F4,
I)lyp_Imgzf*FiimFjimF4F4C'>FOF]jm>FOFdjm>FOFhjm>FO,&FOF]oF\[nFepO-Fcfm6%FOF^oF[
tF4F4F4F4,
I'lyp_LLf*6'F%F0FesFgsFh_lFjimF4F4C$>FO-Fejm6$F]jmF@7$FO-Fgn6%-Fgn6%FOF@F]gmF]z
F]gmF4F4F4F4,
I&lyp_Gf*Faz6&Fjil%#fkGF\`m%"lGF4F4C%>FenF^o@$1F^o-%'degreeG6$FWF=?(FOF^oF]oFa]
nFj`lC$>FS-Fgn6%FWF=FO@$1F^o-Fb]n6$FSF@?(F`oF^oF]oF[^nFj`l@%0FOF`o>Fen,&FenF]o*
*-Fgn6%FSF@F`oF]o,&FOF]oF`oFepFep)F=FOF]o)F@F`oF]oF]p>Fen,&FenF]o*(Fc^nF]oFf^nF
]oFg^nF]oF]o-FetF_hlF4F4F4F4,
I.lyp_conj_polyf*Faz6#%#zbGF4F4C$-%)assumingG6$7#-Fet6#-%*conjugateGF_dl7$'F=%%
realG'F@F[`n-%%evalG6$-F^`n6$-F^`n6$%"%G<#/F=FO/F@F=/FOF@F4F4F4F4
