M7R0
I+weak_focusf*6&%"fG%#x0G%#y0G%&chartG6-%&stypeG%#ffG%%aa10G%%aa01G%%bb10G%"sG%
"gG%#_xG%#ggG%$lypG%"hG6"F5C,-%'writefG6%Q:(%a,%a)~is~a~weak~focus.|+F5-%&evalf
G6#9%-F<6#9&-%)openfileG6#%,result_fileGF7-FC6#%)terminalG@%%,hamiltonianGC*>8.
,&-%*integrateG6$&9$6#"""%"yGFU-FP6$,&-%%diffG6$FO%"xG!""&FS6#""#FhnFgnFU-F86#Q
TSince~the~system~is~hamiltonian,~we~have~a~center.|+F5-F86$QKThe~Hamiltonian~f
unction~is:|+~H(x,y)~=~%a|+F5FMFBF\oF_oFF>8$""%C.>8%-%,translationG6'FSFgnFVF>F
A>8&-%&coeffG6%-F^p6%&FgoFTFgnFUFV""!>8'-F^p6%-F^p6%FbpFgnFcpFVFU>8(-F^p6%-F^p6
%&FgoFjnFgnFUFVFcp>8)-%%sqrtG6#,&*&FepFUF[qFUFhn*$F\pF[oFhn>8*7$,&*(F[qFU-%%sub
sG6$<#/Fgn,&*(FbqFU8+FUF[qFhnFhn*(F\pFUFVFUF[qFhnFUFbpFUFbq!"#FU*(F\pFU-F_r6$Fa
rF`qFUFbqFgrFhn,$*&-F_r6$<#/Fgn,&*(FbqFUFgnFUF[qFhnFhnFfrFUF`qFUFbqFhnFhn@%%-us
er_numericG>Fjq-F<6#-F_r6$/FerFgnFjq>FjqFhs-F86$Q6The~local~system:~%a|+F5Fjq>8
,,&-F_r6$<$/Fgn,&%"zG#FUF[o%"wGFht/FV*&^##FhnF[oFU,&FgtFUFitFhnFU&FjqFTFU*&^#FU
FU-F_r6$Fdt&FjqFjnFUFU>F`t-%'expandG6#F`t@$%)save_allGC%FB-F86$Q)z'~=~%a|+F5F`t
FF@%/%/weakness_levelGFcpC%-FC6$FEFH-F86#QenLyapunov~constants~are~not~calculat
ed.~(weakness~level=0)|+F5>FcoFcpC%@%Fds>8--%)lyapunovG6%,&F`tFU*&^#FhnFUFgtFUF
UFgtFit>F\w-%,lyapunovsymGF_w-F86$Q:Lyapunov~information:~%a|+F5F\w@%0&F\wFTFcp
C'Fcv-F86$Q=The~order~of~weakness~is~%d|+F5&F\wFjn-F86$Q9Lyapunov~constant~is~%
g|+F5,$F[xFhnFF@%2F[xFcpC'-F86#QBWe~have~an~unstable~singularity.|+F5FBFhxFF>Fc
oFUC'-F86#Q?We~have~a~stable~singularity.|+F5FBF]yFF>FcoFhn@%/&F\w6#""$F[oC'-F8
6#QMWe~have~a~center~(the~system~is~quadratic).|+F5FBFgyFF>FcoFdo@%&F\w6#FdoC'-
F86#QPWe~have~a~center~(the~system~is~linear+cubic).|+F5FBF_zFF>FcoFdoC'-F86$QG
The~order~of~weakness~is~at~least~%d.|+F5,&FavFUFUFUFBFdzFF>FcoFcpFB-F86#QZ####
####################################################|+F5FFFiz-%1write_weak_focu
sG6&F>FA9'FcoF56#FJF5F5,
I)lyapunovf*6%F%FgtFit6,%"aG%'bindirG%'infileG%(outfileG%(exefileG%'resultG%'rn
dnumG%#wlG%&linfoG%$auxGF5F5C,>Fjq-%%iremG6$-%%randGF5"%+5>F\p-%$catG6&%,user_t
mpdirGQ'P4LYP_F5FjqQ%.INPF5>Fep-Fi\l6&F[]lF\]lFjqQ%.OUTF5@%/%0user_precision0GF
cp>F[q-Fi\l6$%,user_bindirG%,user_lypexeG>F[q-Fi\l6$Fh]l%0user_lypexe_mpfG>F`t-
%4preparelyapunovfileG6&F\pFSF>FA>Fer&F`tFT-F86#QDDetermining~lyapunov~constant
s~...|+F5>F\w-%(ssystemG6#-Fi\l6.%/user_exeprefixGQ!F5F[qQ#~"F5F\pQ$"~"F5FepQ)"
~MAPLE~F5%.user_platformGF__l%2user_sumtablepathGQ""F5>Fbq-%3readlyapunovresult
G6$FepFer7%-%#opG6#Fbq&F`tFjn&F`tFdyF56)F]_lF[]lFi]lF]^lFd]lFh]l%/user_removecm
dGF5F5,
I3readlyapunovresultf*6$%)filenameG%*weaklevelG6)%(lypdataG%&VdataG%"jG%"nG%%wv
alG%'lypvalG%&okvalGF5F5C.>Fco-%)readdataG6$FSFU-F86$Q4lyapunov~data~=~%a|+F5Fc
o>Fgo7">FepFU-FC6$FHFE?(F\pFUFUF>%%trueGC&@$0&Fco6#FepFhn-F86%Q*V(%d)=%g|+F5-%&
roundG6#F`bl&Fco6#,&FepFUFUFU>Fgo7$-F[`l6#Fgo7$FeblFhbl@$/FeblFhnC$>FepFjbl[>Fe
p,&FepFUF[oFU@$Facl>FepFjbl>FjqFebl>F[q-Ffbl6#Fhbl>Fbq&Fco6#FfclFF7$FbqF[qF5F5F
5F5,
I4preparelyapunovfilef*6&Fd`l%#_fGFgtFit6)F%%&cubicG%"LG%"dGFe[lFi`lF\\lF5F5C.>
Fco-%4optimizepolynomial2G6%F>FAF_[l>Fgo%&falseG-FC6#FS-F86$Q$%d|+F5,&Fd]lF[oF[
oFU>Fep-%%ddegG6%FcoFAF_[l@%/FepF[oC$>FjqFey-F86#Q#3|+F5@%/FepFeyC$>Fjq""&@%33/
-F^p6%-F^p6%FcoFAF[oF_[lFcpFcp/-F^p6%-F^p6%FcoFAFcpF_[lF[oFcp/-F^p6%-F^p6%FcoFA
FUF_[lFUFcpC$-F86#Q#5|+F5>FgoF\blC$>FjqFav-F86$FdelFavC$>FjqFavF_hl-F86$Q$%g|+F
5)"#5,$%/user_precisionGFhn>F\p-%.coeff_degree2GFiel-F86$Fdel-%%nopsG6#F\p?(Fbq
FUFUF_ilF\blC$>F[q&F\pF\`l-F86'Q/~~%d~%d~%g~%g|+F5&F[qFT&F[qFjn-F<6#-%#ReG6#&F[
qFdy-F<6#-%#ImGF_jl-%*closefileGFael7%FjqFepFgoF5F5F5F5,
I,lyapunovsymf*6%FddlFgtFit6+F%F]\lF\\l%"kG%"TG%"VGFj[l%#okGFi`lF5F5C,>Fco-F\el
6%FSF>FA>Fgo-%3preparelyapunovsymG6%FcoF>FA>F\pFbp>FjqFgal>FerF_elFial?(FepFUFU
F\pF\blC(>F[q-%)sumtableG6#,$FepF[o>FbqFcp?(F`tFUFU-F`il6#F[qF\bl>Fbq,&FbqFU-%4
part_lyapunov_coeffG6'FcoF>FA&F[qFhu,&FepF[oFUFUFhn>Fjq7$-F[`l6#Fjq7$FbqFep-F86
&Q2k=%d~V~=~%a~=~%f|+F5FepFbq-F<F\`l@$-%,reduce_nneqG6$FbqFcpC$>FerF\blFdclFF@%
Fer>Fjq&Fjq6#Fhn>Fjq7$FcpFcp7%F_]mF`q&FgoFdyF5F5F5F5,
I3preparelyapunovsymf*Fc[l6(FfdlFgdlFhdlFe[lFi`lF\\lF5F5C'>FcoF_el>F\p-FhelFc[m
@%/F\pF[o>FbqFey@%/F\pFeyC$>FbqFefl@%33/-F^p6%-F^p6%FSF>F[oFAFcpFcp/-F^p6%-F^p6
%FSF>FcpFAF[oFcp/-F^p6%-F^p6%FSF>FUFAFUFcp>FcoF\bl>FbqFav>FbqFav>Fgo-F\ilFc[m7%
FbqF\pFcoF5F5F5F5,
I)sumtablef*6#Fj`l6&Fgdl%"rGF/%+st_compareGF5F5C&>Fco-%*piecewiseG6%/FSFcp7#7#F
U-%$mapG6$F[`l-Fiam6$&%)combinatG6#%(permuteG-&F^bm6#%*partitionG6$FSFS>Fepf*6$
F^amF/F56$%)operatorG%&arrowGF5@%2FR&F>FTF\bl@%/FRF^cm-T#6$&FS6#;F[oFhn&F>FecmF
_elF5F56$F_amFep>Fco-%%sortG6$FcoFepOFcoF5F5F5F5,
I4part_lyapunov_coefff*6'%)vecfieldGFgtFitFgdlF\[m6(%"RG%%exprGF%%"vG%#wwG%"iGF
5F5C%>Fco-Fiam6$f*6#FddmF5FibmF5-%-lyp_findpolyG6&T$T&T(,&FSFUFUFUF5F56(FadmFSF
gtF>FitFAF_[l@%4-%'memberG6$FcpFcoC&>F\pFhn?(FbqFUFU,&-F`il6#FcoFUFhnFUF\bl@%-%
%typeG6$,&FbqFUFhnFU%$oddG>F\p-%)lyp_RegzG6&F\p&FcoF\`lF>FA>F\p-%)lyp_ImgzGFjfm
>FbqF_fm@%FbfmC%>F\p-%/lyp_multc_polyG6'F\pFcpFhnF>FA>6$F\pFep-F[`l6#-%'lyp_LLG
6'F\pF[gmF>FA,&9(FhtF]uFU>F[q-%)simplifyG6#-FdjlFablC$>FggmFhgm>F[q-Fahm6#-F^jl
Fabl>F[qFcpOF[qF5F5F5F5,
I/lyp_multc_polyf*6'F%Fe[l%"bGFgtFitF5F5F5O-Fgu6#*&,&F>FU*&FauFUFAFUFUFUFSFUF5F
5F5F5,
I-lyp_findpolyf*6&%#vfGFgtFitFj`l6$F^amF\[mF5F5C%>FcoFcp?(FgoFcpFUF_[lF\bl>Fco,
&FcoFU*(-F^p6%-F^p6%FSF>FgoFA,&F_[lFUFgoFhnFU)F>FgoFU)FAFejmFUFUFcoF5F5F5F5,
I)lyp_Regzf*6&F%F0FgtFit6#F^amF5F5C(>Fco-Fgu6#*&FSFUF>FU>Fco-Fdgm6'FcoFcpFhnFAF
_[l>Fco-Fen6$FcoFA>Fco-%&lyp_GGFiel>Fco,&FcoFU-%.lyp_conj_polyGFielFUO-Fdgm6%Fc
oFhtFcpF5F5F5F5,
I)lyp_Imgzf*FjjmF[[nF5F5C'>FcoF^[n>FcoFe[n>FcoFh[n>Fco,&FcoFUF\\nFhnO-Fdgm6%Fco
FcpF]uF5F5F5F5,
I'lyp_LLf*6'F%F0FgtFitFj`lF[[nF5F5C$>Fco-Fen6$F^[nFA7$Fco-F^p6%-F^p6%FcoFAF^hmF
_[lF^hmF5F5F5F5,
I&lyp_Gf*Fc[l6&F\[m%#fkGF^am%"lGF5F5C%>F\pFcp@$1Fcp-%'degreeG6$FSF>?(FcoFcpFUFa
^nF\blC$>Fgo-F^p6%FSF>Fco@$1Fcp-Fb^n6$FgoFA?(FepFcpFUF[_nF\bl@%0FcoFep>F\p,&F\p
FU**-F^p6%FgoFAFepFU,&FcoFUFepFhnFhn)F>FcoFU)FAFepFUF[o>F\p,&F\pFU*(Fc_nFUFf_nF
UFg_nFUFU-FguFailF5F5F5F5,
I.lyp_conj_polyf*Fc[l6#%#zbGF5F5C$-%)assumingG6$7#-Fgu6#-%*conjugateGFael7$'F>%
%realG'FAF[an-%%evalG6$-F^an6$-F^an6$%"%G<#/F>Fco/FAF>/FcoFAF5F5F5F5
