M7R0
I+weak_focusf*6&%"fG%#x0G%#y0G%&chartG6,%&stypeG%#ffG%%aa10G%%aa01G%%bb10G%"sG%
"gG%#_xG%#ggG%$lypG6"F4C,-%'writefG6%Q:(%a,%a)~is~a~weak~focus.|+F49%9&-%)openf
ileG6#%,result_fileGF6-F=6#%)terminalG@%%,hamiltonianGC'-F76#QTSince~the~system
~is~hamiltonian,~we~have~a~center.|+F4F<FFF@>8$""%C.>8%-%,translationG6'9$%"xG%
"yGF:F;>8&-%&coeffG6%-FX6%&FN6#"""FSFhnFT""!>8'-FX6%-FX6%FfnFSFinFTFhn>8(-FX6%-
FX6%&FN6#""#FSFhnFTFin>8)-%%sqrtG6#,&*&F[oFhnFaoFhn!""*$FVFhoF`p>8*7$,&*(FaoFhn
-%%subsG6$<#/FS,&*(FjoFhn8+FhnFaoF`pF`p*(FVFhnFTFhnFaoF`pFhnFfnFhnFjo!"#Fhn*(FV
Fhn-Fhp6$FjpFfoFhnFjoF`qF`p,$*&-Fhp6$<#/FS,&*(FjoFhnFSFhnFaoF`pF`pF_qFhnFfoFhnF
joF`pF`p@%%-user_numericG>Fcp-%&evalfG6#-Fhp6$/F^qFSFcp>FcpFbr-F76$Q6The~local~
system:~%a|+F4Fcp>8,,&-Fhp6$<$/FS,&%"zG#FhnFho%"wGFbs/FT*&^##F`pFhoFhn,&FasFhnF
csF`pFhn&FcpFgnFhn*&^#FhnFhn-Fhp6$F^s&FcpFgoFhnFhn>Fjr-%'expandG6#Fjr@$%)save_a
llGC%F<-F76$Q)z'~=~%a|+F4FjrF@@%/%/weakness_levelGFinC%-F=6$F?FB-F76#QenLyapuno
v~constants~are~not~calculated.~(weakness~level=0)|+F4>FJFinC%@%F]r>8--%)lyapun
ovG6%,&FjrFhn*&^#F`pFhnFasFhnFhnFasFcs>Ffu-%,lyapunovsymGFiu-F76$Q:Lyapunov~inf
ormation:~%a|+F4Ffu@%0&FfuFgnFinC'F]u-F76$Q=The~order~of~weakness~is~%d|+F4&Ffu
Fgo-F76$Q9Lyapunov~constant~is~%g|+F4,$FevF`pF@@%2FevFinC'-F76#QBWe~have~an~uns
table~singularity.|+F4F<FbwF@>FJFhnC'-F76#Q?We~have~a~stable~singularity.|+F4F<
FgwF@>FJF`p@%/&Ffu6#""$FhoC'-F76#QMWe~have~a~center~(the~system~is~quadratic).|
+F4F<FaxF@>FJFK@%&Ffu6#FKC'-F76#QPWe~have~a~center~(the~system~is~linear+cubic)
.|+F4F<FixF@>FJFKC'-F76$QGThe~order~of~weakness~is~at~least~%d.|+F4,&F[uFhnFhnF
hnF<F^yF@>FJFinF<-F76#QZ#######################################################
#|+F4F@Fcy-%1write_weak_focusG6&F:F;9'FJF46#FDF4F4,
I)lyapunovf*6%F%FasFcs6,%"aG%'bindirG%'infileG%(outfileG%(exefileG%'resultG%'rn
dnumG%#wlG%&linfoG%$auxGF4F4C,>Fcp-%%iremG6$-%%randGF4"%+5>FV-%$catG6&%,user_tm
pdirGQ'P4LYP_F4FcpQ%.INPF4>F[o-Fc[l6&Fe[lFf[lFcpQ%.OUTF4@%/%0user_precision0GFi
n>Fao-Fc[l6$%,user_bindirG%,user_lypexeG>Fao-Fc[l6$Fb\l%0user_lypexe_mpfG>Fjr-%
4preparelyapunovfileG6&FVFRF:F;>F^q&FjrFgn-F76#QDDetermining~lyapunov~constants
~...|+F4>Ffu-%(ssystemG6#-Fc[l6.%/user_exeprefixGQ!F4FaoQ#~"F4FVQ$"~"F4F[oQ)"~M
APLE~F4%.user_platformGFi]l%2user_sumtablepathGQ""F4>Fjo-%3readlyapunovresultG6
$F[oF^q7%-%#opG6#Fjo&FjrFgo&FjrF^xF46)Fg]lFe[lFc\lFg\lF^\lFb\l%/user_removecmdG
F4F4,
I3readlyapunovresultf*6$%)filenameG%*weaklevelG6)%(lypdataG%&VdataG%"jG%"nG%%wv
alG%'lypvalG%&okvalGF4F4C.>FJ-%)readdataG6$FRFhn-F76$Q4lyapunov~data~=~%a|+F4FJ
>FN7">F[oFhn-F=6$FBF??(FVFhnFhnF:%%trueGC&@$0&FJ6#F[oF`p-F76%Q*V(%d)=%g|+F4-%&r
oundG6#Fj`l&FJ6#,&F[oFhnFhnFhn>FN7$-Fe^l6#FN7$F_alFbal@$/F_alF`pC$>F[oFdal[>F[o
,&F[oFhnFhoFhn@$F[bl>F[oFdal>FcpF_al>Fao-F`al6#Fbal>Fjo&FJ6#F`blF@7$FjoFaoF4F4F
4F4,
I4preparelyapunovfilef*6&F^_l%#_fGFasFcs6)F%%&cubicG%"LG%"dGF_zFc_lFfzF4F4C.>FJ
-%4optimizepolynomial2G6%F:F;Fiy>FN%&falseG-F=6#FR-F76$Q$%d|+F4,&F^\lFhoFhoFhn>
F[o-%%ddegG6%FJF;Fiy@%/F[oFhoC$>FcpF_x-F76#Q#3|+F4@%/F[oF_xC$>Fcp""&@%33/-FX6%-
FX6%FJF;FhoFiyFinFin/-FX6%-FX6%FJF;FinFiyFhoFin/-FX6%-FX6%FJF;FhnFiyFhnFinC$-F7
6#Q#5|+F4>FNFf`lC$>FcpF[u-F76$F^dlF[uC$>FcpF[uFifl-F76$Q$%g|+F4)"#5,$%/user_pre
cisionGF`p>FV-%.coeff_degree2GFcdl-F76$F^dl-%%nopsG6#FV?(FjoFhnFhnFiglFf`lC$>Fa
o&FVFf^l-F76'Q/~~%d~%d~%g~%g|+F4&FaoFgn&FaoFgo-F`r6#-%#ReG6#&FaoF^x-F`r6#-%#ImG
Fihl-%*closefileGF[dl7%FcpF[oFNF4F4F4F4,
I,lyapunovsymf*6%F^clFasFcs6+F%FgzFfz%"kG%"TG%"VGFdz%#okGFc_lF4F4C,>FJ-Ffcl6%FR
F:F;>FN-%3preparelyapunovsymG6%FJF:F;>FVFfn>FcpFa`l>F^qFiclFc`l?(F[oFhnFhnFVFf`
lC(>Fao-%)sumtableG6#,$F[oFho>FjoFin?(FjrFhnFhn-Fjgl6#FaoFf`l>Fjo,&FjoFhn-%4par
t_lyapunov_coeffG6'FJF:F;&FaoFbt,&F[oFhoFhnFhnF`p>Fcp7$-Fe^l6#Fcp7$FjoF[o-F76&Q
2k=%d~V~=~%a~=~%f|+F4F[oFjo-F`rFf^l@$-%,reduce_nneqG6$FjoFinC$>F^qFf`lF^blF@@%F
^q>Fcp&Fcp6#F`p>Fcp7$FinFin7%Fi[mFfo&FNF^xF4F4F4F4,
I3preparelyapunovsymf*F]z6(F`clFaclFbclF_zFc_lFfzF4F4C'>FJFicl>FV-FbdlF]jl@%/FV
Fho>FjoF_x@%/FVF_xC$>FjoF_el@%33/-FX6%-FX6%FRF:FhoF;FinFin/-FX6%-FX6%FRF:FinF;F
hoFin/-FX6%-FX6%FRF:FhnF;FhnFin>FJFf`l>FjoF[u>FjoF[u>FN-FfglF]jl7%FjoFVFJF4F4F4
F4,
I)sumtablef*6#Fd_l6&Facl%"rGF/%+st_compareGF4F4C&>FJ-%*piecewiseG6%/FRFin7#7#Fh
n-%$mapG6$Fe^l-Fc`m6$&%)combinatG6#%(permuteG-&Fh`m6#%*partitionG6$FRFR>F[of*6$
Fh_mF/F46$%)operatorG%&arrowGF4@%2&FRFgn&F:FgnFf`l@%/FhamFiam-T#6$&FR6#;FhoF`p&
F:F`bmFiclF4F46$Fi_mF[o>FJ-%%sortG6$FJF[oOFJF4F4F4F4,
I4part_lyapunov_coefff*6'%)vecfieldGFasFcsFaclFfil6(%"RG%%exprGF%%"vG%#wwG%"iGF
4F4C%>FJ-Fc`m6$f*6#F_cmF4FcamF4-%-lyp_findpolyG6&T$T&T(,&FRFhnFhnFhnF4F46(F\cmF
RFasF:FcsF;Fiy@%4-%'memberG6$FinFJC&>FVF`p?(FjoFhnFhn,&-Fjgl6#FJFhnF`pFhnFf`l@%
-%%typeG6$,&FjoFhnF`pFhn%$oddG>FV-%)lyp_RegzG6&FV&FJFf^lF:F;>FV-%)lyp_ImgzGFeem
>FjoFjdm@%F]emC%>FV-%/lyp_multc_polyG6'FVFinF`pF:F;>6$FVF[o-Fe^l6#-%'lyp_LLG6'F
VFfemF:F;,&9(FbsFgsFhn>Fao-%)simplifyG6#-F^ilF[alC$>FbfmFcfm>Fao-F\gm6#-FhhlF[a
l>FaoFinOFaoF4F4F4F4,
I/lyp_multc_polyf*6'F%F_z%"bGFasFcsF4F4F4O-Fat6#*&,&F:Fhn*&F[tFhnF;FhnFhnFhnFRF
hnF4F4F4F4,
I-lyp_findpolyf*6&%#vfGFasFcsFd_l6$Fh_mFfilF4F4C%>FJFin?(FNFinFhnFiyFf`l>FJ,&FJ
Fhn*(-FX6%-FX6%FRF:FNF;,&FiyFhnFNF`pFhn)F:FNFhn)F;F`imFhnFhnFJF4F4F4F4,
I)lyp_Regzf*6&F%F0FasFcs6#Fh_mF4F4C(>FJ-Fat6#*&FRFhnF:Fhn>FJ-F_fm6'FJFinF`pF;Fi
y>FJ-%%diffG6$FJF;>FJ-%&lyp_GGFcdl>FJ,&FJFhn-%.lyp_conj_polyGFcdlFhnO-F_fm6%FJF
bsFinF4F4F4F4,
I)lyp_Imgzf*FeimFfimF4F4C'>FJFiim>FJF`jm>FJFdjm>FJ,&FJFhnFhjmF`pO-F_fm6%FJFinFg
sF4F4F4F4,
I'lyp_LLf*6'F%F0FasFcsFd_lFfimF4F4C$>FJ-Fajm6$FiimF;7$FJ-FX6%-FX6%FJF;FifmFiyFi
fmF4F4F4F4,
I&lyp_Gf*F]z6&Ffil%#fkGFh_m%"lGF4F4C%>FVFin@$1Fin-%'degreeG6$FRF:?(FJFinFhnF]]n
Ff`lC$>FN-FX6%FRF:FJ@$1Fin-F^]n6$FNF;?(F[oFinFhnFg]nFf`l@%0FJF[o>FV,&FVFhn**-FX
6%FNF;F[oFhn,&FJFhnF[oF`pF`p)F:FJFhn)F;F[oFhnFho>FV,&FVFhn*(F_^nFhnFb^nFhnFc^nF
hnFhn-FatF[hlF4F4F4F4,
I.lyp_conj_polyf*F]z6#%#zbGF4F4C$-%)assumingG6$7#-Fat6#-%*conjugateGF[dl7$'F:%%
realG'F;Fg_n-%%evalG6$-Fj_n6$-Fj_n6$%"%G<#/F:FJ/F;F:/FJF;F4F4F4F4
