M7R0
I.coeff_degree1f*6$%"fG%"xG6&%"gG%"dG%"jG%"LG6"F,C(>8$-%4optimizepolynomial1G6$
9$9%>8%-%$maxG6$""!-%'degreeG6$F/F4>8'7"?(8&F:"""F6%%trueG@$0-%&coeffG6%F/F4FBF
:>F?7$-%#opG6#F?7$FBFG@$/-%%nopsGFNF:>F?7#7$F:F:F?F,F,F,F,,
I.coeff_degree2f*6%F%F&%"yG6)F(F)F*F+%#dxG%"hG%"kGF,F,C(>F/-%4optimizepolynomia
l2G6%F3F49&>8(F7>F?F@?(FBF:FCF`oFDC%>8)FG>F6-F86$F:-F<6$F/F^o?(8*F:FCF6FD@$0-FH
6%FeoF^oF\pF:>F?7$FL7%FBF\pF_p@$FQ>F?7#7%F:F:F:F?F,F,F,F,,
I.coeff_degree3f*6&F%F&FZ%"zG6,F(%#d1G%#d2G%#d3G%#j1G%#g1G%#g2G%#j2G%#j3GF+F,F,
C(>F/-%)norpoly3G6&F3F4F^o9'>F6F7>8-F@?(F`oF:FCF6FDC%>Feo-F\o6%-FH6%F/F4F`oF^oF
jq>FB-F86$F:-F<6$FeoF^o?(8+F:FCFBFDC%>F\p-FH6%FeoF^oF[s>F?-F86$F:-F<6$F\pFjq?(8
,F:FCF?FD@$0-FH6%F\pFjqFfsF:>F]r7$-FM6#F]r7&F`oF[sFfsFis@$/-FSF^tF:>F]r7#7&F:F:
F:F:F]rF,F,F,F,,
I0write_vec_fieldf*6#%#vfG6$F+F*F,F,C(>F/-FW6%&F36#FCF&FZ-%'writefG6$Q$%d|+F,-F
S6#F/?(F6FCFCFeuFD-Fbu6&Q*%d~%d~%g|+F,-FM6$FC&F/6#F6-FM6$""#F]v-%&evalfG6#-FM6$
""$F]v>F/-FW6%&F36#FavF&FZFau?(F6FCFCFeuFDFhuF,F,F,F,,
I9write_vec_field_cylinderf*FhtFjtF,F,C(>F/-Fhp6&F_u%"rG%$_coG%$_siGFau?(F6FCFC
FeuFD-Fbu6'Q-%d~%d~%d~%g|+F,F[vF_vFev-Fcv6#-FM6$""%F]v>F/-Fhp6&F[wFdwFewFfwFau?
(F6FCFCFeuFDFhwF,F,F,F,,
I-write_saddlef*6,%#x0G%#y0G%"aG%"bG%"cGF)Fit%$sepG%&stypeG%&chartG6%F+F*FhnF,F
,C*-%)openfileG6#%)log_fileG-Fbu6&Q*%d~%g~%g|+F,FC-Fcv6#F3-Fcv6#F4-Fbu6'Q/~~%g~
%g~%g~%g|+F,-Fcv6#F^o-Fcv6#Fjq-Fcv6#9(-Fcv6#9)-Fft6#9*-Fbu6$Q&~~%d|+F,9-?(F6FCF
C-FS6#9+FDC'-Fbu6$Q&~~%d~F,&9,F^v>F/-F"6$&Fc[lF^v%"tG-Fbu6$Q#%dF,Feu?(FBFCFCFeu
FD-Fbu6%Q'~%d~%gF,-FM6$FC&F/6#FB-FM6$FavFh\l-Fbu6#Q"|+F,-Fbu6$Q&~~%g|+F,%(epsil
onG-Fby6#%)terminalGF,F,F,F,,
I+write_nodef*6&FgxFhx%%stabGF^yF,F,F,C&Fay-Fbu6&FgyFavFhyFjy-Fbu6%Q)~~%d~%d|+F
,F^oFjqFc]lF,F,F,F,,
I1write_weak_focusf*6&FgxFhxF^yF]yF,F,F,C&Fay-Fbu6&FgyFgvFhyFjy-Fbu6%F_^lFjqF^o
Fc]lF,F,F,F,,
I3write_strong_focusf*Fh]lF,F,F,C&Fay-Fbu6'Q-%d~%d~%g~%g|+F,F_xF^oFhyFjy-Fbu6$F
^[lFjqFc]lF,F,F,F,,
I6write_semi_elementaryf*6,FgxFhxFixFjxF[yF)FitF]yF\yF^yF_yF,F,C*Fay-Fbu6&Fgy""
&FhyFjyF\zFiz-Fbu6&Q,~~%d~%d~%d|+F,&Fc[lF`u&Fc[lF\wF_[l@$553/F_[lF:-%'memberG6$
Fj_l<(FCFavFgvF_x""'""(330F_[lF:/F[`lF:Fa`l33Fi`l/F[`lFC-Fb`l6$Fj_l<&FavFgvFe`l
Ff`l?(F6FCFC-FS6#Fi[lFDC&>F/-F"6$Fh[lF^\l-Fbu6$Q%~~%dF,Feu?(FBFCFCFeuFDFc\lF\]l
F_]lFc]lF,F,F,F,,
I2write_separatricef*6#F\y6(%&transGF*Fhn%#p2GF+FixF,F,C/>F/F_uF_\l?(F6Feu!""FC
FDC&>FeoF]v?(FBFCFCFavFD-Fbu6$Q$~%gF,-Fcv6#&FeoFi\l?(FBFgvFC""*FD-Fbu6$Q$~%dF,F
^clF\]l>F?F[w-Fbu6%Q'%g~%g|+F,-Fcv6#&F?F`u-Fcv6#&F?F\w>F/&F36#Fgv-Fbu6'Q-%g~%g~
%g~%g|+F,-Fcv6#&F/F`u-Fcv6#&F/F\w-Fcv6#&F/F`dl-Fcv6#&F/6#F_x-Fft6#&F3F`el>F`o-F
"6$&F36#Ff_lF^\l-Fbu6$Fa\l-FS6#F`o?(FBFCFCF[flFD-Fbu6%Fe\l-FM6$FC&F`oFi\l-FM6$F
avFbflF\]l-Fbu6$Fdu&F36#Fe`lF,F,F,F,,
I1write_degeneratef*6&FgxFhx%+trajectorsGF^y6#F*F,F,C)Fay-Fbu6&FgyFe`lFhyFjy-Fb
u6$Q$%g|+F,Fb]l-Fbu6$Fdu-FSF`z?(F/FCFCFfglFD-F\bl6#&F^oFfu-Fbu6$FduFjqFc]lF,F,F
,F,,
I*write_gcff*6#%%gcffG6-F*%"pG%"qG%#z1G%#z2G%"sGFewFfwF)F+F(F,F,C&-Fby6#%*vec_t
ableG>Ffs-%%ddegG6%F3F&FZ@%/FfsF:-Fbu6$FduF:CE>F]r-FWF^il-Fbu6%Q&%d~%dF,FfsFbt?
(F/FCFCFbtFD-Fbu6&Q*~%d~%d~%gF,-FM6$FC&F]rFfu-FM6$FavF_jl-Fcv6#-FM6$FgvF_jlF\]l
>F6%'user_pG>FB%'user_qG>8.-%%subsG6%/F&*$)F`oF6Febl/FZ*&F?FC)F`oFBFeblF3>F[[m-
%)norpoly2G6%F[[mF?F`o>F[[m-%&numerG6#F[[m>F]r-FWFh[m-Fbu6$Fa\lFbt?(F/FCFCFbtFD
FjilF\]l>F[[m-F][m6%/F&*&F?FCFa[mFebl/FZ*$Fd[mFeblF3>F[[mFf[m>F[[mFj[m>F]rF^\mF
_\m?(F/FCFCFbtFDFjilF\]l>F[[m-F][m6%/F&,$F`[mFeblFb[mF3>F[[mFf[m>F[[mFj[m>F]rF^
\mF_\m?(F/FCFCFbtFDFjilF\]l>F[[m-F][m6%Fe\m/FZ,$Fh\mFeblF3>F[[mFf[m>F[[mFj[m>F]
rF^\mF_\m?(F/FCFCFbtFDFjilF\]l@$50F6FC0FBFCC)>F[[m-F][m6%/F&*&F\pFC)FeoF6Febl/F
Z*&F[sFC)FeoFBFeblF3>F[[m-Fhq6&F[[mFeoF\pF[s>F[[mFj[m>F]r-FhpF__mF_\m?(F/FCFCFb
tFD-Fbu6'Q-~%d~%d~%d~%gF,F]jlF`jlFdjl-Fcv6#-FM6$F_xF_jlF\]lFc]lF,6$FgjlFijlF,F,
