M7R0
I.coeff_degree1f*6$%"fG%"xG6&%"gG%"dG%"jG%"LG6"F,C(>8$-%4optimizepolynomial1G6$
9$9%>8%-%$maxG6$""!-%'degreeG6$F/F4>8'7"?(8&F:"""F6%%trueG@$0-%&coeffG6%F/F4FBF
:>F?7$-%#opG6#F?7$FBFG@$/-%%nopsGFNF:>F?7#7$F:F:F?F,F,F,F,,
I.coeff_degree2f*6%F%F&%"yG6)F(F)F*F+%#dxG%"hG%"kGF,F,C(>F/-%4optimizepolynomia
l2G6%F3F49&>8(F7>F?F@?(FBF:FCF`oFDC%>8)FG>F6-F86$F:-F<6$F/F^o?(8*F:FCF6FD@$0-FH
6%FeoF^oF\pF:>F?7$FL7%FBF\pF_p@$FQ>F?7#7%F:F:F:F?F,6#%(roundedGF,F,,
I.coeff_degree3f*6&F%F&FZ%"zG6,F(%#d1G%#d2G%#d3G%#j1G%#g1G%#g2G%#j2G%#j3GF+F,F,
C(>F/-%)norpoly3G6&F3F4F^o9'>F6F7>8-F@?(F`oF:FCF6FDC%>Feo-F\o6%-FH6%F/F4F`oF^oF
\r>FB-F86$F:-F<6$FeoF^o?(8+F:FCFBFDC%>F\p-FH6%FeoF^oF]s>F?-F86$F:-F<6$F\pF\r?(8
,F:FCF?FD@$0-FH6%F\pF\rFhsF:>F_r7$-FM6#F_r7&F`oF]sFhsF[t@$/-FSF`tF:>F_r7#7&F:F:
F:F:F_rF,FhpF,F,,
I0write_vec_fieldf*6#%#vfG6$F+F*F,F,C(>F/-FW6%&F36#FCF&FZ-%'writefG6$Q$%d|+F,-F
S6#F/?(F6FCFCFguFD-Fdu6&Q*%d~%d~%g|+F,-FM6$FC&F/6#F6-FM6$""#F_v-%&evalfG6#-FM6$
""$F_v>F/-FW6%&F36#FcvF&FZFcu?(F6FCFCFguFDFjuF,F,F,F,,
I9write_vec_field_cylinderf*FjtF\uF,F,C(>F/-Fjp6&Fau%"rG%$_coG%$_siGFcu?(F6FCFC
FguFD-Fdu6'Q-%d~%d~%d~%g|+F,F]vFavFgv-Fev6#-FM6$""%F_v>F/-Fjp6&F]wFfwFgwFhwFcu?
(F6FCFCFguFDFjwF,F,F,F,,
I-write_saddlef*6,%#x0G%#y0G%"aG%"bG%"cGF)F[u%$sepG%&stypeG%&chartG6%F+F*FhnF,F
,C*-%)openfileG6#%)log_fileG-Fdu6&Q*%d~%g~%g|+F,FC-Fev6#F3-Fev6#F4-Fdu6'Q/~~%g~
%g~%g~%g|+F,-Fev6#F^o-Fev6#F\r-Fev6#9(-Fev6#9)-Fht6#9*-Fdu6$Q&~~%d|+F,9-?(F6FCF
C-FS6#9+FDC'-Fdu6$Q&~~%d~F,&9,F`v>F/-F"6$&Fe[lF`v%"tG-Fdu6$Q#%dF,Fgu?(FBFCFCFgu
FD-Fdu6%Q'~%d~%gF,-FM6$FC&F/6#FB-FM6$FcvFj\l-Fdu6#Q"|+F,-Fdu6$Q&~~%g|+F,%(epsil
onG-Fdy6#%)terminalGF,F,F,F,,
I+write_nodef*6&FixFjx%%stabGF`yF,F,F,C&Fcy-Fdu6&FiyFcvFjyF\z-Fdu6%Q)~~%d~%d|+F
,F^oF\rFe]lF,F,F,F,,
I1write_weak_focusf*6&FixFjxF`yF_yF,F,F,C&Fcy-Fdu6&FiyFivFjyF\z-Fdu6%Fa^lF\rF^o
Fe]lF,F,F,F,,
I3write_strong_focusf*Fj]lF,F,F,C&Fcy-Fdu6'Q-%d~%d~%g~%g|+F,FaxF^oFjyF\z-Fdu6$F
`[lF\rFe]lF,F,F,F,,
I6write_semi_elementaryf*6,FixFjxF[yF\yF]yF)F[uF_yF^yF`yFayF,F,C*Fcy-Fdu6&Fiy""
&FjyF\zF^zF[[l-Fdu6&Q,~~%d~%d~%d|+F,&Fe[lFbu&Fe[lF^wFa[l@$553/Fa[lF:-%'memberG6
$F\`l<(FCFcvFivFax""'""(330Fa[lF:/F]`lF:Fc`l33F[al/F]`lFC-Fd`l6$F\`l<&FcvFivFg`
lFh`l?(F6FCFC-FS6#F[\lFDC&>F/-F"6$Fj[lF`\l-Fdu6$Q%~~%dF,Fgu?(FBFCFCFguFDFe\lF^]
lFa]lFe]lF,F,F,F,,
I2write_separatricef*6#F^y6(%&transGF*Fhn%#p2GF+F[yF,F,C/>F/FauFa\l?(F6Fgu!""FC
FDC&>FeoF_v?(FBFCFCFcvFD-Fdu6$Q$~%gF,-Fev6#&FeoF[]l?(FBFivFC""*FD-Fdu6$Q$~%dF,F
`clF^]l>F?F]w-Fdu6%Q'%g~%g|+F,-Fev6#&F?Fbu-Fev6#&F?F^w>F/&F36#Fiv-Fdu6'Q-%g~%g~
%g~%g|+F,-Fev6#&F/Fbu-Fev6#&F/F^w-Fev6#&F/Fbdl-Fev6#&F/6#Fax-Fht6#&F3Fbel>F`o-F
"6$&F36#Fh_lF`\l-Fdu6$Fc\l-FS6#F`o?(FBFCFCF]flFD-Fdu6%Fg\l-FM6$FC&F`oF[]l-FM6$F
cvFdflF^]l-Fdu6$Ffu&F36#Fg`lF,F,F,F,,
I1write_degeneratef*6&FixFjx%+trajectorsGF`y6#F*F,F,C)Fcy-Fdu6&FiyFg`lFjyF\z-Fd
u6$Q$%g|+F,Fd]l-Fdu6$Ffu-FSFbz?(F/FCFCFhglFD-F^bl6#&F^oFhu-Fdu6$FfuF\rFe]lF,F,F
,F,,
I*write_gcff*6#%%gcffG6-F*%"pG%"qG%#z1G%#z2G%"sGFgwFhwF)F+F(F,F,C&-Fdy6#%*vec_t
ableG>Fhs-%%ddegG6%F3F&FZ@%/FhsF:-Fdu6$FfuF:CE>F_r-FWF`il-Fdu6%Q&%d~%dF,FhsFdt?
(F/FCFCFdtFD-Fdu6&Q*~%d~%d~%gF,-FM6$FC&F_rFhu-FM6$FcvFajl-Fev6#-FM6$FivFajlF^]l
>F6%'user_pG>FB%'user_qG>8.-%%subsG6%/F&*$)F`oF6Fgbl/FZ*&F?FC)F`oFBFgblF3>F][m-
%)norpoly2G6%F][mF?F`o>F][m-%&numerG6#F][m>F_r-FWFj[m-Fdu6$Fc\lFdt?(F/FCFCFdtFD
F\jlF^]l>F][m-F_[m6%/F&*&F?FCFc[mFgbl/FZ*$Ff[mFgblF3>F][mFh[m>F][mF\\m>F_rF`\mF
a\m?(F/FCFCFdtFDF\jlF^]l>F][m-F_[m6%/F&,$Fb[mFgblFd[mF3>F][mFh[m>F][mF\\m>F_rF`
\mFa\m?(F/FCFCFdtFDF\jlF^]l>F][m-F_[m6%Fg\m/FZ,$Fj\mFgblF3>F][mFh[m>F][mF\\m>F_
rF`\mFa\m?(F/FCFCFdtFDF\jlF^]l@$50F6FC0FBFCC)>F][m-F_[m6%/F&*&F\pFC)FeoF6Fgbl/F
Z*&F]sFC)FeoFBFgblF3>F][m-Fjq6&F][mFeoF\pF]s>F][mF\\m>F_r-FjpFa_mFa\m?(F/FCFCFd
tFD-Fdu6'Q-~%d~%d~%d~%gF,F_jlFbjlFfjl-Fev6#-FM6$FaxFajlF^]lFe]lF,6$FijlF[[mF,F,,
I,write_curvef*6#%'curvefGFchlF,F,C$>FhsF^il@%FbilFcilCE>F_rFgilFhil?(F/FCFCFdt
FDF\jlF^]l>F6Fijl>FBF[[m>F][mF^[m>F][mFh[m>F][mF\\m>F_rF`\mFa\m?(F/FCFCFdtFDF\j
lF^]l>F][mFe\m>F][mFh[m>F][mF\\m>F_rF`\mFa\m?(F/FCFCFdtFDF\jlF^]l>F][mF`]m>F][m
Fh[m>F][mF\\m>F_rF`\mFa\m?(F/FCFCFdtFDF\jlF^]l>F][mFi]m>F][mFh[m>F][mF\\m>F_rF`
\mFa\m?(F/FCFCFdtFDF\jlF^]l@$Fb^mC)>F][mFg^m>F][mF`_m>F][mF\\m>F_rFd_mFa\m?(F/F
CFCFdtFDFf_mF^]lF,6%FijlF[[mFipF,F,,
I0write_isoclinesf*6#%+isoclinesfGFchlF,F,C'-Fdy6#%0isoclines_tableG>FhsF^il@%F
bilFcilCE>F_rFgilFhil?(F/FCFCFdtFDF\jlF^]l>F6Fijl>FBF[[m>F][mF^[m>F][mFh[m>F][m
F\\m>F_rF`\mFa\m?(F/FCFCFdtFDF\jlF^]l>F][mFe\m>F][mFh[m>F][mF\\m>F_rF`\mFa\m?(F
/FCFCFdtFDF\jlF^]l>F][mF`]m>F][mFh[m>F][mF\\m>F_rF`\mFa\m?(F/FCFCFdtFDF\jlF^]l>
F][mFi]m>F][mFh[m>F][mF\\m>F_rF`\mFa\m?(F/FCFCFdtFDF\jlF^]l@$Fb^mC)>F][mFg^m>F]
[mF`_m>F][mF\\m>F_rFd_mFa\m?(F/FCFCFdtFDFf_mF^]l-%*closefileGF\cmFe]lF,6%FijlF[
[mF]cmF,F,
